### ISSUE TITLE
Random Ghast Shoot Fireball Sound

### ISSUE THREAD

**Issue by HugoDaBosss** [MylesIsCool/ViaVersion#10]
When ingame there sometimes is a random ghast shoot fireball sound.
This issue also appeared before my pull request. It is not a 'Named Sound Effect' packet, or it doesn't get recognized as that packet.
It is probably the new Sound Effect packet.

**Comment by HugoDaBosss** [comment]
Can anyone confirm this issue? Or is it just me?

**Comment by StamBoom** [comment]
I don't have this problem anymore, Some sound effects are still different, opening an iron door plays "Endereye shoot"

**Comment by StamBoom** [comment]
Possible an natural spawned entity has the wrong sound effect either.

**Comment by MylesIsCool** [comment]
I've had this issue but I have not seen it since, I could just be being unlucky.

**Comment by HugoDaBosss** [comment]
It's strange because I extracted the new sound names from the sounds.json from 1.8 and 1.9.
The script searched for the same internal sound names in 1.8 and 1.9 and combined them.
It could be caused that the actual internal path to the sound file changed for some sounds.

**Comment by MylesIsCool** [comment]
Worth noting that there are 2 different sound packets (I think) it might be the other one needs fixing or something like that.

**Comment by HugoDaBosss** [comment]
Yeah the Named Sound Effect and the Sound Effect.
I listened for the named and unnamed packets, but neither of them were sent when you can hear the ghast fireball sound.

**Comment by Paulomart** [comment]
https://github.com/MylesIsCool/ViaVersion/issues/93#issuecomment-192005193 bats seem to cause this sound

**Comment by PunKeel** [comment]
I confirm, @Paulomart. mobs.bat.takeoff, Effect Packet with ID 1015.
Just drop it and you're good to go. I don't have a remapping ready, but it's easy to generate one : 

For i in 0->2000, send chat message `i` and play effect `i`. There will be "[CHAT] i" "Played effect minecraft:mobs/thing" in logs ;)

**Comment by HugoDaBosss** [comment]
Fixed by https://github.com/MylesIsCool/ViaVersion/pull/126
