### ISSUE TITLE
1.13.1 to PaperMC 1.13 shows wrong recipes

### ISSUE THREAD

**Issue by bundabrg** [MylesIsCool/ViaVersion#1000]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/b8dea53facc7dce6a12429c2f97df90673c491c2e1f515816711488fec13f9c9

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord = "Build 1352"

Plugins = [ "ActionHealth", "AdvancedPortals", "AlmostFlatLandsReloaded", "ArvinLib", "AuthMe", "CommandSigns", "CoreProtect", "DeathMEssagesPrime", "DIYMazes", "dynmap", "FastAsyncWorldEdit", "FastLogin", "LuckPerms", "Multiverse-Core", "MySkin", "NoChat", "ProtocolLib", "TeleportPlus", "WorldEdit", "WorldGuard", "WorldGuardExtraFlags" ]

Version = "Paper version git-Paper-160 (MC: 1.13)"

### How does this error happen? login? Using an item? 
0. Log in with a 1.13.1 client.
1. Get 5 planks
2. Use a crafting table
3. Click 'show craftable'
4. Observe that you can apparently build a 'Lava Bucket'.
5. Click lava bucket and observe it shows it building a boat.

Lots of other wrong recipes.

Log out and back in with 1.13 client. All works fine.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
None

### Additional Notes
I'll try with no plugins later when I can kick all my players out.

**Comment by bundabrg** [comment]
Disabled every plugin on the backend PaperMC server, same issue.

**Comment by MylesIsCool** [comment]
Please use the latest build from https://ci.viaversion.com/job/ViaVersion/

Will soon push a new version of ViaVersion with these fixes :)
