### ISSUE TITLE
Cannot boost elytra using fireworks

### ISSUE THREAD

**Issue by ishland** [MylesIsCool/ViaVersion#1003]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/604e60a73c5f78d28b609d44e8653fb971eed6c02dd75d6743d49a9387eba66e

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Bungeecord version: git:BungeeCord-Bootstrap:1.12-SNAPSHOT:ceb9ea1:1329

Bungeecord plugins: BungeeTabListPlus-2.8.8, ClientStats, HubConnector_2.4.1d, skinfetcher-1.0.1, ViaVersion-1.5.1-SNAPSHOT

PaperSpigot version: git-Paper-1536

PaperSpigot plugins: ASkyBlock (3.0.9.1), ASkyBlock-IslandBorder (2.2.0), AsyncWorldEdit (3.5.4), AsyncWorldEditInjector (3.5.2), AudioConnect (1.3.2), AuthMe (5.4.0-b1877), AutoRespawnPlus (3.2), BlockBreaker (1.0), BungeeTabListPlus (2.8.8), ChatEx (1.6), ChopTree3 (4.0.0), Citizens (2.0.22-SNAPSHOT (build 1487)), CleanroomGenerator (1.0.0), CoreProtect (2.14.4), Craftconomy3 (3.3.1-d99cf63-trv200), CS-CoreLib (v1.5.18), Debug_Stick (0.0.2 In-dev), dynmap (2.6-beta-1-Dev201807082003), Dynmap-ASkyBlock (1.1), EditableSign (4.0.0), Fly (1.1), GuiShopRecoded (1.4), icJukeBox (1.6.3), icUipment (1.2.3), ImageOnMap (3.1), Installer (2.4.1), KillerMoney (4.2.0), Missing_Recipes (0.23), Multiverse-Core (2.5.0-b727), MyPet (2.3.5), NoteBlockAPI (1.2.0), OpenInv (3.3.4), PermissionsEx (1.23.4), PlaceholderAPI (2.9.1), PlugMan (2.1.5), QuickShop (0.9.35), RemoteToolkitPlugin (R10_A15.3), Reports (1.7.2.2), ServerSigns (4.5.1), Shopkeepers (2.2.1), Slimefun (4.1.15), SystemInfo (0.0.4a), TimoSpawn (1.0), TitleAPI (1.7.6), TPA (2.2.2), Vault (1.6.7-b${env.TRAVIS_BUILD_NUMBER}), VirtualPack (2.8.14), WorldEdit (6.1.8-SNAPSHOT;cd4729f), WorldGuard (6.2.1;84bc322)

### How does this error happen? login? Using an item? 
Fly with an elytra, and then use fireworks.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Nope.

**Comment by MylesIsCool** [comment]
Could you explain which versions this happens on? Does it happen on them all, does it happen on the version that the server is?

**Comment by ishland** [comment]
It seems like that it happen on 1.9+

**Comment by shedaniel** [comment]
That feature was added in 1.11.1 tho

**Comment by MylesIsCool** [comment]
See above :)
