### ISSUE TITLE
1.13.x Scoreboard bug

### ISSUE THREAD

**Issue by JH3Y50N** [MylesIsCool/ViaVersion#1004]
Scoreboard Suffix color bug http://prntscr.com/kn4xk3 and http://prntscr.com/kn4zls fence

**Comment by Dinnerwolph** [comment]
the bug of the fences this one is known and the problem of colors of the scoreboard please check that the option team-color-fix is is to true in the file of configuration

**Comment by JH3Y50N** [comment]
yes team-color-fix is true

**Comment by Dinnerwolph** [comment]
can you do the command "viaversion dump" and share the link

**Comment by JH3Y50N** [comment]
https://dump.viaversion.com/b7b9b4619aa075cda5b566069c941d74ddbe9e02aceeca21365a66e7ac3d2946

**Comment by Dinnerwolph** [comment]
can you send me the line of the scoreboard that bug

**Comment by JH3Y50N** [comment]
http://prntscr.com/ko28wq

**Comment by TheIntelloBox** [comment]
Me too, bug isn't fixed.

**Comment by MylesIsCool** [comment]
Could you test with https://ci.viaversion.com/job/ViaVersion/ and screenshot the result? Just wanted to see where we are with this

**Comment by JH3Y50N** [comment]
Dont is fixed :( http://prntscr.com/ksey1z

**Comment by didjee2** [comment]
Having a similar issue, also both tab (header & footer) & scoreboard are not updating (while they do get updated in lower versions).

![Screenshot](https://i.gyazo.com/e0a83b9dd300767903d4d3949ddfcac7.png)

**Comment by MylesIsCool** [comment]
Should be fixed in latest build
