### ISSUE TITLE
Exception after creating Sign with text '{ScreenBox}'

### ISSUE THREAD

**Issue by Sprax2013** [MylesIsCool/ViaVersion#1006]
### What is the output link of /viaversion dump? 
 https://dump.viaversion.com/5cb3c2c5687ac63018e568d05116c8c08d5002fbdf476912bad591ddd2c7a262

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord with Plugins

```
- ADU-Bungee
- ADU-CBN
- AdvancedBan-2.1.6-SNAPSHOT
- AlwaysOnline
- BungeeSocket
- BuycraftX
- CherryEssentials
- CommandSyncServer
- Functions+
- HelpUsers
- HubMagic
- JoinMe
- LuckPerms-Bungee
- McStats
- MoveMeNow
- NuVotifier
- OnChatHACKER
- Rang
- ServerListPlus
- StoreLogs
- TeamChat
- VoteListener
```

### How does this error happen? login? Using an item? 
I think after placing the sign with the Text (First line `{ScreenBox}` and other lines empty)

### Is there an error in the console? Use pastebin.com. Is there a kick message?

> [ViaVersion] Invalid JSON String: "{ScreenBox}" Please report this issue to the ViaVersion Github: us.myles.viaversion.libs.gson.stream.MalformedJsonException: Expected ':' at line 1 column 12 path $.ScreenBox

and
> [ViaVersion] Invalid JSON String: "{ScreenBox}" Please report this issue to the ViaVersion Github: us.myles.viaversion.libs.gson.stream.MalformedJsonException: Expected ':' at line 1 column 12 path $.ScreenBox

**Comment by MylesIsCool** [comment]
Could you clarify which plugin ScreenBox is? And if it happens without the plugin?

**Comment by Sprax2013** [comment]
ViaVersion ist only throwing that warning/error. The Screenbox-Plugin just needs a Sign at a specific location, it could have empty lines. ViaVersion (seems) nit to cause any trouble in any way because of that.
The Screenbox plugin is just not setting signs with the correct rotation, that is because I set the first line as a reminder.

The message is still shown after disabling/removing the ScreenBox-Plugin.

The functionality of the ScreenBox-Plugin:
> A player can right-click on a sign that will open an inventory where you can choose a design/layout/.schematic-File.
> After that (or without choosing one) he can click on a button and will be teleported and the schematic is loaded. Another player can now press the same button and will be teleported right next to the first player. The second player now has a couple of seconds to do a screenshot with player one. A player-queue is available.

**Comment by MylesIsCool** [comment]
Could you test with https://ci.viaversion.com/job/ViaVersion/ as we made a few changes to how we parse JSON recently :) and let me know if it still happens

**Comment by Sprax2013** [comment]
Sorry for keeping you waiting: The issue seems to be fixed. - One quick question (although this issue is not the right place), will the tab-complete on 1.8-Servers with 1.13-Clients be fixed or is it not possible? (You often get kicked for spamming when not disabling it in the ViaVersion config).

**Comment by MylesIsCool** [comment]
You can see other issues for further details otherwise, there's a config option in the latest build from ci.viaversion.com
