### ISSUE TITLE
ProtocolSupport incompatibility

### ISSUE THREAD

**Issue by BestMark** [MylesIsCool/ViaVersion#1007]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/55eee596dbf9fd50232b07b699a42a1154d4cf273aad689d3eb923974f7ed93d

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Paper 1.12.2 latest build (without proxy software like BungeeCord)
Also I use latest PS build for 1.12.2 version (https://github.com/ProtocolSupport/ProtocolSupport/commit/6f3b8b878e967d64b03f1a81685ffe2bba54f4a8)

### How does this error happen? login? Using an item? 
It happens when I try to connect with 1.13 and 1.13.1 versions.
![2018-08-29 15 39 49](https://user-images.githubusercontent.com/18399104/44788225-247ca400-aba2-11e8-9738-40416a5e471a.png)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No, there are no messages in console when I try to connect.

**Comment by MylesIsCool** [comment]
ViaVersion isn't compatible with ProtocolSupport. There are no current plans to support this directly, as it's pretty complicated to do our end.

**Comment by BestMark** [comment]
Thanks for your prompt reply
