### ISSUE TITLE
BossBar Issue?

### ISSUE THREAD

**Issue by Fluxty** [MylesIsCool/ViaVersion#1008]
### What is the output link of /viaversion dump? 
https://pastebin.com/YGqfRNNs - Removed some of the plugins info

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Using latest version of Travertine, we just removed Viaversion at the bungee level and are now only using it on the 1.8.8 Spigot servers. Appears there's an issue with the bossbar now?

### How does this error happen? login? Using an item? 
Logging in and trying to receive a boss bar.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/vsL7BbFG

**Comment by MylesIsCool** [comment]
Fixed in the latest build from ci.viaversion.com :)
