### ISSUE TITLE
Skin bug?

### ISSUE THREAD

**Issue by timr2000** [MylesIsCool/ViaVersion#101]
People in 1.9 can not see the second layer of their skin..
ViaVersion--0.4.6
![1 9 1 8](https://cloud.githubusercontent.com/assets/17603703/13506108/ab6dfb82-e17c-11e5-8785-f50541510caa.png)

**Comment by MylesIsCool** [comment]
Duplicate of #98

**Comment by StamBoom** [comment]
Fixed #103
