### ISSUE TITLE
Spamming characters after / gets you kicked.

### ISSUE THREAD

**Issue by andrewkm** [MylesIsCool/ViaVersion#1010]
Step 1:

https://i.imgur.com/FOea86O.png

Step 2:

Keep going:
https://i.imgur.com/BS8NIUh.png

Step 3:

Eventually:
https://i.imgur.com/YEewHQV.png

BungeeCord
1355

PaperSpigot
1553

ViaVersion
232

**Comment by MylesIsCool** [comment]
See #891, can be worked around with a patch to spigot at this point in time
