### ISSUE TITLE
Could not find type id 12 isObject=false

### ISSUE THREAD

**Issue by andris155** [MylesIsCool/ViaVersion#1011]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/78f0336cd6f189375e396ba71319b42ce2089c726c1b321d55309dca15d47318

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
`Waterfall 1.13.1 build 219`

### How does this error happen? login? Using an item? 
Write console. I don't know.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
02.09 15:46:34 [Server] ERROR [ViaVersion] Could not find type id 12 isObject=false

**Comment by MylesIsCool** [comment]
Could you test with the latest build and see if it still happens?

It might be worth trying to narrow this down and just go around your server by yourself. It might be a mob etc related.

**Comment by MylesIsCool** [comment]
See above,
