### ISSUE TITLE
Received invalid biome ids OpenTerrainGenerator - BiomeBundle custom generator

### ISSUE THREAD

**Issue by andris155** [MylesIsCool/ViaVersion#1012]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/a94468e1aba90964538577aaf1b80bb7083e85737e98560c799cfacbc89741d1

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
`Waterfall 1.13.1 build 219`

### How does this error happen? login? Using an item? 
Players move this custom biomes?

### Is there an error in the console? Use pastebin.com. Is there a kick message?
[ViaVersion] Received invalid biome id custom biome id
https://github.com/BiomeBundle/BiomeBundle/blob/BiomeBundleV6.1/Biome%20Bundle/WorldConfig.ini#L32

**Comment by MylesIsCool** [comment]
If it states your biomes are invalid, they're invalid for vanilla.

You can suppress this in the ViaVersion config under 1.13 conversion errors, but your biomes are invalid.
