### ISSUE TITLE
Players kicked when interacting with/attacking entities

### ISSUE THREAD

**Issue by Thatsmusic99** [MylesIsCool/ViaVersion#1014]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/02d58de753ecd631220cf5561c78173a1fadcf02685fa921ce028df7bf8e96b2

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No, we are running standard Spigot on 1.12.2. A full plugin list can be found here (any questions on them feel free to ask): https://imgur.com/a/dnR2RYO

### How does this error happen? login? Using an item? 
I was told by a player she wasn't able to kill/attack ordinary entities without being kicked from the server, so I had a go at it myself and had the same result. We were both using 1.13.1 clients when doing this. Afterward, I went onto a separate client using 1.13 and couldn't reproduce the issue, so it's only among 1.13.1 clients this takes place.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
There is no error in console - it only says I disconnected for the reason "Disconnected". However, there is a kick message I receive, of which says "Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: 7". There are no errors or even mention of being kicked from the server in my personal log files.

**Comment by MylesIsCool** [comment]
Could you clarify if this happens with - https://ci.viaversion.com/job/ViaVersion ?

**Comment by Thatsmusic99** [comment]
Will give it a shot soon. Cheers for this.

**Comment by Thatsmusic99** [comment]
Right, this went completely from my head since I've had too much going on... that's my fault. But it works flawlessly, thank you kindly!

**Comment by MylesIsCool** [comment]
Great stuff :)
