### ISSUE TITLE
Kicked for SPAM

### ISSUE THREAD

**Issue by 151baccardi** [MylesIsCool/ViaVersion#1015]
Kicked for spam with latest build (the 1.13.1 or build 1.5.0)
does not happen in 1.4.1

Only happens whist connecting with 1.13.1 client to 1.12.2 server using 1.5.0 viaversion on spigot.

**Comment by AustinGarrettRichards** [comment]
In the newest via version there's a new config option where you can disable 1.13 TAB autocomplete, which is what causes the kicked for spamming on 1.13 clients on 1.12 servers. We did that, and it fixed it. I recommend downloading the newest one and turning that on in the config.

**Comment by toxamin** [comment]
you could keep tab completion for 1.13 by using a playerkickevent and cancelling it if it's "disconnect.spam"

**Comment by MylesIsCool** [comment]
See above :)
