### ISSUE TITLE
1.9 and greater scoreboard bug

### ISSUE THREAD

**Issue by Starmixcraft** [MylesIsCool/ViaVersion#1017]
https://dump.viaversion.com/3899ca155b664ea696cf67b2e2af262b244b1f330c37d63d8ecc340e7b4de876

Using bungeecord

The bug is only accuring if you join set a scoreboard team via the bukkit api(I havend tested the packet method yet) if you set the nametag visiblity to Only own team, 1.9 and greater client get kicked!

In the console there is a the error: Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer

**Comment by MylesIsCool** [comment]
Could you provide a screenshot from the client? 

Are you also able to test without Bungee?

**Comment by Starmixcraft** [comment]
I the mean time i have tested the (manual) packet version and that works, looks like a bug in bukkit, sorry to report it on viaversion, il report it on bukkit, i have got the MCP 1.9.4 and got the error that the team is allready registed and therefor the client throws a exeption and disconnects :(
