### ISSUE TITLE
Kick 1.13 clients

### ISSUE THREAD

**Issue by alexlazarev98** [MylesIsCool/ViaVersion#1020]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/701216e1dcd6a0d3eff1a6deecb2ce87eb2a9c34e6bbf6144afa197fd87452da

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Modify [BungeeCord(BotFilter 3.5)](https://github.com/Leymooo/BungeeCord)
Sorry, I didn`t know bungee version
Plugin list on spigot
![screenshot_20180912184614](https://user-images.githubusercontent.com/37180406/45438427-cc749000-b6bf-11e8-9d92-69f5e5e2644f.png)
Plugin list on bungee
![screenshot_20180912191439](https://user-images.githubusercontent.com/37180406/45438569-27a68280-b6c0-11e8-9936-e10efb6523f9.pg)]

### How does this error happen? login? Using an item? 
This happen when player login

### Is there an error in the console? Use pastebin.com. Is there a kick message?
On bungee console > https://hasteb.in/nijepeti.lua
Kick message > Outdated server(from spigot.yml)

P.S. Sorry if I made grammatical mistakes. I'm not English.

**Comment by Lennart99** [comment]
Isn't it an idea to retry with only viaversion and no other spigot plugins?

**Comment by MylesIsCool** [comment]
See above, this will be down to one of your plugins most likely. (I'd suggest copying server)
