### ISSUE TITLE
BungeeCord error during login (1.13.x only)

### ISSUE THREAD

**Issue by BestMark** [MylesIsCool/ViaVersion#1022]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/4728ef752f0553befb9769d087f42fcfcd3768466d305512a3363139bccb7066

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yes, I'm using latest BungeeCord.

### How does this error happen? login? Using an item? 
Sometimes it happens when I login using 1.13.1 version to 1.12.2 server. At the time of login the player was **in nether (world_nether)**.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/AYYatNac

**Comment by MylesIsCool** [comment]
Could you repastebin etc? As it's not available.

**Comment by BestMark** [comment]
Sorry, but I didn't save it. Now I'm using ViaVersion 1.3.0.

**Comment by MylesIsCool** [comment]
Need the above to fix this, otherwise possibly catch me on our Discord (if you have discord).
