### ISSUE TITLE
Villager trade bug (1.13)

### ISSUE THREAD

**Issue by NeuTraLZero** [MylesIsCool/ViaVersion#1023]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/90e844a98f8c28bdb4fdabd3030f7646d23b88b4bc5df9de0752b8d6da88482e

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I am not using BungeeCord.

### How does this error happen? login? Using an item? 
Villager trade system seems to be broken when you log in using 1.13.1 on a 1.13 Spigot server. It's displaying a diffrent items from the game, this also happens with Shopkeeper plugin trades

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Not at all.

### Screenshots
![2561-09-13_22 30 37](https://user-images.githubusercontent.com/43245485/45499020-a5908980-b7a5-11e8-998e-4e4377648e75.png)
![2561-09-13_22 30 46](https://user-images.githubusercontent.com/43245485/45499021-a6292000-b7a5-11e8-8342-c3494cbc39af.png)
![2561-09-13_22 31 04](https://user-images.githubusercontent.com/43245485/45499022-a6292000-b7a5-11e8-8fe6-4796c046e3e9.png)

**Comment by MylesIsCool** [comment]
Use latest build from ci.viaversion.com
