### ISSUE TITLE
1.13 Clients get kicked for Spam (Need to solve ASAP)

### ISSUE THREAD

**Issue by Niko302** [MylesIsCool/ViaVersion#1026]
### What is the output link of /viaversion dump? 
https://www.spigotmc.org/resources/viaversion.19254/ (updated 1.13)

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Spigot 1.12.2

### How does this error happen? login? Using an item? 
Just kick players for using a command 2 times or sometimes even once, if they write in chat same thing happens.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
[05:29:56 INFO]: Niko302 issued server command: /deop Niko302
>
[05:29:56 INFO]: Niko302 lost connection: Kicked for spamming
>
[05:29:57 WARN]: handleDisconnection() called twice

**Comment by MylesIsCool** [comment]
Download latest build from ci.viaversion.com and use config option.
