### ISSUE TITLE
Failed to get 1.12 item

### ISSUE THREAD

**Issue by N0tMyFaultOG** [MylesIsCool/ViaVersion#1028]
### What is the output link of /viaversion dump? 
Server dump https://dump.viaversion.com/221d1d8742b67478a10df3ef28e068c53802ce79adc202eadc1b58e430f912fe

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Proxy dump, HexaCord, plugins are stated in the dump https://dump.viaversion.com/4de544c99ae4858b590ba8a77494dac7e50b5455a4ef198b0c7b1e6ecbce5f64

### How does this error happen? login? Using an item? 
If you try to pick a 6 sided log, such as log:12, log:13 and so on the issue occurs. If you try to pick the item, with middle mouse button, the server console responds with `[ViaVersion] Failed to get 1.12 item for 53` or other numbers. 

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Error stated above.

**Comment by MylesIsCool** [comment]
I would suggest just enabling the suppress-1_13-conversion-errors option in the config if this is still a issue.
