### ISSUE TITLE
 Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured. >

### ISSUE THREAD

**Issue by leoncp9** [MylesIsCool/ViaVersion#1029]
### Is there an error in the console? Use pastebin.com. Is there a kick message?
 Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.
>

**Comment by MylesIsCool** [comment]
Provide more info, enable debug=true and hastebin.com the error and we'll reopen this issue.

**Comment by leoncp9** [comment]
When i use ViaVersion-1.5.2 and ViaVersion-1.5.1 i can't join on my server if i use 1.8.8 because i get this messagge "proxy lost connection to server" if i use 1.12.2 i can join on my server withou problems, my server is paper spigot 1.12.2,  i set enable debug=true, if i use ViaVersion-1.5.1-SNAPSHOT i can join on my server with 1.8.8 without problems, download log and open it with notepad++
https://drive.google.com/open?id=10diMklmm4u4IH9ty3FUJtzrJX_yabK9J
 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.

**Comment by MylesIsCool** [comment]
Update ViaRewind to latest dev build https://ci.viaversion.com/view/ViaRewind/ and use 1.5.2 ViaVersion from Spigot if you don't.
