### ISSUE TITLE
Tallgrass

### ISSUE THREAD

**Issue by Iltotore** [MylesIsCool/ViaVersion#1032]
### What is the output link of /viaversion dump? 
I'm not on my computer. The plugin version is 1.5.0 and I use spigot 1.12

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Bungeecord 1.13

### How does this error happen? login? Using an item? 
When a 1.13 client see a double plant (like sunflower) in a 1.12 server, he see a Peony (pink flower) in place of a Tallgrass.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No errors. I think it's a problem with data values of 1.12 for name 1.13 (wool:1 → orange_wool)

PS: Sorry for my broken English

**Comment by MylesIsCool** [comment]
This is related to Connected Blocks, see the open issue for progress.
