### ISSUE TITLE
Fog?

### ISSUE THREAD

**Issue by OGLuxey** [MylesIsCool/ViaVersion#1034]
### What is the output link of /viaversion dump? 
1.5.2
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Bungee, nothing that would affect the plugin

### How does this error happen? login? Using an item? 
Just fog 

### Is there an error in the console? Use pastebin.com. Is there a kick message?
no

**Comment by MylesIsCool** [comment]
I have no idea what you mean, consider filling out the issue so that we can get the best understanding of what you mean.
