### ISSUE TITLE
ViaVersion with PaperSpigot 1.12.2 shows incorrect blocks/items

### ISSUE THREAD

**Issue by smmmadden** [MylesIsCool/ViaVersion#1037]
### What is the output link of /viaversion dump? 
We've made a dump with useful information, report your issue and provide this url: https://dump.viaversion.com/fef45af0836b68af0c082a4652de3e5433d0eb72c89c11f5a3f4198b0acfa60d

### How does this error happen? login? Using an item? upon login to 1.12.2 from 1.13.1 client, these warnings are written.  https://hastebin.com/uwaquzokub.md

Also in-game, the Fences and Doors have incomplete block textures but appear to still be functional.
![image](https://user-images.githubusercontent.com/10309346/46312292-a7728f00-c592-11e8-8255-748c95c69549.png)
![image](https://user-images.githubusercontent.com/10309346/46312322-bd804f80-c592-11e8-8032-47e24e200549.png)
![image](https://user-images.githubusercontent.com/10309346/46312252-890c9380-c592-11e8-95a1-2e711734cfa2.png)
This is a double door. Not four trapdoors as it appears to look like.
![image](https://user-images.githubusercontent.com/10309346/46312372-e1dc2c00-c592-11e8-85d9-fabeb9697d16.png)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No kick messages and no warnings/exceptions related to the textures.  Since these changed in 1.13.1, I'm guessing that we didn't retain the previous block id's?

**Comment by smmmadden** [comment]
I've also confirmed that using the 1.12.2 client to the 1.12.2 server, the doors and fences are properly rendering their textures including the iron door, though the bottom looks like it is missing a texture as its more fuzzy-gray.
![image](https://user-images.githubusercontent.com/10309346/46312607-8d857c00-c593-11e8-859b-ca220dae1450.png)
![image](https://user-images.githubusercontent.com/10309346/46312620-9a09d480-c593-11e8-9318-4e370258d86c.png)
![image](https://user-images.githubusercontent.com/10309346/46312678-c887af80-c593-11e8-8b4b-abcb715ce020.png)

**Comment by MylesIsCool** [comment]
https://github.com/MylesIsCool/ViaVersion/issues/856#issuecomment-425775164

**Comment by smmmadden** [comment]
If ViaVersion 1.5.1 fixed the issue in the other thread, how is it that viaversion 1.5.2 the issue is not? I found the link pointing to the google drive to download it and it has ViaVersion-1.5.1-SNAPSHOT.jar as the file name.

**Comment by MylesIsCool** [comment]
This issue isn't fixed as per the other thread

**Comment by smmmadden** [comment]
sorry, this is confusing.  If the issue isn't fixed and both this ticket and the other are closed, how will I know when it will be fixed?  I would think one of these should remain open until it is? Yes ?

**Comment by MylesIsCool** [comment]
@smmmadden It isn't closed

**Comment by smmmadden** [comment]
apologies, my mistake - I saw Closed below the last post and thought it was that issue, not the one it was related to. Thanks - will continue to monitor for when it is. :-)
![image](https://user-images.githubusercontent.com/10309346/46315008-40f16f00-c59a-11e8-9ebd-4972e98c5b3a.png)
