### ISSUE TITLE
Player Kick on Connections

### ISSUE THREAD

**Issue by UraharaNZ** [MylesIsCool/ViaVersion#1038]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/b49a423def8530cee2468658096d5a48ee70d6c8840d88596fae7f6e54641a9d

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
WaterFall

### How does this error happen? login? Using an item? 
Login multiple user at the same time "aparently"

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/QxjdxKsQ

**Comment by UraharaNZ** [comment]
Also was tested with ViaVersion 1.5.3 1.5.2 same issue.

**Comment by UraharaNZ** [comment]
update: tested with bungeecord same issue.

**Comment by MylesIsCool** [comment]
Can you test with no other plugins?

**Comment by UraharaNZ** [comment]
Tested and yes apparently it's one of my plugins. I'm sorry.
