### ISSUE TITLE
map Blank on Login - sometimes

### ISSUE THREAD

**Issue by mcraftpete** [MylesIsCool/ViaVersion#1042]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/05ee80a695268e33029d04a6fffe572f0302fcc7d0b78caf2363976a52e9e2d2

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
just bungeecord but with viaversion adn viabackwards

### How does this error happen? login? Using an item? 
on loggging onto a 1.13 server 

### Is there an error in the console? Use pastebin.com. Is there a kick message?
no error or kick message , just chunks do not always load onjoin , relogging sometimes fixes immediately sometimes does not takes 2-3 relogs then chunks load.

**Comment by MylesIsCool** [comment]
We're unable to replicate this ourself, I would suspect it might be related to something else? Does this happen on other versions?

If you're able to describe a simple setup, eg. Bungee with Spigot 1.13 build x, and we can replicate we'll happily reopen and look into.
