### ISSUE TITLE
Keepalive instant kick

### ISSUE THREAD

**Issue by CryLegende** [MylesIsCool/ViaVersion#1043]
https://dump.viaversion.com/9b0c27f5baf9d18ee0164ebf4f6020b7b7971ead9a4343ba4db93dc48829ca60

I use the latest 1.12.2 PaperSpigot

When a player connects to the server, he has this error:
PLAYER sent an invalid keepalive! pending keepalive: false got id: 0 expected id: 0
After that, the player is instantly kick from the server

**Comment by MylesIsCool** [comment]
ViaVersion handles newer versions I suspect this is down to older versions, I would suggest looking at Papers github for instructions on how to adjust keepalives to be nicer.

**Comment by CryLegende** [comment]
I never touch the keepalive option, I did not even know we could change it

**Comment by creeper123123321** [comment]
Gerrygames/ViaRewind#14
