### ISSUE TITLE
PacketPlayOutEntityDestroy

### ISSUE THREAD

**Issue by Hyronymos1337** [MylesIsCool/ViaVersion#1046]
Latest ViaVersion on Bungeecord (latest spigot release)

The Event PacketPlayOutEntityDestroy ensures that people are kicked on the current Server

**Comment by MylesIsCool** [comment]
I can't really understand what your issue is. Please rephrase and follow the issue template.

https://github.com/MylesIsCool/ViaVersion/blob/master/ISSUE_TEMPLATE.md

I'll reopen when further details are provided eg. Client version, server version etc.
