### ISSUE TITLE
Errors with version 0.4.6

### ISSUE THREAD

**Issue by Eternalrealms** [MylesIsCool/ViaVersion#105]
### What version of ViaVersion are you using? Type /ver viaversion
0.4.6

### What version of Spigot are you using? Type /ver
Spigot 1.8.8

### How does this error happen? login? using an item? 
Constant console spam

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://hastebin.com/vuxaxakuni.avrasm
http://hastebin.com/dederoyidi.avrasm

**Comment by HugoDaBosss** [comment]
This is a duplicate I think, don't know which issue though.
Could anyone link it?

**Comment by HugoDaBosss** [comment]
Are you using PaperSpigot? https://github.com/MylesIsCool/ViaVersion/issues/89

**Comment by Eternalrealms** [comment]
It also disconnected me whenever I tried placing a block.

**Comment by Eternalrealms** [comment]
I am it says this on the front page tho. 

"Please use Spigot-1.8.8 (PaperSpigot should also work), all plugins you use should be made for 1.8"

**Comment by MylesIsCool** [comment]
Should be fixed now, as for spam might be a paperspigot issue.
