### ISSUE TITLE
Dev Build 247 on 1.12.2 PaperSpigot - doors still messed up

### ISSUE THREAD

**Issue by smmmadden** [MylesIsCool/ViaVersion#1051]
### What is the output link of /viaversion dump? 
https://hastebin.com/rudokeperi.xml

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Using Waterfall build 230 (1.13.1)
PaperSpigot build 382 (1.13.1)
### How does this error happen? login? Using an item?   Using any door.  If you get the door to look open, you can't pass thru it (if you click on the top half of the door).  The top opens and bottom stays closed.  If you click on the bottom the door opens and closes fine (after a few times to fix the split door).
![image](https://user-images.githubusercontent.com/10309346/47275012-a7562580-d579-11e8-807d-d67b78f40673.png)
What's odd is, if you click on the bottom part of the door to open it and walk through.  Try walking back through again.  You won't be able to unless you close the door and open it from the side you are on.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
No errors - visual display of 1.12.2 doorways.
![image](https://user-images.githubusercontent.com/10309346/47275050-06b43580-d57a-11e8-8a56-0a89bc2828f4.png)

**Comment by smmmadden** [comment]
also the fences still look incomplete and missing textures.
![image](https://user-images.githubusercontent.com/10309346/47275169-efc21300-d57a-11e8-9499-274b3972420f.png)

**Comment by MylesIsCool** [comment]
There's a open issue for this, see#856
