### ISSUE TITLE
1.13 commands.generic.usage ?

### ISSUE THREAD

**Issue by TheCompieter** [MylesIsCool/ViaVersion#1062]
I found a bug that is probbly in viaversion.
When i type a vanilla command in my server when joined in 1.13.x
for example /setblock then i get "commands.generic.usage" as output.
This does not happen in 1.12.2 and this does also not happen in my 1.13.2 survival server.

![2018-10-28_14 05 50](https://user-images.githubusercontent.com/34034571/47616266-aca3fa80-daba-11e8-939d-97f1337e8fe4.png)

**Comment by MylesIsCool** [comment]
See https://github.com/MylesIsCool/ViaVersion/issues/919 for progress
