### ISSUE TITLE
1.13 clients cannot send messages on a 1.12 server that has viaversion installed, (related to venturechat / bungeecord?)

### ISSUE THREAD

**Issue by RealmportalMC** [MylesIsCool/ViaVersion#1063]
### What is the output link of /viaversion dump? 

https://dump.viaversion.com/581313a0c73ee69e473853433effc5bd164e2ba16412a6c35824b383b97330b7

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Bungecord,  waterfall 1.13

Paperspigot version 1.12.2

Bungeecord plugins :  Venturechat, ServerlistPlus, SayNotoMCLeaks, PremiumVanish, Porty-Bungee ,networkmsgs, Luckperms-Bungee, kotlin4mc, Bungeetablistplus

 ### How does this error happen? login? Using an item?

When you send a message in chat, it doesnt go through. nobody recieves it. 
it just doesnt show up in chat,  However, the discord bot picks the chat up and sends it to discord.

Commands work just fine.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

[15:10:48] [Netty Epoll Server IO #1/WARN]: [ViaVersion] Received invalid biome id 71
  ^^^ spams but with various biome ID's

**Comment by creeper123123321** [comment]
You will need to update ViaVersion (https://ci.viaversion.com/job/ViaVersion/) and VentureChat
