### ISSUE TITLE
ViaVersion bungee cannot ping protocolsupport server for version, defaults to -1.

### ISSUE THREAD

**Issue by zedwick** [MylesIsCool/ViaVersion#1064]
**Describe the bug, provide any errors**
A 1.13.1 server with protocolsupport installed behind a viaversion enabled proxy cannot have its protocol version detect properly, resulting in the protocol number being stored as -1 (disabling viaversion for that server, preventing 1.13.2 clients from connecting). This can be overriden by disabling viaversion's pings, and then manually changing the server's recorded protocol from -1 to 401.

Removing ProtocolSupport from the spigot server resolves the issue, allowing the server to be pinged by viaversion again.

**How can we reproduce it?**
1. Install [ProtocolSupport](https://build.true-games.org/job/ProtocolSupport/291/) on 1.13.1 spigot server connected to bungeecord with viaversion installed
2. Try to connect with a 1.13.2 client (and be unable to)
3. Open viaversion's config file. The ProtocolSupport enabled server should be listed with protocol version -1.

**Expected behaviour**
As overriding Viaversion's ping with a manually set protocol number works perfectly fine with protocolsupport behind a viaversion proxy, I assume this is not intentional. I would expect viaversion to be able to detect the server's default protocol and connect users to the 1.13.1 via the 1.13.1 protocol when they are on a supported later client version.

**Additional server info**
Spigot server:
* [ProtocolSupport 4.29.dev b291](https://build.true-games.org/job/ProtocolSupport/291/)
* CraftBukkit version git-Spigot-f6a273b-a639ae4 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

BungeeCord:
* Viaversion 1.6.0
* BungeeCord version git:BungeeCord-Bootstrap:1.13-SNAPSHOT:1c5bff7:1359 by md_5

**Comment by MylesIsCool** [comment]
This is definitely a bug however I'm not 100% sure if we can fix it. The way protocol detection works is by sending out the server list ping, which we're using Bungee's built in code.

https://github.com/MylesIsCool/ViaVersion/blob/master/bungee/src/main/java/us/myles/ViaVersion/bungee/service/ProtocolDetectorService.java#L57

I need to look into what ProtocolSupport does later to see how this is happening, but I'd assume it doesn't specify the server version.

**Comment by zedwick** [comment]
My workaround is currently causing me more problems, as some of my servers regularly change versions (changing minigames) and can no longer detect the new versions without pings being enabled. So if this cannot be fixed directly, it would be great to have a way to disable pings for certain servers so the protocol can be manually set, whilst still pinging other servers for version changes.

**Comment by MylesIsCool** [comment]
This shouldn't override your config now and should allow you just to put fallbacks in your config if a server returns -1 :)
