### ISSUE TITLE
Minecraft 1.13 Stairs is not being connected!

### ISSUE THREAD

**Issue by Simon942** [MylesIsCool/ViaVersion#1068]
**Describe the bug, provide any errors**
The problem is the stairs is not being displayed correctly like in older versions.
The stairs is displaying as not connected together with other stairs.
Example if you set a stair at 90 degress and another one at 180 degress they will normally display as connected, but if you login in 1.13.2 it's displaying as not connected just like a single stair, that is placed randomly.

**How can we reproduce it?**
1. Login on 1.13'
2. Look at a stair that should been connected with another stairs

**Expected behaviour**
There is no errors logs in the console.

**ViaVersion Dump:**
https://dump.viaversion.com/e6b596b331a1582a4f02cff72ae6f6ac6afa17ec26d815cbde66d3491659a541

**Additional server info**
I use Spigot 1.8.8 (Latest version) 
The server system is connected up with the proxy system fork: Waterfall

**Comment by krusic22** [comment]
Look at #856 and #1061

**Comment by Simon942** [comment]
Alright, so a cache bug?
It doesn't tell me how to clear the cache and also fix the issue.

**Comment by shedaniel** [comment]
No, this is a bug where clients no longer auto link the blocks like fences and stairs together. In the 1.13 update, or aka the technical update or idc, servers will tell the clients how the blocks are linked. So ViaVersion needs to send stuff to tell the clients to link them. #1061 is a WIP prototype but it has been reported that it consumes ram like hell.
