### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by DarkFort** [MylesIsCool/ViaVersion#1070]
Too much warning 
[log.txt](https://github.com/MylesIsCool/ViaVersion/files/2545745/log.txt)
https://dump.viaversion.com/7eb174ef08c30537a9bfbcb0acab11960885d2994ab11dae3641875f3590b5c5

**Comment by MylesIsCool** [comment]
You're using dev builds which aren't ready for production. 
 - ViaBackwards
