### ISSUE TITLE
Kicked for spamming

### ISSUE THREAD

**Issue by linuxhus** [MylesIsCool/ViaVersion#1072]
**Describe the bug, provide any errors**
no errors

**How can we reproduce it?**
1. Login on 1.13.2'
Server 1.12.2

**Expected behaviour**
Users are kicked for spamming, while write a command or message in the chat

**Screenshots**

**ViaVersion Dump:**

**Additional server info**
Bungeecord with viaversion build 255

**Comment by MylesIsCool** [comment]
See config option for 1.13 auto complete.
