### ISSUE TITLE
ViaVersion v1.6.0 Task Exception Spamming Console

### ISSUE THREAD

**Issue by chilybones222** [MylesIsCool/ViaVersion#1074]
**Describe the bug, provide any errors**
This task exception is being spammed continuously in my console https://hastebin.com/vudaxosape.pl

**How can we reproduce it?**
1. Use Spigot 1.12.2
2. Using latest version of ViaBackwards and ViaRewind

**Expected behaviour**
N/A

**Screenshots**
N/A

**ViaVersion Dump:**
https://dump.viaversion.com/8ac8d8c645161aa164b8bc3ef0aba46271f50533de793d1cbf04c79a026ef974

**Additional server info**
I use BungeeCord and Spigot

**Comment by creeper123123321** [comment]
Update ViaRewind
