### ISSUE TITLE
Can't save Books

### ISSUE THREAD

**Issue by Fabrimat** [MylesIsCool/ViaVersion#1076]
#1044 still happens with ViaVersion-1.6.1-SNAPSHOT compiled from #1061 on a 1.13.1 Server with 1.13.2 clients.

_Originally posted by @Fabrimat in https://github.com/MylesIsCool/ViaVersion/issues/1044#issuecomment-437100453_

**Comment by MylesIsCool** [comment]
Have you tried with the latest build which isn't connecting blocks, can you verify if it's present in this build?

https://ci.viaversion.com/job/ViaVersion/

**Comment by Fabrimat** [comment]
Yes, the issue persist.

**Comment by YourturnGaming** [comment]
Can Confirm this issue with latest build as well. 

https://pastebin.com/MqCQrYWK
