### ISSUE TITLE
Kick from the server

### ISSUE THREAD

**Issue by DanielAlves123** [MylesIsCool/ViaVersion#1080]
**Describe the bug, provide any errors**
When I join the server on 1.12 after some time I get kicked with this error. This can happen on join, on tp to another player. Kicks with: https://cl.ly/2a3d587cbfa9
https://pastebin.com/raw/0ABhJEia

**ViaVersion Dump:**
https://pastebin.com/raw/xfyBY9fX

**Additional server info**
bungee
This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by DanielAlves123** [comment]
It was caused by PacketPlayOutEntityEquipment. Why armor bar is not updating properly btw?

**Comment by MylesIsCool** [comment]
If you're getting those errors you have a plugin doing something wrong or badly (invalid armour slot ids probably). I can't help you if you're not willing to provide a proper plugin list, I'd suggest removing plugins to narrow down the cause.

Armour after 1.8 is controlled by attributes which ViaVersion adds, in rare cases (usually other plugins doing something) it doesn't work.
