### ISSUE TITLE
Cant build up on 1.12.2

### ISSUE THREAD

**Issue by DanielAlves123** [MylesIsCool/ViaVersion#1086]
While being on 1.12.2 you cant simply build up by placing blocks under yourself. Like it would get your position being too short to place a block, while in reality you could do that.

**Comment by MylesIsCool** [comment]
Consider filling out issues fully before reporting them - https://github.com/MylesIsCool/ViaVersion/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Will reopen when the issue is filled out properly.

**Comment by DanielAlves123** [comment]
@MylesIsCool 
Describe the bug, provide any errors: While being on 1.12.2 you cant simply build up by placing blocks under yourself. Like it would get your position being too short to place a block, while in reality you could do that.

How can we reproduce it? ^
Expected behaviour ^
Screenshots -
ViaVersion Dump:
https://pastebin.com/raw/NcDbEMJN
