### ISSUE TITLE
Can't build up on 1.12

### ISSUE THREAD

**Issue by HAMMERxPL** [MylesIsCool/ViaVersion#1087]
Describe the bug, provide any errors: While being on 1.12.2 you cant simply build up by placing blocks under yourself. Like it would get your position being too short to place a block, while in reality you could do that.

How can we reproduce it? ^
Expected behaviour ^
Screenshots -
ViaVersion Dump:
https://pastebin.com/raw/NcDbEMJN
Additional server info: bungeecord

**Comment by MylesIsCool** [comment]
See https://github.com/MylesIsCool/ViaVersion/issues/592

You can either switch from Paper which will disable the patch, modify paper to fix the faulty patch or modify viaversion to disable the paper patch (which will cause you more issues than you have now). The patch we provide works relatively well but obviously server and client latency can make it worse.

**Comment by FormallyMyles** [comment]
The patch in question is https://github.com/PaperMC/Paper/commit/8f0aaf3411f52f0650bf4c610488af799f57ffec

Just posting this as this issue will be pinned.
