### ISSUE TITLE
18w45a crash when I join server

### ISSUE THREAD

**Issue by Patbox** [MylesIsCool/ViaVersion#1088]
**Describe the bug, provide any errors**
When I try to join my server with MC 18w45a, it crash

**How can we reproduce it?**
1. Login on 18w45a
2. Join the server
3. The '....' is displayed wrong

**Expected behaviour**
In total, connect to the server

**Screenshots**
https://i.tipr.pl/zoxwx4.gif
Crash report:
https://pastebin.pl/view/4e38079f
**ViaVersion Dump:**
https://dump.viaversion.com/724c7bd2480936ef720b9e9ac0ea39559b1a13b9d1dd376f1785054bb07f591b

**Additional server info**
I use Traveltine (Bungee fork). On the lobby I use Paper 1.12.2. Plugins:
AdvancedPortals, AuthMe, AuthMeBridge, FastLogin, NoChat, NoCmds, PermissionsEx, PlaceholderAPI, RealTime, SkinsRestorer, SpigotBoard, SuperLobby, Tablist

It happens too on server without BungeeCord.

**Comment by MylesIsCool** [comment]
See above, if it turns out to be something we can fix in a later snapshot we will :)
