### ISSUE TITLE
Invisible entity for client superior to 1.8.9 server

### ISSUE THREAD

**Issue by xion87** [MylesIsCool/ViaVersion#1091]
**Describe the bug, provide any errors**
Entity are invisible in some rare cases for 1.12.2 client that login a server with 1.8.8 viaversion

A clear and concise description of what the bug is. Can you https://hastebin.com the error?
Nope

**How can we reproduce it?**
1. Login into a 1.8.9 server with viaversion by using 1.12.2
2. entity like armor stand, villager, animals, sometimes are invisible in rare cases, you can hear only sounds for them

**Expected behaviour**
Entity must stay visibile

**Screenshots**
None

**ViaVersion Dump:**
https://dump.viaversion.com/47d8ae6906d9baec00bc4e8ced5166dc6432b7164d17fee4944b1d39e8cd68b2

**Additional server info**
Waterfall
Paperspigot 1.8.8

**Comment by MylesIsCool** [comment]
Unless we can consistently replicate this / others can replicate, we unfortunately can't fix it.

Closing this for now, but if anyone can provide a scenario for this will happily investigate.
