### ISSUE TITLE
Riding on enderpearl

### ISSUE THREAD

**Issue by DanielAlves123** [MylesIsCool/ViaVersion#1094]
When riding enderpearl on 1.8 client you dont really ride it you just like teleport behind it.

**Comment by MylesIsCool** [comment]
This issue isn't related to ViaVersion.

**Comment by Luuzzi** [comment]
Sorry for the necropost, but the problem actually exists. On 1.8 servers with ViaVersion installed, on a 1.16.5 client, when I throw an ender pearl and set a player as a passenger, it seems to teleport abruptly behind them, and the packet responsible for setting the passenger doesn't seem to be triggered. Could you please review your code to check this? The issue may have arisen with the introduction of the Mount packet. And on the 1.8 client, everything works fine.

**Comment by Luuzzi** [comment]
@FormallyMyles sorry for the necropost, but the problem actually exists. On 1.8 servers with ViaVersion installed, on a 1.16.5 client, when I throw an ender pearl and set a player as a passenger, it seems to teleport abruptly behind them, and the packet responsible for setting the passenger doesn't seem to be triggered. Could you please review your code to check this? The issue may have arisen with the introduction of the Mount packet. And on the 1.8 client, everything works fine.

**Comment by FormallyMyles** [comment]
> @FormallyMyles sorry for the necropost, but the problem actually exists. On 1.8 servers with ViaVersion installed, on a 1.16.5 client, when I throw an ender pearl and set a player as a passenger, it seems to teleport abruptly behind them, and the packet responsible for setting the passenger doesn't seem to be triggered. Could you please review your code to check this? The issue may have arisen with the introduction of the Mount(Set Passengers) packet. And on the 1.8 client, everything works fine.

I'd make a new issue for this identifying what versions it starts to happen on with full details.

**Comment by Luuzzi** [comment]
Thank you for fast response, Before I need to be sure of the problem, I will then do a more thorough investigation.

**Comment by Luuzzi** [comment]
Forget it. This is not a ViaVersion problem. Sorry for bothering you over nothing :(
