### ISSUE TITLE
Internal Exception io.netty.handler.codec.DecoderException: com.google.gson.JsonSyntaxException: JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1

### ISSUE THREAD

**Issue by Tedm2018** [MylesIsCool/ViaVersion#1097]
I have ViaVersion and ViaBackwards
My spigot server is 1.12.2
when I try to use 1.9 it gives this error and kicks me when I try to login
Internal Exception io.netty.handler.codec.DecoderException: com.google.gson.JsonSyntaxException: JsonReader.setLenient(true) to 
accept malformed JSON at line 1 column 1
but 1.10, 1.11, 1.12, and 1.13 works

**Comment by MylesIsCool** [comment]
ViaBackwards handles backwards compatible.

This is probably scoreboard / chat related honestly best way is just to experiment, test without plugins, scoreboard data etc.
