### ISSUE TITLE
Can't build under yourself on 1.11 or higher

### ISSUE THREAD

**Issue by DanielAlves123** [MylesIsCool/ViaVersion#1098]
**Describe the bug, provide any errors**
Connect to the server with 1.11/1.12. Try placing blocks under yourself and jumping at the same time to build higher. You can't really place blocks like that.

**How can we reproduce it?**
Connect to the server with 1.11/1.12. Try placing blocks under yourself and jumping at the same time to build higher. You can't really place blocks like that.

**Expected behaviour**
Make it possible to place blocks.

**Screenshots**
-

**ViaVersion Dump:**
- latest viaversion

**Additional server info**
BungeeCord

**Comment by MylesIsCool** [comment]
Read #1087

**Comment by DanielAlves123** [comment]
@MylesIsCool you know its totally bugged on versions higher than 1.9 probably and you dont have to place these blocks under yourself but it happens when you place blocks near you.

**Comment by MylesIsCool** [comment]
> @MylesIsCool you know its totally bugged on versions higher than 1.9 probably and you dont have to place these blocks under yourself but it happens when you place blocks near you.

Perhaps you should consider reading the issue linked above, it's not something we can fix - modify paper/switch.

**Comment by DanielAlves123** [comment]
@MylesIsCool thats a very annoying 100% bug. What should we modify or change to get this work?

**Comment by MylesIsCool** [comment]
https://github.com/PaperMC/Paper/commit/8f0aaf3411f52f0650bf4c610488af799f57ffec
