### ISSUE TITLE
entity meta data error?

### ISSUE THREAD

**Issue by timr2000** [MylesIsCool/ViaVersion#110]
### What version of ViaVersion are you using? Type /ver viaversion
# 0.4.7
### What version of Spigot are you using? Type /ver
# 1.8.8
### What plugins are you using? /plugins
Plugins (44): CleanroomGenerator, HubBasics, WorldEdit, HealthBar, SimpleElevator, Essentials, GroupManager, TuxTwoLib, Buycraft, BetterChairs, Lockette, Votifier, LaggRemover, WorldGuard, HugeItems, EssentialsChat, BossBarAPI, EssentialsGeoIP, TimeIsMoney, ViaVersion, CustomJoinItems, GAListener, Vault, RealTime, DrugMeUp, TitleManager, MultiInv, PlotSquared, ProtocolLib, LibsDisguises, AAC, ASkyBlock, ChestCommands, AgarMC, SexyMotd, Autorank, Multiverse-Core, Shopkeepers, GriefPrevention, SkyWarsReloaded, ItemSlotMachine, HolographicDisplays, WarpPortals, InfoBoardReborn
### Is there an error in the console? Use pastebin.com. Is there a kick message?

http://pastebin.com/PkAYrDb2

**Comment by MylesIsCool** [comment]
Don't use bossbar.

**Comment by timr2000** [comment]
Sure :-)
