### ISSUE TITLE
Lag Server + Error java console - 1.13.2

### ISSUE THREAD

**Issue by Guest1131** [MylesIsCool/ViaVersion#1101]
Hey,

I installed the plugins on spigot 1.13.2:

ProtocolSupport - Last build from Jenkins

ViaVersion - Last Build by Jenkins

ViaRewind - Last build by Jenkins

ViaBackRewards - Last build by Jenkins

I logged in with client 1.12.2, and I get a ViaVersion error java in the console, and it reads the server a lot.

**Comment by MylesIsCool** [comment]
Not enough info, fill out the issue template and then we'll help you - https://github.com/MylesIsCool/ViaVersion/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
