### ISSUE TITLE
1.13.2 - lag server + error java console

### ISSUE THREAD

**Issue by Guest1131** [MylesIsCool/ViaVersion#1102]
**Describe the bug, provide any errors**

https://hastebin.com/ecufihiqoz.pl

**How can we reproduce it?**

I entered with the client 1.12.2, the server reads a lot, and appears that error in java in the console

**Expected behaviour**

I expected everything to work properly.

**ViaVersion Dump:**

https://dump.viaversion.com/af281c922b32924c20e46664348fcac892463edfc3b6e80e0ef526e7c050f95a

**Additional server info**

Server : Spigot 1.13.2

List Plugins : plugin : https://hastebin.com/piyoliqira.nginx

**Comment by MylesIsCool** [comment]
This is a bug we're investigating with ProtocolSupport, we're currently able to reproduce ourselves.

cc: @7kasper
