### ISSUE TITLE
Fences do not connect on 1.13.2 client thats connected to 1.12.2 server

### ISSUE THREAD

**Issue by marvic24099** [MylesIsCool/ViaVersion#1111]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?

**How can we reproduce it?**
1. Login on 1.13.2
2. Place down to fences to connect them
3. The fences will not connect

**Expected behaviour**
The fence should connect

**Screenshots**

**ViaVersion Dump:**
- https://dump.viaversion.com/c921a45a990b8cd8db91ad61b5e959151fbcad2eb54354ff3fbf12bb8babf695

**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?

**Comment by MylesIsCool** [comment]
Consider reading the changelog on a release before reporting an issue.

If you also read through the issues you'll find our dev build is testing a fix enabled by an option.

**Comment by creeper123123321** [comment]
#1093
