### ISSUE TITLE
1.12 kick from the server

### ISSUE THREAD

**Issue by HAMMERxPL** [MylesIsCool/ViaVersion#1112]
https://pastebin.com/raw/Mr7ZL77r
Latest viaversion, viarewind and viarewind legacy support.

**Comment by krusic22** [comment]
Please follow the issue template and attach the viaversion dump link.

**Comment by MylesIsCool** [comment]
Will reopen when all info is provided, see issue template https://github.com/MylesIsCool/ViaVersion/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by HAMMERxPL** [comment]
@krusic22 @MylesIsCool Join the server with 1.12, get kicked from the server? What else do you want?

**Comment by creeper123123321** [comment]
c5c7d36bd11696f5414ecc5640f1e0dbe12cc5fa is the cause of this issue

**Comment by HAMMERxPL** [comment]
@creeper123123321 so you added a function to kick 1.12 players with this commit?

**Comment by creeper123123321** [comment]
It is fixed. https://ci.viaversion.com/job/ViaVersion/
