### ISSUE TITLE
Random disconnect error

### ISSUE THREAD

**Issue by Wouterkaas** [MylesIsCool/ViaVersion#1114]
Hello, i have a bungeecord server with 5 servers, all run on 1.9.4 the bungeecord too because of the giant end update, i want to use viaversion to let players with higher version on, so i install viaversion on bungeecord but then when i join i get kicked for "Disconnected" In the lobby console it indeed says that i was kicked, so I did join the lobby but i get directly kicked

**Comment by MylesIsCool** [comment]
Please fill out the issue template fully https://github.com/MylesIsCool/ViaVersion/blob/master/.github/ISSUE_TEMPLATE/bug_report.md then we'll reopen and look into. Use debug=true in server.properties to display full errors.
