### ISSUE TITLE
Random disconnect error

### ISSUE THREAD

**Issue by Wouterkaas** [MylesIsCool/ViaVersion#1115]
Hello, i have a bungeecord server with 5 servers, all run on 1.9.4 the bungeecord too because of the giant end update, i want to use viaversion to let players with higher version on, so i install viaversion on bungeecord but then when i join i get kicked for "Disconnected" In the lobby console it indeed says that i was kicked, so I did join the lobby but i get directly kicked

Viaversion error bungeecord: https://hastebin.com/nebemarapi.bash

Error in lobby server: https://hastebin.com/ufohehajeq.bash

Issue screenshot: https://gyazo.com/0e4846260e8fbc83b59a075e6cf61975

Plugins bungeecord: https://gyazo.com/6e2fd09f091e6f197ce93f0410a1702a

Plugins on lobby server: https://gyazo.com/a9cb3fea37b767d9f3d6f421ae79fcea

Bungee = Bungeecord 1.9.4 Build #1152

Lobby = Spigot 1.9.4 Latest / Final release

**Comment by Wouterkaas** [comment]
Viaversion dump: https://dump.viaversion.com/8ddbce1770a718dfe5d36b795cb207fe0ab72eb0a99529cce8d3b34b0ad72187

**Comment by krusic22** [comment]
You need to update your Bungee version.

**Comment by Wouterkaas** [comment]
now it says it won't bind to its ip?

**Comment by Wouterkaas** [comment]
Could not bind to host /144.217.223.82:25585

**Comment by krusic22** [comment]
You might already be running something on that port or you don't have permission to use that address. 
Use 0.0.0.0 instead (for Bungee).

**Comment by Wouterkaas** [comment]
Really weird i use bought hosting(shockbyte) this never happens

**Comment by Wouterkaas** [comment]
an you hgelp?

**Comment by krusic22** [comment]
If you use the old version of Bungee does it work again?

**Comment by Wouterkaas** [comment]
Yes

**Comment by Wouterkaas** [comment]
Help please?

**Comment by danjono** [comment]
Try running your server with no plugins except ViaVersion. Ensure you have the latest version as well as the latest version of BungeeCord and Spigot for your server.

If that works then start adding your plugins back onto your Proxy and Server slowly until you can work out what is causing it.

**Comment by Wouterkaas** [comment]
ok

**Comment by danjono** [comment]
Any update?

**Comment by Wouterkaas** [comment]
Yes, it is a bungeecord config error, I deleted the whole config, it
worked(on a port that is normal already used and I shouldn't have access to
because it probably already used by another shockbyte user, so I added the
lobby server, once I restart it it changes the port back and gives me the
cannot bind error again,now I ordered a deticated IP, let's see if that can
solve the problem

Op di 11 dec. 2018 23:37 schreef danjono <notifications@github.com>:
