### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by BiGUNMAN** [MylesIsCool/ViaVersion#112]
### What version of ViaVersion are you using? Type /ver viaversion
0.4.8
### What version of Spigot are you using? Type /ver
1.8.8: http://i.imgur.com/UCBqnwM.png
### What plugins are you using? /plugins
http://i.imgur.com/wowFiSF.png - Yes... Tell me about the number..
### How does this error happen? login? using an item? 
Upon login. I can join my hub server running ViaVersion 0.4.8 but once I join the gamemode server I get disconnectted with an kick message. I also tried directly joining the gamemode server and that did not work (got exact same kick message). The plugins in the PL list are the ones on the gamemode server.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
Kick Message: http://i.imgur.com/6tjeR9W.png
Server Error: None.
Bungeecord Error: http://pastebin.com/y6Q5NX0F

**Comment by Paulomart** [comment]
Remove some plugins and try to track down the cause of this. Thanks

**Comment by MylesIsCool** [comment]
AAC is not compatible, try removing it and joining without.

**Comment by MylesIsCool** [comment]
Gonna close, assuming it's AAC.

**Comment by BiGUNMAN** [comment]
I run AAC on my Hub server so I can't imagine it causing the problem.

**Comment by MylesIsCool** [comment]
Using AAC on any server while this plugin is active will prevent it from working, you can look at our plugin page for suggested settings to fix this for now.

**Comment by BiGUNMAN** [comment]
Just removed AAC, got this: http://i.imgur.com/pHERlKn.png
