### ISSUE TITLE
Could not find type id -1

### ISSUE THREAD

**Issue by Straiker123** [MylesIsCool/ViaVersion#1127]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?

1. Login on 1.13.1 Kostka (Server version: 1.13.1)'
2. Go to server Kostka MiniGames (Server version: 1.12.2)
3. and i get this error: [ViaVersion] Could not find type id -1 isObject=false
4. And if i /reload server i cant see NPC types like a Pig , Villager etc.

If i go to other world i get this error to console ... [ViaVersion] Could not find type id -1 isObject=false

I have no ScreenShorts

https://dump.viaversion.com/070868e66008f8ab93f3bbac2274bfd808f3ce7e8f2e509940e061dcf02911a9

BungeeCord

**Comment by MylesIsCool** [comment]
This is down to a plugin sending bad data (possibly bad ordering), you can suppress metadata errors in the ViaVersion config otherwise.
