### ISSUE TITLE
Using 1.13.2 with latest viaversion and viarewind DEV-builds lots of WARNS spammed console

### ISSUE THREAD

**Issue by axemwa** [MylesIsCool/ViaVersion#1128]
**Describe the bug, provide any errors**
Using 1.13.2 with latest viaversion and viarewind DEV-builds lots of WARNS spammed console all of a sudden

**How can we reproduce it?**
1. Add latest DEV builds of viarewind and viaversion and the latest release build of via backwards to 1.13.2 plugin folder
2. Start Minecraft 1.13.2 Paper Spigot 488 server
3. WARNS spamm something to do with materials

**Expected behaviour**
Not for WARNS to spam? Unsure

**Screenshots/paste links**
WARNS SPAMMING PART 1
https://pastebin.com/HH3TbLdF
WARNS SPAMMING PART 2
https://pastebin.com/nBZcgAPm

**ViaVersion Dump:**
- https://dump.viaversion.com/b8583afa074235d8b35d5e421b7cc0890de1282c52bdbbb6529271f45a39e8a6

**Comment by MylesIsCool** [comment]
-DEV builds may not be complete hence the tag, this is from ViaBackwards

**Comment by axemwa** [comment]
I know just letting yas know anyway I like to try and help, should I report this to ViaBackwards?

**Comment by MylesIsCool** [comment]
1.13 support isn't finished so the output is actually a indicator of what needs doing :)
