### ISSUE TITLE
Armor status

### ISSUE THREAD

**Issue by DanielAlves123** [MylesIsCool/ViaVersion#1131]
When you break your armor part it doesnt update and you still see full armor for example.

**Comment by MylesIsCool** [comment]
Once again, like several previous issues, you need to fill out the full template because we have no idea on versions etc. I'll reopen when you've done this

**Comment by DanielAlves123** [comment]
@MylesIsCool latest versions of all plugins, 1.8.8 paperspigot. What else do you want to know?
