### ISSUE TITLE
No velocity bug

### ISSUE THREAD

**Issue by DanielAlves123** [MylesIsCool/ViaVersion#1136]
Everyone has no velocity and no knockback, on newest bungeecord and viaversion.

**Comment by MylesIsCool** [comment]
Until you fill out the bug report template properly, I'm closing this issue. 

https://github.com/MylesIsCool/ViaVersion/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by DanielAlves123** [comment]
@MylesIsCool why the fuck would i use this template
