### ISSUE TITLE
Glass panes

### ISSUE THREAD

**Issue by ridalarry** [MylesIsCool/ViaVersion#114]
Using the latest spigot and ViaVersion 0.9, the glass panes is bugged I dont know how to describe it here is a picture hopefully will make you understand https://gyazo.com/78ece0d2ccdde933d3e773985938139f

**Comment by MylesIsCool** [comment]
This issue behind this one is the bounding box has changed between versions.

**Comment by MylesIsCool** [comment]
I'm going to close this for now, I've discussed solutions and they'd allow people to abuse hacked clients with panes so we're not going to change it for now. There's no way we can tell 1.9 a certain bounding box.

If it becomes possible we'll add an optional option in the future but this is not on the short term road map.
