### ISSUE TITLE
ViaVersion 1.6.0 Error on startup

### ISSUE THREAD

**Issue by LudnicaKiller** [MylesIsCool/ViaVersion#1144]
Hello,
There is an error in console on startup but the plugin is working properly: https://pastebin.com/xybYNLcA
Server version: This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by MylesIsCool** [comment]
From the looks of it, it might of just been a hiccup in Spigets server which is what we use for update checking. This is safe to ignore but I'll keep an eye on it.
