### ISSUE TITLE
task 466

### ISSUE THREAD

**Issue by Straiker123** [MylesIsCool/ViaVersion#1145]
https://hastebin.com/avusasilim.bash

**How can we reproduce it?**
1. Login on 1.13.1'
2. And i get this error to console

https://hastebin.com/avusasilim.bash

https://dump.viaversion.com/8ae2352db05567eee04b5cb523365a5ad8296c2cb7a55dc9dbdfd83ba62a627d

BungeeCord

**Comment by electronicboy** [comment]
Duplicate of #1144

**Comment by MylesIsCool** [comment]
Should be fixed no, kudos to inventivetalent :)
