### ISSUE TITLE
Chunk Loading Bugs

### ISSUE THREAD

**Issue by MultiDJRoni** [MylesIsCool/ViaVersion#115]
The Chunk Loading is Bugy (Its not the ChunkLoader Plugin, i tested it) and i sometimes cant playe Blocks until i die, usually its also becaused of the Chunk Bug.

The Version, Plugins, Bugs etc. you can see in the Video!
Link: https://youtu.be/J5WxUA1ZvAw

**Comment by MylesIsCool** [comment]
This issue is already reported. #38

**Comment by MultiDJRoni** [comment]
Please ReOpen this because #38 is closed. I dont think its the client because on HyPixel and on rewinside it works finde.
