### ISSUE TITLE
Fences, Stone walls and Glass Panes won't connect

### ISSUE THREAD

**Issue by felix920506** [MylesIsCool/ViaVersion#1151]
**Describe the bug, provide any errors**
A clear and concise description of what the bug is. Can you https://hastebin.com the error?

**How can we reproduce it?**
1. Login on 1.13'
2. Fences, Stone walls and Glass panes are not displayed properly

**Expected behaviour**
All fences, Stone walls and glass panes should display properly

**Screenshots**
![2019-01-13_00 26 22](https://user-images.githubusercontent.com/25688628/51075753-f7e9a480-16ca-11e9-9682-44baecaa405f.png)
![2019-01-13_00 26 27](https://user-images.githubusercontent.com/25688628/51075754-f7e9a480-16ca-11e9-882b-7ee0845f8b81.png)
![2019-01-13_00 26 41](https://user-images.githubusercontent.com/25688628/51075755-f7e9a480-16ca-11e9-942a-01ae54054f57.png)
![2019-01-13_00 26 51](https://user-images.githubusercontent.com/25688628/51075756-f7e9a480-16ca-11e9-8f01-40057178affc.png)
![2019-01-13_00 27 06](https://user-images.githubusercontent.com/25688628/51075757-f8823b00-16ca-11e9-9674-21b1fabf7bc7.png)

**ViaVersion Dump:**
- Type /viaversion dump, and put the link here.
https://dump.viaversion.com/4dec8c0950575fa42f2b1c93d19f056c234696b541bb293a7bf48b0b0ddeecd4
**Additional server info**
Do you use a proxy (eg. BungeeCord)? What software do you use and what plugins?
Viaversion is installed on Bungeecord but issue still exists when it is installed on backend servers

**Comment by MylesIsCool** [comment]
See latest dev builds - https://github.com/MylesIsCool/ViaVersion/pull/1093
