### ISSUE TITLE
No key for "x"

### ISSUE THREAD

**Issue by Kizburb** [MylesIsCool/ViaVersion#1155]
**Describe the bug, provide any errors**
Error on server startup with ViaVersion
https://pastebin.com/yKgJ2xHA

**How can we reproduce it?**
1. Install plugin
2. Start server
3. Profit???

**Expected behaviour**
A startup without errors.

**Screenshots**

**ViaVersion Dump:**
https://dump.viaversion.com/ea3381cc9e89ae73628d25f73959ccdfc48b056298225b105230aba26f647d57

**Additional server info**
Paperspigot 1.12.2 plugins should be irrelevant for this error.

**Comment by MylesIsCool** [comment]
Don't use ViaBackwards-DEV

**Comment by Kizburb** [comment]
I'm using ViaBackwards Dev because of the "sent an invalid keepalive! pending keepalive: false got id: 0 expected id: 0" error.

**Comment by Kizburb** [comment]
Could you link please? I think I had the latest build before I changed to dev.
