### ISSUE TITLE
Armor status not working properly

### ISSUE THREAD

**Issue by Ronaldinho12** [MylesIsCool/ViaVersion#1157]
**Describe the bug, provide any errors**
Armor status doesn't update when part of armor is broken or when you change armor.

**How can we reproduce it?**
Armor status doesn't update when part of armor is broken or when you change armor.

**Expected behaviour**
Armor status should work properly.

**Screenshots**
-

**ViaVersion Dump:**
https://pastebin.com/raw/mRNMxuCP

**Additional server info**
BungeeCord

**Comment by MylesIsCool** [comment]
Should be fixed in the latest build

**Comment by Ronaldinho12** [comment]
@MylesIsCool works better, how about situations when you equip armor with a plugin or when not respawning player?

**Comment by MylesIsCool** [comment]
Not possible without constant updating which to me seems a hassle for what it's worth
