### ISSUE TITLE
Door facing issue

### ISSUE THREAD

**Issue by SubZeroExtaByte** [MylesIsCool/ViaVersion#1159]
I'm using the latest viaversion build, 1.6.0 and all the doors are facing the way and you can just half open them. Am i doing something wrong or it's a know bug?
![2019-01-16_20 46 19](https://user-images.githubusercontent.com/38505743/51274589-d856c280-19cf-11e9-8710-3c75cf9c7ff7.png)

**Comment by MylesIsCool** [comment]
Use latest dev and enable block connections in the config.

**Comment by SubZeroExtaByte** [comment]
sorry, where can i find it?

**Comment by creeper123123321** [comment]
https://ci.viaversion.com/job/ViaVersion/

**Comment by SubZeroExtaByte** [comment]
thank you very much
