### ISSUE TITLE
can't interract command blocks

### ISSUE THREAD

**Issue by Wilco2998** [MylesIsCool/ViaVersion#116]
### What version of ViaVersion are you using? Type /ver viaversion
0.4.9
### What version of Spigot are you using? Type /ver
1.8.8
### What plugins are you using? /plugins
only viaversion
### How does this error happen? login? using an item? 
can't interact with command_blocks while op and gm 1
### Is there an error in the console? Use pastebin.com. Is there a kick message?
nothing

**Comment by StamBoom** [comment]
Yeah, I'm currently looking into it

**Comment by MylesIsCool** [comment]
Fixed in latest version <3 @StamBoom
