### ISSUE TITLE
PaperPatch blocks building up

### ISSUE THREAD

**Issue by Ronaldinho12** [MylesIsCool/ViaVersion#1169]
**Describe the bug, provide any errors**
PaperPatch blocks building up. It messes when someone is building a bridge too. It works better when class looks like this, but I'm sure it can be done better: https://pastebin.com/raw/8Qu7u4UG

**How can we reproduce it?**
Start building up or making a bridge while shifting on 1.12 for example.

**Expected behaviour**
Building up and making a bridge should work perfect.

**Screenshots**
-

**ViaVersion Dump:**
https://pastebin.com/raw/FcyAMvaK

**Additional server info**
BungeeCord

**Comment by MylesIsCool** [comment]
See https://github.com/MylesIsCool/ViaVersion/issues/1098

**Comment by Ronaldinho12** [comment]
@MylesIsCool I can't really pr and you can do better changes. Is it possible to fix that by changing the source code of paper?

**Comment by Ronaldinho12** [comment]
@MylesIsCool can you implement it in the ViaVersion or give link to this code?

**Comment by MylesIsCool** [comment]
> @MylesIsCool can you implement it in the ViaVersion or give link to this code?

The paper link in the other issue is the patch. It's not possible for VV to patch this.

**Comment by Ronaldinho12** [comment]
@MylesIsCool how to edit paper source code to fix that?

**Comment by MylesIsCool** [comment]
> @MylesIsCool how to edit paper source code to fix that?

You'd need to apply that patch, on the specific way to do it you'd have to find that out yourself (mainly because I'm not versed with modifying paper / porting patches)
