### ISSUE TITLE
exceptionCaught() Broken Pipe

### ISSUE THREAD

**Issue by Bodoo** [MylesIsCool/ViaVersion#117]
http://bodooo.de/BildUploads/spigotviaversionbug.png

This error spams in the console after a few seconds and puts the root cpu on 9999%.
The spigot server crashes then and hangs.

I could not even copy the error thats why the screenshot.

Thanks

**Comment by MylesIsCool** [comment]
Could you follow the format for issues and provide, your version, plugins and spigot version?

**Comment by Bodoo** [comment]
Plugins: PermissionsEx, Protocollib, Buycraft
Spigot version: 1.8.8
BungeeCord 1.8/1.9
ViaVersion plugin version: 0.4.9

**Comment by HugoDaBosss** [comment]
Could you post more of the error? There should be a lot more similar errors.

**Comment by rj0495** [comment]
I get the exact same behind bungee. Without bungee works fine though

**Comment by HugoDaBosss** [comment]
@Bodoo Can you confirm that you are using Bungee as well?

**Comment by rj0495** [comment]
https://www.spigotmc.org/threads/viaversion.127105/page-18 Post 359 references the same problem

**Comment by MylesIsCool** [comment]
Are you using Bungee Cord, if so what plugins?

**Comment by Bodoo** [comment]
Yeah, we're using Bungeecord 1.8/1.9

**Comment by xkuyax** [comment]
Im in the same network as @Bodoo and yes, we are using bungeecord (commit a7664a5) with some small modifications to command handling, but nothing which should interact with packet de/encoding, the same is for our bungeecord plugins which are not really interacting with bungeecord packets, except for sending messages. On our server we are running spigot version 1.8.8 (commit e4d4710-e1ebe52) with a lot of custom plugins which are interacting with protocollib (build b231) and a tag plugin which modifies and sends scoreboard packets for tag and tablist colors which is working fine. 

These are the exceptions we are getting on our hub server with the newest via version installed  http://hastebin.com/uwixodecuv.avrasm

**Comment by rj0495** [comment]
@xkuyax Can you send a Plugin list?

**Comment by rj0495** [comment]
for Both Bungee and the Hub?

**Comment by MylesIsCool** [comment]
I've been informed that this bug is now fixed.
