### ISSUE TITLE
Problem displaying ScoreBoard - 1.12.2 - 1.13.2

### ISSUE THREAD

**Issue by Guest1131** [MylesIsCool/ViaVersion#1170]
Hi, I noticed that there is a problem, the scoreboard, example FeatherBoard, is not displayed correctly on the screen, in width, you see only half of the writing, and does not expand automatically.

This problem is with any scoreboard plugin, not just FeatherBoard.

And a problem with ViaBackRewards?

Server Usage 1.13.2 , and Client Usage 1.12.2

**Comment by Gerrygames** [comment]
This is not an issue with ViaVersion, but ViaBackwards. It should be fixed in my pull request https://github.com/Matsv/ViaBackwards/pull/84.

**Comment by Guest1131** [comment]
Normally, the scoreboard, should widen itself, based on how much and along the text, but it does not.

**Comment by Gerrygames** [comment]
Update to the latest dev build as soon as the pull request mentioned is merged. Or clone the repo, merge the pull request and build the project yourself.

**Comment by Gerrygames** [comment]
The pull request has just been merged, so just download the latest build right [here](https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/).
If you are still having issues, please report them [here](https://github.com/Matsv/ViaBackwards/issues).

**Comment by Guest1131** [comment]
I installed the new build, the problem for a while has been solved, but not entirely, the problem there is still :( 

In the scoreboard configuration, I put www.militarycraft.it , and instead only www.militarycraf appears

![immagine](https://user-images.githubusercontent.com/43791580/51613554-f5d1e200-1f23-11e9-9915-44abd2a39390.png)

**Comment by Gerrygames** [comment]
There is a smaller limit for team prefix and suffix in 1.12.2 than in 1.13. We can't do anything about that.
