### ISSUE TITLE
Problem ViaVersion or Viabackrewards - connecting to servers via Bungeecord

### ISSUE THREAD

**Issue by Guest1131** [MylesIsCool/ViaVersion#1176]
**Describe the bug, provide any errors**

The connection to the servers via BungeeCord does not work.

I use the ChestCommands plugin for the compass, and inside I created the menu, with the objects, which when clicked, run the command "server: nameserver_bungee", I click, and nothing happens, no message or teleport appears, nothing at all. And I found that the problem is either ViaVersion or ViabackRewards.

If I use ProtocolSupport, this problem is gone.

i use server version, spigot 1.13.2 last build

**How can we reproduce it?**
1. Login with client 1.12.2
2. Click on the compass, or use the bungeecord command "server name_server" directly.

**Expected behaviour**

I expected the connection to the server to work as it should.

**ViaVersion Dump:**

https://dump.viaversion.com/db372385cd651618b0903a0133e0e2d715e4b8579fce15cb3f395796d9db7151

**Additional server info**
 
BungeeCord

**Comment by MylesIsCool** [comment]
ViaVersion supports newer versions.

If the issue happens on older versions, it's down to other Via plugins. ViaBackwards isn't 1.13 complete, so use protocol support.

**Comment by Guest1131** [comment]
use ViaBackRewards build : #107

I tried to use the last build, the number : #116

But it doesn't get me on the server, this error message appears: 

![immagine](https://user-images.githubusercontent.com/43791580/51925345-21a30b00-23ef-11e9-8bbc-4a2b5c489054.png)

what?

**Comment by Guest1131** [comment]
use ViaBackRewards build : #107

I tried to use the last build, the number : #116

But it doesn't get me on the server, this error message appears:

**Comment by MylesIsCool** [comment]
ViaBackwards isn't complete, use protocol support.
