### ISSUE TITLE
Flint and steel

### ISSUE THREAD

**Issue by ridalarry** [MylesIsCool/ViaVersion#118]
Im using the latest version of spigot with ViaVersion 0.9 and when a player right click on a block with a flint and steel it will make the sound twice.

**Comment by HugoDaBosss** [comment]
Thanks for opening this issue, i'm going to look and fix this.

**Comment by HugoDaBosss** [comment]
Should be fixed #122

**Comment by MylesIsCool** [comment]
Fixed in next version
