### ISSUE TITLE
reddust/take particle on area_effect_cloud disconnects 1.13 clients

### ISSUE THREAD

**Issue by zedwick** [MylesIsCool/ViaVersion#1180]
**Describe the bug, provide any errors**
Summoning an area_effect_cloud with particle `take` will disconnect a 1.13.2 client on a 1.12.2 server with a NullPointerException error shown in the client.
`reddust` particle also disconnects the client, with no NullPointerException shown.
`cloud` will not disconnect the client.

**How can we reproduce it?**
1. Setup 1.12.2 server
2. Login on 1.13.2'
3. summon an `area_effect_cloud` with particle `take`: `/summon minecraft:area_effect_cloud ~ ~ ~ {Duration:1,Particle:take}`
4. Be disconnected with a NullPointerException

**Expected behaviour**
The take particle is used to hide particles, so an area_effect_cloud with no visible particles would be the desired effect, but any particle would do.

**Additional server info**
Tested behind a BungeeCord proxy, with viaversion installed on the Minecraft server.
MC Server: (git-paper-1339 MC 1.12.2) (Viaversion 2.0.0-SNAPSHOT
 build 285)

**Comment by creeper123123321** [comment]
Can you test https://github.com/creeper123123321/ViaVersion/commit/67ee72a768abbde29361ad84025a77c36eb6cb8e ?

**Comment by MylesIsCool** [comment]
Closing as we've merged this to master :)
