### ISSUE TITLE
Waiting for chunks in 19w05a

### ISSUE THREAD

**Issue by cakoyo** [MylesIsCool/ViaVersion#1183]
**Describe the bug, provide any errors**
No errors, however, when I join the server more than once, the chunks will never load.

**How can we reproduce it?**
1. Login on 1.13.2 server with ViaVersion-DEV for 19w05a (build 194 or 195)
2. Quit the server once
3. Login on the server again

**Expected behaviour**
Chunk loads just like the first time.

**Screenshots**
![Chunks not load](https://i.imgur.com/Htlyo5M.png)

**ViaVersion Dump:**
https://dump.viaversion.com/8c36a6680a005668e821ccfd2e740b8bb75ec421f80da0ed7a192349f40e09f2

**Additional server info**
Tested in Paper 1.13.2

**Comment by cakoyo** [comment]
I've also tested with the default config, but the same on.

**Comment by cakoyo** [comment]
I believe this is a Paper bug.

**Comment by creeper123123321** [comment]
Seems to happen in vanilla servers
