### ISSUE TITLE
Question about block placing on 1.8 server with 1.9+

### ISSUE THREAD

**Issue by Matocolotoe** [MylesIsCool/ViaVersion#1197]
Sometimes, placing blocks very quickly (10+ cps) make them "disappear" in 1.9+ on 1.8.8 Spigot servers. Any value to increase or decrease to prevent that from happening ? I have the latest dev build of ViaVersion.

**Comment by MylesIsCool** [comment]
See https://github.com/MylesIsCool/ViaVersion/issues/1098
