### ISSUE TITLE
1.13 Client -> 1.12.2 Paper spigot incorrectly renders blocks and models

### ISSUE THREAD

**Issue by mio9** [MylesIsCool/ViaVersion#1198]
**Describe the bug, provide any errors**
Redstone wires are all displayed as disconnected pieces, custom models are not loaded as expected (as shown in the picture)
![image](https://user-images.githubusercontent.com/11581624/52927411-c2953e00-337d-11e9-80e0-7489c8e7c149.png)

**How can we reproduce it?**
1. Login to 1.12 server with 1.13
2. (Load up resourcepack with custom model)
3. Redstone is displayed disconnected, custom models are displayed wrongly

**Expected behaviour**
As what we seen with 1.12 client on 1.12 server

**ViaVersion Dump:**
using 1.6.0

**Additional server info**
We use "waterfall"(a fork of bungeecord by papermc) for server proxy, latest build installed and used

**Comment by mio9** [comment]
this issue is not necessarily an issue with ViaVersion itself, since the probability of both minecraft versions being incompatible to each other is high, but still, since I heard that ViaVersion allows connection to "mismatched version" servers by manupulating packets, it **might** be caused by ViaVersion, so yea, idk, but still gonna let other viaversion users willing to let 1.13 players join 1.12 servers know this issue

**Comment by MylesIsCool** [comment]
In regards to resource packs, the format changes between versions and you may need to use a plugin and have different versions of your pack. 

Block connections have a patch in our builds on ci.viaversion.com, and you need to enable block connections in the config (if you get stuck feel free to join our discord and we'll point you in the right direction).
