### ISSUE TITLE
Arrows Don't have Correct Velocity

### ISSUE THREAD

**Issue by HugoDaBosss** [MylesIsCool/ViaVersion#12]
When shooting an arrow, it falls to the ground in front of you.
A second later you will see it appear at the correct location.
Probably has something to do with the entity velocity packet.

**Comment by StamBoom** [comment]
I think USE_ITEM causes this. It's not sending any cursor position

http://wiki.vg/Protocol#Player_Block_Placement
https://github.com/MylesIsCool/ViaVersion/blob/master/src/main/java/us/myles/ViaVersion/transformers/IncomingTransformer.java#L206-L219

**Comment by HugoDaBosss** [comment]
It's really strange, because the bow is actually fired. You can damage other entities.
However, from the wiki.vg about the slot item: "A value of -1 signifies that the slot is empty, and no further data follows." So this would indicate that the server would think that the packet is finished,while it isn't.

**Comment by StamBoom** [comment]
Same problem with buckets

**Comment by HugoDaBosss** [comment]
I Investigated the arrows further, and it seems there is sent a "Spawn Object" packet with velocity (0,0,0). Afterwards there is never sent any "Entity Velocity" packet for that arrow.
This results in the client drawing an arrow which has been shot, but as soon as it receives the "Spawn Object" packet from the server it will stop the arrow mid-air.

**Comment by HugoDaBosss** [comment]
It turns out when you fire a bow in 1.8, it will send this to the server: (ProtocolLib)
[17:15:08 INFO]: [ProtocolLib] Received PacketPlayInBlockDig[7, legacy: 14] from HugoDaBosss:
{ a = { a = 0, c = 0, d = 0 }, b = { g = 0, h = 1, i = -1, j = "down", k = { e = "y", f = "VERTICAL", name = "Y", ordinal = 1 }, l = { c = -1, d = "Towards negative", name = "NEGATIVE", ordinal = 1 }, m = { a = 0, c = -1, d = 0 }, name = "DOWN", ordinal = 0 }, c = { name = "RELEASE_USE_ITEM", ordinal = 5 } }
And it answers with this:
[17:15:08 INFO]: [ProtocolLib] Sent PacketPlayOutSpawnEntity[14, legacy: 23] to HugoDaBosss:
{ a = 509, b = 4353, c = 2272, d = -5426, e = 21589, f = 10548, g = -271, h = 18, i = 64, j = 60, k = 79 }
So what I'm thinking is that when firing a bow, we should use the Block Dig packet, not the Block Placement. Using this will result in an SpawnEntity packet with velocity.

**Comment by HugoDaBosss** [comment]
This is fixed now, don't know how.
Probably a combination of things:
https://github.com/MylesIsCool/ViaVersion/commit/0db43e612e1cab1f6a85085cba1ef606ffbfe87f
https://github.com/MylesIsCool/ViaVersion/commit/153a68bf06a1dd629f5399f2675e22ee03b3f511
