### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by timr2000** [MylesIsCool/ViaVersion#120]
### What version of ViaVersion are you using? Type /ver viaversion
0.5.0
### What version of Spigot are you using? Type /ver
1.8.8
### Is there an error in the console? Use pastebin.com. Is there a kick message?

http://pastebin.com/A6ekazEk

**Comment by LukvonStrom** [comment]
Same sending Bulk Chunks Spam noticed. Pls fix that ASAP

**Comment by MylesIsCool** [comment]
Closed use 0.5.1
