### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by Eternalrealms** [MylesIsCool/ViaVersion#121]
The issue I am having is major lag spikes, basically the server will freeze and a bunch of errors in console occur.
### What version of ViaVersion are you using? Type /ver viaversion
0.5.0
### What version of Spigot are you using? Type /ver
Spigot 1.8.8

### What plugins are you using? /plugins
Tested this with viaversion spigot and protocal lib.
### How does this error happen? login? using an item? 
Im not sure, its very random. The errors happen on login i believe. 
### Is there an error in the console? Use pastebin.com. Is there a kick message?
Yes http://hastebin.com/idapikuret.avrasm

**Comment by HugoDaBosss** [comment]
Probably related to #117

**Comment by Eternalrealms** [comment]
Yes, that's exactly whats happening! Didn't even see that report.

**Comment by HugoDaBosss** [comment]
Well the error code for the broken pipe is a little bit different. Probably both have the same cause, but were doing other stuff when the error was thrown.

**Comment by Eternalrealms** [comment]
I wish I could be more help to reproduce the error.

**Comment by HugoDaBosss** [comment]
Could you post more of the error? There should be a lot more similar errors.

**Comment by Eternalrealms** [comment]
Sure: http://hastebin.com/ebivecumab.avrasm

**Comment by Eternalrealms** [comment]
http://hastebin.com/ibuqocimoy.avrasm

**Comment by Eternalrealms** [comment]
http://hastebin.com/cojevipiwo.avrasm

**Comment by MylesIsCool** [comment]
Bungee plugins?

**Comment by Eternalrealms** [comment]
We don't have any Bungee plugins.

**Comment by HugoDaBosss** [comment]
But you are using Bungee?

**Comment by Eternalrealms** [comment]
Yes

**Comment by HugoDaBosss** [comment]
Bungee can cause issues sometimes, we are looking on a way to fix this.
There is way too much rerouting of the packets going on then, so eventually something will break then.

**Comment by Eternalrealms** [comment]
Awesome, let me know if you need me to test a fix!

**Comment by MylesIsCool** [comment]
Should be fixed.

**Comment by WabMiran** [comment]
This is not fixed!
