### ISSUE TITLE
NPE while writing Metadata for PLAYER

### ISSUE THREAD

**Issue by timr2000** [MylesIsCool/ViaVersion#123]
### What version of ViaVersion are you using? Type /ver viaversion
0.5.1
### What version of Spigot are you using? Type /ver
1.8.8
### What plugins are you using? /plugins
Plugins (42): CleanroomGenerator, HubBasics, WorldEdit, HealthBar, SimpleElevator, Essentials, GroupManager, TuxTwoLib, Buycraft, BetterChairs, Lockette, Votifier, LaggRemover, WorldGuard, HugeItems, EssentialsChat, EssentialsGeoIP, TimeIsMoney, ViaVersion, CustomJoinItems, GAListener, Vault, RealTime, DrugMeUp, TitleManager, MultiInv, PlotSquared, ProtocolLib, LibsDisguises, AAC, ASkyBlock, ChestCommands, SexyMotd, Autorank, Multiverse-Core, Shopkeepers, GriefPrevention, SkyWarsReloaded, ItemSlotMachine, HolographicDisplays, WarpPortals, InfoBoardReborn
### How does this error happen? login? using an item? 
When someone uses a 1.9 client
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/Uryv8VtV

**Comment by MylesIsCool** [comment]
Can you post above the error please? Has AAC been configured correctly?

**Comment by timr2000** [comment]
Yes but cant find spawn rate 0% in the config

**Comment by timr2000** [comment]
Full error: http://pastebin.com/rbQQmXrz

**Comment by HugoDaBosss** [comment]
Same error at the same line which appears with custom bossbars, but then for enderdragons and withers.
Do you use any coloured player names?

**Comment by timr2000** [comment]
Yup i use coloured player name's, but only op's have a coloured name.

**Comment by HugoDaBosss** [comment]
Same thing is causing a different issue now #152 
Will close this one now.
