### ISSUE TITLE
Array out of bounds while reading chunk data

### ISSUE THREAD

**Issue by ChavitaHD** [MylesIsCool/ViaVersion#125]
### What version of ViaVersion are you using? Type /ver viaversion
0.5.1
### What version of Spigot are you using? Type /ver
1.8.8-R0.1-SNAPSHOT
### What plugins are you using? /plugins
http://prntscr.com/abap84
### How does this error happen? login? using an item? 
Switching Inventory Items, Logging in, Jumping, Clicking Inventory, other small things.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://paste.parallaxmc.com/igudahenov.apache
https://paste.parallaxmc.com/oxupibonuc.apache
https://paste.parallaxmc.com/unubavifon.avrasm

**Comment by HugoDaBosss** [comment]
The last error log is the same as #123 
The other two errors could be related to https://github.com/MylesIsCool/ViaVersion/issues/48

**Comment by XNoki200010** [comment]
Same here:

http://hastebin.com/jejekaneco.apache

**Comment by MylesIsCool** [comment]
Will be in the next version, thanks for reporting.
