### ISSUE TITLE
Spawners don't show correct mob

### ISSUE THREAD

**Issue by R4G3-BABY** [MylesIsCool/ViaVersion#127]
### What version of ViaVersion are you using? Type /ver viaversion
0.5.1
### What version of Spigot are you using? Type /ver
CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
### What plugins are you using? /plugins
ViaVersion
### How does this error happen? login? using an item? 
Spawners don't show the correct mob inside
### Is there an error in the console? Use pastebin.com. Is there a kick message?
No errors

**Comment by HugoDaBosss** [comment]
Thanks for the clear issue report, I will personally look into it right now.

**Comment by R4G3-BABY** [comment]
I would look into it but im corrently busy just trying to help

**Comment by HugoDaBosss** [comment]
It looks like in 1.9 the NBT tag for spawners now use SpawnPotential, not just a single entityId.
http://minecraft.gamepedia.com/Chunk_format#Block_entity_format
I'll try to fix this!

**Comment by R4G3-BABY** [comment]
Thanks for being so helpful

**Comment by HugoDaBosss** [comment]
Fixed, submitting pull request now!

**Comment by HugoDaBosss** [comment]
Fixed https://github.com/MylesIsCool/ViaVersion/pull/130
