### ISSUE TITLE
Books

### ISSUE THREAD

**Issue by ridalarry** [MylesIsCool/ViaVersion#128]
Using the latest version of spigot with version 0.5.1 If there is only 1 word in the page it will look like this
https://gyazo.com/5a73f063b8f8d108ffc8218fa468afc1

**Comment by ridalarry** [comment]
I have asked a player with 1.8 client to read that book and he didnt see the quotation marks, and I have asked him to make a similar one and it had quotation marks. I have also tried to do it in vanila and it seems not a vanila bug.

**Comment by MylesIsCool** [comment]
I'm stuck seeing what the issue is in the first bit?

**Comment by ridalarry** [comment]
the issue is its adding quotation marks to the word if its only 1 word in the page

**Comment by StamBoom** [comment]
Fixed #131

**Comment by MylesIsCool** [comment]
In next version it's fixed see above

**Comment by ridalarry** [comment]
Now the opposite is happening if you use quotation marks in the book it will be disapeared.

**Comment by MylesIsCool** [comment]
@ridalarry Should be fixed in next version

**Comment by ridalarry** [comment]
Im using ViaVersion 0.5.3 and latest spigot the issue is there, but in the opposite way https://gyazo.com/f15b9b51cece39b627f1c4fde0f1b135

**Comment by StamBoom** [comment]
@ridalarry probably fixed in the next version 
https://github.com/MylesIsCool/ViaVersion/commit/3c5a6a3b7b4e20d03ce0c5cbd51f26948e64f368
