### ISSUE TITLE
Make sure you update your bungee plugins: MapManager

### ISSUE THREAD

**Issue by haelexuis** [MylesIsCool/ViaVersion#129]
**### What version of ViaVersion are you using? **
0.5.1

**### What version of Spigot are you using? **
git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8)

**### What plugins are you using?**
CleanroomGenerator , WorldEdit , Essentials , PacketListenerApi , PlugMan , MapManager , Multiverse-Core , WorldGuard , EssentialsChat , PermissionsEx , Microblocks , ViaVersion , Vault , HideStream , EssentialsSpawn , FakaHedaMinequery , UltraCosmetics , AnimatedFrames , ProtocolLib , NoCheatPlus , Citizens , CommandNPC , AuthMe , HolographicDisplays , Basic (my own)

**### How does this error happen?** 
Join to server

**### Is there an error in the console?** 
No, but on minecraft screen, http://pasteboard.co/21CTR1u9.png

**Comment by ridalarry** [comment]
Try to disable plugins with plugman try to do /plugman disable PluginName until you found the bug. I feel that this bug is caused by PacketListenerApi , MapManager , Microblocks , FakaHedaMinequery , UltraCosmetics , AnimatedFrames , Citizens , or CommandNPC ,

**Comment by ridalarry** [comment]
When you find the cause please mention it here, so the developers can fix it.

**Comment by MylesIsCool** [comment]
Are you using Bungee Cord, if so what plugins?

**Comment by haelexuis** [comment]
Yes, I use bungeecord.. I gonna try disable plugins

**Comment by haelexuis** [comment]
Hm, it was MapManager, thanks :)

**Comment by MylesIsCool** [comment]
Closed, please make sure your bungee plugins are up to date <3 lots of love

**Comment by haelexuis** [comment]
Btw chunks weren't fixed? https://cdn.pbrd.co/images/21FhyMZD.png

**Comment by MylesIsCool** [comment]
@haelexuis Might just be client issue if you can verify /viaversion is latest. There has been reports that this on rare occasion does occur.

**Comment by haelexuis** [comment]
Yes, chunks were fixed :D sorry I tryed it on other server...

**Comment by MylesIsCool** [comment]
*praise the lord*
