### ISSUE TITLE
1.9 users cannot join 1.8 servers

### ISSUE THREAD

**Issue by Wazez** [MylesIsCool/ViaVersion#132]
### What version of ViaVersion are you using? Type /ver viaversion
[06:31:40 INFO]: Author: _MylesC
[06:31:40 INFO]: ViaVersion version 0.5.1

### What version of Spigot are you using? Type /ver
[06:31:49 INFO]: You are 83 version(s) behind
[06:31:49 INFO]: Checking version, please wait...
[06:31:49 INFO]: This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

6:32:46 [INFO] This server is running BungeeCord version git:BungeeCord-Bootstrap:1.9-SNAPSHOT:903ada0:1129 by md_5

### What plugins are you using? /plugins
[06:32:04 INFO]: Plugins (9): Jarvis, ViaVersion, BuycraftX, AutoRestart, Vault, ProtocolLib, MHCore, Hub, ChatManager

### How does this error happen? login? using an item? 
When a 1.9 user attempts to login  to a 1.8 server they receive the following error:

### Is there an error in the console? Use pastebin.com. Is there a kick message?

http://paste.mineheroes.net/aruyujiziw.coffee

http://puu.sh/nvyc1/d256085b30.png

http://paste.mineheroes.net/deyepuloyi.coffee

**Comment by ridalarry** [comment]
What bungee plugins are you using?

**Comment by Wazez** [comment]
6:32:46 [INFO] This server is running BungeeCord version git:BungeeCord-Bootstrap:1.9-SNAPSHOT:903ada0:1129 by md_5

**Comment by ridalarry** [comment]
not the version of bungee the plugins of bungee

**Comment by HugoDaBosss** [comment]
This issue is caused in combination with ProtocolLib, the error itself is thrown by protocollib.
Guess we still aren't fully compatible then in combination with Bungee and ProtocolLib.

**Comment by MylesIsCool** [comment]
Does this still happen?

**Comment by Wazez** [comment]
You can close the issue
