### ISSUE TITLE
Spawners

### ISSUE THREAD

**Issue by olliegardner** [MylesIsCool/ViaVersion#136]
The plugin isn't compatible with SilkSpawners or simply using the essentials command /spawner to change the spawner type of the spawner at the player is looking at. No errors, simply just doesn't change the type of spawner when I execute the command.

**Comment by HugoDaBosss** [comment]
This has been fixed, just not pushed to a public release

**Comment by olliegardner** [comment]
Ah okay, thank you.

**Comment by HugoDaBosss** [comment]
Here is the PR for the fix: #130

**Comment by olliegardner** [comment]
Alright I didn't see that before, sorry

**Comment by HugoDaBosss** [comment]
No problem, it was closed alredy, and I understand people don't look there ;)

**Comment by HugoDaBosss** [comment]
Already*

**Comment by olliegardner** [comment]
True, when will this be released?

**Comment by HugoDaBosss** [comment]
@MylesIsCool will be home in a few hours, he has access to the plugin on spigotmc. So probably in ~6 hours.
You can always compile it yourself, if you know how.

**Comment by olliegardner** [comment]
Okay, yep I know how so I probably will.
