### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mat41997** [MylesIsCool/ViaVersion#137]
### What version of ViaVersion are you using? Type /ver viaversion
0.5.1 and java 9

### What version of Spigot are you using? Type /ver
paperspigot 1.8.8 latest
https://tcpr.ca/downloads/paperspigot

### What plugins are you using? /plugins
authme, pluginmenager, worldedit, viaversion

### How does this error happen? login? using an item? 
???

### Is there an error in the console? Use pastebin.com. Is there a kick message?
error logs
http://hastebin.com/edujofufud.avrasm

**Comment by HugoDaBosss** [comment]
The error and line correspond with #125

**Comment by HugoDaBosss** [comment]
Paperspigot is not supported, will close for now.
