### ISSUE TITLE
Move Error

### ISSUE THREAD

**Issue by ChavitaHD** [MylesIsCool/ViaVersion#140]
### What version of ViaVersion are you using? Type /ver viaversion
0.5.2
### What version of Spigot are you using? Type /ver
1.8.8
### What plugins are you using? Type /plugins
http://prntscr.com/abnesk
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord [Waterfall #125]
### How does this error happen? login? Using an item? 
Moving
### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://paste.parallaxmc.com/equrojepum.apache

**Comment by HugoDaBosss** [comment]
Wooohh 100th issue!
Why did you repost the issue the same as #125? 
@MylesIsCool is currently looking on how to fix this. Will close this issue for now.
