### ISSUE TITLE
server resource pack does not automatically update

### ISSUE THREAD

**Issue by timr2000** [MylesIsCool/ViaVersion#143]
### What version of ViaVersion are you using? Type /ver viaversion
0.5.3
### What version of Spigot are you using? Type /ver
1.8.8
### How does this error happen? login? Using an item? 
server resource pack does not automatically update in 1.9 clients
### Is there an error in the console? Use pastebin.com. Is there a kick message?
nope

**Comment by StamBoom** [comment]
Are you updating your file hash? Please check your minecraft client launcher, that!ll throw most of the time a exception when something is wrong with resourcepacks

**Comment by timr2000** [comment]
i removed my server resource pack in %appdata% and now it works :p

**Comment by HugoDaBosss** [comment]
This is solved
