### ISSUE TITLE
Colored Chat

### ISSUE THREAD

**Issue by Kakifrucht** [MylesIsCool/ViaVersion#144]
### What version of ViaVersion are you using? Type /ver viaversion
0.5.3
### What version of Spigot are you using? Type /ver
git-Spigot-db6de12-3f3c65f
### What plugins are you using? Type /plugins
NoCheatPlus, EssentialsChat
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No
### How does this error happen? login? Using an item? 
When chatting with permission to use color code, NoCheat's color protection will deny the message, as if the user is not allowed to. Disabling NoCheat's color check fixes this issue (temporarily). This issue happens to both 1.8 and 1.9 clients.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
No

**Comment by Rida94** [comment]
NoCheatPlus has a permission to ignore chat color checks, you can give this permission to the ranks that has permission to use chat colors. And there is no hack that has chat colors, so you can give the permission to your default rank or even disable the chat color checks.

**Comment by Rida94** [comment]
Also as its happening to both clients it could be caused by NoCheatPlus, try to test the issue without ViaVersion

**Comment by Kakifrucht** [comment]
I already stated that this workaround is possible. Are you sure that it is no longer possible to send colored messages with section signs, without appropriate colored chat permissions?

And no, it only happens with ViaVersion and Nocheat running together.

**Comment by MylesIsCool** [comment]
Does this still happen in the latest version?

**Comment by Kakifrucht** [comment]
Yes it does.

**Comment by MylesIsCool** [comment]
This issue is not related to ViaVersion, as it works with 1.8 and 1.9. We only modify client side packets incoming and outgoing for 1.9.

**Comment by Kakifrucht** [comment]
Than why does it only happen when ViaVersion is installed?

**Comment by HugoDaBosss** [comment]
Isn't this caused because the 1.9 client sends chat data in JSON? Not sure about this though.

**Comment by Kakifrucht** [comment]
As said, also happens to 1.8 Clients.

**Comment by MylesIsCool** [comment]
I'd suggest taking this up with NoCheat, it sounds like NoCheat's working fine from my perspective in this case and you should just add the permission to fix the issue or what.
