### ISSUE TITLE
Player gets disconnectet when putting item in offhand (gm 0 only)

### ISSUE THREAD

**Issue by i9hdkill** [MylesIsCool/ViaVersion#145]
### What version of ViaVersion are you using? Type /ver viaversion
ViaVersion version 0.5.3
### What version of Spigot are you using? Type /ver
git-Spigot-db6de12-3f3c65f (MC: 1.8.8)
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord, our custom version build reimplementing 1.7 support

### How does this error happen? login? Using an item?
Put an item in the offhand slot (client gets disconnected)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/pK7zUAqV

**Comment by HugoDaBosss** [comment]
This issue isn't present when not using bungeecord. Isn't there any error message in the server console?

**Comment by MylesIsCool** [comment]
I would assume your custom bungeecord does not properly implement this. We don't support custom software unfortunately.

**Comment by i9hdkill** [comment]
Yep, we realized that. Sry for bothering you^^
