### ISSUE TITLE
new IndexOutOfBoundsException

### ISSUE THREAD

**Issue by XNoki200010** [MylesIsCool/ViaVersion#149]
### What version of ViaVersion are you using? Type /ver viaversion
ViaVersion 0.5.3

### What version of Spigot are you using? Type /ver
PaperSpigot 1.8.8

### What plugins are you using? Type /plugins
WorldEdit, NCP, EffectLib, ArmorStandTools, HolographicDisplays

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord 1.8.x, 1.9 (newest version)
only selfwritten plugins, nothing spectacular

### How does this error happen? login? Using an item? 
Don't know, after a few minutes the server was lagging and this error was spammed.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://hastebin.com/caxudazati.avrasm
http://pastebin.com/cacbXc3e

**Comment by HugoDaBosss** [comment]
There should be a line above your error, could you please post the lines before this error?

**Comment by HugoDaBosss** [comment]
Oh just saw you are running paperspigot. PaperSpigot is not supported at this time, will close this for now.

**Comment by HugoDaBosss** [comment]
Could you test with the normal Spigot build and see if the error persists?

**Comment by XNoki200010** [comment]
I've tested it with normal spigot.

http://hastebin.com/oxipuquhav.avrasm

**Comment by HugoDaBosss** [comment]
Again:

> There should be a line above your error, could you please post the lines before this error?

**Comment by XNoki200010** [comment]
There was no error above :/

**Comment by xion87** [comment]
got the same error  issue, it happen on login server an make my file log going to 70-600mb
error log: http://hastebin.com/hunujetozi.css
Using latest 1.8.8 spigot and VV 0.5.3

**Comment by HugoDaBosss** [comment]
Please enable ViaVersion debug mode so we can see which packet causes this issue.
You can enable it using /ViaVersion debug
(Warning: This will print out all packets sent, so don't do this with a lot of players online)

**Comment by xion87** [comment]
i restarted the server and enabled debug, i will let you know when that error come

**Comment by xion87** [comment]
there you are
http://hastebin.com/akodariten.css

**Comment by MylesIsCool** [comment]
Do any of your custom plugins modify the minecraft version?

**Comment by xion87** [comment]
nope, i got only skript on my login server that cancel some event, like weather, damage, ecc, i got pure 1.8.8 spigot, in bungee side i use skinsrestorer

**Comment by MylesIsCool** [comment]
Have you updated your skins plugin to 1.9? It won't work otherwise.

**Comment by xion87** [comment]
Yeah i already updated all plugin and bungee to latest version, skin work greats both in 1.8 and 1.9, i just got that anoying error spam sometimes

**Comment by XNoki200010** [comment]
Don't know if it helps you, but a player sends me this Screenshot:

https://img3.picload.org/image/wprrgwi/2016-03-11_14.09.13.png

**Comment by MylesIsCool** [comment]
Use 0.6.7, closing issue. Request reopen if still occurs.
