### ISSUE TITLE
client disconnect due entity HORSE

### ISSUE THREAD

**Issue by hunter688** [MylesIsCool/ViaVersion#15]
http://pastebin.com/LuuFN4ut

**Comment by HugoDaBosss** [comment]
Fixed: https://github.com/HugoDaBosss/ViaVersion/commit/45dfe7261bf3a9b8507818650c987c96366a4574
https://github.com/MylesIsCool/ViaVersion/pull/14

**Comment by MylesIsCool** [comment]
See above.
