### ISSUE TITLE
An error occurred with entity meta data for PLAYER OldID: 11

### ISSUE THREAD

**Issue by timr2000** [MylesIsCool/ViaVersion#152]
### What version of ViaVersion are you using? Type /ver viaversion
0.5.4
### What version of Spigot are you using? Type /ver
1.8.8
### How does this error happen? login? Using an item? 
When someone uses a 1.9 client
### Is there an error in the console? Use pastebin.com. Is there a kick message?

http://pastebin.com/snEgp0ua

**Comment by HugoDaBosss** [comment]
It seem that you are using ProtocolLib. Could you please provide a list of your plugins?
Also, did you recently update a plugin for 1.9?

**Comment by HugoDaBosss** [comment]
This error is essentially the same as #123 , but we changed our code so the error message is different, will close your old issue.

**Comment by timr2000** [comment]
Yes i updated some plugins to 1.9, but they are compatible whith 1.8, Plugins (41): CleanroomGenerator, HubBasics, WorldEdit, SimpleElevator, Essentials, GroupManager, TuxTwoLib, BetterChairs, BuycraftX, Lockette, Votifier, LaggRemover, WorldGuard, HugeItems, EssentialsChat, EssentialsGeoIP, TimeIsMoney, ViaVersion, CustomJoinItems, GAListener, Vault, RealTime, DrugMeUp, TitleManager, MultiInv, PlotSquared, ProtocolLib, LibsDisguises, AAC, ASkyBlock, ChestCommands, SexyMotd, Autorank, Multiverse-Core, Shopkeepers, GriefPrevention, SkyWarsReloaded, ItemSlotMachine, HolographicDisplays, WarpPortals, InfoBoardReborn

**Comment by timr2000** [comment]
ah okay sorry xd, i didn't know that..

**Comment by HugoDaBosss** [comment]
You should downgrade your plugins to the latest 1.8 version. Plugins made for spigot 1.9 are not compatible with ViaVersion.
