### ISSUE TITLE
Unable to ride entities

### ISSUE THREAD

**Issue by HugoDaBosss** [MylesIsCool/ViaVersion#16]
For example when you try to ride a horse, it will push you off.
It's very buggy.

**Comment by MylesIsCool** [comment]
It's the same with minecarts etc. I believe the new packet Attach entity needs to be used, I can look into it sometime, main priority is getting ProtocolLib working for myself.

**Comment by StamBoom** [comment]
Fixed #17

**Comment by MylesIsCool** [comment]
See above.
