### ISSUE TITLE
Nether portals are slow in survival

### ISSUE THREAD

**Issue by StatelyMC** [MylesIsCool/ViaVersion#160]
### What version of ViaVersion are you using? Type /ver viaversion
0.5.6
### What version of Spigot are you using? Type /ver
git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Also tested with
git-Spigot-870264a-0a645a2 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
git-Spigot-550ebac-7019900 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
### What plugins are you using? Type /plugins
ViaVersion only
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No
### How does this error happen? login? Using an item? 
On a fresh install, create and light a portal. Passing through it in creative mode is as expected, but if the player switches to survival, it takes over a minute to pass through the portal.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
There are no errors in console or log. The player does not disconnect.

**Comment by HugoDaBosss** [comment]
What do you mean by it takes over a minute to pass trough the portal?
Does the world take over a minute to load, or does the world only starts to load after a minute?

**Comment by StatelyMC** [comment]
Since transit of the portal in creative mode is near instantaneous and the player can still walk out of the portal while subject to the portal nausea, I assume it's the latter.

**Comment by HugoDaBosss** [comment]
I'm currently looking into this issue.

**Comment by StatelyMC** [comment]
Let me know if you need any further information from me.

**Comment by HugoDaBosss** [comment]
I can test this myself since the bug seems to occur in all situations. 
I am not able to find something though ;( There is no change between 1.9 and 1.8 in the packets related to changing dimensions. The packet to change dimension is somehow sent very very late to the client when ViaVersion is installed.

**Comment by HugoDaBosss** [comment]
Made a dirty fix https://github.com/MylesIsCool/ViaVersion/pull/170 , but it will break more things than it fixes. There are some changes with nether portal detection between 1.8 and 1.9, but we didn't find any changes in the packets yet.

**Comment by StatelyMC** [comment]
FWIW I was able to fix this on my server with a little plugin that changes the player's gamemode to creative and blocks them opening an inventory when they enter a portal. It's a hideous hack, of course, but it does work and I figure maybe it would give you an idea of how to move forward.

**Comment by HugoDaBosss** [comment]
Yeah I made my 'hack' as well to fix it, but it should be fixable with just a packet.
