### ISSUE TITLE
[Player Disconnect] Team viaversion already exists in scoreboard

### ISSUE THREAD

**Issue by wow4201** [MylesIsCool/ViaVersion#161]
Player gets sent to lobby after 3 seconds of logging in server with viaversion.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

**BungeeCord Log**
**Team viaversion already exists in this scoreboard**
at com.google.common.base.Preconditions.checkargument(Preconditions.java:145)
at net.md_5.bungee.api.score.Scoreboard.AddTeam(Scoreboard.java:68)

**Comment by MylesIsCool** [comment]
As a short term fix, simple disable auto-team in your config.

**Comment by MylesIsCool** [comment]
Fixed in next version

**Comment by wow4201** [comment]
The shorterm fix "As a short term fix, simple disable auto-team in your config." Worked

However the new viaversion didn't seem to help

**Comment by wow4201** [comment]
What are the consequences of disable auto-team in your config?
Is this related to the Attack Cooldown?

**Comment by MylesIsCool** [comment]
@wow4201 Entity collision happens if you don't have a team for the player.

**Comment by wow4201** [comment]
Ok, but this doesn't result in any crashing behavior or anything. Simply just entities push each other.
