### ISSUE TITLE
1.9 bungee

### ISSUE THREAD

**Issue by AlexNova1555** [MylesIsCool/ViaVersion#164]
### What version of ViaVersion are you using? Type /ver viaversion
0.5.6
### What version of Spigot are you using? Type /ver
This server is running CraftBukkit version git-Spigot-e4d4710-e
1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
### Are you using any additional software like BungeeCord? If so, what software and version?
Plugins (26): MinecraftMarket, WorldEdit, NoRain, ChatControl,
Votifier, PlayerLaunchpad, WorldGuard, BungeePortals, UltimateHub, PermissionsEx
, ViaVersion, ActionAnnouncer, GAListener, Vault, HideStream, HubEssentials, Nam
eManager, Essentials, ProtocolLib, LibsDisguises, Citizens, EssentialsChat, Esse
ntialsSpawn, TitleManager, UltraCosmetics, HolographicDisplays

### How does this error happen? login? Using an item? 
when i login with 1.9 i got kick message here is the pic http://imgur.com/t4UJjUx

### Is there an error in the console? Use pastebin.com. Is there a kick message?
i got error at the bungee console 
http://pastebin.com/8JU6FBs9

**Comment by HugoDaBosss** [comment]
This error is the same as #161 
This has been fixed in the newest (unreleased) version.
As a temporary fix disable auto-team in the ViaVersion config.yml
