### ISSUE TITLE
Bugged 1.9 sound

### ISSUE THREAD

**Issue by timr2000** [MylesIsCool/ViaVersion#168]
### What version of ViaVersion are you using? Type /ver viaversion
0.5.7
### What version of Spigot are you using? Type /ver
1.8.8
### How does this error happen? login? Using an item? 
When i open a door it has the minecraft 1.8 sound and minecraft 1.9 sound.
### Is there an error in the console? Use pastebin.com. Is there a kick message?

nope

**Comment by HugoDaBosss** [comment]
I'll look into this.

**Comment by HugoDaBosss** [comment]
This is not a bug, it's just the new 1.9 sound. Exact same sound in singleplayer.
