### ISSUE TITLE
Jukebox don't work

### ISSUE THREAD

**Issue by Taulukauppias** [MylesIsCool/ViaVersion#169]
Spigot version, viaversion version and plugins list.
https://gyazo.com/d80f15bf49e0153991992ded2c5ea467
We have Bungeecord 1.9

This error happen when player uses a jukebox with 1.9 client on 1.8 server. When player put disk to the jukebox, it dont start the music playing and sometimes kick player. Still jukebox continue playing and players which have 1.8 can hear that music. Jukebox's work well with minecraft 1.8. 

I dont have that error message, sry. I tried to get that error but it dont send anything to the console at this time.

Noteblocks works fine with 1.8 and 1.9

**Comment by HugoDaBosss** [comment]
First, consider updating since you are not running the latest version.
It is true jukeboxes are broken, will look into this.

**Comment by Matsv** [comment]
Confirmed. I'll look into this

**Comment by Taulukauppias** [comment]
Yep, i updated the plugin and this happened still.
https://gyazo.com/9c0dafa4db4be2c7d5f61a3e90afa345

**Comment by Matsv** [comment]
Fixed #171

**Comment by HugoDaBosss** [comment]
Thanks @Matsv !
Still trying to use @StamBoom... RIP
