### ISSUE TITLE
Kicked when pressing shift when you are a mob

### ISSUE THREAD

**Issue by AlexNova1555** [MylesIsCool/ViaVersion#172]
### What version of ViaVersion are you using? Type /ver viaversion
0.5.7

### What version of Spigot are you using? Type /ver
[01:14:22 INFO]: This server is running CraftBukkit version git-Spigot-db6de12-1
8fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins
Plugins (26): MinecraftMarket, WorldEdit, NoRain, ChatControl,
Votifier, PlayerLaunchpad, WorldGuard, BungeePortals, UltimateHub, PermissionsEx
, ViaVersion, ActionAnnouncer, GAListener, Vault, HideStream, HubEssentials, Nam
eManager, Essentials, ProtocolLib, LibsDisguises, Citizens, EssentialsChat, Esse
ntialsSpawn, TitleManager, UltraCosmetics, HolographicDisplays

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
yes i'm using bungeecord
BungeeAdminTools-1.4.1-basics
BungeeKick
BungeeReport
BungeeShout
FriendSystem
GeneralHub
Yamler-Bungee-2.3.0-SNAPSHOT

### How does this error happen? login? Using an item? 
when i become a mob like creeper and i press shift and its kicking me with an error
http://prntscr.com/aci2pm

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/QbzBPfiQ

**Comment by rj0495** [comment]
This is Caused by ProtocolLib.

**Comment by Matsv** [comment]
I don't have this problem: https://fileserver.matsv.nl/media?id=9258ab88f03aa2e537a90c730f8e5b1d
Please make sure you update all your plugins to the latest 1.8 version

**Comment by HugoDaBosss** [comment]
This error is probably caused by NameManager, which uses ProtocolLib. Did you update any plugins to 1.9? Because you should not do this, update all plugins to the latest 1.8 version.

**Comment by AlexNova1555** [comment]
no i have not updated any plugin for 1.9 but i will try to change the ProtocolLib version to older

**Comment by HugoDaBosss** [comment]
And any luck yet @AlexNova1555 ?
Could you also try disabling NameManager?

**Comment by AlexNova1555** [comment]
yes it beacue the NameManager /=

**Comment by Matsv** [comment]
Might be fixed #191 
I got kicked with 1.9 and NameManager. But not after this

**Comment by AlexNova1555** [comment]
even after the update its still not working )":

**Comment by Matsv** [comment]
Do you get some errors?

**Comment by AlexNova1555** [comment]
idk if its the same error but heres is the error
http://pastebin.com/8qQWwDN5

**Comment by Matsv** [comment]
@AlexNova1555 Did you update all your plugins to the latest 1.8 version?

**Comment by AlexNova1555** [comment]
yes i do /=
