### ISSUE TITLE
Chunk missing?

### ISSUE THREAD

**Issue by Z609** [MylesIsCool/ViaVersion#173]
### What version of ViaVersion are you using? Type /ver viaversion
Latest commit on GitHub
### What version of Spigot are you using? Type /ver
This server is running CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
### What plugins are you using? Type /plugins
Plugins (6): ViaVersion, RemoteToolkitPlugin, ProtocolLib, AAC, HolographicDisplays, Hub
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord (Bungee Remote Toolkit and a custom plugin)
### How does this error happen? login? Using an item? 
It happens a little while after I join and it usually happens when I look away.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
No errors whatsoever. DEFINITELY not an AAC issue. ONLY happens on 1.9.

http://i.imgur.com/W9uOzd1.jpg

**Comment by MylesIsCool** [comment]
Out of curiosity, does it work without AAC? haha

And also what are the chunk co-ordinates of the missing chunk? Are they 0, 0?

**Comment by Z609** [comment]
From my testing, it always happens a couple blocks away from the spawn. E.g. http://prntscr.com/acnmzr (in an SG map)

It only happens with AAC (From my testing). The question I have is: Why would they even need to update blocks (if they do)

**Comment by MylesIsCool** [comment]
So you state it's not an AAC issue but it only happens with AAC.

I don't own a copy of AAC so I don't know how it works but it may hook into how chunks are sent while hooking into packets.

**Comment by MylesIsCool** [comment]
Closed #72

**Comment by HugoDaBosss** [comment]
This issue has been reported without using AAC, reopening

**Comment by File14** [comment]
I'm having this problem but without the ACC plugin.

**Comment by MylesIsCool** [comment]
Fixed in next version
