### ISSUE TITLE
Toggle 1.9 Client Features

### ISSUE THREAD

**Issue by wow4201** [MylesIsCool/ViaVersion#180]
Hi,

I think it would be a great idea to create a toggle able config option for 1.9 Client Features like shields.
Many people prefer the 1.8 combat system.

**Comment by MylesIsCool** [comment]
Shields are client sided and just simulate blocking?

**Comment by Adaptified** [comment]
@MylesIsCool Like hypixel, some people would like the same 1.8 animations/features, while allowing 1.9 users to connect.

**Comment by SpEeD11** [comment]
A config option to turn off the automatic shield blocking would be great, I don't need blocking and it currently conflicts with other things when right clicking with a sword.

**Comment by MylesIsCool** [comment]
Done

**Comment by Adaptified** [comment]
@MylesIsCool May I suggest implementing something for the sword attack animation, as well? Along with 1.9 items? (All toggleable config options)
