### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by DragonbornCommunity** [MylesIsCool/ViaVersion#181]
ViaVersion-0.5.9.jar

Latest BuildTools, built 09/03/2016

Tested on my test-server which has only CoreProtect, WorldEdit, Essentials, GroupManager, WorldGuard, EssentialsChat, Vault, ParticleLib, Skript

Latest BungeeCord

After starting the server, it crashes in 1-2 minutes.

http://pastebin.com/2CznWtDt

**Comment by MylesIsCool** [comment]
Fixed in latest commit, thanks for the error log.
