### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by det483** [MylesIsCool/ViaVersion#182]
### What version of ViaVersion are you using? Type /ver viaversion
0.6.0
### What version of Spigot are you using? Type /ver
1.8.8
### What plugins are you using? Type /plugins
- 
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Bungeecord 1132
### How does this error happen? login? Using an item? 
The server crashes randomly, every server on my bungeecord with viaversion 0.6.0 crashes, with 0.5.8 the server didn't crash, but now it does.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/GDP4mCZ4
The crashreport in the console error; http://pastebin.com/C2AXZUE8
Every server with viaversion 0.6.0 crashes every -+ 10 minutes. 
This is the lobby log/error, but since i upgraded to 0.6.0 from 0.5.8, each server with viaversion crashes.

I downgraded to 0.5.8 again, no crashes anymore.

Kind Regards,
det483

**Comment by MylesIsCool** [comment]
Should be fixed in 0.6.1
