### ISSUE TITLE
Another jenkins server + built-in maven repo

### ISSUE THREAD

**Issue by sgdc3** [MylesIsCool/ViaVersion#183]
Jenkins Job:
http://ci.xephi.fr/job/ViaVersion/

Maven Repo:
http://ci.xephi.fr/plugin/repository/everything/

**Comment by MylesIsCool** [comment]
Added

**Comment by HugoDaBosss** [comment]
The build server doesn't seem to automatically build new patches, can you fix this @sgdc3 ?

**Comment by sgdc3** [comment]
whoops, let me check ;)

**Comment by HugoDaBosss** [comment]
Thank you for fixing @sgdc3 :+1:
