### ISSUE TITLE
Chunks not rendering properly

### ISSUE THREAD

**Issue by lenis0012** [MylesIsCool/ViaVersion#184]
### What version of ViaVersion are you using? Type /ver viaversion
0.6.1

### What version of Spigot are you using? Type /ver
git-Spigot-e3d4710-e1ebe52 (MC: 1.8.8)

### What plugins are you using? Type /plugins
CCN-Hub (Custom), ViaVersion

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord v1.9-SNAPSHOT:52d6689:1131
- CCN-Proxy (Custom)

### How does this error happen? login? Using an item? 
moving around
NOTE: This error seems to happen only in void worlds, and in specific chunks.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
No errors

http://i.imgur.com/AvdIYaK.jpg

**Comment by brunyman** [comment]
Issue confirmed on 0.6.2

**Comment by lenis0012** [comment]
@brunyman im working on a fix.
tell me if im right: this issue only happends in void worlds?

**Comment by rj0495** [comment]
Yea Just void @lenis0012

**Comment by brunyman** [comment]
Well, possible, haven't tested it on non void worlds yet, just on lobby and one minigame, and there is a lot of void indeed.
But very few chunks load as they should.

here some screenshots: 
http://imgur.com/a/G9Jdn

Thanks

**Comment by minoneer** [comment]
Running into similar issues in our SkyBlock world, likely connected. Happened on both, version 0.6.2 and 0.6.3 on Spigot git-Spigot-db6de12-3f3c65f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT). No Bungee or other proxies.
![2016-03-11_02 57 49](https://cloud.githubusercontent.com/assets/6442649/13700169/8a866c48-e77f-11e5-89ad-c592d9fecfbb.png)
![2016-03-11_02 58 35](https://cloud.githubusercontent.com/assets/6442649/13700171/8aaaf874-e77f-11e5-9965-4ae020eb560f.png)
![2016-03-11_11 38 42](https://cloud.githubusercontent.com/assets/6442649/13700170/8aaae3f2-e77f-11e5-8f5c-27554a8a2173.png)

**Comment by MylesIsCool** [comment]
Has anyone tried this on previous versions? Are you able to identify a version where this is not broken?

**Comment by MultiDJRoni** [comment]
In older Versions (im using 0.5.8) the Chunks are working perfect

**Comment by lenis0012** [comment]
should be fixed by #200

**Comment by MylesIsCool** [comment]
Fixed in next version.
