### ISSUE TITLE
Can`t see other Players

### ISSUE THREAD

**Issue by MultiDJRoni** [MylesIsCool/ViaVersion#193]
### What version of ViaVersion are you using? Type /ver viaversion

0.5.8 (It also isn`t working in newer versions!)

### What version of Spigot are you using? Type /ver

http://prntscr.com/advsil

### What plugins are you using? Type /plugins

http://prntscr.com/advsu7

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Yes, im using the newest version of BungeeCord

### How does this error happen? login? Using an item? 

Its completely random. Sometime everyone can see everyone, and sometimes nobody saw nobody.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

There are no errors :c

**Comment by MylesIsCool** [comment]
Have you tried without AAC?

**Comment by MultiDJRoni** [comment]
Yes, it is also not working.

**Comment by XNoki200010** [comment]
Same here, some Players are invisible. Don't know if it is a 1.9 Bug or a ViaVersion Bug.

**Comment by MultiDJRoni** [comment]
@XNoki200010 I think its a ViaVersion problem, because i also cant see other players in the 1.8.9, but only on ViaVersion servers

**Comment by HugoDaBosss** [comment]
@XNoki200010 could you list your spigot version with your plugins and bukkit version with your plugins as well?

**Comment by MultiDJRoni** [comment]
@HugoDaBosss if you mean me, its all in the Screenshots up here.

**Comment by Matsv** [comment]
@MultiDJRoni Are players sometimes invisible if they walk/fly in some places? But become visible if they fly/walk back?

**Comment by MultiDJRoni** [comment]
@Matsv They are completely random invisible. I also cant see them in the TAB until the Server restarts.

**Comment by Matsv** [comment]
@MultiDJRoni Does it also happen without TablistPrefix?

**Comment by MultiDJRoni** [comment]
Im not using Tablist Prefix on my BedWars servers

**Comment by Matsv** [comment]
But you said it also happend to 1.8.9 users?

**Comment by MultiDJRoni** [comment]
Yes, it happens to everyone. 1.9 and 1.8.x

**Comment by Matsv** [comment]
@MultiDJRoni Does it also happen without viaversion?

**Comment by MultiDJRoni** [comment]
Nope

**Comment by MylesIsCool** [comment]
Going to close this issue, you may say the bug does not occur without ViaVersion but sadly ViaVersion doesn't touch any 1.8 clients. I've seen this in vanilla bukkit and it's a teleport packet order issue.
