### ISSUE TITLE
Disconnected on join in Creative Mode

### ISSUE THREAD

**Issue by PizzaStix423** [MylesIsCool/ViaVersion#195]
Happens on both 0.6.2 and 0.6.3 but not on 0.6.1 and earlier

No extra plugins installed. Just Spigot and ViaVersion.
Spigot version git-Spigot-15fa8e1-17a3db7 (1.8-R0.1-SNAPSHOT)

Error happens upon login. Player unable to join server.

Kicked with the message "Internal Exception: java.io.IOException: An established connection was aborted by the software in your host machine".

Console error: http://pastebin.com/9dACtcEM

**Comment by HugoDaBosss** [comment]
You are running quite an old version of bukkit, although it should be supported.
Can you try if this error persists with the latest 1.8 version of bukkit?

**Comment by PizzaStix423** [comment]
I use this older version for certain plugins that don't work on later versions.

Attempted to re-create issue using version git-Bukkit-e1ebe52 (1.8.8-R.0.1-SNAPSHOT) with no plugins except ViaVersion 0.6.3

ViaVersion seems unable to enable. Server does not display as 1.9 compatible.

Log: http://pastebin.com/Khv8jmdw

**Comment by HugoDaBosss** [comment]
Did you compile Bukkit yourself? Because the API seems v0.1, but nms seems 0.3

**Comment by PizzaStix423** [comment]
Spigot 1.8.8 fixes both issues.

Sorry for the trouble.

**Comment by HugoDaBosss** [comment]
No problem, but right now ViaVersion isn't working for bukkit?
