### ISSUE TITLE
Boat / horses sync

### ISSUE THREAD

**Issue by Matsv** [MylesIsCool/ViaVersion#196]
### What version of ViaVersion are you using? Type /ver viaversion
0.6.4-SNAPSHOT

### What version of Spigot are you using? Type /ver
1.8.8-latest

### What plugins are you using? Type /plugins
ViaVersion

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No.

### How does this error happen? login? Using an item? 
Boat/horses synchronization sucks. We should probably support the new VEHICLE_MOVE packet some day.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No

**Comment by Matsv** [comment]
> ridalarry @ridalarry 07:27
Ok I just checked the 1.9 changes in boats and found this
that they disabled the sprinting while riding a boat making it go faster in snapshot 15w41a
then they have made the speed of the boat slightly faster than sprinting in snapshot 15w42a
so if a player on 1.8 try to sprint while being in the boat it will be nearly same speed as a player on 1.9 riding a boat

**Comment by Matsv** [comment]
I'm going to close this issue.

**Why?**
We think this issue is too complex to fix without touching directly into spigot.
With 1.10 coming on his way, we recommend you to update to 1.9 when you are ready if you want to use boats that are sync.

**Comment by L4BORG** [comment]
Would changing boat/horse speed on 1.8 server (in a way that it would match 1.9 speed) fix the issue?

**Comment by Matsv** [comment]
Nope, the problem is that we don’t handle the new incoming (Steer vehicle)[http://wiki.vg/Protocol#Vehicle_Move_.28serverbound.29] information. It’s basically just missing real-time information.
