### ISSUE TITLE
ViaVersion isn't compatible with CraftBukkit

### ISSUE THREAD

**Issue by HugoDaBosss** [MylesIsCool/ViaVersion#198]
### What version of ViaVersion are you using? Type /ver viaversion
0.6.4-SNAPSHOT
### What version of Spigot are you using? Type /ver
CraftBukkit version git-Bukkit-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
### What plugins are you using? Type /plugins
ViaVersion, ProtocolLib
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No
### How does this error happen? login? Using an item? 
Start the server
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/3kuNTkHM

**Comment by MylesIsCool** [comment]
Fixed in next version.
