### ISSUE TITLE
'com.google.gson.stream.MalformedJsonException' upon login

### ISSUE THREAD

**Issue by ajthemacboy** [MylesIsCool/ViaVersion#2]
I'm certain this is a dumb question, but I'm not a dev so I don't really know what else to do.

When running `mvn install` I get the error `Failed to execute goal on project ViaVersion: Could not resolve dependencies for project us.myles:ViaVersion:jar:1.0-SNAPSHOT: Could not find artifact org.bukkit:bukkit:jar:1.8.8-R0.1-SNAPSHOT -> [Help 1]`.

As far as I know, Bukkit got taken down in the DMCA, so I assume I have to put a 1.8.8 bukkit.jar in some folder somewhere to use it as a dependency, right? I just don't know where.

Thanks and sorry for the ignorant question.

**Comment by Paulomart** [comment]
You need to build bukkit + craftbukkit + spigot with buildtools

**Comment by ajthemacboy** [comment]
@Paulomart Thanks, I successfully built the plugin.

When I first installed it I got errors about Spigot's anti-xray in console and was unable to login. I disabled anti-xray, and the errors stopped, but I still couldn't login.

Console log: https://gist.github.com/ajthemacboy/df9a2646b6e8661c0b9e
Client error: http://i.imgur.com/Gxafd3U.png

Could this be because I'm using PaperSpigot?

**Comment by ajthemacboy** [comment]
Occurs on Spigot as well.

**Comment by MylesIsCool** [comment]
Try latest version which fixes signs? You can find binary compiled over here https://www.spigotmc.org/threads/viaversion.127105/

**Comment by ajthemacboy** [comment]
@MylesIsCool Looks like the same error, nothing in console: http://i.imgur.com/pNrnWZl.png

**Comment by ajthemacboy** [comment]
Any idea why this happens to me but (seemingly) not anyone else?

**Comment by Bocktrow** [comment]
Experiencing the exact same issue as well.

Stacktrace: https://gist.github.com/Bocktrow/7fe4552a4bbe72874b07

**Comment by MylesIsCool** [comment]
They don't look like same error? 

@Bocktrow Thanks for the new stack trace, i'll look into getting this done ASAP.

@ajthemacboy Are you using any plugins? I've found this error occurs with specific items added by plugins? (I'm looking into fixing it, it's down to how Minecraft are much more strict on certain formatting.)

**Comment by ajthemacboy** [comment]
Here's my plugins: 

`AsyncWorldEditInjector, AntiWDL, WorldEdit, AsyncWorldEdit, Essentials, EssentialsChat, PermissionsEx, PlugMan, ConsoleScheduler, Modifyworld, ViaVersion, BossShop, EssentialsSpawn, Multiverse-Core, MassiveCore, Sunny, WorldGuard, Factions, CombatTagPlus, FactionChat, MineResetLite, SilkSpawners`

Nothing that's not widely used and supported, and nothing that's badly programmed as far as I know.

**Comment by MylesIsCool** [comment]
Gonna close this issue, if you still get an issue please reopen so we can have seperate errors. Try using the new version 0.3.5 it fixes a lot of bugs.
