### ISSUE TITLE
Server hang/crash: java.lang.reflect.InvocationTargetException; Caused by: java.lang.IndexOutOfBoundsException: readerIndex(10) + length(1) exceeds writerIndex(10): UnpooledHeapByteBuf(ridx: 10, widx: 10, cap: 10)

### ISSUE THREAD

**Issue by Bodoo** [MylesIsCool/ViaVersion#202]
### What version of ViaVersion are you using? Type /ver viaversion
0.6.3

### What version of Spigot are you using? Type /ver
1.8.8-R0.1-Snapshot

### What plugins are you using? Type /plugins
Plugins: EchoPet, PermissionsEx, Buycraft, ViaVersion, ProtocolLib

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yes, we're using the newest BungeeCord 1.8/1.9, only self made plugins

### How does this error happen? login? Using an item? 
We don't know. If this error appears, the Exception is thrown multiple hundred times in a second, and the server totally hangs in this time. Sometimes, but only sometimes it stops spamming the exception and the server keeps running, but most of the time the server crashes.
We don't think just catching this error will help, because it is still thrown a lot of times and catching just stops printing the error in the console but still blocks the minecraft server.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://hastebin.com/alaqucigex.css
In 10 seconds 300 Megabyte Exception Log
Players are mostly kicked with Timeout reason

**Comment by Bodoo** [comment]
I've seen the same error with other numbers: http://hastebin.com/alaqucigex.css
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledHeapByteBuf(ridx: 1, widx: 1, cap: 1)
I hope this helps.

**Comment by Bodoo** [comment]
I've actually seen another thing which could be related to this error too: it says 
**[13:57:36] [Server thread/WARN]: Janoschmen was kicked for floating too long!
[13:57:36] [Server thread/INFO]: Janoschmen lost connection: Flying is not enabled on this server
[13:57:36] [Server thread/WARN]: handleDisconnection() called twice**
I'm not sure if this warning has anything to do with the error, but often the error starts getting spammed after a player disconnects.

**Comment by MylesIsCool** [comment]
Use 0.6.7, closing issue. Request reopen if still occurs.
