### ISSUE TITLE
shield bug

### ISSUE THREAD

**Issue by smessie** [MylesIsCool/ViaVersion#204]
### Is there an error in the console? Use pastebin.com. Is there a kick message?

------
Version of ViaVersion: 0.6.3
Version of spigot: 1.8.8
I'm using bungeecord 
-----
I was playing in my 1.8.8 survival world with ViaVersion and I (1.9 client) saw another guy with a shield in his second hand (1.8 client).
Could this be a bug in your plugin or not?
I'm not sure if it is caused  by your plugin but I report it so you can look at it :)

There are also no errors in the console.

**Comment by HugoDaBosss** [comment]
This is not a bug, this is a feature. This way 1.9 players can tell if 1.8 players are blocking.
