### ISSUE TITLE
Sending holograms updates to 1.8 users

### ISSUE THREAD

**Issue by R4G3-BABY** [MylesIsCool/ViaVersion#209]
### What version of ViaVersion are you using? Type /ver viaversion
0.6.5-SNAPSHOT (Build 58 from http://build.fillecraft.com:8080/job/ViaVersion)
### What version of Spigot are you using? Type /ver
git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
### What plugins are you using? Type /plugins
ViaVersion & R4G3Facs(Custom Plugin)
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No
### How does this error happen? login? Using an item? 
When i changed world it gave me an error on the console i think its because of the holograms.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/xzxcuQvR

**Comment by Matsv** [comment]
Thanks for reporting

**Comment by Matsv** [comment]
@R4G3-BABY Should be fixed when #210 get merged :)

**Comment by R4G3-BABY** [comment]
@Matsv Should i close this then?

**Comment by Matsv** [comment]
@R4G3-BABY Yeah, thank you :+1:

**Comment by R4G3-BABY** [comment]
close
