### ISSUE TITLE
Ride bug

### ISSUE THREAD

**Issue by davewanders** [MylesIsCool/ViaVersion#211]
You can't ride on Silverfishes etc too. You can only ride on horses.. Please fix this! (You can ride on every mob/animal with NPC)

**Comment by Matsv** [comment]
This is not a problem from ViaVersion

**Comment by davewanders** [comment]
Yes it is. With 1.8 you can ride on every animal and mob

**Comment by Matsv** [comment]
What plugin do you use? I'll take a look

**Comment by davewanders** [comment]
NPC for riding at mobs

**Comment by Matsv** [comment]
@davewanders Can you please give me a link? :)

**Comment by davewanders** [comment]
http://dev.bukkit.org/bukkit-plugins/citizens/

**Comment by Matsv** [comment]
@davewanders Oh I see. Let me check

**Comment by davewanders** [comment]
Could you fix that?

**Comment by Matsv** [comment]
I'm sorry, this is at Citizens end. I can be passenger of every entity with the normal Bukkit API.
https://fileserver.matsv.nl/media?id=b36b71669d157ec30a46a07c9d4f83d9
I'll take a look at the citizens source later

**Comment by davewanders** [comment]
Allright, could you look at the other bugs?

**Comment by Matsv** [comment]
I close the issue for now. This is something at citizens end. Because it's open-source I might take a look at it later.
