### ISSUE TITLE
Right-clicking food without having hunger looks like interacting

### ISSUE THREAD

**Issue by davewanders** [MylesIsCool/ViaVersion#212]
And if you have full hunger bars, and you have food and you do right click you keep eating food..

**Comment by Matsv** [comment]
I don't have this problem, https://fileserver.matsv.nl/media?id=2d23f42bceabf614d6b6484ef403f67f.
Are you using the latest version? Can you please use the issue template? https://github.com/MylesIsCool/ViaVersion/blob/master/ISSUE_TEMPLATE.md

**Comment by davewanders** [comment]
Newest version of spigot and your plugin.

**Comment by davewanders** [comment]
Come have a look, on my server than you will see.

**Comment by Matsv** [comment]
@davewanders Sure, what is your server ip?

**Comment by davewanders** [comment]
play.blaze-network.net

**Comment by davewanders** [comment]
This bug is only on 1.9

**Comment by TiTo-418** [comment]
It's a vanilla bug

**Comment by HugoDaBosss** [comment]
Can confirm this in singleplayer 1.9 as well, closing this issue
