### ISSUE TITLE
Shield Bug

### ISSUE THREAD

**Issue by davewanders** [MylesIsCool/ViaVersion#213]
And fix that if you have shield-enabled on false in the config, that if you do in the server right click hold, that you can walk normal speed not the speed with the shield button, you understand?

**Comment by Matsv** [comment]
The whole point of the shield is to look like blocking with your sword in 1.8. In 1.8 you get slower, so in 1.9 too

**Comment by davewanders** [comment]
Allright, than this issue can be closed.
