### ISSUE TITLE
*QUESTION* PvP

### ISSUE THREAD

**Issue by davewanders** [MylesIsCool/ViaVersion#214]
Is the attack speed of 1.9 already changed to that of 1.8? Or can players who are on 1.9 hit faster than players at 1.8?

**Comment by Matsv** [comment]
Attackspeed is 1.8

**Comment by davewanders** [comment]
Hmh, doesnt look like, because i can hit faster than someone in 1.8. My sword is going faster than his.

**Comment by davewanders** [comment]
Allright, i have my answer.
