### ISSUE TITLE
I got kicked whenever a bossbar is shown to my client

### ISSUE THREAD

**Issue by TiTo-418** [MylesIsCool/ViaVersion#216]
### What version of ViaVersion are you using? Type /ver viaversion

http://prntscr.com/aetb30
Tested in 0.6.4 too

### What version of Spigot are you using? Type /ver

http://prntscr.com/aetbfv

### What plugins are you using? Type /plugins

http://prntscr.com/aetbnh

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

No

### How does this error happen? login? Using an item? 

Whenever I try to spawn a custom wither
https://github.com/twizmwazin/CardinalPGM/blob/8348aa4f055f06e292473732348d86ce0ae1b19e/src/main/java/in/twizmwaz/cardinal/module/modules/bossBar/FakeWither.java

### Is there an error in the console? Use pastebin.com. Is there a kick message?

http://pastebin.com/1QD1Di9Y
http://prntscr.com/aetes7

**Comment by MylesIsCool** [comment]
Consider using something like BarAPI or looking how BarAPI works I'd assume some of your metadata is wrong

**Comment by HugoDaBosss** [comment]
Index 5 isn't a valid metadata index for a wither, not even for any entity. From the plugin you are using:
`watcher.a(5, isVisible() ? (byte) 0 : (byte) 0); // Visibility of the wither`
There is something wrong with the plugin you are using. Are you sure you are using a plugin made for minecraft 1.8?

**Comment by TiTo-418** [comment]
I removed that line and it still happen, logs: http://pastebin.com/WKbsaf1E

**Comment by TiTo-418** [comment]
@HugoDaBosss Do you have plans on reopen this?

**Comment by MylesIsCool** [comment]
Why would he when it's your code at fault?

**Comment by TiTo-418** [comment]
@MylesIsCool I removed that line, and it still happens, meaning that the line has nothing to do with the error

**Comment by MylesIsCool** [comment]
@TiTo-418 and your code is still wrong.

Look at the error

"[15:23:56] [Netty Epoll Server IO #16/INFO]: An error occurred with entity meta data for WITHER OldID: 15
[15:23:56] [Netty Epoll Server IO #16/INFO]: Old ID: 15 New ID: 10"

Then work from there.
(in other words, remove watcher.a(15, 1); // Prevent wither from moving)

**Comment by TiTo-418** [comment]
It works now, thanks ;)
