### ISSUE TITLE
Bug when dropping items in creative when PlayerDropItemEvent is cancelled

### ISSUE THREAD

**Issue by JBYoshi** [MylesIsCool/ViaVersion#217]
### What version of ViaVersion are you using? Type /ver viaversion

ViaVersion version 0.6.4

### What version of Spigot are you using? Type /ver

This server is running CraftBukkit version git-Spigot-db6de12-3f3c65f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins

AsyncWorldEdit, WorldEdit, ViaVersion, Multiverse-Core, ProtocolLib, LibsDisguises, NoCheatPlus, and a custom plugin.

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

None

### How does this error happen? login? Using an item?

Both of the situations described below involve a 1.9 player in creative mode with a plugin cancelling all `PlayerDropItemEvent`s coming from the player.

Whenever the player attempts to drop an item by clicking an item in the inventory and dropping it outside the window, the stack count may double. This begins after doing the above twice, and only seems to occur on the inventory tab.

When hovering the mouse cursor over an item in creative and pressing Q, the stack count will either increase by 1 (if on the inventory tab) or decrease by 1 without returning the item (if on a different tab).

### Is there an error in the console? Use pastebin.com. Is there a kick message?

None

**Comment by HugoDaBosss** [comment]
Wow, this is by far the strangest bug I have ever seen. I will do some more testing to find the cause of this.

**Comment by MylesIsCool** [comment]
As a progress update on this one so we're not keeping you in the dark:

I've tried modifying the packet so that it sends the regular inventory drop instead and it seems to cause the item just to delete itself. I haven't looked more into it, this isn't a major bug but it's still a bug. And at this point in time duplication > removal.

Hopefully someone else will take another look at this soon

**Comment by Matsv** [comment]
Also happens on Spigot 1.9. Might be a client-sided glitch?

**Comment by MylesIsCool** [comment]
I believe the client can no longer have items revoked, as it isn't vanilla behaviour. Sadly this can't really be fixed :-(

**Comment by Matsv** [comment]
This is a bug inside Spigot 1.8.x, also happens on a 1.8 client.
We'll not fix this.
