### ISSUE TITLE
Can't create BossBar with ViaVersion API

### ISSUE THREAD

**Issue by TheTonyk** [MylesIsCool/ViaVersion#218]
Version: 0.6.4

Spigot: 1.8.8-R0.1

Plugins: ProtocolLib, my own and ViaVersion

BungeeCord: BungeeCoord-1.9-Snapshot

When: On enable of my plugin.

Problem:

I've try yo create BossBar with your API:

`public static BossBar bar = ViaVersion.getInstance().createBossBar("test", 100f, BossColor.WHITE, BossStyle.SOLID);`

and i've also try:

`public static BossBar bar = ViaVersion.getInstance().createBossBar("test", BossColor.WHITE, BossStyle.SOLID);`

My includes:

```
import us.myles.ViaVersion.api.ViaVersion;
import us.myles.ViaVersion.api.boss.BossBar;
import us.myles.ViaVersion.api.boss.BossColor;
import us.myles.ViaVersion.api.boss.BossStyle;
```

I obtain this error: [Pastebin](http://pastebin.com/VEmKVMn4)

Thanks !

**Comment by MylesIsCool** [comment]
This looks fine, your error is somewhere else in the code.

**Comment by MylesIsCool** [comment]
There's a chance that this is happening before ViaVersion has loaded possibly, make sure you depend on it in your config and this is run after it has loaded.

**Comment by TheTonyk** [comment]
When i remove this line i don't have any error.

I've try to add ViaVersion to soft depend in plugin.yml.

The same error again :/

**Comment by TheTonyk** [comment]
Okay, i've define the BossBar as local variable in the onEnable() method and there are no longer error. But there are no BossBar (I've try in 1.8 and 1.9). 

```
BossBar bar =  ViaVersion.getInstance().createBossBar("test", BossColor.WHITE, BossStyle.SOLID);
		
		for (Player player : Bukkit.getOnlinePlayers()) {
			
			bar.addPlayer(player);
			
		}
		
		bar.show();
```

**Comment by Matsv** [comment]
@TheTonyk The bossbar api is only for 1.9. Maybe because nobody is only yet when it enables? Or did you reload?

**Comment by MylesIsCool** [comment]
Don't use it in a static sense then :)

**Comment by TheTonyk** [comment]
Okay, that's work ! But if i can't create a static one, i need to create a new BossBar at every PlayerJoinEvent ?

**Comment by Matsv** [comment]
@TheTonyk I use it like this, this will give players a bossbar when they join: http://pastebin.com/9SkuTicy

**Comment by Matsv** [comment]
@TheTonyk You can make it static and public if you want to

**Comment by TheTonyk** [comment]
Oh yes, i'm stupid lol. Thanks !

**Comment by Matsv** [comment]
No problem :smile:

**Comment by Matsv** [comment]
@TheTonyk If you don't update the bossbar, you might want to remove the players if they leave too
