### ISSUE TITLE
Crash?

### ISSUE THREAD

**Issue by mat41997** [MylesIsCool/ViaVersion#219]
### What version of ViaVersion are you using? Type /ver viaversion
0.6.4

### What plugins are you using? Type /plugins
Plugins (46): AsyncWorldEditInjector, WorldEdit, EggCatcher, Skript, LogBlock, PluginManagerReloaded, SkQuery, RandomTP, Lockette, CustomRecipes, UnCrafter, WorldGuard, SkinsRestorer, ImageMaps, Shopkeepers, WildSkript, BlocksHub, PermissionsEx, HorseTpWithMe, Simple-AutoSave, BlocksHub-LogBlock, AntiJoinBot, ViaVersion, StaffChat, Tablist, Vault, SilkChests, Titlebar, Essentials, multispleef, MobArena, Trading, PreciousStones, ProtocolLib, LibsDisguises, NoCheatPlus, AsyncWorldEdit, ColoredTags, BlocksHub-WorldGuard, EssentialsChat, Parkour, EssentialsSpawn, SexyMotd, AuthMe, ScoreboardStats, HolographicDisplays

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://hastebin.com/xuyuqiqanu.coffee

**Comment by MylesIsCool** [comment]
You are giving yourself invalid items, this is vanilla functionality?
