### ISSUE TITLE
Bug In Creative

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#220]
### What version of ViaVersion are you using? Type /ver viaversion

6.4

### What version of Spigot are you using? Type /ver

Spigot 1.8.8

### How does this error happen? login? Using an item? 

After having the dragon skull

### Is there an error in the console? Use pastebin.com. Is there a kick message?

Nothing

http://zupimages.net/up/16/11/8s6r.jpg

**Comment by HugoDaBosss** [comment]
What exactly is your bug? This plugin is to allow 1.9 players to connect to 1.8 servers, not to add 1.9 features to a 1.8 server.

**Comment by TheIntelloBox** [comment]
Yes but look at the screen : http://www.zupimages.net/up/16/11/8s6r.jpg

In the second hand, there is a strange picture.

**Comment by HugoDaBosss** [comment]
How would you reproduce this error? I am unable to get the same glitch. Could you provide a step by step guide?

**Comment by TheIntelloBox** [comment]
When I put a dragon skull in the second hand.

**Comment by JBYoshi** [comment]
This should not be possible to reproduce anymore, thanks to #232 (you can no longer put items into the off hand in creative).

**Comment by HugoDaBosss** [comment]
This is reproducable, it was done by @Matsv , but is most likely not related to ViaVersion (although not with a dragon head)
https://fileserver.matsv.nl/media?id=04ca29f5969da34587dc9417d7baeba3

**Comment by Matsv** [comment]
1.9 glitch. Happens in singleplayer too.
https://fileserver.matsv.nl/media?id=68d47b7434888dcdf622d32e7d4298ac
