### ISSUE TITLE
Lots of issues (But amazing plugin overall)

### ISSUE THREAD

**Issue by BalloonChamp** [MylesIsCool/ViaVersion#221]
Using ViaVersion 0.6.4

(all versions of spigot and craftbukkit do this that I've tried)

Bug 1: In 1.9 when a player right clicks with a sword, the sheild is still in their hand, but if they take the sheild out of the slot, it disappears. Now the bug: after they take it out, and try to block again, they won't be able to block. They have to relog.

Bug 2: In 1.9, the Spigot built in anti-xray does not work.

Bug 3: NoCheatPlus seems to be freaking out, but not doing anything when a player flies arround.

Bug 4: (Maybe its just me, but players flying arround, and then landing, don't take fall damage. (1.8 and 1.9)

That is all for now, but can someone explain to me how to use this with Bungee? I'm confused. Thanks 

BalloonChamp

**Comment by HugoDaBosss** [comment]
Bug 4 is intented vanilla behaviour. Will test the rest of the bugs.

**Comment by BalloonChamp** [comment]
Ok! Also, how do you do run this with BungeeCord?

**Comment by BalloonChamp** [comment]
And I would be willing to help develop as well!

**Comment by HugoDaBosss** [comment]
@BalloonChamp just use the latest bungee 1.8 + 1.9 build, it will work. 
And if you want to help developing, just fork and submit a PR! We will merge it if it's good ;)

**Comment by BalloonChamp** [comment]
how do i install the plugin on bungee though?

**Comment by Matsv** [comment]
@BalloonChamp it's a bukkit plugin, you can't install it on bungee

**Comment by Matsv** [comment]
It is compatible with bungeecord though, just install it on your spigot/bukkit servers and use the latest bungeecord version

**Comment by BalloonChamp** [comment]
Ok, thanks!, I will try to get the latest 1.8 Bungee!

**Comment by Matsv** [comment]
@BalloonChamp you'll need the latest 1.9 bungee to allow 1.9 players to join. Spigot has to be 1.8

**Comment by MylesIsCool** [comment]
Going to close, if the issues occur please open them in seperate tickets and check they aren't already in the list.

Thanks,

Myles
