### ISSUE TITLE
Arrows at short distance don't look like they fire properly

### ISSUE THREAD

**Issue by davewanders** [MylesIsCool/ViaVersion#222]
### What version of ViaVersion are you using? Type /ver viaversion
Newest version
### What version of Spigot are you using? Type /ver
/
### What plugins are you using? Type /plugins
/
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
yes, 1133 (newest version)
### How does this error happen? login? Using an item? 
If you shoot with a bow, you see the arrow coming back

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No

**Comment by HugoDaBosss** [comment]
This issue is know, I don't think if this will be fixed since it's only a small amount of the time.

**Comment by MylesIsCool** [comment]
This will need retesting with latest build from build server to see if the patch fixes it.

**Comment by MylesIsCool** [comment]
Test on latest please. (0.7.0)

**Comment by HugoDaBosss** [comment]
Still happens, only when firing with a small velocity though.
You can see the arrow coming back, and as soon as it lands serverside it will be placed at the correct loaction.

**Comment by TheIntelloBox** [comment]
When is it fixed ?

**Comment by MylesIsCool** [comment]
Not going to be fixed, so going to lock this issue.

Why? Because there's no easy fix as far as i'm aware. And it's to do with how arrows are sent being changed on the client.
