### ISSUE TITLE
Splash potion entities shown as splash water bottles

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#223]
### What version of ViaVersion are you using? Type /ver viaversion

6.4 

### What version of Spigot are you using? Type /ver

1.8.8

When I heal me with a splash potion of health, I saw the texture of Splash Water Bottle potion ! :(

**Comment by HugoDaBosss** [comment]
Could you please follow the issue template? I will test this.

**Comment by HugoDaBosss** [comment]
Can confirm with the latest spigot and ViaVersion.

**Comment by HugoDaBosss** [comment]
The issue is also present in the latest 1.9 spigot build.
Although with ViaVersion the splash particles are blue, and with spigot 1.9 they are correctly colored.

**Comment by TheIntelloBox** [comment]
What must I do so ?

**Comment by HugoDaBosss** [comment]
We are working on a fix, but there is no proper documentation on this so we have to figure it out ourselves.
