### ISSUE TITLE
Some items show as stone when you drop them

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#224]
### What version of ViaVersion are you using? 

0.6.4

### What version of Spigot are you using? 

1.8.8

When I take a flower like Daisy or Orchid, and when I drop it, this drop a stone/cobble
Same for sapling, dead bush.. This is the same for all the inventory I think.

**Comment by Matsv** [comment]
Thanks for reporting.

**Comment by TheIntelloBox** [comment]
No problem.
If I find another bug I will create another issue.

**Comment by Matsv** [comment]
Happens in Minecraft vanilla 1.9. gg mojang

**Comment by Matsv** [comment]
Client-sided glitch. You can solve it by restarting your minecraft client
