### ISSUE TITLE
Custom Plugin AuraCheck entity spawning causing errors

### ISSUE THREAD

**Issue by NLthijs48** [MylesIsCool/ViaVersion#225]
At first, thank you for this plugin, it is great that I can now allow 1.9 clients on my server next to 1.8.

### What version of ViaVersion are you using? Type /ver viaversion
0.6.4

### What version of Spigot are you using? Type /ver
This server is running CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins
Lots of them, one causing the error is my own plugin AuraCheck.

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord #1133 (of 11 March 2016)

### How does this error happen? login? Using an item? 
Performing an AuraCheck, spawning invisible entities around the player by using packets, and then listening for hits. The spawning packet itself seems to be the cause.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
[http://pastebin.com/Uq5pJigR](http://pastebin.com/Uq5pJigR) The player does not notice anything, it only has errors server side.

The main page of ViaVersion does mention to turn off plugins like this, but I did not see an issue for this problem, so that is why I made this one.
Let me know if you need any more information, like the code that spawns the entities.

**Comment by HugoDaBosss** [comment]
Did you even read the compatibility guide on the spigot plugin page?
AAC is not fully supported, and it never will, because the author doesn't want to work together with us and the plugin is closed source.
To make AAC work use these settings: Disable forcefield checks, make killaura, npcs, spawn rate 0%) (Note: You can just turn on an option in the config to suppress any metadata warnings.)

**Comment by NLthijs48** [comment]
I know that AAC does not work, I have even mentioned that in the ticket, I'm not using that plugin. The page however does not mention why it is not supported, which might be wise to add.

The point here is that my own plugin that performs an killaura check by spawning entities does not work, and produces the error as shown in the linked pastebin. And for this plugin I can give you the source, which should make it possible to debug the issue and search for solutions. This is the reason that I made this ticket.

**Comment by HugoDaBosss** [comment]
Yeah I'm sorry D: @NLthijs48 , saw AuraCheck and assumed AAC...

**Comment by NLthijs48** [comment]
No problem, you probably get a lot of tickets :)

I'm using a modified version of [AntiAura](http://dev.bukkit.org/bukkit-plugins/antiaura/files/2-anti-aura-check-aura-v0-3-mc-1-8/), I have just tested it with AntiAura itself and get the same error. Source of AntiAura is [here](https://github.com/maciekmm/antiaura). Stacktrace with the AntiAura v0.3 version [http://pastebin.com/yEgKG6Yb](http://pastebin.com/yEgKG6Yb).

Let me know if you need any more information.

**Comment by Matsv** [comment]
@NLthijs48 Any idea why AntiAura is setting this to 1? 
https://github.com/maciekmm/AntiAura/blob/master/src/main/java/tk/maciekmm/antiaura/AuraCheck.java#L127

**Comment by NLthijs48** [comment]
@Matsv I honestly have no idea, I could test if it works without it tomorrow.

**Comment by Matsv** [comment]
@NLthijs48 Yeah, that would be helpful, for some reason anticheat plugins use it. it's not documented and I can't find anything about it in the server source.

**Comment by HugoDaBosss** [comment]
If I remove the index of 11 the players will just be visible... @NLthijs48  @Matsv

**Comment by NLthijs48** [comment]
Okey that means the field is useful, is the problem that you don't know to which other field this should be mapped to in 1.9 or is the problem something else?

**Comment by Matsv** [comment]
@NLthijs48 Yeah that's the problem. We can't find anything about it.

**Comment by NLthijs48** [comment]
I have done some research and testing.

AntiAura uses the [WrapperPlayServerNamedEntitySpawn](https://github.com/dmulloy2/PacketWrapper/blob/master/PacketWrapper/src/main/java/com/comphenix/packetwrapper/WrapperPlayServerNamedEntitySpawn.java) class provided by the creators of ProtocolLib to spawn the fake player entities used for the killaura check. As far as I can tell this eventually is using the[ Spawn Mob](http://wiki.vg/Protocol#Spawn_Mob) packet. This packet has a MetaData field, which AniAura sets [here](https://github.com/maciekmm/AntiAura/blob/master/src/main/java/tk/maciekmm/antiaura/AuraCheck.java#L124-L128). This metatdata field is of the [Entity Metadata](http://wiki.vg/Entities#Entity_Metadata_Format) type. Position 11 is the OptUUID field as described on that page, defined as:

> 11, OptUUID (Boolean + Optional UUID), UUID is present if the Boolean is set to true

If I read that I would expect that a combined type with a boolean AND UUID would need to be set, but reading the [Data types](http://wiki.vg/Protocol#Data_types) definition at 'Optional X' it seems that either 0 or the object should be present, 0 or the UUID in this case. Which would also make a lot more sense if you ask me. 
What I actually think it is is the variable listed in the [Player](http://wiki.vg/Entities#Player) entity data table lists position 11, which is 'Score', with data type VarInt. I however have no idea what that would actually do.
In [this commit of AntiAura](https://github.com/maciekmm/AntiAura/commit/7ef9971fb212c18cd984637d8072ed2730728121) it is added, while adding invisibility as an option.

However, I have tested the plugin without setting the thing on index 11, and then it works fine. It correctly spawns the player entities in 1.8 and 1.9, and also spawns them invisible if the option in the config is set to that (in gamemode 3 you can see the fake players spawning).

So it looks like my problem is solved by simply not setting the metadata at index 11. It is however strange that the creator of AntiAura used this, it is likely with a reason.

**Comment by Matsv** [comment]
@NLthijs48 Great to hear it works without setting the metadata index to 11. The strange thing is, in 1.8 there was no index 11: OptUUID (According to wiki.vg http://wiki.vg/index.php?title=Entities&oldid=7097).  :confused:

**Comment by NLthijs48** [comment]
Yeah that is indeed weird, would it be possible to look into the source of MCP and find out what the field does that way?

**Comment by Matsv** [comment]
@NLthijs48 Can't find anything in MCP except these indexes http://wiki.vg/index.php?title=Entities&oldid=7097#Human . Could it be that index 11 never did something, but you didn't got kicked because of invalid metadata in 1.8?

**Comment by NLthijs48** [comment]
Yeah I have seen that page, also looked at the 1.8 version of that. I was thinking the source code might have it somewhere, I myself have no idea where to look for something like that though. It is completely possible that index 11 did nothing at all. Note that the player does not get kicked though, only the server has an error and does not send the packet because of it. Does ViaVersion simply copy all unknown values or does it explicitly declare all mappings?

Since we don't know what index 11 is supposed to do and leaving it out seems to work fine I propose we close the ticket.

**Comment by HugoDaBosss** [comment]
ViaVersion will skip unknown values, it will throw an error @NLthijs48

**Comment by Matsv** [comment]
I close the issue because it's fixed, thanks for your help & research @NLthijs48
