### ISSUE TITLE
Dropped items showing as stone

### ISSUE THREAD

**Issue by HugoDaBosss** [MylesIsCool/ViaVersion#226]
### What version of ViaVersion are you using? Type /ver viaversion
tested with 0.6.4, 0.6.2, 0.4.6
### What version of Spigot are you using? Type /ver
 git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
### What plugins are you using? Type /plugins
ViaVersion, Protocol
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No
### How does this error happen? login? Using an item? 
Drop any item, it will appear as stone
@Matsv stated this was working yesterday, maybe a secret 1.9 client update?
### Is there an error in the console? Use pastebin.com. Is there a kick message?
No errors

**Comment by Matsv** [comment]
#224

**Comment by HugoDaBosss** [comment]
Whoops @Matsv
