### ISSUE TITLE
Server List Plus

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#227]
### What version of ViaVersion are you using? Type /ver viaversion

1.8.8

### What version of Spigot are you using? Type /ver

6.4

### What plugins are you using? Type /plugins

Server List Plus.

Hello,

In my MOTD my slots are in 1.8 : http://zupimages.net/up/16/11/h2ve.jpg
And in 1.9 : http://zupimages.net/up/16/11/pvi4.jpg

**Comment by Matsv** [comment]
Should be fixed next version.
