### ISSUE TITLE
Golden Apple

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#229]
### What version of ViaVersion are you using? 

6.4

### What version of Spigot are you using? 

1.8.8

When I put a Golden Apple in the second hand, they are dropped : but 64 golden apples are dropped or, I've the 63 others in my inventory.

**Comment by Matsv** [comment]
I'm sorry, I'm not sure what you mean. Do you mean, when you have 64 golden apples in your inventory, and pick up 1, leave the other 63 in your inventory -> Put it into your second hand, it'll throw all 64 items on the ground? :confused:

**Comment by TheIntelloBox** [comment]
Yes. :)

**Comment by Matsv** [comment]
What plugins are you using?

**Comment by TheIntelloBox** [comment]
Via Version and other plugins who don't affect ViaVersion and minecraft.

**Comment by HugoDaBosss** [comment]
@TheIntelloBox We are happy to help you with your issues, but if you don't follow the issue template there is not much we can do. The issue template was not just made to annoy you, but for us to better analize the problem. I will mark this as invalid while there is still missing some information like your plugins.

**Comment by MylesIsCool** [comment]
Going to close, nobody else reports this can't replicate on latest version. Using Spigot and just ViaVersion.
