### ISSUE TITLE
Bow

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#230]
### What version of ViaVersion are you using? 

6.4

### What version of Spigot are you using? 

1.8.8 - latest

### What plugins are you using? Type /plugins

Server List Plus

When I have a bow in my second hand and when I shoot an arrow, it isn't shoot : it stays in the inventory and I don't see it.

**Comment by Matsv** [comment]
Don't use items in your second hand. It's not supported.
