### ISSUE TITLE
Potions

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#234]
### What version of ViaVersion are you using? 

6.4

### What version of Spigot are you using?

1.8.8-latest

### What plugins are you using? 
ViaVersion

When I take three potions like 2 splash of healing and one lingering of jumpboost, and when I click on one of the 2 splash of healing, the lingering is disappeared.

**Comment by Matsv** [comment]
The lingering is a ghost item, the client thinks you have that potion. But the server didn't register it.. Lingering potions doesn't exists in 1.8.
