### ISSUE TITLE
Potions (2) : Another Issue

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#235]
### What version of ViaVersion are you using? 

6.4

### What version of Spigot are you using? Type /ver

1.8.8-latest

I can drink a splash uncraftable potion

**Comment by HugoDaBosss** [comment]
@TheIntelloBox Again, please follow the issue template. Could you add some more details on this 'splash uncraftable potion'? How to reproduce, what data values etc etc.

**Comment by MylesIsCool** [comment]
This is not a bug, you are using a 1.9 item on 1.8. Uncraftable potion is just a water bottle I believe.
