### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#237]
### What version of ViaVersion are you using? 

6.4

### What version of Spigot are you using? 

1.8.8-latest

### What plugins are you using?

ViaVersion

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Not BungeeCord

### How does this error happen? login? Using an item? 

This error happens when I hit a player in gamemode creative and when I see me in F5 mode, I don't see the hit on ThePlayer.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

Nothing

**Comment by HugoDaBosss** [comment]
This is most likely a client-side glitch and has nothing to do with ViaVersion. To add, I'm not able to reproduce this bug.
