### ISSUE TITLE
Black Colour

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#238]
### What version of ViaVersion are you using? 

6.4

### What version of Spigot are you using? 

1.8.8-latest

### What plugins are you using? 

Via Version

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Not BungeeCord

### How does this error happen? login? Using an item? 

When I put a skull in my head, the chestplate, the leggings and the boots are black in the inventory.
Using a player skull.

**Comment by Matsv** [comment]
This is probably a client-sided glitch. Can't reproduce it.

**Comment by TheIntelloBox** [comment]
https://bugs.mojang.com/browse/MC-94576

**Comment by Matsv** [comment]
Thanks for sharing the bug report

**Comment by TheIntelloBox** [comment]
You're welcome.
