### ISSUE TITLE
Title on join is causing crash (JSON error)

### ISSUE THREAD

**Issue by HAlexTM** [MylesIsCool/ViaVersion#24]
I think is the title, and not the tab's header & footer that..
cause another crash with the JSON error

**Comment by HugoDaBosss** [comment]
Could you please provide a crash log or the actual error?
Or what Title you are trying to send?

**Comment by HAlexTM** [comment]
The title is a colored one (&a)(So changed to colored)

Title: MineLight
Subtitle: If you are on 1.9 it is in BETA

Cannot provide a crash log for now sorry

**Comment by MylesIsCool** [comment]
See above. Will be in next version.

**Comment by HAlexTM** [comment]
WoW thank you, I never known devs like you are, The best for you and contributors
