### ISSUE TITLE
Error spam: Unable to get entity for ID: xx

### ISSUE THREAD

**Issue by SpEeD11** [MylesIsCool/ViaVersion#240]
### What version of ViaVersion are you using? Type /ver viaversion
0.6.4
### What version of Spigot are you using? Type /ver
1.8.8
### What plugins are you using? Type /plugins
ProtocolLib, Custom plugin (see below)
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
no
### How does this error happen? login? Using an item? 
tested with just protocollib (latest 3.6.5) and a custom plugin which hides snowballs:  http://pastebin.com/khqkSf58

### Is there an error in the console? Use pastebin.com. Is there a kick message?
everything works as intended (snowballs are hidden), no one kicked but spams console with:
http://pastebin.com/nxMbHRYb

only happens when using 1.9 client, not 1.8

**Comment by HugoDaBosss** [comment]
This is because other packets like velocity and metadata are still sent for this specific snowball. The packet is never sent, so Via\version is unable to know about this snowball. You should also stop all other packets with the same entityid as the cancelled snowball spawn packets.
