### ISSUE TITLE
Some sounds missing using 1.9 client

### ISSUE THREAD

**Issue by SpEeD11** [MylesIsCool/ViaVersion#241]
### What version of ViaVersion are you using? Type /ver viaversion
0.6.5
### What version of Spigot are you using? Type /ver
1.8.8
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
no
### How does this error happen? login? Using an item? 
some sounds such as Sound.FIRE_IGNITE can not be heard when using 1.9 client. the actual sound works when naturally occuring (using a flint and steel) but not when using the p.playSound() method. 
Not sure if related to viaversion, apologies if it isnt.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
no

**Comment by HugoDaBosss** [comment]
This is caused by #199 
1.9 clients handle some sound clientside, but only sounds which are produced by the player itself. The 1.8 server doesn't make a difference between different sound packets, so we have been unable to fix this problem yet...

**Comment by MylesIsCool** [comment]
Going to close, see #199 for progress
