### ISSUE TITLE
Little bug : PlayerInteractEvent is send 2 time in 1.9 and 1 time in 1.8

### ISSUE THREAD

**Issue by fabien91** [MylesIsCool/ViaVersion#244]
### What version of ViaVersion are you using? Type /ver viaversion
ViaVersion 0.6.5

### What version of Spigot are you using? Type /ver
This server is running CraftBukkit version git-Spigot-db6de12-3f3c65f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins
Plugins (28): WorldEdit, Essentials, AutoMessage, Buycraft, HolographicDisplays, FancyPortals, TeleportSigns, WorldGuard, BungeePlayerCounter, EssentialsChat, WGRegionEvents, PressurePush, PermissionsEx, SQLibrary, Just2Tools, ViaVersion, WGCustomFlags, StaffChat, CustomJoinItems, Vault, HubSpeed, EssentialsSpawn, TitleManager, PlayerPoints, ColoredTags, ChestCommands, WGRegionCommands, ColoredTablist

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Last version of Bungeecord 1.8-1.9
Plugins : BungeePerms, BungeeStaffChat, CommandControl and ServerListPlus

### How does this error happen? login? Using an item? 
The event PlayerInteractEvent is send 2 time in 1.9 because we have two hand but in 1.8 it's good, the event was send 1 time.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No

Sincerely,
Fabien

**Comment by HugoDaBosss** [comment]
Can confirm this. 
There has to have been a clientsided change, because this issue has only been appearing recently, and I didn't update anything on my server.

**Comment by xXAndrew28Xx** [comment]
Still persists in 0.7.9 for me.

**Comment by Matsv** [comment]
@xXAndrew28Xx #326
