### ISSUE TITLE
Randomly dying when riding an entity

### ISSUE THREAD

**Issue by Zaino60** [MylesIsCool/ViaVersion#245]
### What version of ViaVersion are you using? 
0.6.4
### What version of Spigot are you using? 
https://gyazo.com/12baec23b163ec77133d1fd6eaeb665e
### What plugins are you using? 
https://gyazo.com/1a2843a3aa775ad63d248e4001e2fecd
### Are you using any additional software like BungeeCord? If so, what software and version? 
Yes, Bungeecord. Version: https://gyazo.com/c71bea89826f7fe01d44dffa3c113d14
### How does this error happen? login? Using an item? 
When you are riding a mob in 1.9 (I just tested with a pig and a horse but I think it's with all entities), you randomly die when you are walking/jumping around and void is near. I have an adventure map and its really annoying because currently the levels you ride a pig and a horse are impossible if you are using 1.9 Example of the bug: https://www.youtube.com/watch?v=OfIMcFknayQ (Skip to 13:50 to start watching when the youtubers try the impossible level due to the bug and die many times).
### Is there an error in the console? Use pastebin.com. Is there a kick message? 
Nope, no errors

**Comment by Matsv** [comment]
The new client sided horse / boat sync is not implemented yet. #196

**Comment by Zaino60** [comment]
Any idea when this will be done?

**Comment by Matsv** [comment]
@Zaino60 I'm currently checking out the possibilities how we can implement this well. I've tried to just make it 1.8 (boat/horse) riding, but that looks pretty shit, but is sync. https://fileserver.matsv.nl/media?id=1c881701fa32aa09bce6dd7d18053db4

**Comment by MylesIsCool** [comment]
Closing as it's a duplicate see #196 for progress
