### ISSUE TITLE
Sword ==> Shield

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#246]
### What version of ViaVersion are you using? 

6.5

### What version of Spigot are you using? 

1.8.8-latest

### What plugins are you using? 

ViaVersion 6.5

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

No 
### How does this error happen? login? Using an item? 

When I have a sword in my hand and when I do a right click on someone, this appears a shield in my hand.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

No.

**Comment by Matsv** [comment]
Do you mean it stays in your second hand?

**Comment by Matsv** [comment]
The shield is a feature which replace blocking with your sword in 1.8. You can disable it in the config if you don't want it

**Comment by MylesIsCool** [comment]
As intended.
