### ISSUE TITLE
Server crash - Possible deadlock with BossBar API

### ISSUE THREAD

**Issue by alexmarkey** [MylesIsCool/ViaVersion#249]
### What version of ViaVersion are you using? Type /ver viaversion

0.6.6

### What version of Spigot are you using? Type /ver

http://prntscr.com/ah1ppz

### What plugins are you using? Type /plugins

http://prntscr.com/ah1puv

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Using LilyPad, Plugins are LilyPad-Connect

### How does this error happen? login? Using an item? 

Server randomly crashes, shows the following in console - http://prnt.sc/ah0n39

### Is there an error in the console? Use pastebin.com. Is there a kick message?

Log file from the crash - http://pastebin.com/sRBLzCMz

**Comment by HugoDaBosss** [comment]
This has something do with your machine or server, not with ViaVersion

**Comment by MylesIsCool** [comment]
Use 0.6.7, closing issue. Request reopen if still occurs.

**Comment by alexmarkey** [comment]
Issue is still here using 0.6.7

**Comment by alexmarkey** [comment]
Running 4 kitpvp servers on same machine, 1270 V3 machine each server has 6gb dedicated each

**Comment by L4BORG** [comment]
I think we have the same issue on our SkyWars server it would kept getting killed (by OS, due high load) ...

**Comment by alexmarkey** [comment]
Not sure what your issue is however we fixed this by not using your provided boss bar API, all servers have now been online for the past 24+ hours.

**Comment by alexmarkey** [comment]
Have the following information that may help you guys out in resolving :)

Our only server that didn't crash using your API was our Creative server, only thing that Creative has that's different is players don't die on it, server that crashed the most was kitpvp, players die a shit load in Kitpvp, so im assuming something is going wrong when resending the packets after they die? not sure.

**Comment by MylesIsCool** [comment]
@alexmarkey so does it work just without using bossbar API?

**Comment by alexmarkey** [comment]
We are currently just using this API https://www.spigotmc.org/resources/api-bossbarapi-1-7-1-8-1-9.7504/ for the 1.8 boss bar, then letting ViaVersion convert it and that is working fine for us.

The crashes occur when using the boss bar implemented into ViaVersion :)

**Comment by MylesIsCool** [comment]
Will continue to investigate overviewed our code and can't find a cause but it may be easy in other code to cause this using concurrency elsewhere. Will reopen if I find more cases.
