### ISSUE TITLE
KitPvP Server Crash

### ISSUE THREAD

**Issue by alexmarkey** [MylesIsCool/ViaVersion#251]
### What version of ViaVersion are you using? Type /ver viaversion

0.6.5

### What version of Spigot are you using? Type /ver

http://prntscr.com/ah490g

### What plugins are you using? Type /plugins

http://prntscr.com/ah4927

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

LilyPad - LilyPad-Connect.jar

### How does this error happen? login? Using an item? 

Server randomly crashes, unknown what causes it

### Is there an error in the console? Use pastebin.com. Is there a kick message?

Server log during crash - http://pastebin.com/Q4frBNSz

**Comment by HugoDaBosss** [comment]
Well it just looks like your server timed out, probably has nothing to do with ViaVersion.

**Comment by alexmarkey** [comment]
We run a 5,000 player network.  Our 4 kitpvp servers have been running flawlessly for months on end without crashing until 48 hours ago when we updated our entire network to viaversion.

Since then all 4 of our kitpvp servers have been crashing atleast 5 times a day.  This has something to do with Viaversion.

**Comment by alexmarkey** [comment]
Should probably mention this crash has only happened once, all the other crashes are all my other issue that I posted which you also said had nothing to do with viaversion.  Sorry for the confusion.

**Comment by HugoDaBosss** [comment]
Okay if this is the case the server timeouts are caused by ViaVersion. The timeout of the getInHandItem method is 10 seconds, so maybe there was a lag spike which lasted 10+ seconds?

**Comment by alexmarkey** [comment]
could be possible, ill see how we go over night and report back with any more crashes that we have, this one may have been a one off hopefully.

**Comment by HugoDaBosss** [comment]
Okay I was able to crash my own server by overloading it: http://pastebin.com/P1HcAnTw

**Comment by HugoDaBosss** [comment]
It looks like your server is stuck on saving some chunks. The current server thread is blocked because it is waiting for IO. 
Line 223:
```
[21:30:50] [crash-observer/INFO]: Current Thread: Server thread
[21:30:50] [crash-observer/INFO]:     PID: 17 | Alive: true | State: BLOCKED
[21:30:50] [crash-observer/INFO]:     Stack:
[21:30:50] [crash-observer/INFO]:         net.minecraft.server.v1_8_R3.RegionFile.chunkExists(RegionFile.java:91)
```
Line 247:
```
[21:30:50] [crash-observer/INFO]: Current Thread: File IO Thread
[21:30:50] [crash-observer/INFO]:     PID: 74 | Alive: true | State: RUNNABLE
[21:30:50] [crash-observer/INFO]:     Stack:
[21:30:50] [crash-observer/INFO]:         java.io.RandomAccessFile.write0(Native Method)
```
This error seems not related to ViaVersion. You probably changed something else which causes this error.

**Comment by YellowZaki** [comment]
c

**Comment by MylesIsCool** [comment]
@YellowZaki Your using an old version or something, check your config options and delete and renew if necessary ensure you're on 0.8.2.
