### ISSUE TITLE
Void Lag

### ISSUE THREAD

**Issue by wow4201** [MylesIsCool/ViaVersion#256]
### How does this error happen? login? Breaking through ground that exposes void

This only affects 1.9 clients it seems. But if you put a hole in ground, and underneath it is void,
It fps lags 1.9 clients really bad, everyone complains to me, I tested 0.5.5 -> 0.6.6

I also tried most config options

**Comment by MylesIsCool** [comment]
Have you tested this in vanilla, pretty sure this might be a vanilla issue.

**Comment by HugoDaBosss** [comment]
This is not caused by ViaVersion. This has been the same in all clients when you create a hole to a closed area, because the client needs to recalculate the light. This has never been the case with the void before though, but this is surely a 1.9 bug.

**Comment by MylesIsCool** [comment]
Closing as it seems to be vanilla issue
