### ISSUE TITLE
Version 0.6.7 / 0.6.6 causing lag/crashes?

### ISSUE THREAD

**Issue by L4BORG** [MylesIsCool/ViaVersion#262]
### What version of ViaVersion are you using? Type /ver viaversion
Tried both, 0.6.7 and 0.6.6 but now I'm using 0.6.5 because it seems to be more stable...

### What version of Spigot are you using? Type /ver
Latest PaperSpigot

### What plugins are you using? Type /plugins
On most of servers: ServerManager, AsyncWorldEditInjector, Deadbolt, OpenInv, PlayerWarps, Buycraft, Chairs, WorldBorder, Votifier, AutoSaveWorld, AsyncWorldEdit, ViaVersion, GAListener, Vault, WorldEdit, Essentials, LogBlock, Auctions, TrailGUI, SilkSpawners, ProtocolLib, WorldGuard, AuctionHousePlus, NoCheatPlus, EchoPet, PlayerVaults, EssentialsSpawn, GriefPrevention, ChestShop, CombatTagPlus, HolographicDisplays, TradeMe, UserManager

Lastest versions caused huge issues on our SkyWars server (https://github.com/walrusone/SkyWarsReloaded) and some lag on all other servers actually... (could be memory leaks causing GC to act out or something else) but funny thing is this was not happening with ViaVersion 0.6.5...

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Using latest BungeeCord with NuVotifier, ServerListPlus, SkinsRestorer

### How does this error happen? login? Using an item? 
0.6.6 and 0.6.7 soon after restart (minutes if we have lots of players online, 100+)... TPS drops would get worse and worse along with CPU load (spikes).

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Not really it would usually ended with OS killing process (due high CPU load) or just massive lags (like TPSs would jump between 5 and 20, which got me thinking it could be GC, memory leak...).

Also it looks like 0.6.7 would crash even more often than 0.6.6, but with any of those two versions of ViaVersion our SkyWars server wouldn't make it pass 6 hours without restart...

**Comment by MylesIsCool** [comment]
Are you able to use a profiler to gather the cause of the memory leaks?

Otherwise we can't help, as we can't replicate.

**Comment by HugoDaBosss** [comment]
We are getting reports of memory leaks by you and @alexmarkey as well.
Would it be possible that you profile the server with a profiler?

**Comment by L4BORG** [comment]
Lobby server with 2GB ram running for aprox. 40 minutes:

![screen](http://shrani.si/f/Y/QD/qcHPKk/1.png)
![screen](http://shrani.si/f/2/ha/3H5t6VCU/2.png)
![screen](http://shrani.si/f/3n/US/3yoTr2T8/3.png)

sadly I can't do profiling on SkyWars server because it would make it unplayable...

**Comment by L4BORG** [comment]
That's with latest ViaVersion (screens).

**Comment by HugoDaBosss** [comment]
Wow that SoundEffect array is trange, I'll look into it

**Comment by MylesIsCool** [comment]
@L4BORG Are you able to get the references for these big objects to find out what strings these are?

Sound effect should be fine as it's constant.

**Comment by HugoDaBosss** [comment]
Yeah but 19k instances? That's not normal right @MylesIsCool

**Comment by L4BORG** [comment]
![screen](http://shrani.si/f/q/cC/3mbHLFwF/4.png)

Ofc. the issue isn't that obvious on lobby... but it's best I've come up so far...

**Comment by L4BORG** [comment]
![screen](http://shrani.si/f/C/mn/3IkSqE5f/5.png)

**Comment by L4BORG** [comment]
Okey, maybe there is no memory leaks in 0.6.7... could it be the same issue as https://github.com/MylesIsCool/ViaVersion/issues/194 ? I've been doing some testing and 0.6.5 would get killed due high load after console is spammed with exceptions, now with 0.6.7 the exact same thing would happen except that I can't see exceptions (because they're caught in try catch?) ...

**Comment by L4BORG** [comment]
Yep, high load and... "killed" (with 0.6.7) but without exception spam in console. Testing without ViaVersion now.

**Comment by HugoDaBosss** [comment]
Thanks for you work on trying to fix this issue, we really appreciate it.
So the issue persists on 0.6.5 and 0.6.7?

**Comment by HAlexTM** [comment]
On 0.6.6 and 0.6.7

**Comment by xion87** [comment]
Also i got a lot of user disconected for broken pipe... with latest releases, is related to this issue?

**Comment by L4BORG** [comment]
xion87 on connect? If player is connected to bungee and tries to join the server before "startup" is complete? I don't think that's related....

Maybe it was PaperSpigot issue (my issue), just downgraded to old version (10 mar) and it seems ok now, will do some more testing (with ViaVersion 0.6.7).

**Comment by xion87** [comment]
I am using normal spigot and i see  messages like this sometimes, also a my friend say that crashed for "this server stop to respond" and 1-3 times  you are alaredy  connected to this proxy (bungee)
also is normal these messages?
Line 6808: [09:33:31] [Server thread/INFO]: emakiller lost connection: Internal Exception: java.io.IOException: Pipe interrotta
	Line 6809: [09:33:31] [Server thread/INFO]: RapZ lost connection: Internal Exception: java.io.IOException: Pipe interrotta
	Line 6873: [09:34:07] [Server thread/INFO]: oSweg lost connection: Internal Exception: java.io.IOException: Pipe interrotta
	Line 7053: [09:35:48] [Server thread/INFO]: Car321 lost connection: Internal Exception: java.io.IOException: Pipe interrotta
	Line 7347: [09:37:55] [Netty Server IO #0/WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
	Line 7347: [09:37:55] [Netty Server IO #0/WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
	Line 7349: [09:37:55] [Server thread/INFO]: Misterybox132YT lost connection: Internal Exception: java.io.IOException: Pipe interrotta
	Line 7350: [09:37:55] [Server thread/INFO]: foxgy11 lost connection: Internal Exception: java.io.IOException: Pipe interrotta
	Line 7402: [09:38:20] [Server thread/INFO]: ambrogio05 lost connection: Internal Exception: java.io.IOException: Pipe interrotta
	Line 7406: [09:38:22] [Server thread/INFO]: geco lost connection: Internal Exception: java.io.IOException: Pipe interrotta
	Line 7419: [09:38:30] [Server thread/INFO]: xSamumine_ lost connection: Internal Exception: java.io.IOException: Pipe interrotta
	Line 7452: [09:38:56] [Server thread/INFO]: haters lost connection: Internal Exception: java.io.IOException: Pipe interrotta
	Line 7464: [09:39:07] [Server thread/INFO]: AriannA02 lost connection: Internal Exception: java.io.IOException: Pipe interrotta

**Comment by L4BORG** [comment]
Not ViaVersion issue, works fine after PaperSpigot downgrade...

```
>sm
[23:44:15 INFO]: Players: 99 / 250
[23:44:15 INFO]: TPS: 20, 19.94 (NMS)
[23:44:15 INFO]: Uptime: 24 hours 25 minutes 17 seconds
[23:44:15 INFO]: Memory: 5,059 MB free, out of 7,168 MB (Maximum 7,168 MB)
```

**Comment by HugoDaBosss** [comment]
Thanks for your updates @L4BORG ! Good to hear it wasn't ViaVersion

**Comment by xion87** [comment]
so is also a issue of latest paperspigot?
