### ISSUE TITLE
unable to load plugin

### ISSUE THREAD

**Issue by jerzean** [MylesIsCool/ViaVersion#272]
### What version of ViaVersion are you using? Type /ver viaversion
0.6.7
### What version of Spigot are you using? Type /ver
git-Spigot-ec3f46e-2359f6f (MC: 1.8.7)
### What plugins are you using? Type /plugins
GroupManager, WorldEdit, BossShop, Vault, EmptyWorldGenerator, BungeePortals, WorldGuard, Essentials, PlotSquared, CTSNC, Citizens, GuiShopManager, EssentialsProtect, EssentialsSpawn, Sentry, CommandNPC, EssentialsChat, Multiverse-Core, EssentialsAntiBuild
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
yes   default plugins
### Is there an error in the console? Use pastebin.com. Is there a kick message?

23.03 22:24:38 [Server] ERROR Could not load 'plugins/ViaVersion-0.6.7.jar' in folder 'plugins'
23.03 22:24:38 [Server] INFO org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
23.03 22:24:38 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[spigot40.jar:git-Spigot-ec3f46e-2359f6f]
23.03 22:24:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot40.jar:git-Spigot-ec3f46e-2359f6f]
23.03 22:24:38 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [spigot40.jar:git-Spigot-ec3f46e-2359f6f]
23.03 22:24:38 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot40.jar:git-Spigot-ec3f46e-2359f6f]
23.03 22:24:38 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot40.jar:git-Spigot-ec3f46e-2359f6f]
23.03 22:24:38 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
23.03 22:24:38 [Server] INFO Caused by: java.util.zip.ZipException: zip file is empty
23.03 22:24:38 [Server] INFO at java.util.zip.ZipFile.open(Native Method) ~[?:1.7.0_80]
23.03 22:24:38 [Server] INFO at java.util.zip.ZipFile.<init>(ZipFile.java:215) ~[?:1.7.0_80]
23.03 22:24:38 [Server] INFO at java.util.zip.ZipFile.<init>(ZipFile.java:145) ~[?:1.7.0_80]
23.03 22:24:38 [Server] INFO at java.util.jar.JarFile.<init>(JarFile.java:154) ~[?:1.7.0_80]
23.03 22:24:38 [Server] INFO at java.util.jar.JarFile.<init>(JarFile.java:118) ~[?:1.7.0_80]
23.03 22:24:38 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:150) ~[spigot40.jar:git-Spigot-ec3f46e-2359f6f]

**Comment by jerzean** [comment]
its my hub server  it worked before i updated the plugin

**Comment by Matsv** [comment]
It looks like you changed the plugin.ynl

**Comment by JBYoshi** [comment]
```
23.03 22:24:38 [Server] INFO Caused by: java.util.zip.ZipException: zip file is empty
```
Uh...?

**Comment by MylesIsCool** [comment]
You have a corrupted version, redownload. Closing this.
