### ISSUE TITLE
Team viaversion already exists in this scoreboard

### ISSUE THREAD

**Issue by fabien91** [MylesIsCool/ViaVersion#276]
### What version of ViaVersion are you using? Type /ver viaversion
Last on GitHub 0.6.8

### What version of Spigot are you using? Type /ver
Last version

### What plugins are you using? Type /plugins
Plugins (28): WorldEdit, Essentials, AutoMessage, Buycraft, HolographicDisplays, FancyPortals, TeleportSigns, WorldGuard, BungeePlayerCounter, EssentialsChat, WGRegionEvents, PressurePush, PermissionsEx, SQLibrary, Just2Tools, ViaVersion, WGCustomFlags, StaffChat, CustomJoinItems, Vault, HubSpeed, EssentialsSpawn, TitleManager, PlayerPoints, ColoredTags, ChestCommands, WGRegionCommands, ColoredTablist

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Last version of Bungeecord 1.8-1.9
Plugins : BungeePerms, BungeeStaffChat, CommandControl, ServerListPlus and Just2Ban

### How does this error happen? login? Using an item? 
Random

### Is there an error in the console? Use pastebin.com. Is there a kick message?
We have someone disconnection with this error in bungee console : http://pastebin.com/B2b2ubCV

**Comment by MylesIsCool** [comment]
Disable auto-team
