### ISSUE TITLE
Poison potion / eating

### ISSUE THREAD

**Issue by GaryTheSnail** [MylesIsCool/ViaVersion#278]
### What version of ViaVersion are you using? Type /ver viaversion
ViaVersion 0.6.7
### What version of Spigot are you using? Type /ver
CraftBukkit version git-PaperSpigot-443 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
### What plugins are you using? Type /plugins
ViaVersion
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
N/a
### How does this error happen? login? Using an item? 
Upon a receiving a poison debuff in 1.9, the player does not take damage until he moves. Similarly, eating food is not possible unless the player is simultaneously moving and eating.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
N/a

**Comment by HugoDaBosss** [comment]
This should have been fixed by: https://github.com/MylesIsCool/ViaVersion/commit/d5e9170109085c80b30ddb71015bc538d8bbfecc
Make sure 'simulate-pt' is set to true in your config.

**Comment by MylesIsCool** [comment]
Gonna close can't replicate, also probably simulate-pt being off.

**Comment by GaryTheSnail** [comment]
Very sorry for submitting the issue. I did have simulate-pt at false, must've skimmed past it somehow.
Thanks for helping though.
