### ISSUE TITLE
ERRORS

### ISSUE THREAD

**Issue by JustJordyNL** [MylesIsCool/ViaVersion#281]
0.7.0

 CraftBukkit version git-Spigot-6c9b0a1-de5c261 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Plugins (40): MotdManager, CoreProtect, Ridemycraft, ArmorColorChanger, GUICalculator, WorldEdit, Installer, HealthBar, RolePlayCalendar, Essentials, GroupManager, AutoBroadcaster, Aspiire-public, CrackShot, StopCrafting, Chairs, MinetopiaATM, Multiverse-Core, ProtocolLib, WorldGuard, pvpWhitelist, SignEdit, AnvilBlock, Multiverse-Inventories, Rename, cShortcut, EssentialsChat, MaintenanceMode, Vault, EssentialsSpawn, UndineMailer, ArmorWeight, Titlebar, LWC, HolographicDisplays, CommandSigns, CraftHeads, OnTime, ChestCommands, ServerSigns

###  IDK

THE ERROS:
Error fetching hand item: java.lang.IllegalArgumentException
 &
 incoming packet not found 79 state: HANDSHAKE

**Comment by HugoDaBosss** [comment]
Please follow the issue template, that way we will be able to actually assist you.
Could you post the full log of your console to [www.pastebin.com](www.pastebin.com)?
I'll look into this, but I'm not sure if I'm able to help with this little information.

**Comment by HugoDaBosss** [comment]
I saw you also reviewed our plugin. If we fix this issue, could you please remember to update your review? It would mean a lot to us, thanks!

**Comment by MylesIsCool** [comment]
"incoming packet not found 79 state: HANDSHAKE" is not given by version 0.7.0.

Reloads are not supporting / your server is lagging. Most likely the first.
