### ISSUE TITLE
Server List Plus : AGAIN

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#282]
### What version of ViaVersion are you using? 

7.0

### What version of Spigot are you using?

1.8.8-latest

### What plugins are you using?

Via Version

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Nothing

### How does this error happen? login? Using an item? 

https://github.com/MylesIsCool/ViaVersion/issues/227

### Is there an error in the console? Use pastebin.com. Is there a kick message?

Nothing

**Comment by Matsv** [comment]
Thanks for reporting.

**Comment by Matsv** [comment]
Fixed in the next version.
