### ISSUE TITLE
ItemRewriter does not keep NBT data for names of spawned in items.

### ISSUE THREAD

**Issue by ridalarry** [MylesIsCool/ViaVersion#284]
### What version of ViaVersion are you using? Type /ver viaversion
0.6.7
### What version of Spigot are you using? Type /ver
https://gyazo.com/ebcddd00b5ce50d17256f6e2820a447a
### What plugins are you using? Type /plugins
Essentials, and ProtocolLib
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No
### How does this error happen? login? Using an item? 
giving a named spawn egg would reset the spawn egg name if the player is on 1.9 client
https://gyazo.com/af83e172b89eba72f8018bac1c522579
### Is there an error in the console? Use pastebin.com. Is there a kick message?
There is no error in console nor kick message

**Comment by HugoDaBosss** [comment]
I'm not experiencing this issue on 0.7.0. Could you retest this please on 0.7.0?

**Comment by ridalarry** [comment]
@HugoDaBosss I tried it on 0.7.0 and it still happening

**Comment by Matsv** [comment]
Confirmed, also happening for me.

**Comment by Matsv** [comment]
This is how I get it,

* Rename any item with an anvil
* put that item in your hand
* open your inventory
* Itemname goes back to default

**Comment by Matsv** [comment]
Fixed
