### ISSUE TITLE
Chests do not open if clicked with a non-block item in hand

### ISSUE THREAD

**Issue by ItsHarry** [MylesIsCool/ViaVersion#285]
Not sure if this is a bug or just 1.9 behavior

### What version of ViaVersion are you using? Type /ver viaversion
0.6.8-SNAPSHOT (Latest dev build before you released 0.7.0)

### What version of Spigot are you using? Type /ver
git-Spigot-76236cb-62a2169 (MC: 1.8.8)

### What plugins are you using? Type /plugins
Happens without plugins

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Happens regardless of Bungee or not

### How does this error happen? login? Using an item? 
Right-click a chest while holding a stick, does not work. Do the same while holding air or a block, does work

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No

**Comment by MylesIsCool** [comment]
This is due to an interaction issue unfortunately due to the change in items, it is known internally and we're still working out a fix, but an issue always helps haha

**Comment by ItsHarry** [comment]
Alright, thanks for the quick response

**Comment by MylesIsCool** [comment]
@ItsHarry I just had another look into this, chests seem to open fine for my client? (Using 1.9) with any item. I know there is an issue relating to interaction to items but it doesn't break vanilla behaviour.

**Comment by ItsHarry** [comment]
I tried again and removed every plugin except ViaVersion to be sure, the chest doesn't open for me. The swing animation is there but nothing happens

**Comment by HugoDaBosss** [comment]
@ItsHarry could you try this with ViaVersion 0.7.0?

**Comment by MylesIsCool** [comment]
@HugoDaBosss @ItsHarry That'll be the issue haha

**Comment by ItsHarry** [comment]
Seems to work fine in 0.7.0, nice

Is version 0.7.0 stable enough for production use?

**Comment by MylesIsCool** [comment]
We've got some networks as big as yours using it. @ItsHarry

**Comment by HugoDaBosss** [comment]
To add, the 0.7.0 update fixes several issues which are present in 0.6.8-SNAPSHOT @ItsHarry

**Comment by ItsHarry** [comment]
Alright cool, I will update. Thanks guys
