### ISSUE TITLE
Respawning = glitched chunk sometimes

### ISSUE THREAD

**Issue by alexmarkey** [MylesIsCool/ViaVersion#287]
### What version of ViaVersion are you using? Type /ver viaversion

0.7.0

### What version of Spigot are you using? Type /ver

CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins

HideStream, LilyPad-Connect, ViaVersion, QuickNoColon, CustomHelp, AutoLapis, WorldReset, Updater, ProtocolLib, HolographicDisplays, CaptureTheFlag, NoCheatPlus >

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

LilyPad

### How does this error happen? login? Using an item? 

Only noticed this start happening since 0.7.0, sometimes when you die and respawn the chunk you are in after respawning is completely glitched and invisible, reloading chunks by using F3+a does nothing.  You are unable to look around or move, the only way to fix is by relogging (Assuming the server doesnt kick you for flying).

Have noticed this happen 3 times so far since updating.

**Comment by alexmarkey** [comment]
Only able to reproduce this using 1.9, 1.8 clients do not encounter this.
Reproduced using 1 plugin (ViaVersion)
Reproduced on regular spigot (Not paper)

Easiest way to reproduce is to simply start up a server and keep killing yourself in the console over and over, eventually will happen.

**Comment by Matsv** [comment]
@alexmarkey thanks, let me try

**Comment by HugoDaBosss** [comment]
Can confirm @alexmarkey

**Comment by Matsv** [comment]
Wow this is strange

**Comment by Matsv** [comment]
Doesn't happen for me when switching worlds -> nether -> overworld -> nether etc

**Comment by themazim** [comment]
unfortunately, this is not fixing the issue. Still experiencing the issue.

**Comment by Matsv** [comment]
@themazim It's working for me, did you try it with the latest build from the build server? http://ci.xephi.fr/job/ViaVersion/39/artifact/target/ViaVersion-0.7.0.jar

**Comment by themazim** [comment]
I pulled and build. Just tried your build, same behaviour.

**Comment by MrStickySlime** [comment]
Same problem here!!!

**Comment by MylesIsCool** [comment]
@themazim Could you be clear, does this happen in relation to respawning or just TP'ing?

**Comment by MrStickySlime** [comment]
@MylesIsCool Happens when respawning as far as i know but i think it has to do with unloaded chunks

**Comment by HugoDaBosss** [comment]
It happened for me as well when respawning in the chunk I died in. But the client probably unloads chunks on death/respawn.

**Comment by themazim** [comment]
setRespawnLocation in Player Respawn Event:

`event.setRespawnLocation(loc);`

The chunk is definitely loaded.

**Comment by themazim** [comment]
Chunks are loaded. tp into loaded chunks is working fine, which was fixed with commit https://github.com/MylesIsCool/ViaVersion/commit/1b99e2cf57f36996fe4723ddda5ba1d1350af00d 
Respawning into loaded chunks is still buggy, most if the time it doesn't work.

**Comment by MylesIsCool** [comment]
@themazim Can you try the latest patch?

**Comment by themazim** [comment]
Just tried the latest patch - still not working. The chunk is not visible. No sure if this is related, but right after respawning the console prints:

```
[20:16:51 INFO]: [Debug] Respawn player1 -> Chunk loaded
[20:16:51 INFO]: Unable to find entity for metadata, entity ID: 144
[20:16:51 INFO]: Unable to find entity for metadata, entity ID: 151
[20:16:51 INFO]: Unable to find entity for metadata, entity ID: 156
```

**Comment by alexmarkey** [comment]
Confirmed that it is still happening to me.

**Comment by wow4201** [comment]
Also happening latest build

**Comment by Schuchie** [comment]
@MylesIsCool 
This bug only appears when the player die's near his respawn location. But not every time.
This respawn goes wrong: http://haste.cloudwi.de/axefevoboy.css
This respawn works: http://haste.cloudwi.de/kuwiwotoco.css
