### ISSUE TITLE
Kick

### ISSUE THREAD

**Issue by ridalarry** [MylesIsCool/ViaVersion#288]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.0
### What version of Spigot are you using? Type /ver
latest 1.8
### What plugins are you using? Type /plugins
Protocollib, Essentials, Skript, AutoIn, Authme, HolographicDisplays, AAC, ChatControl
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No
### How does this error happen? login? Using an item? 
Nothing in particular as in the first time it crashed me when I was spectating a player the second time I was kicked while flying and the last time I was kicked on join.It could be by flying as in the 3 situatios I was flying or its a chunk bug. The kick message is https://gyazo.com/24a9585a549783ec977c33125f98ab79
### Is there an error in the console? Use pastebin.com. Is there a kick message?
This is my config https://gyazo.com/52d0fe40d5b2aeb54337353b1f35f411 and this is a crash on my client side http://pastebin.com/eiYgTZ7w

**Comment by HugoDaBosss** [comment]
And what is the error in the server console? @ridalarry

**Comment by ridalarry** [comment]
I didnt have any as I had the option of metadata set to false I have just enabled it and restarted I will try to see if this issue is going to have any console errors and post it

**Comment by HugoDaBosss** [comment]
If you are testing, please enable debug mode as well, with /viaversion debug @ridalarry

**Comment by ridalarry** [comment]
without using the debug nothing appears but after enabling the debug this is the log 
http://pastebin.com/pAvyciqd

**Comment by HugoDaBosss** [comment]
The debug output is only useful when the actual bug appeared during the debug. So please wait before this error to occur again, and post the relevant debug output.

**Comment by MylesIsCool** [comment]
You may need to enable debug=true in server.props

**Comment by ridalarry** [comment]
@MylesIsCool @HugoDaBosss I have enabled debug and got this log, but for some reason it says that debug is disabled http://pastebin.com/sJ8rM7Vk

the first time I got disconnected because I noticed that I was using a 1.8 client

**Comment by MylesIsCool** [comment]
Fixed in next version assuming the error 255 is because the list ended prematurely.
