### ISSUE TITLE
Chat crashes client with JSON error

### ISSUE THREAD

**Issue by mcarey10** [MylesIsCool/ViaVersion#29]
I can login to the server just fine, but when typing `/list` right when the list of users comes up, I get the 

"malformed JSON  at line 1 column 2" error. This happens with the latest version as well as the pre-compiled version on spigot.

EDIT: when titlemanager is installed on the server a client crash happens as well.

**Comment by MylesIsCool** [comment]
I'm guessing this needs the same fix as everything else JSON. I'll get it fixed ASAP, just needs same treatment on chat packets as rest, someone else might beat me.

**Comment by MylesIsCool** [comment]
Fixed in 0.3.6 (Coming Soon)

or you can compile the repo
