### ISSUE TITLE
When TP'd to unloaded chunks it will not load the chunks and glitch out your game on 1.9

### ISSUE THREAD

**Issue by MrStickySlime** [MylesIsCool/ViaVersion#292]
BTW i have the same problem as #287 

### What version of ViaVersion are you using? 
0.7.0

### What version of Spigot are you using? 
git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[18:42:24 INFO]: You are 203 version(s) behind

### What plugins are you using? Plugins (37): AsyncWorldEditInjector, WorldEdit, TimTheEnchanter, Essentials, ClearLag, ChatControl, PlugMan, LuckyBlock, WorldBorder, Multiverse-Core, WorldGuard, AsyncWorldEdit, EssentialsProtect, Multiverse-Inventories,
VoxelSniper, EssentialsChat, EssentialsAntiBuild, PermissionsEx, PTweaks, Simple-AutoSave, CommandSync, ViaVersion, Multiverse-Portals, Vault, EssentialsSpawn,
MyCommand, RedstoneClockPreventer, TitleManager, SkyWarsReloaded, ProtocolLib, LibsDisguises, NoCheatPlus, Citizens, OtherDrops, MagicSigns, ServerSigns, HolographicDisplays

### Are you using any additional software like BungeeCord? If so, what software and version? 
This server is running BungeeCord version git:BungeeCord-Bootstrap:1.9-SNAPSHOT:f53e66e:1133 by md_5
 Plugins - AlwaysOnline, AnimMOTD, BungeeAdminTools-1.3.4, BungeeAliases-1.1.2, BungeeChat-1.0.11, BungeeTabListPlus-2.0.5, CommandSyncServer, Yamler-Bungee-2.3.0-SNAPSHOT

### How does this error happen? login? Using an item? 
It happens when you get tp'd to unloaded chunks.

### Is there an error in the console? Use pastebin.com. Is there a kick message? 
no

**Comment by HugoDaBosss** [comment]
This could be the same case as #287 , thanks for reporting!

**Comment by MylesIsCool** [comment]
Should now be fixed.
