### ISSUE TITLE
Clients crashing (Metadata not converted right)

### ISSUE THREAD

**Issue by alexmarkey** [MylesIsCool/ViaVersion#293]
### What version of ViaVersion are you using? Type /ver viaversion

0.7.0

### What version of Spigot are you using? Type /ver

http://prntscr.com/altuyb

### What plugins are you using? Type /plugins

http://prntscr.com/altv0c

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

LilyPad

### How does this error happen? login? Using an item? 

Players are randomly geting disconnected, says on the client "Lost connection..." something along those lines, just a basic message.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

Enabled debug in the server properties and managed to get this error in the log, resulting in 3 clients crashing includng myself.

http://pastebin.com/xkFExdUt

**Comment by MylesIsCool** [comment]
Need retest with 0.7.1 for more info, it's metadata related ofc
