### ISSUE TITLE
1.9 clients getting stuck on top of lilypads

### ISSUE THREAD

**Issue by alexmarkey** [MylesIsCool/ViaVersion#294]
### What version of ViaVersion are you using? Type /ver viaversion

0.7.0

### What version of Spigot are you using? Type /ver

http://prntscr.com/am0a7y

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

LilyPad

### How does this error happen? login? Using an item? 

Setup a line of lilypads in the water then run across them using 1.9, your client gets stuck on one of the lilypads and it is impossible to get off, only way to fix it is by relogging or being teleported out.

**Comment by alexmarkey** [comment]
Trying to get more info, will update when I do

**Comment by alexmarkey** [comment]
Alright cracked it,

Reproduced using 2 plugins,

ViaVersion & NoCheatPlus 

ViaVer build 0.7.0
NCP build - http://prntscr.com/am0kk1

Default NCP config

**Comment by MylesIsCool** [comment]
Maybe you need to disable hit box detection in NCP as it might of changed? We can't really patch that.

**Comment by MylesIsCool** [comment]
Gonna close this issue, if you have this issue consider disabling noclip detection for no cheat (or making it exclude lilypads not sure if that's possible though)
