### ISSUE TITLE
Disconnected

### ISSUE THREAD

**Issue by Lmmb74** [MylesIsCool/ViaVersion#296]
ViaVersion Version: 0.7.3-SNAPSHOT

Spigot Version: git-Spigot-d20369f-7fc5cd8 (MC: 1.9) (Implementing API version 1.9-R0.1-
SNAPSHOT) {Checked at 2:15 PM GMT -3 03/30 [latest version]}

Plugins (99): NetherWater, Gender, PerWorldPlugins, PlugMan, WebServers, BanManager, PerWorldTab, SpiderNest, SuperLuckyBlock, ViaVersion, GetPerms, ObsidianBox, A, BowSpleef, Modifyworld, BackPacks-1.9, ResourcePackApi, VotingPlugin, PermissionsEx, mcMMO, WDLCompanion, Spawnx, PlaceholderAPI, BukkitSpeak, SkinsRestorer, BossBarAPI, NoteBlockAPI, ItemBuilder, ParticleLIB, BossShop, MoBlocks, HotPotato, dynmap, WorldEdit, RandomArmorEffects, CityWorld, ElytraDelay, PacketListenerApi, ClearLag, ReversiLab, SurvivalGames, Anti-Plugin, HothGenerator, DeluxeMenus, TinkererAndEnchanter, Friends2.0, SkyPvP, Vault, GoldenApplePlus, HyperConomy, BarAPI, MenuBuilder, MinigamesLib, Compassance, Marriage, SkyWars, ChestCommands, Jobs, Citizens, DuelMe, PlotSquared, WorldGuard, ParticleHats, UndineMailer, NickNamer, BuildingGame, Residence, Plot2Dynmap, CommandNPC, GeneralRegionAPI, Multiverse-Core, WGRegionEvents, WGCustomFlags, Multiverse-Portals, RegionalTunes, WizardlyMagic, NPCLib, Multiverse-Inventories, Duels, InfernalMobs, GriefPrevention, Scavenger, Murder, FiveNightAtFreddysInMinecraft, uSkyBlock, ProtocolLib, VentureChat, MyPet, LibsDisguises, NoCheatPlus, HeavySpleef, HolographicDisplays, DonationsHolograms, PvPManager, RedProtect, ProtectionLib, FurnitureLib, FurnitureMaker, DiceFurniture

No additional software

When I log with any version, I get disconnected (the version I use of viaversion is supposed to avoid this, i compiled it like 5 minutes ago).
The only message I get when disconnected is "Disconnected".

**Comment by MylesIsCool** [comment]
Is there any console output?

Can you turn on debug=true in server.properties and use pastebin please.

**Comment by MylesIsCool** [comment]
Closing since no reply.
