### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#297]
This isn't a bug. 
This is a request. 

Could you add a GUI to allow players, using 1.9 and above, to choose if they want to see the bossbar, if they want to see the new effet indicator, if they want to see the new bow's animation...

**Comment by MylesIsCool** [comment]
An external plugin should probably do this.

**Comment by Matsv** [comment]
Every developer can implement this using ViaVersions' API. I don't think this plugin will implement this

**Comment by TheIntelloBox** [comment]
I'm not a developer so I can't do this ! :(

**Comment by MylesIsCool** [comment]
Going to close this, this won't be implemented as it's too much overhead and not really worth the time to do. If an external plugin wants to do it that's cool but we're not gonna support it ourselves.
