### ISSUE TITLE
Disconnected with Debug Mode

### ISSUE THREAD

**Issue by alexmarkey** [MylesIsCool/ViaVersion#298]
### What version of ViaVersion are you using? Type /ver viaversion

0.7.2

### What version of Spigot are you using? Type /ver

http://prntscr.com/am9uid

### What plugins are you using? Type /plugins

http://prntscr.com/am9up9
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

LilyPad

### How does this error happen? login? Using an item? 

AFKing on my lobby, get randomly disconnected with the message "Disconnected"

### Is there an error in the console? Use pastebin.com. Is there a kick message?

Enabled debug mode in the server properties and got a long as 1.2gb error when it occured, here is the tail of it http://pastebin.com/nTbn4pH6

**Comment by MylesIsCool** [comment]
Going to close this as you want to report the issue in your already made issue, #293.

This is not useful as this is just the errors behind disconnects, (eg. The client hitting the close button, or losing connection), the error you want most likely will contain the word ViaVersion but it won't be related to broken pipes, socket closing.
