### ISSUE TITLE
NPC's not showing handheld items on 1.9

### ISSUE THREAD

**Issue by alexmarkey** [MylesIsCool/ViaVersion#299]
### What version of ViaVersion are you using? Type /ver viaversion

0.7.2

### What version of Spigot are you using? Type /ver

http://prntscr.com/amaydi

### What plugins are you using? Type /plugins

http://prntscr.com/amayez
NPC plugin is custom in our lobby, spawned via packets.

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

LilyPad

### How does this error happen? login? Using an item? 

Handheld items of our spawn NPC's are only visible to 1.8 clients (http://prntscr.com/amayvf)
On 1.9 clients all NPC's have no item in their hand - http://prntscr.com/amayq0

**Comment by Matsv** [comment]
Fixed when #301 get merged.
