### ISSUE TITLE
ERROR Item entity 159357 has no item?!

### ISSUE THREAD

**Issue by davewanders** [MylesIsCool/ViaVersion#302]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.2
### What version of Spigot are you using? Type /ver
Newest 1.8.8
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yes, bungeecord : version 1141
### How does this error happen? login? Using an item? 
IDK
### Is there an error in the console? Use pastebin.com. Is there a kick message?
Console message: ERROR Item entity 159357 has no item?!

**Comment by Matsv** [comment]
Please give us the full error log.

**Comment by Matsv** [comment]
ViaVersion is not causing this, we don't have this error message.
