### ISSUE TITLE
Fail after reload

### ISSUE THREAD

**Issue by MrJoki007** [MylesIsCool/ViaVersion#303]
git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Doesnt matter, plugin error

BungeeCord

Happens after a reload

http://pastebin.com/PdQmYaYC

Join error: Exception Connecting:NativeIoException : syscall:read(...)() failed: COnnection reset by peer

**Comment by MylesIsCool** [comment]
Reloads are not supported as said in the plugin description in red text.

**Comment by MrJoki007** [comment]
Then i will delete the plugin again

**Comment by HugoDaBosss** [comment]
A little appreciaton for all this hard work would be in its place here @MrJoki007

**Comment by MrJoki007** [comment]
It be able to implement reloads
You see it on all the other protocol hacks, that have reloads too

**Comment by HugoDaBosss** [comment]
Well then use another one, (oh wait, there isn't), bye @MrJoki007
