### ISSUE TITLE
Invalid Chunk Data with LilyPad & lots of players

### ISSUE THREAD

**Issue by Eternalrealms** [MylesIsCool/ViaVersion#310]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.2
### What version of Spigot are you using? Type /ver
1.8.8 spigot
### What plugins are you using? Type /plugins
viaversion, bukkit connect, essentials, protocallib, 
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Lilypad no plugins

### How does this error happen? login? Using an item? 
Randomly
### Is there an error in the console? Use pastebin.com. Is there a kick message?

Kick message: https://gyazo.com/50c87abc98ea55f902e662912d7cfdb9

**Comment by Eternalrealms** [comment]
Everyone gets kicked at the same time when this happens.

**Comment by MylesIsCool** [comment]
Message doesn't help need output of with debug mode on, also turning on debug=true on server.properties may also help.

**Comment by Eternalrealms** [comment]
For some reason it wont happen when i type ./viaversion debug. As soon as i turn it off the message occurs.

**Comment by Eternalrealms** [comment]
The instant I turn debug mode off it happens.

**Comment by XNoki200010** [comment]
Same here.

Picture from a player: http://image.prntscr.com/image/f13e5e24c2c94c4ab87984b099ce903d.png

Because it happens random i can't set the debug mode to true :/
By me it happend when i tried to throw the rod. Or it happens maby when the rod breaks?

**Comment by MylesIsCool** [comment]
Renamed, this happens randomly.

**Comment by steven30303** [comment]
glpop

**Comment by steven30303** [comment]
oeps sorry

**Comment by lenis0012** [comment]
What a weird bug.

**Comment by Matsv** [comment]
Does this still occur with the latest ViaVersion?

**Comment by lenis0012** [comment]
Remember when i said "what a weird bug"?
I thought he meant the lillypad block.
lol

**Comment by Matsv** [comment]
I'm going to close this issue.
If you are still having this issue, and more information why this could be caused, you can always comment it. :smile:
