### ISSUE TITLE
ProtocolLib error at startup

### ISSUE THREAD

**Issue by MisterIdeas** [MylesIsCool/ViaVersion#316]
### What version of ViaVersion are you using? Type /ver viaversion

0.7.3

### What version of Spigot are you using? Type /ver

1.8.8-R0.1-SNAPSHOT

### Error

I have an error with ProtocolLib at startup and when whe try to connect in 1.9

ProtocolLib error at startup : http://pastebin.com/uzYD3sk2
ProtocolLib kick error : http://pastebin.com/PdAvjajF

Thanks

**Comment by HugoDaBosss** [comment]
Is there any chance you reloaded your server before this?

**Comment by MisterIdeas** [comment]
No i don't use /reload at all.
I have this after each reboot and it is the only server with this error.

**Comment by HugoDaBosss** [comment]
Could you redownload the latest version of ProtocolLib (for 1.8) and the latest PaperSpigot?
And just to be sure, download ViaVersion again and see if the error still occurs.

**Comment by MylesIsCool** [comment]
Please could you actually follow the format and put all your plugins.

**Comment by MisterIdeas** [comment]
When i remove ProtocolLib it's ok but when there is ProtocolLib (same version of other servers) i have the error. 

Plugins : http://prntscr.com/aohue2
Bungee Plugins : http://prntscr.com/aohuna
