### ISSUE TITLE
Request : Auto Updater / And /viaversion update

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#317]
Hello,

This is a request.
Could you add an auto updater or a command /viaversion update, to update the plugin ?

Thanks.

**Comment by HugoDaBosss** [comment]
I think @MylesIsCool already stated that this is not going to happen, but I'm not sure.

**Comment by boomboompower** [comment]
@TheIntelloBox its not that hard to make :P

**Comment by HeroCC** [comment]
Is it that he doesn't want to do it, or deems it unsafe?

**Comment by MylesIsCool** [comment]
The reasons which I'm currently against this:

- If we deploy a bad build by accident, servers will instantly upgrade to it.
- This is a protocol modification, reloads are not good. It would require a reboot.
- Owners become less aware of changes / incompatibilities that could happen to their server.

**Comment by boomboompower** [comment]
@MylesIsCool im kinda split on this, maybe instead of an 'Auto updater' have an update checker simply messaging the admins if they join (can be turned on and off in configuration file)

**Comment by MylesIsCool** [comment]
@boomboompower Currently you do get notified of new versions, just no auto download

**Comment by boomboompower** [comment]
@MylesIsCool ah, thanks for confirmation

**Comment by Matsv** [comment]
Will close this for now, because this is something we will not make at the moment.
