### ISSUE TITLE
internal excepton when using /viaversion list

### ISSUE THREAD

**Issue by MinecraftB0ss** [MylesIsCool/ViaVersion#322]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.3
### What version of Spigot are you using? Type /ver
CraftBukkit version git-Spigot-db6de12-3f3c65f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
### What plugins are you using? Type /plugins
Plugins (64): GhillieSuit, zPermissions, BukkitHiddenSyntaxBlocker, BarbedWire, WorldReset, BanManager, DispenserStorage, GuardianManager, RideMe, ViaVersion, SpawnSystem, BlockManagerPlus, DebugInfected, BloodInfectZ, WorldEdit, ResourcePacks, Essentials, AntiDupeInv, ClearLag, CrackShot, ChatControl, Chairs, WorldBorder, BuycraftX, Thirsty, Votifier, ProtocolLib, NoCheatPlus, ZombieInfections, CrackShotPlus, AmazingKit, ArmorNerfer, EssentialsChat, TimeIsMoney, FeatherBoard, PumpkinZoom, HeliManager, RandomBox, TeeMobile, SuperVanish, Vault, Engrave, StackableItems, SuperPotions, WorldGuard, ChestCommands, PhatLoots, uPlanes, EssentialsSpawn, MyCommand, PvPManager, EZRanksPro, PlayerHeads, TitleManager, RegionFX, MiscPlugin, Fe, SimpleClans, MoneyDrop, WGCustomFlags, JLib, GAListener, ItemCommand, MythicMobs
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Bungee: BungeeCord version git:BungeeCord-Bootstrap:1.9-SNAPSHOT:b6b015f:1142 by md_5
Plugins: BungeeMtod, NuVotifier, HubMagic
### How does this error happen? login? Using an item? 
The error happens when doing /viaver list or /viaversion list
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/1YPJTtqp
http://pastebin.com/2jjCLgyy

**Comment by MylesIsCool** [comment]
Fixed in next version, don't worry.

**Comment by MinecraftB0ss** [comment]
Thanks!
