### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#325]
### What version of ViaVersion are you using? 

7.3

### What version of Spigot are you using? 

1.8.9

### What plugins are you using?

Via-Version

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

No

### How does this error happen? login? Using an item? 

When I do /viaversion list

### Is there an error in the console? Use pastebin.com. Is there a kick message?

http://hastebin.com/ilawucewin.sm

**Comment by MedicOP** [comment]
Was already fixed in 1fa7211

**Comment by Matsv** [comment]
Fixed in the next version https://github.com/MylesIsCool/ViaVersion/commit/4431ca63c2d0b6f3c662789548a43f0a3c4015d4
