### ISSUE TITLE
Multiple right click / interact with 1 click

### ISSUE THREAD

**Issue by alexmarkey** [MylesIsCool/ViaVersion#326]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.2

### What version of Spigot are you using? Type /ver

http://prntscr.com/anyskv

### What plugins are you using? Type /plugins

http://prntscr.com/anysop
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

LilyPad

### How does this error happen? login? Using an item? 

When right clicking with for example a gadget on our lobby using 1.9 it detects multiple clicks (You must right click on a block, not on air) 

Example - Right click the floor = http://prntscr.com/anysx4 (Prints 2 messages in chat since it picks up 2 clicks)
Right clicking the air only picks up 1 click = good

Using the latest 0.7.4 snapshot that Myles sent to me via skype, it detects 4 clicks when i interact with the floor - http://prntscr.com/anyt5j
Right clicking the air on 0.7.4 detects 2 clicks.

**Comment by TheTonyk** [comment]
I've the same bug, on usage of PlayerInteractEntityEvent, message is sended two times. (ViaVersion 0.7.7, PaperSpigot 1.8.8 4c7641d, ProtocolLib and my own plugins)

Thanks

**Comment by Dinfyru** [comment]
On my server the same problem.

**Comment by fabien91** [comment]
Yes, i confirm this, i've the same bug on my server.

**Comment by TheTonyk** [comment]
Not any news from dev's ?

**Comment by MylesIsCool** [comment]
There is currently no decent fix to this that does not break functionality with chests. If anyone else wants to attempt to fix, feel free.

**Comment by Matsv** [comment]
Fixed next version #390
