### ISSUE TITLE
Hologram item drops being broken by 'Hologram fix'

### ISSUE THREAD

**Issue by alexmarkey** [MylesIsCool/ViaVersion#327]
### What version of ViaVersion are you using? Type /ver viaversion

0.7.4 Snapshot

### What version of Spigot are you using? Type /ver

http://prntscr.com/ao03vi

### What plugins are you using? Type /plugins

http://prntscr.com/ao03za

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

LilyPad

### How does this error happen? login? Using an item? 

When enabling the hologram fix which fixes holograms that are too high, it breaks holgrams which involve entities (By default entity holograms dont have the too high issue, however when enabling the patch it pushes the entity down).

Example:
Desired outcome of our crate plugin - http://prntscr.com/ao04jc (This is the outcome for 1.8 clients)

Outcome on 1.9 clients - http://prntscr.com/anucsr (The entity is actually inside the chest as it is pushed down.)

**Comment by Matsv** [comment]
@alexmarkey Does it happen when you use this build? :) http://fileserver.matsv.nl/files/viaversion.jar

**Comment by alexmarkey** [comment]
Issue is sadly still there

**Comment by Matsv** [comment]
If you created the 'crate plugin', this is what you can do:

* Let the Item entity ride on the ArmorStand entity that is not small, for me this only occurs on armorstand entities with setSmall(true) (with my build, or the development build when #328 get merged)

**Comment by MylesIsCool** [comment]
The fix as described by his dev:
` if (((String)getMetaByIndex(metadataList, 2).getValue()).length() == 0)
                buf.writeShort((short)(int)(128.0D * ((((ViaVersionPlugin)ViaVersion.getInstance()).getHologramYOffset() + 1.0D) * 32.0D)));`

in EntityTracker line 160


Will be patched when I get the chance, needs to have a config option for offset too and it'll be by default disabled as it could mess up other servers :P
