### ISSUE TITLE
2 Items but One in the hand !

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#329]
### What version of ViaVersion are you using? 

7.3

### What version of Spigot are you using?

1.8.8-latest

### What plugins are you using? 

Via-Version

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

No

### How does this error happen? login? Using an item? 

When a player has an item in his hand, another player sees 2 items : one in the left hand, one in the right hand. 

### Is there an error in the console? Use pastebin.com. Is there a kick message?

Nothing

**Comment by Matsv** [comment]
I don't have this problem, does it still happen for you? If yes, can you please tell me when/how it happens?

**Comment by xion87** [comment]
same problem here
http://i.imgur.com/1S8eksI.png
http://i.imgur.com/71XyFNr.png
he is using 1.9.2 but he don't have 2 item, only one

**Comment by Matsv** [comment]
@xion87 What plugins do you use?

**Comment by Matsv** [comment]
I was able to reproduce this with Multiverse-Core. Fixed next version #363

**Comment by xion87** [comment]
i was not using multiverse core

**Comment by xion87** [comment]
CleanroomGenerator, WorldEdit, SQLibrary, 
[0;32;1mViaVersion, BungeePerms, Vault, PlayerPoints, ForceSpawn, ProtocolLib, WorldGuard, LibsDisguises, TitleManager, HideAndSeek>

**Comment by Matsv** [comment]
@xion87 Can you try if the error still occurs with this version? http://fs.matsv.nl/files/ViaVersion-0.7.7-SNAPSHOT.jar

**Comment by xion87** [comment]
i will try when i am at home :)

**Comment by Matsv** [comment]
@xion87 Thanks :+1:
