### ISSUE TITLE
Kick when you create a AnimatedFrames on 1.9 

### ISSUE THREAD

**Issue by PlugKa** [MylesIsCool/ViaVersion#330]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.3
### What version of Spigot are you using? Type /ver
CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
### What plugins are you using? Type /plugins
AnimatedFrames; PacketListenerAPI; MapManager
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No
### How does this error happen? login? Using an item? 
When you create a AnimatedFrames or look at it on 1.9. Than you will be kicked.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/cYKm3NUt

**Comment by MylesIsCool** [comment]
Duplicate issue of #315 consider looking through issues before reporting.
