### ISSUE TITLE
Item Frame - MapManager/AnimatedFrames

### ISSUE THREAD

**Issue by mat41997** [MylesIsCool/ViaVersion#331]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.4

### What version of Spigot are you using? Type /ver
spigot 1.8.8 latest

### What plugins are you using? Type /plugins
AnimatedFrames_v3.1.1, MapManager_v1.1.3, PacketListenerAPI_v3.3.3, ViaVersion-0.7.4 and other.

### How does this error happen? login? Using an item?
/af create https://media.giphy.com/media/jG186kNLKs6TS/giphy.gif 128

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://hastebin.com/oqeteguqoc.vbs

**Comment by MylesIsCool** [comment]
Uh, this will be something that MapManager is doing wrong again >.> will talk to inventive again sometime.

**Comment by mat41997** [comment]
https://www.spigotmc.org/threads/animatedframes-1-7-1-8-1-9.58635/page-30#post-1458659

**Comment by Matsv** [comment]
/af create https://media.giphy.com/media/jG186kNLKs6TS/giphy.gif (with 128 & 6 item frames gives entity not found errors, mapmanager is trying to update non-existing entities (https://gyazo.com/3fde6ead3ea6f086acff5b3773849276))

But 4 item frames and the command without 128 worked without any error for me :)

Info:
PacketListenerAPI_v3.3.5.jar

**Comment by Matsv** [comment]
Video: https://fileserver.matsv.nl/media?id=mapmanager

**Comment by mat41997** [comment]
ok, it work, thanks : >
