### ISSUE TITLE
Some plugin using ProtocolLib error at startup

### ISSUE THREAD

**Issue by MisterIdeas** [MylesIsCool/ViaVersion#332]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.4

### What version of Spigot are you using? Type /ver
1.8.8-R0.1-SNAPSHOT

### What plugins are you using? Type /plugins
http://prntscr.com/aohue2

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Latest version.
http://prntscr.com/aohuna

### How does this error happen? login? Using an item? 
When i remove ProtocolLib it's ok but when there is ProtocolLib (same version of other servers) i have the error.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
ProtocolLib error at startup : http://pastebin.com/uzYD3sk2
ProtocolLib kick error : http://pastebin.com/PdAvjajF

**Comment by MylesIsCool** [comment]
Are you sure you're running the latest version?

Can you do /viaver and print screen output.

**Comment by MisterIdeas** [comment]
Yes i am
http://prntscr.com/aou2eu

**Comment by ridalarry** [comment]
@MisterIdeas Try to remove skinsrestorer from bungeecord and skinsmoudle from spigot server and restart then check if the bug still exist, if it does try to test it on online mode. 

Also for better bugs detection change debug=false to debug=true in server.propertise. Finally post the entire server log using pastebin.com

**Comment by MisterIdeas** [comment]
http://pastebin.com/v24Tk6yp

**Comment by MylesIsCool** [comment]
Ensure all your plugins are up to date, this is not a ProtocolLib issue it will be down to a plugin that uses. I'd suggest removing plugins until you can't replicate so you can work out which it is.

**Comment by MylesIsCool** [comment]
Closing, if you have this issue open new ticket.
