### ISSUE TITLE
Broken pipe when connecting 1.9.2 -> 1.8.8

### ISSUE THREAD

**Issue by danbovey** [MylesIsCool/ViaVersion#333]
ViaVersion 0.74
```
This server is running CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
```
- Too many plugins to list

```
This server is running BungeeCord version git:BungeeCord-Bootstrap:1.9-SNAPSHOT:b6b015f:1142 by md_5
```
- BungeeTabListPlus
- ServerListPlus

Logging in from 1.9.2 onto the 1.8 server, gives an error and puts me back onto the 1.9 server.

[Pastebin](http://pastebin.com/raw/DrihK8r3) of log from 1.8 server
[Pastebin](http://pastebin.com/raw/s9L7XNQw) of log from 1.9 Bungee

**Comment by MylesIsCool** [comment]
Are you running bungee for 1.9.2?

**Comment by MylesIsCool** [comment]
Are you running bungee for 1.9.2?

**Comment by danbovey** [comment]
Latest as of today from here http://ci.md-5.net/job/BungeeCord/

**Comment by MylesIsCool** [comment]
@danbovey 

If it still doesn't work with latest Bungee, I'd suggest trying without ServerListPlus / Updating it if there is an update. To see if that is the issue.

**Comment by MylesIsCool** [comment]
No reply since 2 weeks, closing. If you're still experiencing this follow steps above and provide more info.
