### ISSUE TITLE
Support for FurnitureLib

### ISSUE THREAD

**Issue by wow4201** [MylesIsCool/ViaVersion#335]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.4
### What version of Spigot are you using? Type /ver
1.8.8
### What plugins are you using? Type /plugins
FurnitureLib, DiceFurniture, ProtocolLib
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord

Can you add in support for FurnitureLib.
It's an amazing cosmetic plugin, and helps servers comply with eula.

DiceLib (Last 1.8.8 support)
https://www.spigotmc.org/resources/dicefurniture-plugin-m%C3%B6bel-plugin.6006/download?version=58998

FurnitureLib (last 1.8.8 Support)
https://www.spigotmc.org/resources/furniturelibary-protectionlib.9368/download?version=57892

Put .jars in plugin folder with viaversion and run.
Run 1.9 Client
type /furniture give chair username

Place egg, you will see the legs of chair are above the seat.
About 70%+ are broken I believe FurnitureLib uses ArmorStands.

**Comment by Matsv** [comment]
@wow4201 Does it still happen in 0.7.4?

**Comment by wow4201** [comment]
Yes

**Comment by Matsv** [comment]
@wow4201 Could you try if it happens with hologram-patch -> false in the config?

**Comment by wow4201** [comment]
Having it false, the problem occurs, having it true, the problem occurs, but furniture is displaced y -1 as expected.

**Comment by Matsv** [comment]
@wow4201 I'm home, I'll take a look at it.

**Comment by Matsv** [comment]
The Minecraft client renders the levers as hat differently (https://fileserver.matsv.nl/media?id=headpos)
That is why the levers are above the chair.

**Comment by MylesIsCool** [comment]
Closing this issue as it's something we can't fix. Minecraft has changed rendering methods and it's not really something we can touch at a packet level.
