### ISSUE TITLE
Autorespawn at death cause chunk to be unloaded for 1.9.x clients

### ISSUE THREAD

**Issue by xion87** [MylesIsCool/ViaVersion#338]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.4
### What version of Spigot are you using? Type /ver
This server is running CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)>

### What plugins are you using? Type /plugins
AsyncWorldEditInjector, WorldEdit, HealthBar, Skript, Craftconomy3, ChatControl, SkQuery, 
BungeePerms, WorldGuard, AsyncWorldEdit, Nicky, DuckSuiteTeleports, ViaVersion, pvpstats, Vault, EnderMaxiChest, PvPManager, TitleManager, ChestShop, DuckSuiteHomes, ProtocolLib, AAC, DuckSuiteWarps, HolographicDisplays, LeaderHeads

### How does this error happen? login? Using an item? 
I am using PvPManager premium version, with a config that allow to avoid death screen and autorespawn at death, sometimes player will get unloaded chunk when they respawn and have to relog for fix it

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No errors

**Comment by gigosaurus** [comment]
This bug along with #292 appears to have been introduced by 0.7, as they did/does not happen in 0.6.8 or earlier.

**Comment by MylesIsCool** [comment]
@gigosaurus Have you tested this with the versions you said? Are you using any plugins? Do you get the same issue as above?

I'm in belief that the changes to chunks between 0.6.8 & 0.7.0 have the same functionality and would not fix this issue.

**Comment by gigosaurus** [comment]
@MylesIsCool I tested this with a server only containing the ViaVersion plugin and the following plugin:

```java
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.craftbukkit.v1_8_R3.CraftServer;
import org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.event.player.PlayerRespawnEvent;
import org.bukkit.plugin.java.JavaPlugin;

public class BreakPlugin extends JavaPlugin implements Listener {

	@Override
	public void onEnable() {
		Bukkit.getPluginManager().registerEvents(this, this);
	}

	@EventHandler
	public void onJoin(PlayerJoinEvent event) {
		event.getPlayer().teleport(new Location(event.getPlayer().getWorld(), 0, 100, 0));

		Bukkit.getScheduler().runTaskLater(this, () ->

				// The following method is normally called when a player changes world or the client clicks "respawn"
				((CraftServer) Bukkit.getServer()).getServer().getPlayerList()
						.moveToWorld(((CraftPlayer) event.getPlayer()).getHandle(), 0, false, null, false), 1);
	}

	@EventHandler
	public void onRespawn(PlayerRespawnEvent event) {

                // make them respawn exactly where they died
		event.setRespawnLocation(event.getPlayer().getLocation());
	}

}
```

Checking out from https://github.com/MylesIsCool/ViaVersion/commit/6c8ccb1b1e58f91fb50e724dbbf6d62906a52e82  does not produce this bug but 406500b0bd88756b7c8539d533a76a66ee2da9f9 does.

**Comment by MylesIsCool** [comment]
@gigosaurus This seems very weird, are you able to test more branches for me with this code? to find which exact commit broke it? 

I've been looking at the differences and can't see anything glaringly obvious which would break it :(

**Comment by gigosaurus** [comment]
@MylesIsCool Checking out from https://github.com/MylesIsCool/ViaVersion/commit/c300c47a14d089f5d93e8f0eee2b3935f612641d does not produce the bug but https://github.com/MylesIsCool/ViaVersion/commit/89427cb2dadd897ba85762da8ef059f61d900681 does.
The only difference between  https://github.com/MylesIsCool/ViaVersion/compare/89427cb2dadd897ba85762da8ef059f61d900681...c300c47a14d089f5d93e8f0eee2b3935f612641d is https://github.com/MylesIsCool/ViaVersion/commit/c300c47a14d089f5d93e8f0eee2b3935f612641d, so whatever change https://github.com/MylesIsCool/ViaVersion/commit/c300c47a14d089f5d93e8f0eee2b3935f612641d  made introduced the bug.
