### ISSUE TITLE
Bows Error

### ISSUE THREAD

**Issue by JakeNelson1999** [MylesIsCool/ViaVersion#339]
### What version of ViaVersion are you using? Type /ver viaversion
ViaVersion version 0.7.4

### What version of Spigot are you using? Type /ver
CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8)
### What plugins are you using? Type /plugins
 Plugins (31): TTA, PlayerHeads, WorldEdit, HealthBar, NoRain, ClearLag, JoinMessagePlus, Modifyworld, RandomTP, WeatherRestrictions, Votifier, Multiverse-Core, WorldGuard, AdvancedPortals, GrammarPlus, ObsidianBreaker, DeathMessages, PermissionsEx, ViaVersion, Vault, MassiveCore, Essentials, HolographicDisplays, WhatIsIt, CTSNC, EssentialsChat, EssentialsSpawn, floAuction, Factions, CombatTagPlus, FactionChat

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Nope
### How does this error happen? login? Using an item? 
Using bows
### Is there an error in the console? Use pastebin.com. Is there a kick message?
No, clients crash when they try using a bow on 1.9 :(

**Comment by JBYoshi** [comment]
What is the crash report on the client?

**Comment by ridalarry** [comment]
@JakeNelson1999 Plugins that could be the reason (I am using the other plugins with not bugs): TTA, HealthBar, NoRain, JoinMessagePlus, Modifyworld, RandomTP, WeatherRestrictions, AdvancedPortals, GrammarPlus, ObsidianBreaker, DeathMessages, WhatIsIt, CTSNC, EssentialsSpawn, floAuction, CombatTagPlus

Also for better bugs detection change debug=false to debug=true in server.propertise. After the restart do /viaversion debug then use a bow. Finally post the entire server log with the client crash report using pastebin.com .

**Comment by MylesIsCool** [comment]
Are you sure you aren't using BungeeCord? We've discovered an issue in the rewriting with bungee which can cause this. Going to close since no reply in almost 2 weeks. (Reply with details for reopen)
