### ISSUE TITLE
Unable to sign and read books

### ISSUE THREAD

**Issue by HugoDaBosss** [MylesIsCool/ViaVersion#34]
You can write text in them, but signing them is not possible.
Also when trying to read a signed book it won't open.

**Comment by MylesIsCool** [comment]
If anyone can figure this one out, it'd be cool. I'm unable to sign my autographs in books! (I kid).

**Comment by HugoDaBosss** [comment]
I can't find anything in the protocol specification about signing books. It's probably the confirm transaction packet, but I'll have to figure this out.

**Comment by Paulomart** [comment]
In 1.8 it was a plugin message

**Comment by MylesIsCool** [comment]
The code between 1.9 and 1.8 signing has definitely changed, just gotta work out what.

**Comment by MylesIsCool** [comment]
Fixed in next version.
