### ISSUE TITLE
Freeze @ Handshake

### ISSUE THREAD

**Issue by Z609** [MylesIsCool/ViaVersion#340]
### What version of ViaVersion are you using? Type /ver viaversion
GitHub latest

### What version of Spigot are you using? Type /ver
This server is running CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins
Plugins (5): ViaVersion, GameAPI(custom), RemoteToolkitPlugin, ProtocolLib, SurvivalGames(custom)

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord(plugins: BungeeRTK; latest Bungee)

### How does this error happen? login? Using an item? 
Logging in (HANDSHAKE)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No error, just a message after debug is turned on:
INCOMING: HANDSHAKE 0 -> 0 [HANDSHAKE[-1]]

**Comment by Z609** [comment]
To be clear, I try to join with any 1.9 client and it just says "Logging in" until it disconnects me for "Disconnected." The handshake is apparently never completed. Tested with 1.9 and 1.9.2. AsyncPlayerPreLoginEvent is never fired, either.

**Comment by Z609** [comment]
Overlooked something, logging in with 1.8 causes this error:  Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.
and doesn't let me log in.

**Comment by Z609** [comment]
The issue happens even with JUST ViaVersion, no other plugins.

**Comment by Z609** [comment]
It appears it had to do with my custom build of the plugin, which only changes ~2 things, odd.

**Comment by MylesIsCool** [comment]
Going to close, we recommend being careful with what you do with the plugin. Packet formats and the configuration we use it quite sensitive with slipping causing disconnects.
