### ISSUE TITLE
Signs sometimes don't render correctly with some ProtocolLib depending plugins

### ISSUE THREAD

**Issue by rj0495** [MylesIsCool/ViaVersion#352]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.4
### What version of Spigot are you using? Type /ver
1.8.8
### What plugins are you using? Type /plugins
ViaVersion, ProtocolLib, Libsdisguises
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Nope
### How does this error happen? login? Using an item? 
When logging in all signs appear to be blank when using ProtocolLib. The signs seem to work fine prior to the chunk rewrite.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
Nope

**Comment by Matsv** [comment]
I have the same problem on my server

**Comment by rj0495** [comment]
Matsv, It all started when @lenis0012 Changed the chunk sender

**Comment by lenis0012** [comment]
@rj0495 seems to be plugin related issue
can you try to narrow down which plugin causes it
this issue does not occur with ViaVersion only

**Comment by rj0495** [comment]
Packetlistenerapi is the best alternative to protocol lib and it works great with ViaVersion

**Comment by AdminZero** [comment]
I too have this error and it dont let me signs render this is a MAJOR issue can you please fix ASAP... :)

ViaVersion 0.7.9
Spigot 1.8.8

Is what im using.... and still seems to be and issue!

**Comment by rj0495** [comment]
@lenis0012 It happens with ProtocolLib and MVDWPLACEHOLDERS loaded.

**Comment by wow4201** [comment]
Can someone explain MVDWPLACEHOLDERS /sign glitch? Just don't want to encounter this bug, sounds bad.

**Comment by AdminZero** [comment]
So I need ProtocolLib... what can you do to make it work?

**Comment by Matsv** [comment]
@AdminZero Could you post your plugin list?

**Comment by AdminZero** [comment]
Yes Here is what you asked `for:`
<img>http://imgur.com/qZuJ2oZ</img>

**Comment by Matsv** [comment]
@AdminZero Alright, the same plugin I use is 'BKCommonLib' when I removed that, it worked again. Could you confirm this for me that that's also the issue for you?

**Comment by AdminZero** [comment]
YES YES YES!  You are 100% correct... I removed the BKcommonLib and the signs work 100% now!  Luckily for me only 1 other rarely used plugin used that lib so i just removed those and it working great.  

However, If you can do something to make it work that would be great! Thanks.

**Comment by Matsv** [comment]
@rj0495 are ViaVersion, ProtocolLib, Libsdisguises the only plugins you used?

**Comment by Matsv** [comment]
@AdminZero Our hero @MylesIsCool created a patch for BKCommonLib, download link here: http://myles.us/ViaVersion/BKCommonLib.jar

**Comment by Matsv** [comment]
Going to close this, please create a new issue if you are still experiencing this issue.
