### ISSUE TITLE
Player collision disabling doesn't work.

### ISSUE THREAD

**Issue by iLemon1** [MylesIsCool/ViaVersion#354]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.4
### What version of Spigot are you using? Type /ver
Paperspigot 1.8.8
### What plugins are you using? Type /plugins
n/a
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
LilyPad
### How does this error happen? login? Using an item? 
Just doesn't work, you can push players.

**Comment by Matsv** [comment]
Is autoteam enabled in the config?
```
autoteam: true
```

**Comment by iLemon1** [comment]
Yep

`# Do you want us to prevent collision?
prevent-collision: true
# If the above is true, should we automatically team players until you do?
auto-team: true`

**Comment by Matsv** [comment]
What plugins do you use?

**Comment by iLemon1** [comment]
![image](https://cloud.githubusercontent.com/assets/18317307/14508097/e2587620-01bd-11e6-9801-548f68790028.png)

**Comment by Matsv** [comment]
@iLemon1 Can you maybe try if it happens without LilyPad?

**Comment by iLemon1** [comment]
Can't remove it, sorry.

**Comment by Matsv** [comment]
Ok, I'll try to reproduce it tomorrow

**Comment by TitanicFreak** [comment]
I can also confirm this, player collision is still an issue with LilyPad.

![1zpfnnpjim72rmjjlswds9vdlif5ubff](https://cloud.githubusercontent.com/assets/6857939/14519777/06b6a57e-01ef-11e6-90c4-99119424d582.png)

**Comment by Matsv** [comment]
@MylesIsCool found out that there is a mistake in the LilyPad packets, https://github.com/LilyPad/GoLilyPad/blob/master/packet/minecraft/v19/clientTeams.go#L116

**Comment by Matsv** [comment]
Update your lilypad

**Comment by ElitStrikerzHD** [comment]
can't get player collosion to work neither :/, would like to get it disabled
