### ISSUE TITLE
Can't interact with command blocks on a 1.8 server with 1.9 client

### ISSUE THREAD

**Issue by Dann763** [MylesIsCool/ViaVersion#355]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.5
### What version of Spigot are you using? Type /ver
1.8
### What plugins are you using? Type /plugins
SkinsModule, Essentials, PermissionsEx, CrazyCore, CS-CoreLib, ViaVersion, NametagEdit, EssentialsSpawn, Prism, BanManager, BungeeTabListPlus, ProtocolLib, CrazyLogin, SlimeFun and HolographicDisplays.
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord build 1144 (Plugins: BungeeTabListPlus and SkinsRestorer)
### How does this error happen? login? Using an item? 
Right-click a command block. It's possible to place them, but interacting is not possible from a 1.9 client.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/3bMMtYNn

**Comment by Matsv** [comment]
Thanks for reporting, when I created this feature, I only checked 1.8-R3, you can fix this by updating to 1.8.8 or wait until I (or someone else) fixed this

**Comment by Matsv** [comment]
Fixed next version.
