### ISSUE TITLE
Bug with Brewing

### ISSUE THREAD

**Issue by TheAgentCookie** [MylesIsCool/ViaVersion#358]
So there is a bug with this plugin on 1.9
Players cannot use brewing stands to make potions. 
It doesnt work at all, i am getting several reports per day from the players on my server!
Please fix it as soon as possible
Best regards,
_TheAgentCookie

**Comment by Matsv** [comment]
Please provide us with more information.
First of all, use the issue template: https://github.com/MylesIsCool/ViaVersion/blob/master/ISSUE_TEMPLATE.md
Second, does it only happen with some potions or does it happen with every potion? 

I haven't seen any problems with it myself while testing.
Thanks

**Comment by ridalarry** [comment]
this issue is not happening with me

**Comment by TheAgentCookie** [comment]
Since I updated ViaVersion to 1.9 the issue seems to be resolved
