### ISSUE TITLE
Error fetching hand item

### ISSUE THREAD

**Issue by timr2000** [MylesIsCool/ViaVersion#360]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.5
### What version of Spigot are you using? Type /ver
1.8.8 spigot
### How does this error happen? login? Using an item? 
I dont know
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/wzUz71M6

**Comment by MylesIsCool** [comment]
This is your server lagging. This is not a viaversion issue. Ensure you have 20 TPS, etc.
