### ISSUE TITLE
Bug with versions

### ISSUE THREAD

**Issue by TheAgentCookie** [MylesIsCool/ViaVersion#361]
So i found a bug with /viaversion list command. It actually shows wrong version as u can see in the screenshot below. I have joined my server with optifine mod.

http://imgur.com/3TYqaWJ

(I am using viaversion 0.7.6 (latest version on spigot)

**Comment by ridalarry** [comment]
I have the same issue, its showing that all 1.8 client as 1.9.2 clients. I think its saving the client data on join if the player joined with 1.9.2 it will consider him on 1.9.2 all the time

**Comment by MylesIsCool** [comment]
If anyone has a valid guide to replicate 100% of time it would be useful :)

**Comment by MylesIsCool** [comment]
Fixed in next version.
