### ISSUE TITLE
Nobody can login after server restart

### ISSUE THREAD

**Issue by MedicOP** [MylesIsCool/ViaVersion#362]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.5

### What version of Spigot are you using? Type /ver
This server is running CraftBukkit version git-Spigot-76236cb-62a2169 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins
DisguiseCraft, ProtocolLib, EchoPet, NoCheatPlus, ViaVersion

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Bungeecord

### How does this error happen? login? Using an item? 
The console only shows one login attempt after the server has restarted. From then on, any other player that tries to connect is not shown in the console, and also nothing happens when a player tries to log in. It just keeps connecting but never actually works until the client stops the login attempt.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No errors whatsoever, here is what is shown in the console. Nothing showed up in the console until the server was restarted.

```java
[04:00:21] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[04:00:21] [Server thread/INFO]: Done (7.229s)! For help, type "help" or "?"
[04:00:21] [Server thread/INFO]: Starting GS4 status listener
[04:00:21] [Query Listener #1/INFO]: Query running on 123.123.123.123:123
[04:00:21] [Server thread/INFO]: [ViaVersion] ViaVersion detected protocol version: 47
[04:00:21] [Server thread/INFO]: [NoCheatPlus] Post-enable running...
[04:00:22] [Server thread/INFO]: [NoCheatPlus] Post-enable finished.
[04:00:22] [Craft Scheduler Thread - 1/INFO]: [NoCheatPlus] Added hook: AllViolations(NCP) [1.0].
[04:00:22] [Server thread/INFO]: User[/123.123.123.123:12345] logged in with entity id 40 at ([world]30.5, 64.0, 0.5)
[04:00:47] [Timer-2/INFO]: [WorldGuard] Region data changes made in 'world' have been background saved
[04:00:53] [Server thread/INFO]: User lost connection: Timed out
```

The usernames and IP address have been redacted. Just so you know, this problem has occured 5 times in total now on different servers. One person attempts to log in, and then after that no more logins are accepted by the server.

Perhaps it only happens when the first login attempt failed/timed out? Cause it does say that the first player who logged in lost connection due to timed out. But that could also have been caused by this glitch cutting off traffic?

**Comment by MylesIsCool** [comment]
Have you tried without the other plugins?
Have you tried turning on debug=true in server.properties?

If the above work fine, have you considered this could be your connection.

**Comment by MedicOP** [comment]
I've been running the same plugins and Spigot for a couple of months already, this particular issue only arised after I installed ViaVersion, so I'm pretty sure it's caused by it. 

It can't be a connection problem because as soon as I restart the server again, the problem is fixed and players come flooding in in a matter of seconds.

**Comment by MylesIsCool** [comment]
@MedicOP Can you try without other plugins as I said, I don't ask this so you can blame Via, because with what you given it does sound like Via related but another plugin obviously conflicts with it and I would like to know.

**Comment by ridalarry** [comment]
@MedicOP try without DisguiseCraft because I have all the other plugins in my server without any bugs also make sure that you have late-bind=false in spigot.yml

**Comment by MylesIsCool** [comment]
Closing as it seems no reply, if you're having an issue similar remove other plugins to find which one conflicts with ViaVersion and get back to us.
