### ISSUE TITLE
Disconnecting by pressing "F"

### ISSUE THREAD

**Issue by Kiryushaz** [MylesIsCool/ViaVersion#364]
ViaVersion 0.7.7 (Not snapshot!)

This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Plugins (10): PermissionsEx, SkinsRestorer, ViaVersion, Vault, ProtocolLib, NoCheatPlus, Essentials, EssentialsSpawn, EssentialsChat, AuthMe

Not using BungeeCord.

Pressing "F" (move the item from the right hand to the left) disconnects from the server.

Kiryushaz lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.
Kick with reason: Disconnected.

**Comment by Matsv** [comment]
Thanks for reporting, fixed next version #365

**Comment by Kiryushaz** [comment]
@MylesIsCool Thanks for fix ViaVersion
