### ISSUE TITLE
CancelException

### ISSUE THREAD

**Issue by XNoki200010** [MylesIsCool/ViaVersion#366]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.7
### What version of Spigot are you using? Type /ver
newst spigot
### What plugins are you using? Type /plugins
my own ReplaySystem
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
nope
### How does this error happen? login? Using an item? 
For example if I place a block with 1.9
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://hastebin.com/iqaluselin.avrasm

Is this a bug in my ReplaySystem? I listen to the Netty Channels to record packets. Or a bug in ViaVersion?

**Comment by MylesIsCool** [comment]
You're overriding netty wrong.

**Comment by XNoki200010** [comment]
Without ViaVersion are no problems.

How is the right way to override netty and stay compatible with ViaVersion?

**Comment by MylesIsCool** [comment]
Yes because you're implementing your handlers wrong.

You need to make sure that you're injecting it right and not overriding exceptionCaught and causing it to throw.

**Comment by MylesIsCool** [comment]
Going to close, if you need help. Feel free to send me your code and I'll attempt to aid to somewhat with compatibility. (I just need netty handlers etc)
