### ISSUE TITLE
The Armor Stands custom names appears 1 block too high

### ISSUE THREAD

**Issue by TheTonyk** [MylesIsCool/ViaVersion#369]
### What version of ViaVersion are you using? Type /ver viaversion

ViaVersion 0.7.7

### What version of Spigot are you using? Type /ver

PaperSpigot-4c7641d (MC: 1.8.8)

### What plugins are you using? Type /plugins

ProtocolLib, ViaVersion, My own plugin

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

BungeeCord 1.9-SNAPSHOT:4872075:1145

### How does this error happen? login? Using an item? 

Summon Armor Stand with my plugin. Code:

```
ArmorStand textEntity = (ArmorStand) world.spawnEntity(location, EntityType.ARMOR_STAND);
		
textEntity.setVisible(false);
textEntity.setSmall(true);
textEntity.setGravity(false);	
textEntity.setBasePlate(false);
textEntity.setArms(false);
textEntity.setCustomName(text);
textEntity.setCustomNameVisible(true);
```

### Is there an error in the console? Use pastebin.com. Is there a kick message?

Not any errors.

When summoning armor stand with Custom Name, there is like y=1 between top of armor stand and the custom name. (Work fine in 1.8)

Thanks for this awesome plugin !

**Comment by TheTonyk** [comment]
Update: After a few tests, when we summon small Armor Stands, Custom Name is displayed like normal Armor Stand. I think it will not be hard to fix :D

**Comment by Matsv** [comment]
This is already a feature :)
Enable hologram-patch=true in the config

**Comment by TheTonyk** [comment]
Oh, my bad, sorry !
