### ISSUE TITLE
The version of each player is not updated when player switch from 1.9 to 1.8

### ISSUE THREAD

**Issue by TheTonyk** [MylesIsCool/ViaVersion#370]
### What version of ViaVersion are you using? Type /ver viaversion

ViaVersion 0.7.7

### What version of Spigot are you using? Type /ver

PaperSpigot-4c7641d (MC: 1.8.8)

### What plugins are you using? Type /plugins

ProtocolLib, ViaVersion, My own plugin

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

BungeeCord 1.9-SNAPSHOT:4872075:1145

### How does this error happen? login? Using an item? 

Usage of /viaversion list

### Is there an error in the console? Use pastebin.com. Is there a kick message?

Not any errors.

When a player connect to the server in 1.9 and re-launch his game and then connect to the server in 1.8, the version of player was not updated and still display "1.9.x".

It's quite annoying when we want to use isPorted() from ViaVersion API.

Thanks, and sorry for my bad english !

**Comment by Matsv** [comment]
Same problem as #361, but thank you for the clear explanation how to reproduce it!

**Comment by MylesIsCool** [comment]
Fixed in next version.

**Comment by TheTonyk** [comment]
Thanks !
