### ISSUE TITLE
Undropapble items for 1.9.x players

### ISSUE THREAD

**Issue by TheAgentCookie** [MylesIsCool/ViaVersion#371]
I found another bug of this plugin,
Players from 1.9.x clients cannot drop items with "q"
I am using the latest version of the plugin (0.7.8)

**Comment by MylesIsCool** [comment]
Have you ensured you're using 0.7.8? I can do it fine locally.

**Comment by TheAgentCookie** [comment]
Yes 100%

**Comment by MylesIsCool** [comment]
Then can you actually fill out the issue template properly. (https://github.com/MylesIsCool/ViaVersion/blob/master/ISSUE_TEMPLATE.md) Nobody else has reported this issue, also version 0.7.9 was also released so make sure you updated.

**Comment by Matsv** [comment]
Closing this because you didn't respond.
