### ISSUE TITLE
ViaVersion, error, slow tping, timed out

### ISSUE THREAD

**Issue by ArmaCell** [MylesIsCool/ViaVersion#372]
###  Version: 
ViaVersion v0.7.8
git-Spigot-5f38d38-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

###  Plugins (76):
AcceptRules, PlayerFreeze, LampControl, BarAPI, GroupManager, TuxTwoLib, PlugMan, Pl3xMOTD, Trading, FarmProtect, SpectatorDisabler, SkinsRestorer, HorseTpWithMeBeta4, PlusOne, AntiJoinBot, ViaVersion, ArmorWeight, AsyncWorldEditInjector, CoreProtect, WorldEdit, HealthBar, CustomList, ProSpam, OpenInv, Essentials, ClearLag, AutoMessage, Chairs, WorldBorder, DisableTopOfNether, BlockSyntax, EnchantedFurnace, ProtocolLib, AntiWDL, AutoSaveWorld, AsyncWorldEdit, AutoPickup, EssentialsChat, Vault, WorldEditSelectionVisualizer, SimpleRename, KillerMoney, LWC, WorldGuard, ChestCommands, EssentialsProtect, EssentialsAntiBuild, EssentialsSpawn, afkTerminator, RedstoneClockPreventer, CombatLog, PlotMe, Autorank, Jobs, NoPluginStealers, RandomTP, WhatIsIt, Citizens, ChestShop, PlotMe-DefaultGenerator, PlaceholderAPI, floAuction, TitleManager, CompatNoCheatPlus, Multiverse-Core, InfoBoardReborn, NoCheatPlus, Shopkeepers, ActionAnnouncer, Multiverse-Portals, SavageDeathChest, Lift, AuthMe, Multiverse-Inventories, ServerSigns, MyPet

Im getting timed out while im am tp-ing from one world to other one, if this is way to slow (my computer is not slow) but when im tping it slows down, I kicked out myself from the console because I wasnt able to do a thing in the game.

I get this error from the log: http://pastebin.com/vhWGamgF

**Comment by MylesIsCool** [comment]
You're using an outdated version. Update. Otherwise if you still experience latency after, this may not be our fault, consider using /timing to work out the cause.

**Comment by MylesIsCool** [comment]
Going to close see above.
