### ISSUE TITLE
1.9 Clients having advantages on 1.8 server

### ISSUE THREAD

**Issue by Laos1996** [MylesIsCool/ViaVersion#375]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.9
### What version of Spigot are you using? Type /ver
git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
### What plugins are you using? Type /plugins
https://gyazo.com/564110092ba94d06b1d6d033075d750e
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord 1.9
### How does this error happen? login? Using an item? 
1.ST Issue: 1.9 Clients are able to push players in server, meaning afk players can easely be moved around
2.ND Issue: What I got reports from players is 1.9 users when in combat drawing their shield will save them from arrow damage.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
No errors noticed.

**Comment by Matsv** [comment]
First issue: Enable auto-team and prevent-collision in the config.
Second issue: Hm I'll try that out, would be strange because the shield is only client-sided.

**Comment by Laos1996** [comment]
I have both options enabled.

**Comment by Matsv** [comment]
@Laos1996 Are you using the latest Bungeecord version?

**Comment by Laos1996** [comment]
Well I see latest build was 10 hours ago, I am using build from 3 days ago.

**Comment by Matsv** [comment]
Second issue doesn't happen to me (https://fs.matsv.nl/media?id=effb07dd7b701c93f94c2351abb465eb)
Are you sure that it did happen on your server or did people think that it'd block arrows?

**Comment by MylesIsCool** [comment]
Shields are client side, they don't give any advantage, it's the same as blocking.
