### ISSUE TITLE
Internal Error with /viaversion pps

### ISSUE THREAD

**Issue by fabien91** [MylesIsCool/ViaVersion#376]
### What version of ViaVersion are you using? Type /ver viaversion
Last version 0.7.9

### What version of Spigot are you using? Type /ver
This server is running CraftBukkit version git-Spigot-fdc1440-53fac9f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins
![pl](https://cloud.githubusercontent.com/assets/5675697/14737543/e57b0d66-087c-11e6-8ff5-b5f6865bc849.png)

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yes
Bungee Plugins : BungeePerms, Just2Ban, BConfReloader, BungeeStaffChat, CommandControl and ServerListPlus

### How does this error happen? login? Using an item? 
The command "/viaversion pps" work the first time but after someone minutes, she produce an error in log (Internal error occurred)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Yes : http://pastebin.com/cFdxLLDp

**Comment by MylesIsCool** [comment]
Will be fixed in next version.

**Comment by xSzescianPL** [comment]
Next is this error :(
