### ISSUE TITLE
Viaversion + Animated Frames [Maps don't work in 1.9]

### ISSUE THREAD

**Issue by melerpe** [MylesIsCool/ViaVersion#379]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.9
### What version of Spigot are you using? Type /ver
1.8.8
### What plugins are you using? Type /plugins

![](https://i.gyazo.com/9a15179a5b5a78a73b969873b38011bf.png)

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No bungee, newest of all
### How does this error happen? login? Using an item? 
Rejoining and maps are blank for some people and for some not
### Is there an error in the console? Use pastebin.com. Is there a kick message?
No error

**Comment by melerpe** [comment]
I think its viaversion because on a test server, tested both 1.8 and 1.9 and it worked just fine

**Comment by Matsv** [comment]
Does it work in 1.8? I have no problems with it both versions

**Comment by melerpe** [comment]
also happens on 1.8

**Comment by Matsv** [comment]
ViaVersion is not changing the packets for 1.8 clients. I don't think ViaVersion is causing this, please make sure you update all your plugins to the latest 1.8 version

**Comment by melerpe** [comment]
Fixed, didnt do anything.The only thing that happen was that the vps got a restart

**Comment by Matsv** [comment]
Great to hear that :smile:
