### ISSUE TITLE
getClickedInventory is null on InventoryClickEvent

### ISSUE THREAD

**Issue by MLGProCookie** [MylesIsCool/ViaVersion#382]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.9
### What version of Spigot are you using? Type /ver
This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
### What plugins are you using? Type /plugins
WorldEdit, EmptyWorldGenerator, FactionsCore, PlaceholderAPI, PermissionsEx, ViaVersion, Vault, MassiveCore, WorldGuard, Essentials, PacketListenerApi, EssentialsSpawn, PlayerVersion, Factions, HologramAPI, TitleAPI
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Nope
### How does this error happen? login? Using an item? 
Clicking the new Slot in 1.9 in player inventory
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/raw/hx1eHChe
Aka getClickedInventory is null on InventoryClickEvent.

Great work on ViaVersion! Keep it up.

**Comment by MylesIsCool** [comment]
This slot is not real, totally client side. I'm thinking we need to possibly ensure the click event is totally cancelled.

**Comment by Matsv** [comment]
The getClickedInventory is always null when you drop items, ofcourse a better fix for the new slot would be instead of throwing the item, preventing the user to put it into that slot, (How it looks when you cancel InventoryClickEvent)

**Comment by MylesIsCool** [comment]
Going to close for now, as this is normal behaviour. We may revisit how denying of the slot works or what, but for now dropping the item is the best approach due to otherwise requiring a more complex system of using transaction packets.
