### ISSUE TITLE
random kicks

### ISSUE THREAD

**Issue by xion87** [MylesIsCool/ViaVersion#384]
### What version of ViaVersion are you using? Type /ver viaversion
0.7.9
### What version of Spigot are you using? Type /ver
1.8.9
### How does this error happen? login? Using an item? 
randomly
### Is there an error in the console? Use pastebin.com. Is there a kick message?
no error on console but player get random kicked in all servers where viaversion is installed:
kick screen 1: http://i.imgur.com/jen5VbX.png
kick screen 2: http://i.imgur.com/YJZRdJd.jpg

**Comment by MylesIsCool** [comment]
You didn't fill out the section on plugins / if you're using bungee.

How often is randomly also.

**Comment by xion87** [comment]
I am using under bunee servers,  it appen in random occasions example in hub or factions
hub

[23:15:12 INFO]: Plugins (28): CleanroomGenerator, MinecraftMarket, WorldEdit, DoubleJump, Skript, SkinsModule, ChatControl, Janus, BungeePerms, TeleportSigns, BungeePlayerCounter, WorldGuard, PlayerVisibility, Nicky, DuckSuiteTeleports, ;
32;1mSQLibrary, ViaVersion, Vault, TitleManager, DuckSuiteHomes, PlayerPoints, ProtocolLib, LibsDisguises, DuckSuiteWarps, ChestCommands, UltraCosmetics, HolographicDisplays, LeaderHeads>

Factions
[23:17:33 INFO]: Plugins (48): MinecraftMarket, AsyncWorldEditInjector, HealthBar, Skript, ClearLag, Craftconomy3, ChatControl, FlyPlugin, BungeePerms, MCItaliaRewards, GuiRedeemMCMMO, AsyncWorldEdit, Nicky, DuckSuiteTeleports, SQLibrary, mcMMO, ViaVersion, pvpstats, Vault, MassiveCore, TitleManager, WorldEdit, DuckSuiteHomes, MarriageMaster, Jobs, Auctions, PlotSquared, PlayerPoints, Multiverse-Core, ProtocolLib, WorldGuard, LibsDisguises, AAC, MythicDrops, Citizens, Factions, MobStacker, DuckSuiteWarps, ChestCommands, PvPManager, MyPet, ChestShop, NoFlyZone, FactionChat, HolographicDisplays, CrateReloaded, MyPet-NPC, LeaderHeads>

**Comment by xion87** [comment]
I noticed there are also some user that are unable to connect to my login server giving him this error (on bungee side)
http://hastebin.com/gayihilago.sm

Login server error:
http://hastebin.com/fasimesapo.avrasm

**Comment by MylesIsCool** [comment]
@xion87 For the login server issue, enable debug=true in server.properties then post error which has the message to post to github.
Thanks

**Comment by xion87** [comment]
not sure if is related, i enabled debug and i got these errors
http://hastebin.com/ibolazowew.vbs

**Comment by MylesIsCool** [comment]
@xion87 Ignore them, every disconnect has a reason, i.e network cable being unplugged causing said thing. You need to look for ones with ViaVersion in them

**Comment by xion87** [comment]
gotcha
http://hastebin.com/sejiqazeno.pas
and this
http://hastebin.com/elegequlig.avrasm

**Comment by MylesIsCool** [comment]
@xion87 Test without SkinsModule

**Comment by xion87** [comment]
skin module is installed on the hub, not in login server

**Comment by MylesIsCool** [comment]
@xion87 The errors you posted are in relation to something sending invalid skin data / tab list data.
(Skins are sent through the same system as the tab list.)

**Comment by xion87** [comment]
i tried to remove it from the hub and restart both the server, let see if happen it again

**Comment by xion87** [comment]
same http://hastebin.com/ijoxurulok.avrasm

**Comment by xion87** [comment]
Maybe is related to mojang change and player reported me to don't have skin and viaversion kick them... i tried to log in my server with that nick, and i have the same error

**Comment by Th3Tr0LLeR** [comment]
@xion87 Try to remove SkinsRestorer for your bungeecord network.

**Comment by xion87** [comment]
i removed skinrestorer, and now i can login with the player that got issue

**Comment by Th3Tr0LLeR** [comment]
@MylesIsCool  It could be my mistake, but i believe i am sending the data in right way. If not please tell/help me with fixing that.

@xion87 Thanks for reporting that.

**Comment by xion87** [comment]
i reputed skinrestorer and when i log that player it give this
http://i.imgur.com/WTXYDXg.png
@Th3Tr0LLeR  i will be happy to help you both ^^

**Comment by xion87** [comment]
any news about this issue?

**Comment by MylesIsCool** [comment]
This is a plugin compatibility issue it looks like or there is some way to replicate, without you being able to remove plugins and see when it crashes or what or if it doesn't crash without bungee, it won't get solved. (unless someone else has the issue.)

**Comment by xion87** [comment]
I removed viaversion, still having the issue, i will try to check other bungee plugin/skin restorer and update bungeecord... you can close the ticket since is not a viaversion bug... sorry >.<
