### ISSUE TITLE
Disconnected from server

### ISSUE THREAD

**Issue by Kiryushaz** [MylesIsCool/ViaVersion#388]
### What version of ViaVersion are you using? Type /ver viaversion
0.8.0-SNAPSHOT Build 111

### What version of Spigot are you using? Type /ver
This server is running CraftBukkit version git-Spigot-e6f93f4-ed60c01 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins
Plugins (10): PermissionsEx, SkinsRestorer, ViaVersion, Vault, ProtocolLib, NoCheatPlus, Essentials, ChatGuard, EssentialsSpawn, EssentialsChat

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I not using BungeeCord.

### How does this error happen? login? Using an item? 
I can't connect to the server version 1.9.x (Not 1.9.2, Not 1.9.3)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Not errors in console.

**Comment by Matsv** [comment]
You can use a 1.8 server and allow 1.9 and 1.9.1/1.9.2 to connect.
You can use a 1.9 server and allow 1.9.1/1.9.2 to connect. (Spigot recently patched to do this, so not much point!)

At the moment this plugin doesn't work with spigot 1.9.2

**Comment by Kiryushaz** [comment]
Not work.
This server is running CraftBukkit version git-Spigot-d20369f-7fc5cd8 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

**Comment by Matsv** [comment]
What does not work?

**Comment by MylesIsCool** [comment]
The compatibility patch spigot did in 1.9.1 broke it.
It's not really worth using it for 1.9.1 + 1.9.2 support, just use latest spigot.
