### ISSUE TITLE
1.9.4 support

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#392]
### What version of ViaVersion are you using? 

8.0.0

### What version of Spigot are you using? 

1.8.8

### What plugins are you using?

Via Version

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

No

Hi,

Can you add 1.9.4 support ?

**Comment by MylesIsCool** [comment]
Please consider testing before making issues as it wastes our time.

1.9.4 is compatible.

**Comment by Carbonax** [comment]
I'm having issue with it too, so it's clearly a bug.

**Comment by Matsv** [comment]
@Carbonax It isn't, use the latest official Spigot release.https://www.spigotmc.org/resources/viaversion.19254/

**Comment by TheIntelloBox** [comment]
Could you add Minecraft Snapshot 1.10 compatibility ?

**Comment by EvilOlaf** [comment]
Are you on drugs? ^^

**Comment by Matsv** [comment]
@TheIntelloBox #408 :wink:
