### ISSUE TITLE
BKCommonLib causes packet issues

### ISSUE THREAD

**Issue by Legobuilder0813** [MylesIsCool/ViaVersion#394]
### What version of ViaVersion are you using? Type /ver viaversion
0.8.1
### What version of Spigot are you using? Type /ver
CraftBukkit version git-Spigot-db6de12-4ac2347 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
### What plugins are you using? Type /plugins
CoreProtect, WorldEdit, WorldBorder, ViaVersion, ProtocolLib, Pixelator, WorldGuard, LibsDisguises, BKCommonLib, Train_Carts
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord version git:BungeeCord-Bootstrap:1.9-SNAPSHOT:a12ac37:1152, no plugins
### How does this error happen? login? Using an item? 
Error happens on login. Bungee sends player to the server, player almost sees world, then they're sent to the fallback.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/uQp6ysTS - Bungee connects

**Comment by MylesIsCool** [comment]
Have you tried without traincarts?

**Comment by Matsv** [comment]
Could you post your startup log?

**Comment by EliLevy-Dev** [comment]
@MylesIsCool Traincarts is something that's essential to our server, however we did disable it for some testing and had the same error.

**Comment by Matsv** [comment]
@EliLevy-Dev Not sure if you are on the same server as @Legobuilder0813, but could you post your startup log, give us more information? Also make sure you use the latest 1.8 versions from all your plugins. And please try to debug, try to remove some plugins, see what is causing it.

**Comment by MylesIsCool** [comment]
If you experience this issue:

Use https://github.com/MylesIsCool/BKCommonLib and scroll down for download.

BKCommonLib has some issues with ProtocolLib and us, this fixes it.
