### ISSUE TITLE
Connecting from 1.9.2 to 1.9.4 server won't work

### ISSUE THREAD

**Issue by dadus33** [MylesIsCool/ViaVersion#398]
### What version of ViaVersion are you using? Type /ver viaversion
0.8.1

### What version of Spigot are you using? Type /ver
git-Paper-748 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins
http://prntscr.com/b59ex6

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Latest BungeeCord version.

### How does this error happen? login? Using an item?
I have the following setup:
Bungeecord->Hub (running on 1.8 with ViaVersion to allow both 1.8 and 1.9 clients to connect. I can connect to this server with 1.9.4)->Survival (running on 1.9.4 with ViaVersion and the plugins listed above.)
The thing is, I can connect to the hub flawlessly, but I can't connect to the survival server.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No kinds of error or whatsoever. Bungeecord just sends the usual message: "Kicked whilst connecting to Survival: Outdated Client! Please use 1.9.4." as if the server wouldn't be using ViaVersion. I am really confused about this, so I am really looking forward for help! Thanks!

**Comment by Matsv** [comment]
Hey, there is currently a beta version that supports backwards compatibility for 1.9.4. If you want to help testing it, here is the link: http://myles.us/ViaVersion/temp/ViaVersion-0.8.2-SNAPSHOT.jar

Please let us know if you found any bugs :)
