### ISSUE TITLE
error - ConcurrentModificationException

### ISSUE THREAD

**Issue by mat41997** [MylesIsCool/ViaVersion#401]
logs
http://hastebin.com/xokuzumixu.css

timings
https://timings.aikar.co/v2/?id=5c746cb353d040c782d72b1bca94520a

**Comment by MylesIsCool** [comment]
This is not related to this plugin, contact the author of:
at niko.api.v1_9_R2.PingInjector.injectOpenConnections(PingInjector.java:44)

And consider learning to read stack traces, thanks.
