### ISSUE TITLE
An error occurred with entity meta data for ...

### ISSUE THREAD

**Issue by cloakfox** [MylesIsCool/ViaVersion#403]
### What version of ViaVersion are you using? Type /ver viaversion
0.8.2
### What version of Spigot are you using? Type /ver
Latest 1.8.8 paperspigot
### What plugins are you using? Type /plugins
Not relevant I think
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Also not usefull
### How does this error happen? login? Using an item? 
Not sure, it get's spammed a few times in console, might have something to do with particles
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/Wp4XCARJ

**Comment by Matsv** [comment]
First of all, plugins are always relevant.
Second of all, one of your plugins is sending invalid metadata.
You can disable this message in your config.
