### ISSUE TITLE
Chunks messed up

### ISSUE THREAD

**Issue by EvilOlaf** [MylesIsCool/ViaVersion#404]
### What version of ViaVersion are you using? Type /ver viaversion
0.8.2
Configuration default/untouched.

### What version of Spigot are you using? Type /ver
1.8.8-R0.1
As this branch will not receive any further updates I think "latest available build" is a legit indication ;).

### What plugins are you using? Type /plugins
If needed for debugging let me know.
Using Spigots built-in Orebfuscator if this is important.

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No

### How does this error happen? login? Using an item? 
When teleporting to a random location the chunks near to the player are fine, but when walking around it gets kind a weird....

![2016-05-20_11 55 29](https://cloud.githubusercontent.com/assets/3305006/15424307/33c338b6-1e82-11e6-9ac3-13f34d9a979e.png)
![2016-05-20_11 56 14](https://cloud.githubusercontent.com/assets/3305006/15424308/33c4c6ea-1e82-11e6-827c-ff109e3acfe9.png)
![2016-05-20_11 58 13](https://cloud.githubusercontent.com/assets/3305006/15424309/33c4e026-1e82-11e6-8959-4eba748b1bce.png)
![2016-05-20_11 58 16](https://cloud.githubusercontent.com/assets/3305006/15424310/33c9e878-1e82-11e6-90c6-0b800420ab0d.png)

It seems like this does happen to 1.9.2 clients only.
1.9 and 1.9.4 were not affected.
All tested independently twice, by myself and another player. Other versions were not tested.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No

Thanks for reading.

**Comment by MylesIsCool** [comment]
Does this only happen only with the orefuscator turned on?

**Comment by EvilOlaf** [comment]
Did not test yet. Will do tomorrow.

**Comment by EvilOlaf** [comment]
Sorry for the delay, overslept two testing windows ^^.

Anyway, for unknown reason the issue seems to be disappeard. For me at least. I'll ask some fellows to verify this.

**Comment by Matsv** [comment]
Great to hear that. I thought I broke the chunks

**Comment by EvilOlaf** [comment]
@Matsv Just received some screenshots from an user which in principle look like the ones above.
Did not test without Spigot orebfuscator yet.

**Comment by Matsv** [comment]
@EvilOlaf Alright, let me know if you tried it without the orefuscator

**Comment by EvilOlaf** [comment]
Damnit. I always forget to test this in the early morning. I'll set up an alert or something to remind me -.-

**Comment by EvilOlaf** [comment]
Was not able to reproduce. However this may not mean it fixed itself as it did not occur each and every time earlier.
Anyway one of my users got an idea that this is client-side and could be fixed by using `VBOs` in the graphic settings.

**Comment by Matsv** [comment]
Oh, yeah it would be weird if viaversion caused the chunk issue only on 1.9.2 since there are no chunk changes (protocol wise) for chunks

**Comment by MylesIsCool** [comment]
Any update on the problems with this issue?

**Comment by EvilOlaf** [comment]
Not for me at least. Guess most using 1.9.4 or 1.10 now which seem not to be affected.

**Comment by MylesIsCool** [comment]
Going to close for now, if you come up with a way to cause this issue. (or maybe it's just Minecraft) Please reopen :)
