### ISSUE TITLE
Random Disconnect not fix with last version of BungeeCord and Viaversion

### ISSUE THREAD

**Issue by fabien91** [MylesIsCool/ViaVersion#405]
### What version of ViaVersion are you using? Type /ver viaversion

0.8.2

### What version of Spigot are you using? Type /ver

This server is running CraftBukkit version git-Spigot-5f38d38-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins

![pl](https://cloud.githubusercontent.com/assets/5675697/14737543/e57b0d66-087c-11e6-8ff5-b5f6865bc849.png)

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Bungeecord last version

Bungee Plugins : BungeePerms, Just2Ban, BConfReloader, BungeeStaffChat, CommandControl and ServerListPlus

### How does this error happen? login? Using an item? 

![error](https://cloud.githubusercontent.com/assets/5675697/15447657/fbe36934-1f49-11e6-82e2-9345a5bfafed.jpg)

**Comment by Matsv** [comment]
Can you set debug=true in server.properties and post the error?

**Comment by MylesIsCool** [comment]
I'd suggest trying what @Matsv said but also try without ServerListPlus and see if still happens and if that doesn't change attempt to remove a few of your plugins so we can identify the incompatibility.

**Comment by xion87** [comment]
i got a similiar issue but skinsrestorer, but is not viaversion fault...

**Comment by xion87** [comment]
btw the only plugin that i use it in common is bungeeperms

**Comment by fabien91** [comment]
@Matsv I've try but i don't see change in log

@MylesIsCool Why remove ServerListPlus because this error is produce on only one server among the 8 server available ? I think the problem come just one of our plugin, i go look this.

@xion87 Not possible because on my network only one server is affect by this problem.

**Comment by Matsv** [comment]
@fabien91 Also no errors in your bungee log?

**Comment by MylesIsCool** [comment]
No response for nearly 2 weeks, going to close, if you are having this issue please open an new issue with all your logs, plugins, bungee plugins and versions of via, spigot and bungee. (Also using debug=true in server.properties can also help)
