### ISSUE TITLE
Can't connect with 1.9.4 to a 1.8.8-ViaVer server

### ISSUE THREAD

**Issue by Carbonax** [MylesIsCool/ViaVersion#406]
### What version of ViaVersion are you using? Type /ver viaversion
0.8.1

### What version of Spigot are you using? Type /ver
git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins
CoreProtect, WorldEdit, OpenInv, BetterBeds, PlugMan, ChatControl, Lockette, WorldGuard, Multiverse-Core, ChopTree3, SignEdit, WGRegionEvents, GlobalMarket, PermissionsEx, RandomTeleport, LagMonitor, ViaVersion, WGCustomFlags, Vault, MyCommand, Admin-Chat-Channel, ChestShop, Essentials, ProtocolLib, NoCheatPlus, Citizens, WGRegionCommands, CommandNPC, ServerListPlus, EssentialsSpawn, TitleManager, HolographicDisplays, ShopGUIPlus, SuperTrails, WirelessRedstone

### Are you using any additional software like BungeeCord? If so, what software and version? 
N/A

### How does this error happen? login? Using an item? 
It says "This server is outdated, please use 1.8.8" when I connect with a 1.9.4 client. This also occurs on a 1.9.2 client.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
N/A

**Comment by Matsv** [comment]
Could you post your startup log?

**Comment by Carbonax** [comment]
Issue located; late-bind is the culprit. Is this a bug?

**Comment by Matsv** [comment]
late-bind can't work in combination with ProtocolLib at the moment.
