### ISSUE TITLE
Auto Download

### ISSUE THREAD

**Issue by TonyOneZero** [MylesIsCool/ViaVersion#407]
Please add a auto Download on update

**Comment by Matsv** [comment]
Please checkout #317 why it's chosen to not do this.
However, there is now a direct download link available, to allow people to make auto-update scripts.

> 
> These should work fine on the most recent versions of wget:
> If you want it downloaded as ViaVersion.jar:
> 
> `wget -O ViaVersion.jar http://myles.us/ViaVersion/latest.jar`
> 
> If you want it downloaded as ViaVersion-X.Y.Z.jar:
> 
> `wget http://myles.us/ViaVersion/latest.jar --content-disposition`
> 
> You could use these in a start-up script if you wanted.
>
