### ISSUE TITLE
JoinERROR

### ISSUE THREAD

**Issue by GoNotCougsWA** [MylesIsCool/ViaVersion#409]
0.8.2

This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[07:36:11 INFO]: Checking version, please wait...
[07:36:12 INFO]: You are 270 version(s) behind

Plugins I am using is 
Noteblock API
Vault 
ViaVersion - 0.8.2

I am not using bungeecord I am using the server for test my own plugins I make.

This error happens when I join my server

http://pastebin.com/PSRW2ZYZ 
the kick message is "Internal exception: java.io.IOException: An existing connection was forcibly closed by the remote host"

**Comment by MylesIsCool** [comment]
This doesn't seem like a full plugin list? You're doing something wrong in your plugin with entity metadata.

**Comment by GoNotCougsWA** [comment]
So... Look's like 
There is a DiamondMiner-Core plugin I am working on and if I 
getServer().getScheduler().scheduleSyncRepeatingTask(this, new removeParticle(), interval, interval);

to remove /effects Particle's 

Viaversion Stop's working 


Class removeParticle:


package <Not Saying :D>

import org.bukkit.Bukkit;
import org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity;
import org.bukkit.entity.Player;

public class removeParticle implements Runnable {

	public void run() {
        for (Player player : Bukkit.getServer().getOnlinePlayers()) {
            ((CraftLivingEntity) player).getHandle().getDataWatcher().watch(8, Integer.valueOf(0));
        }
	}
}

**Comment by MylesIsCool** [comment]
I'm not technical support for other plugins but I'd suggest looking at what your doing in relation to wiki.vg values.

**Comment by GoNotCougsWA** [comment]
Ok
