### ISSUE TITLE
Boss Bars don't work

### ISSUE THREAD

**Issue by MylesIsCool** [MylesIsCool/ViaVersion#41]
I mean they're kind of a hack in the first place, but they don't work for like BossBarAPI or what.

Probably need fixing.

**Comment by Z609** [comment]
When do you think they will be fixed?

**Comment by HugoDaBosss** [comment]
We have an API for this now @Z609 
https://github.com/MylesIsCool/ViaVersion/blob/master/src/main/java/us/myles/ViaVersion/api/boss/BossBar.java

**Comment by L4BORG** [comment]
So we can use VIaVersion BossBar API with plugins and it would work with 1.8 and 1.9 clients?

**Comment by Matsv** [comment]
@L4BORG The BossBar api will only work for 1.9.

**Comment by HugoDaBosss** [comment]
Probably being fixed by #186

**Comment by PaulBGD** [comment]
I'm having an issue with them in 1.8< again, did something change?

**Comment by Matsv** [comment]
Nope! We didn’t change anything, we are also not touching the 1.8 and lower clients. (:
