### ISSUE TITLE
Players timed out and became invisible

### ISSUE THREAD

**Issue by MineTheCube** [MylesIsCool/ViaVersion#410]
### What version of ViaVersion are you using? Type /ver viaversion
0.8.2

### What version of Spigot are you using? Type /ver
```
This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
```

### What plugins are you using? Type /plugins
It happens on the 3 servers under my Bungee with different plugins, but all have ViaVersion. They have also these plugins in common: http://pastebin.com/raw/mPjZLgWv

And another custom plugin to manage scoreboard prefix.
Also, I disabled auto-team as every players are in team, even if they don't have a prefix.

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Bungeecord #1156 with ServerListPlus 3.4.5

### How does this error happen? login? Using an item? 
Sometimes, for no obvious reason, a random player is losing connection to the server. During 30 seconds, he is still on the server, but not able to send or receive anything from it.
Then he is kicked (I think it's client side) due to "Timed out".
And when he comes back, he is totally invisible for certains players, he does not appear in TAB even for him, and sometimes has default skin.

It happened to me, I'm MTC and as you can see **[here](http://i.imgur.com/rnGQYNj.jpg)** I'm not in TAB, and I've alex skin.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
```
[21:16:54] [Server thread/INFO]: MTC lost connection: Timed out
[21:16:54] [Server thread/INFO]: [LOGOUT] MTC logged out at world (79.21, 98, 190.56)
```
```
[21:17:06] [Thread-833/INFO]: UUID of player MTC is e9464e86-daf1-4414-900b-2b08e8710459
[21:17:06] [Server thread/INFO]: MTC[/84.102.201.179:33950] logged in with entity id 8698777 at ([world]79.20569840930992, 98.0, 190.55983679524365)
```

**Also the bug began to appear since few days, it may be related to 0.8.2 update.**

**Comment by MylesIsCool** [comment]
Have you checked that this is not just a connection issue with your server and without viaversion? (Ensuring you test close to the same time in case it is and it comes back and goes away)

**Comment by MineTheCube** [comment]
I think not, as each time it's only one player which is affected by the bug, every others don't notice any lag or something at all.
Also I forgot to mention that it seems to be often the same players, but nothing related to internet issues as they all have a good ping (< 80ms).

**Comment by MylesIsCool** [comment]
Could you do further testing?

**Comment by MineTheCube** [comment]
Well, I don't really know what to test..

Also, if I do hidePlayer() then showPlayer(), he re-appear to others who weren't able to see him.

**Comment by MylesIsCool** [comment]
You should test with and without the plugin in specifics to this user. 

Also what's different about your setup to everyone else using the plugin if it is ViaVersion?

**Comment by MineTheCube** [comment]
I thought it came from ViaVersion as the bug started to appear just after update to 0.8.2.
But it's not, as after a lot of tries I got the bug, without ViaVersion, and I know how to reproduce it.

So, sorry for inconvenience... and keep up the good work (as you always did) 👍
