### ISSUE TITLE
Netty crash

### ISSUE THREAD

**Issue by Dimatert9** [MylesIsCool/ViaVersion#411]
### What version of ViaVersion are you using? Type /ver viaversion
[20:40:07 INFO]: ViaVersion version 0.8.3
[20:40:07 INFO]: Author: _MylesC

### What version of Spigot are you using? Type /ver
[20:40:17 INFO]: This server is running CraftBukkit version git-Spigot-8a048fe-a022dd2 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)
[20:40:17 INFO]: Checking version, please wait...
[20:40:18 INFO]: You are running the latest version
### What plugins are you using? Type /plugins
https://i.gyazo.com/92ac29f02570209812836d4dd9974a40.png
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Waterfall, https://i.gyazo.com/e400fbd01df6da3bfe6ee4150cb7edeb.png
### How does this error happen? login? Using an item? 
Login
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/Un0K6mdw , http://pastebin.com/XxEz810m

Only this plugin use netty.

**Comment by Matsv** [comment]
Could you enabled debug=true in server.properties and post the console log?

**Comment by MylesIsCool** [comment]
Also try without SkinRestorer. ^^

**Comment by Dimatert9** [comment]
http://pastebin.com/1bh5e7Px

**Comment by Matsv** [comment]
Does it happen without ViaVersion?

**Comment by Dimatert9** [comment]
I dont can test it. I have 2 servers with 200+ online. 60% players dont use 1.9.3/4.
And i had this error in version 1.9.2.

**Comment by MylesIsCool** [comment]
I don't think this is ViaVersion related. Unless you can test otherwise we can't help you.

**Comment by Dimatert9** [comment]
SkinsRestorer error
