### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by Kyzderp** [MylesIsCool/ViaVersion#412]
We installed ViaVersion yesterday and noticed today that memory usage kept climbing. This seemed to occur only on the dedicated login server; there was no noticeable difference in the other servers despite having the exact same config, perhaps the issue is caused by higher traffic? We did also have slightly higher-than-usual CPU, disk, and network usage, but this was to be expected because 1.9 clients were no longer being turned away. The memory usage however was disproportionally high.

![](http://puu.sh/p6w0n/f2915c3c44.png)

After disabling many of the options (we don't need them on the login server anyway), memory seems to be much more stable.

![](http://puu.sh/p6wDa/87bc1129f3.png)

The max-pps is also disabled now, didn't catch it in the screenshot.

### What version of ViaVersion are you using? Type /ver viaversion
ViaVersion version 0.8.3

### What version of Spigot are you using? Type /ver
CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins
PermissionsEx, ViaVersion, HolographicDisplays, xAuth, HideStream, DeltaRedis (custom), LoginPlugin (custom)

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord version git:BungeeCord-Bootstrap:1.9-SNAPSHOT:ec48077:1156

Plugins: BungeeTabListPlus; all others are custom

### How does this error happen? login? Using an item? 
N/A

### Is there an error in the console? Use pastebin.com. Is there a kick message?
N/A

**Comment by MylesIsCool** [comment]
If you could get a Java profiler and find the usage of all the memory that would be cool. I've had no other reports of this which is weird.

Otherwise I can't really replicate it, :(

**Comment by MylesIsCool** [comment]
Need full logs etc, got nobody else experiencing this. Maybe a memory dump would be nice.
