### ISSUE TITLE
MalformedJsonException

### ISSUE THREAD

**Issue by TheChampTF** [MylesIsCool/ViaVersion#413]
On 0.8.2

28.05 15:20:30 [Server] INFO Invalid JSON String: "{}{}{}{}{}{}{}{}{}" Please report this issue to the ViaVersion Github: us.myles.viaversion.libs.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 4 path $

**Comment by Matsv** [comment]
Please fill in the issue template. It's there for are reason.
https://github.com/MylesIsCool/ViaVersion/blob/master/ISSUE_TEMPLATE.md
