### ISSUE TITLE
Java 1.7 compat

### ISSUE THREAD

**Issue by Kakifrucht** [MylesIsCool/ViaVersion#414]
### What version of ViaVersion are you using? Type /ver viaversion
This was on 0.8.4
### What version of Spigot are you using? Type /ver
1.9.4-R0.1-SNAPSHOT
### How does this error happen? login? Using an item? 
Unknown, it is spammed around 6 times per second. I'm still on Java 1.7 :(
### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/8GbFCJ8g

**Comment by Matsv** [comment]
Please re-download the latest version. That should fix it :smile:

**Comment by Kakifrucht** [comment]
Fixed, thanks.
