### ISSUE TITLE
Zombie/Skeleton horse (babies?) invisible on 1.9.4 when spawned on 1.8 server

### ISSUE THREAD

**Issue by semmeess** [MylesIsCool/ViaVersion#417]
### What version of ViaVersion are you using? Type /ver viaversion
0.8.4
### What version of Spigot are you using? Type /ver
git-spigot-e4d4710-e1ebe52
### What plugins are you using? Type /plugins
http://i.imgur.com/BLguDe9.png
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
git:BungeeCord-Bootstrap:1.9-SNAPSHOT:a12ac37:1152 by md_5
### How does this error happen? login? Using an item? 
https://github.com/DSH105/EchoPet/blob/06947a8b08ce40be9a518c2982af494b3b99d140/modules/EchoPet/src/main/java/com/dsh105/echopet/api/pet/type/HorsePet.java

When the method on line 44 sets  the variant of a horse to skeleton, or zombie (and baby), the horse is invisible, and http://i.imgur.com/6N39BdT.png <-- that error spams in the client output.

However the error is not present when using the essentials /spawnmob command with /spawnmob horse:skeleton;baby

**Comment by Matsv** [comment]
Does this only happen for 1.9 users or also for 1.8?

**Comment by semmeess** [comment]
Only for 1.9 users

**Comment by Matsv** [comment]
I can confirm this is happening, I'll try to debug it a little bit.

**Comment by Matsv** [comment]
I only have this problem with horses, can you tell me how to reproduce the other mobs?

**Comment by Matsv** [comment]
Fixed next version :) #419
