### ISSUE TITLE
Potions are converted incorrectly from 1.8 to 1.9

### ISSUE THREAD

**Issue by joserobjr** [MylesIsCool/ViaVersion#420]
### What version of ViaVersion are you using? Type /ver viaversion
0.8.4

### What version of Spigot are you using? Type /ver
git-Spigot-5f38d38-12698ea (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### How does this error happen?
1.8 uses a byte flag based system to manage potion effects, it's not based on a fixed key or id, so the same potion effect can be obtained from many different data values.

For example you can get the same fire resistance potion on 1.8 with:
```
/give @p 1 3
/give @p 1 8227
/give @p 1 12323
/give @p 1 10275
/give @p 1 11299
```
And there are many more possibilities to get the exact same effect with different data values as long we don't change some specifics bits.

That's why it's incorrect to assume that only 8227 must be converted to `fire_resistance`.

This incorrect conversion affected my server because I use the Bukkit's potion API to create potions and it does not generate the same potion ids as the creative tabs.

This is an example of valid item stack on 1.8 that is converted incorrectly to 1.9, it's shown as a normal water bottle on 1.9.
```java
import org.bukkit.potion.*;
ItemStack brokenOn1_9 = new Potion(PotionType.SPEED).toItemStack(1);
```

I've already fixed it in a branch and I'm going to send a pull request soon :wink:

**Comment by MylesIsCool** [comment]
We only port certain ids as they are the vanilla way of obtaining them. I mean if you have a better way to convert them that isn't ugly and gives same results, that's also cool. :)
