### ISSUE TITLE
Chests has enderchest sounds on 1.10

### ISSUE THREAD

**Issue by joserobjr** [MylesIsCool/ViaVersion#423]
### What version of ViaVersion are you using? Type /ver viaversion
1.9.1

### What version of Spigot are you using? Type /ver
CraftBukkit version git-Spigot-5f38d38-12698ea (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### How does this error happen? login? Using an item? 
Open/close a normal chest and enderchest sound is played on 1.10.
Minecraft 1.10 changed the enderchest sound, it doesn't match 1.8 chest's anymore.

**Comment by Matsv** [comment]
Thanks for reporting

**Comment by Matsv** [comment]
Hm strange, only happens on 1.8 servers, will look into it soon if someone else didn't do it yet.
