### ISSUE TITLE
Spam in the console

### ISSUE THREAD

**Issue by Kiryushaz** [MylesIsCool/ViaVersion#428]
### What version of ViaVersion are you using? Type /ver viaversion
0.9.2

### What version of Spigot are you using? Type /ver
This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins
Plugins (10): PermissionsEx, ViaVersion, IPWhitelist, SkinsModule, Vault, ProtocolLib, NoCheatPlus, Essentials, EssentialsSpawn, EssentialsChat

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
This server is running BungeeCord version git:BungeeCord-Bootstrap:1.10-SNAPSHOT:e4cf010:1158 by md_5

### How does this error happen? login? Using an item?
Spam in the console.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
[10:38:13 WARN]: Ignoring unknown attribute 'generic.armor'
[10:38:13 WARN]: Ignoring unknown attribute 'generic.armorToughness'
[10:38:13 WARN]: Ignoring unknown attribute 'generic.armor'
[10:38:13 WARN]: Ignoring unknown attribute 'generic.armorToughness'
[10:38:19 WARN]: Ignoring unknown attribute 'generic.armor'
[10:38:19 WARN]: Ignoring unknown attribute 'generic.armorToughness'
[10:38:19 WARN]: Ignoring unknown attribute 'generic.armor'
[10:38:19 WARN]: Ignoring unknown attribute 'generic.armorToughness'
[10:38:19 WARN]: Ignoring unknown attribute 'generic.armor'
[10:38:19 WARN]: Ignoring unknown attribute 'generic.armorToughness' and etc.

**Comment by TiTo-418** [comment]
You updated your server to 1.9 and then switched back to 1.8, right?

**Comment by Kiryushaz** [comment]
I wanted to make a test server at 1.8-1.10

**Comment by Matsv** [comment]
Not a viaversion issue. This will happen if you downgrade your server from 1.9 like @TiTo-418 said.

**Comment by BadassDevelop** [comment]
How could I fix this?

**Comment by BadassDevelop** [comment]
I don't have a backup for it.

**Comment by Matsv** [comment]
@BadassDevelop Downgrading your server without having a backup is dangerous, it can cause several problems like world corruption. We cannot support you for this issue. You might want to try looking around/asking on the Spigot forums.

**Comment by BadassDevelop** [comment]
I never ran my server on 1.9... which is why I didn't take a backup... it's a fresh 1.8.8 world running on a PaperSpigot server 1.8,8

**Comment by EvilOlaf** [comment]
Then you may not mind setting up your server from scratch.

**Comment by BadassDevelop** [comment]
It's exactly that, however, pasting in my spawn (built on a flat world) takes nearly two hours because of it being so huge. I was hoping there a quick solution to it.
