### ISSUE TITLE
Sound UI_BUTTON_CLICK in 1.9 on 1.9.4 server

### ISSUE THREAD

**Issue by sebastianbinder** [MylesIsCool/ViaVersion#430]
ViaVersion 0.9.2
Server is running on Spigot 1.9.4 (latest build), players join via BungeeCord
Clients joining with 1.9 don't hear the correct sound 'UI_BUTTON_CLICK'. Instead it sounds like kinda "rain" sound. It works fine with 1.9.4 and 1.10 clients.

**Comment by Matsv** [comment]
Does this happen on non viaversion 1.9 servers?

**Comment by sebastianbinder** [comment]
Spigot 1.9.2 (R1) e000104-4cb3258 - Client 1.9 - No ViaVersion - WORKS
Spigot 1.9.2 (R1) e000104-4cb3258 - Client 1.9 - With ViaVersion - WORKS

Spigot 1.9.2 (R1) e000104-4cb3258 - Client 1.9.4 - No ViaVersion - not compatible (of course)
Spigot 1.9.2 (R1) e000104-4cb3258 - Client 1.9.4 - With ViaVersion - WORKS

Spigot 1.9.4 (R2) 798f32d-0cd0397 - Client 1.9 - No ViaVersion - not compatible (of course)
Spigot 1.9.4 (R2) 798f32d-0cd0397 - Client 1.9 - With ViaVersion - __WRONG SOUND__

Spigot 1.9.4 (R2) 798f32d-0cd0397 - Client 1.9.4 - No ViaVersion - WORKS
Spigot 1.9.4 (R2) 798f32d-0cd0397 - Client 1.9.4 - With ViaVersion - WORKS

**Comment by Matsv** [comment]
I can't reproduce it, isn't the UI sound client-sided? (I'm currently trying the buttons like settings, resume to game, sign accept) if you meant that

**Comment by sebastianbinder** [comment]
Ehm, no, I'm not talking about the Client UI. Sorry, I should have mentioned that :)
I'm talking about e.g. ``player.playSound(player.getLocation(), Sound.UI_BUTTON_CLICK, 1, 3);`` used by plugins.

**Comment by Matsv** [comment]
Fixed next version. Thanks for reporting and taking the time on Gitter :wink:

**Comment by sebastianbinder** [comment]
Great. Thanks for the great support and chat on Gitter :)
