### ISSUE TITLE
Error Java | Spigot 1.8.8  - Client 1.10

### ISSUE THREAD

**Issue by elstringer** [MylesIsCool/ViaVersion#431]
What version of ViaVersion are you using? Type /ver viaversion
**ViaVersion 0.9.2**
What version of Spigot are you using? Type /ver
**Spigot 1.8.8-R1** 
Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
**BungeeCord lastbuild ** 

console
**http://pastebin.com/JNh14Kfp**

**Comment by Matsv** [comment]
One of your plugins is sending invalid metadata, you can disable this message in the viaversion config
