### ISSUE TITLE
Random kick with 1.10 update

### ISSUE THREAD

**Issue by semmeess** [MylesIsCool/ViaVersion#433]
### What version of ViaVersion are you using? Type /ver viaversion
0.9.2 (not the dev build, straight from spigot.org)
### What version of Spigot are you using? Type /ver
git-spigot-e4d4710-e1ebe52
### What plugins are you using? Type /plugins
http://i.imgur.com/6g28L5u.png
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Bungeecord (build #1158 from jenkins)
### How does this error happen? login? Using an item? 
Messing around with armorstands/holograms?? (or perhaps not)
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/vyP6e3j1

**Comment by MylesIsCool** [comment]
Try suppressing errors in the config, otherwise if it still persists try our latest dev build on ci.viaversion.com as it fixed an issue with holos on another server.

**Comment by semmeess** [comment]
Thanks

**Comment by Matsv** [comment]
If this is not solving it, is there an exception in the console when you get kicked (without the metadata errors enabled). And is there a disconnect message?

**Comment by MylesIsCool** [comment]
Is this solved? Otherwise if no response going to assume it is and close in a few days.

**Comment by semmeess** [comment]
Seems solved in dev build with error suppression yes
