### ISSUE TITLE
Glass pane appearance. 

### ISSUE THREAD

**Issue by fiba1** [MylesIsCool/ViaVersion#435]
ViaVersion
**0.9.2**

Spigot
**1.8.8**

Plugins
**Pex, NoDamage, NoWeather, WorldEdit, Chat (BungeeSuitChat), SpawnonLogin, BungeeCompass, AntiVoid, Vault, HideStream**

**BungeeCord** --- BungeeSuite, BungeeJoinMesseges, GlobalTabList, ServerListPlus, BungeeAliases

### How does this error happen? login? Using an item? 

(In 1.9 when Glass panes are placed they appear as sticks (similar to the EnderRod) rather than the small glass wall it makes. (in the shape of a plus sign)

### Is there an error in the console? Use pastebin.com. Is there a kick message?

None.

![2016-06-09_21 45 47](https://cloud.githubusercontent.com/assets/6036228/15952035/8fe21cac-2e8b-11e6-84b2-ec19da9bc766.png)

**Comment by TiTo-418** [comment]
Pretty sure the can't be fixed server side, how the blocks are rendered it's up to the client

**Comment by Matsv** [comment]
This is a feature from 1.9.
