### ISSUE TITLE
Updating Player Inventory Plays Switch Item Animation

### ISSUE THREAD

**Issue by chartx** [MylesIsCool/ViaVersion#436]
ViaVersion version: 0.9.2
Spigot version: 0359393-cd1111 (1.8.8-R0.1)
Bungeecord: The bug appears with and without Bungeecord.

Description: Running player.updateInventory() plays the switch item animation ([gif](https://giphy.com/gifs/3o72F8pbconZwSmEc8)), but only in 1.9 and 1.10. I first discovered it on my Bungeecord network, which has other factors at play. Then I made a plugin that runs player.updateInventory() every two seconds for every online player and tested it on a server with no other plugins except ViaVersion. The bug doesn't happen in 1.8 (with ViaVersion).

How to Reproduce: It happens every time you run player.updateInventory().

**Comment by TiTo-418** [comment]
Vanilla bug

**Comment by chartx** [comment]
player.updateInventory() is a Bukkit method. Are you saying Spigot 1.9 and 1.10 also have this issue?

**Comment by TiTo-418** [comment]
It's a client side bug that appeared in 1.9, it doesn't matter the server version.

**Comment by chartx** [comment]
Alright. Thanks for the fast responses.

**Comment by chartx** [comment]
9
