### ISSUE TITLE
Proxy lost connection

### ISSUE THREAD

**Issue by 99IRock** [MylesIsCool/ViaVersion#438]
### What version of ViaVersion are you using? Type /ver viaversion
0.9.2 
### What version of Spigot are you using? Type /ver
1.8.8-R0.1
### What plugins are you using? Type /plugins
https://gyazo.com/d0c83495fba8095df59fbc352b998f2b

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yes I am using bungeecord #1159 (latest with 1.10 support)

### How does this error happen? login? Using an item? 
When I log in on the lobby server I get kicked

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Kick message when I join in the lobby, it's random but mostly of the time in a few seconds I get kicked:
Bungeecord kick message: 15:49:53 [INFO] [ThomasssMC] disconnected with: [Proxy] Lost connection to server.

I thought that a while ago I saw something in the plugin description, that if you get this error you need to disable something. I can't find that anymore though.. hope you can help me out soon :)

**Comment by 99IRock** [comment]
Oh and I don't have this problem with Viaversion 0.6.4, that's why I didn't update because it kept on giving me this problem

**Comment by Matsv** [comment]
I'm going to close this because you didn't respond. Please ask a re-open when you can provide us with more information.
