### ISSUE TITLE
Collision Cancel Appears to be Ignored

### ISSUE THREAD

**Issue by RyanHecht** [MylesIsCool/ViaVersion#439]
### What version of ViaVersion are you using? Type /ver viaversion
0.9.3
### What version of Spigot are you using? Type /ver
1.8.8
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord Build #1159 (latest as of 6/15/2016)
Plugins: http://prntscr.com/bgzbo1

### How does this error happen? login? Using an item? 
I have 'prevent-collision' set to 'true' in my config, and yet players on versions 1.9/1.10 still experience player collision. Have I set something up incorrectly? 
Complete config.yml: http://pastebin.com/7hJ6YSmm

**Comment by Matsv** [comment]
Make sure auto-team is also enabled

**Comment by Matsv** [comment]
What bungee plugins do you use?

**Comment by Matsv** [comment]
What bungee plugins do you use?

**Comment by RyanHecht** [comment]
jkl123m14's BungeeChatClear, Bloodsplat's BungeeSuite-1.9, CodeCrafter47's BungeeTabListPlus, Niklas Stambor's Maintenancemode, Troydesante's Server Switcher, joehot200's ServerInfo, and Yamler @Matsv

**Comment by Matsv** [comment]
@RyanHecht could you try to remove some of those plugins to see if one of them is causing it?

**Comment by RyanHecht** [comment]
@Matsv What's the gist of how the collision cancelling works? That way I can make an educated guess as to what may be causing it

**Comment by MylesIsCool** [comment]
@RyanHecht It simply overrides scoreboard packets.

**Comment by TiTo-418** [comment]
This team option is flipped (https://bugs.mojang.com/browse/MC-87984)

**Comment by RyanHecht** [comment]
BungeeTabListPlus, which by nature obviously also overrides scoreboard packets, is causing the issue..unfortunately, looks like there isn't a way to use the collision cancelling feature AND BungeeTabListPlus together. Oh well, haha

**Comment by Matsv** [comment]
Try contacting the developer from bungeetablist :smile:
