### ISSUE TITLE
[Feature request] Auto update or update with command.

### ISSUE THREAD

**Issue by camdenorrb** [MylesIsCool/ViaVersion#440]
Was just wondering since you guys make so many updates if it was possible you would add a Auto update feature?

I can possibly add it and make a pull request if it helps.

**Comment by Matsv** [comment]
We'll not implement an auto-updater.

There are a few reasons for that.

_Quote from @MylesIsCool _ 
> The reasons which I'm currently against this:
> 
> - If we deploy a bad build by accident, servers will instantly upgrade to it.
> - This is a protocol modification, reloads are not good. It would require a reboot.
> - Owners become less aware of changes / incompatibilities that could happen to their server.

However, you can create your own auto-updater for your server.

**From the Spigot page:**

> These should work fine on the most recent versions of wget:
> If you want it downloaded as ViaVersion.jar:
> `
> wget -O ViaVersion.jar http://myles.us/ViaVersion/latest.jar
> `
> or on windows:
> `
> curl -o ViaVersion.jar http://myles.us/ViaVersion/latest.jar
> `
> If you want it downloaded as ViaVersion-X.Y.Z.jar:
> `
> wget http://myles.us/ViaVersion/latest.jar --content-disposition
> `
> You could use these in a start-up script if you wanted.

Full discussion #317

**Comment by camdenorrb** [comment]
Sorry I should have read the other issues.
