### ISSUE TITLE
Protocol Version

### ISSUE THREAD

**Issue by VatPik** [MylesIsCool/ViaVersion#442]
### What version of Spigot are you using? Type /ver
1.10
### What plugins are you using? Type /plugins
Plugins (18): ChestFiller, WorldEdit, ItemRenamer, iDisguise, Vault, PermissionsEx, ViaVersion, WorldGuard, MakeYourOwnCommands, Essentials, PlotSquared, MultiWorld, Autorank, EssentialsSpawn, EssentialsChat, ProtocolLib, HolographicDisplays, CratesPlus
### How does this error happen? login? Using an item? 
When i try to log in. It wont make me able to join with other versions.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
![skaermbillede 2016-06-22 kl 21 56 38](https://cloud.githubusercontent.com/assets/20097506/16281380/74d6c032-38c4-11e6-8e15-01811612a717.png)

**Comment by Matsv** [comment]
As mentioned on the Spigot page, this plugin is meant to support newer versions on an older server.
There are other plugins out there that support backwards compatibility (Like ProtocolSupport)

**Comment by MrPowerGamerBR** [comment]
ProtocolSupport Link: https://www.spigotmc.org/resources/protocolsupport.7201/
