### ISSUE TITLE
0.9.4 log spam

### ISSUE THREAD

**Issue by alexmarkey** [MylesIsCool/ViaVersion#444]
### What version of ViaVersion are you using? Type /ver viaversion

0.9.4

### What version of Spigot are you using? Type /ver

http://prntscr.com/bjslp3

### What plugins are you using? Type /plugins

http://prntscr.com/bjsltk

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

LilyPad

### How does this error happen? login? Using an item? 

Just randomly spamming my console 

### Is there an error in the console? Use pastebin.com. Is there a kick message?

http://pastebin.com/qAsP1y0y

**Comment by Matsv** [comment]
One of your plugins is sending invalid metadata. You can disable this warning in the ViaVersion config by changing the 'suppress-metadata-errors' value to true.
