### ISSUE TITLE
1.10.1 Client crashes

### ISSUE THREAD

**Issue by alexmarkey** [MylesIsCool/ViaVersion#445]
### What version of ViaVersion are you using? Type /ver viaversion

0.9.4

### What version of Spigot are you using? Type /ver

http://prntscr.com/bjslp3

### What plugins are you using? Type /plugins

http://prntscr.com/bjsltk

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

LilyPad

### How does this error happen? login? Using an item? 

Upon joining my Prison servers (mc-central.net both prison 1 and 2) 1.10.1 clients instantly crash when loading the chunks in spawn.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

Client Crash:
https://www.dropbox.com/s/x69j0sqsnxpcuis/crash-2016-06-23_09.45.42-client.txt?dl=0

**Comment by Matsv** [comment]
This is a Minecraft bug in 1.10.1. @MylesIsCool created a small patch for it that replace the block with another (When you enable it in the config). You can download the devbuild on https://ci.viaversion.com

**Comment by MylesIsCool** [comment]
Use 1.10.2
