### ISSUE TITLE
Crash pistons

### ISSUE THREAD

**Issue by ridalarry** [MylesIsCool/ViaVersion#448]
Using the latest ViaVersion on spigot 1.9.4 and I am having issue with piston extensions crashing the players on 1.10.1

http://pastebin.com/jdAVjNwP

**Comment by EvilOlaf** [comment]
https://github.com/MylesIsCool/ViaVersion/pull/443

**Comment by Matsv** [comment]
There is a devbuild on the server that makes you replace that client crashing block. We are going to wait and see if Mojang patches the issue today.

**Comment by ridalarry** [comment]
that patch didn't work

**Comment by Matsv** [comment]
@ridalarry did you enable the config option?

**Comment by Rida94** [comment]
@Matsv yes i did

**Comment by Matsv** [comment]
@Rida94 Use the version Mojang released today 1.10.2
