### ISSUE TITLE
End portal block is invisible for 1.10.2 players

### ISSUE THREAD

**Issue by haelexuis** [MylesIsCool/ViaVersion#451]
### What version of Spigot are you using? 1.9

This is end portal, https://cdn.pbrd.co/images/1U8IhY4J.png.. I belive, you don't need any description :D

**Comment by Matsv** [comment]
Please use the issue template. https://github.com/MylesIsCool/ViaVersion/blob/master/ISSUE_TEMPLATE.md

**Comment by haelexuis** [comment]
But.. it is texture o.O you don't need any info, try it and send me screen where is portal on minecraft 1.10.2

**Comment by Matsv** [comment]
I can't reproduce this with spigot 1.9.4. That's why I ask for more info.

**Comment by Matsv** [comment]
Screenshot you asked for: https://fs.matsv.nl/media?id=w0wh7fbo

**Comment by haelexuis** [comment]
Ah, I have 1.9 R1..

**Comment by Matsv** [comment]
Could you give me the full output of /ver ViaVersion and /ver

**Comment by MylesIsCool** [comment]
Closing this as it's down to you using 1.9.2 which is not supported, watch the above pull request for progress.

This is a good reason why you should fill out the issue template.
