### ISSUE TITLE
console errors bungeecord and spigot

### ISSUE THREAD

**Issue by smessie** [MylesIsCool/ViaVersion#453]
### What version of ViaVersion are you using? Type /ver viaversion
I'm using the latest version downloaded on SpigotMC

### What version of Spigot are you using? Type /ver
Spigot 1.8.8 and latest bungeecord version

### What plugins are you using? Type /plugins
See console log

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yes, latest version of bungeecord, even here an error.
http://pastebin.com/3TtymuFD
Error with the teams, probably you are creating the same teams named as Viaversion

### How does this error happen? login? Using an item? 
Uhm, not sure when it is, I think on login or it is just random

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/NQHmz6K5
Also the plugins and spigot version is included :)

**Comment by Matsv** [comment]
The first problem:
Disable auto-team in the ViaVersion config.

The second problem:
One of your plugins is sending invalid metadata, you can disable this informative warning by changing 'suppress-metadata-errors' to true in the ViaVersion config.

**Comment by Matsv** [comment]
I'm going to close this, let me know if you still have any issues after changing those config values.
