### ISSUE TITLE
Invalid JSON String

### ISSUE THREAD

**Issue by C-Gaming** [MylesIsCool/ViaVersion#454]
What version of ViaVersion are you using? **0.9.3**

What version of Spigot are you using? **1.8.8-R0.1**

What plugins are you using? Conflict with **TokenEnchant** it seems

Are you using any additional software like BungeeCord? Yes, but that is not the issue it seems

How does this error happen? Creating an Enchantment Sign for TokenEnchant

Is there an error in the console? http://pastebin.com/u0XaKNfV

**Comment by Matsv** [comment]
The TokenEnchant plugin is sending invalid json data. Contact the TokenEnchant developer.

**Comment by Matsv** [comment]
I took a small look at it, turns out he is not trying to send json, but has similar syntax.
Could you try if this patch works for you? https://fs.matsv.nl/files/ViaVersion-0.9.5-SNAPSHOT.jar

**Comment by C-Gaming** [comment]
Ohh haha lol, ill try it now :)

**Comment by C-Gaming** [comment]
The variable is stuck on {ench_cost} until you interact, after that it works :p

**Comment by Matsv** [comment]
And that doesn't happen on 1.8?

**Comment by C-Gaming** [comment]
Oh i'm using 1.9 rn lol

**Comment by C-Gaming** [comment]
Possible to add you on Skype? Easiest

**Comment by Matsv** [comment]
I'm sorry, I don't really like to add random people on Skype. However, you can join Gitter with your GitHub account to chat -> https://gitter.im/Matsv

**Comment by Matsv** [comment]
Fixed next version.
