### ISSUE TITLE
Internal Exception: io.netty.handler.codec.DecoderException

### ISSUE THREAD

**Issue by Callahhh** [MylesIsCool/ViaVersion#457]
### What version of ViaVersion are you using? Type /ver via version
0.9.4
### What version of Spigot are you using? Type /ver
spigot 1.8.8
### What plugins are you using? Type /plugins
Custom coded // pretty sure it won't help in this case.
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Hexachord 1.7 - 1.10
### How does this error happen? login? Using an item? 
Not sure.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
29.06 12:57:04 [Server] INFO {Type: Short, Source #0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.WorldPackets$9 (Anonymous), Data: [Pair{Type|Short, 0}, Pair{Type|Position, Position(x=2, y=69, z=1)}], Packet ID: 7}
29.06 12:57:04 [Disconnect] User **removed** has disconnected, reason: Internal Exception: io.netty.handler.codec.DecoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/MylesIsCool/ViaVersion/issues

**Comment by MylesIsCool** [comment]
This error looks short and a plugin list would be nice.

**Comment by Callahhh** [comment]
That was the error, there was nothing else.
Core plugin, kitpvp plugin, Protocol Support and ViaVersion

**Comment by MylesIsCool** [comment]
@Callahhh Does it happen without ProtocolSupport? and it feels like there should be 1 more line?

**Comment by Callahhh** [comment]
I just noticed it in console and thought I'd report it, but I haven't seen it since. There was nothing before or after it, sadly.

**Comment by MylesIsCool** [comment]
I can't really help if there's no other info unfortunately

**Comment by Callahhh** [comment]
Alright.

**Comment by BestMark** [comment]
I have same problem. Please, help to resolve it.

**Comment by Matsv** [comment]
@BestMark Could you give us all the info we need? (https://github.com/MylesIsCool/ViaVersion/blob/master/ISSUE_TEMPLATE.md)

**Comment by MylesIsCool** [comment]
Can you test this issue in latest version as we performed quite a few rejigs with packet stuff @BestMark @Callahhh

**Comment by BestMark** [comment]
This problem has fixed when I changed TacoSpigot to Spigot
Thanks
