### ISSUE TITLE
Change the reload message

### ISSUE THREAD

**Issue by wiiarctus** [MylesIsCool/ViaVersion#459]
Hello I want to ask if it is possible to change the kick message on a reload (Server reload, please rejoin!)? ^^

**Comment by MylesIsCool** [comment]
It's there because you shouldn't reload.

We'll think about making it configurable. You should really use a plugin manager.

**Comment by wiiarctus** [comment]
Do you mean something like PlugMan? If you have any others to recommend then please tell it to me because I have some problems with this and it's not working correctly..^^

**Comment by MylesIsCool** [comment]
I'd never suggest unloading ViaVersion due to it's nature.

Otherwise things like PlugMan should work with other plugins.

**Comment by EvilOlaf** [comment]
Like others developers you could forcefully disable the plugin when a `/reload` is detected. This way the server owner has to do a clean restart in order to get it to work again. Also with some kind a educational background ;)

**Comment by MylesIsCool** [comment]
In next version
