### ISSUE TITLE
Compatibility for Orebfuscator  

### ISSUE THREAD

**Issue by KillerAntMC** [MylesIsCool/ViaVersion#462]
### What version of ViaVersion are you using? Type /ver viaversion
ViaVersion version 0.9.4
### What version of Spigot are you using? Type /ver
This server is running CraftBukkit version git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
### What plugins are you using? Type /plugins
Plugins (70): AnimatedNames, AntiAura, AuctionHouse, Banknotes, BanManager, BattleLevels, BetterAlias, BossMessenger, BuycraftX, ChatControl, ClearLag, CoinFlip, CombatTagPlus, CompatNoCheatPlus, CustomCrates, CustomEnchantments, DeluxeChat, DeluxeTags, DisguiseCraft, DropParty, EchoPet, Essentials, EssentialsSpawn, Factions, FactionsTop, FactionUUIDLogout, FastCraftPlus, FBasics, FeatherBoard, FixFreecam, GAListener, GiveMeHead, GroupManager, HideStream, HolographicDisplays, IcyHotCommands, InfiniteBlocks, InstantDamageCooldown, LavaSponge, LitBooster, LitCore, LitEvents, Lottery, MergedMob, Multiverse-Core, MVdWPlaceholderAPI, NamelessMC, NoCheatPlus, ObsidianDestroyer, PlaceholderAPI, PlugMan, ProtocolLib, Punish, ServerListPlus, ShopGUIPlus, Shopkeepers, ShowItem, SilkSpawners, SimpleTrading, StatTrakItems, SuperTrails, SupplyCrates, TallNether, Vault, ViaVersion, VoteParty, Votifier, WorldBorder, WorldEdit, WorldGuard
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
This server is running Waterfall version git:Waterfall-Bootstrap:1.10-SNAPSHOT:df0c469:unknown by md_5
Plugins (4): MoveMeNow, NuVotifier, ServerListPlus, BungeeToolsHubCommand
### How does this error happen? login? Using an item? 
Any player that connects to the server using minecraft 1.9 or higher crashes instantly while Orebfuscator is enabled.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
There is no error, the player just gets kicked with a generic disconnect message (ex. The server you were on went down!).

**Comment by MylesIsCool** [comment]
Just use Spigot's built in anti xray?

**Comment by KillerAntMC** [comment]
The reason I want to use Orebfuscator is because of its ProximityHider feature which hides players chest from far away to stop ChestESP. Spigot's built in X-Ray doesn't have this feature.

**Comment by MylesIsCool** [comment]
What does it crash with?

Where can I obtain the version you're using?

**Comment by KillerAntMC** [comment]
I'm using these: http://tcpr.ca/files/paperspigot/PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar
https://github.com/lishid/Orebfuscator/releases/tag/v3.0.6-R3-legacy

**Comment by MylesIsCool** [comment]
"What does it crash with?"

**Comment by KillerAntMC** [comment]
The crash message is either "The server you were previously on went down" or "Kicked for flying".

**Comment by MylesIsCool** [comment]
Anything in your server logs?

**Comment by KillerAntMC** [comment]
Nothing shows up, it just shows that the player disconnected.

**Comment by MylesIsCool** [comment]
I can't replicate your issue.

I'm using latest ViaVersion from ci.viaversion.com

ProtocolLib, Orefuscator, ViaVersion

I have Spigots anti-xray disabled and when using Xray it shows the ground as TNT showing it works. And chest proximity also works.

Could you try just these plugins and tell me if it works?

**Comment by MylesIsCool** [comment]
Going to close if no response within 2 days as can't replicate.

**Comment by KillerAntMC** [comment]
Thanks! I forgot that I had ProtocolSupport when testing this and it kept crashing my players. You can close this now.

**Comment by KillerAntMC** [comment]
Hello, can this be reopened? The last time I tested this was without bungeecord, now I know that this error happens when you have protocollib, orebfuscator, and viaversion while running under bungeecord. I'm also using paper spigot 1.8.8 but the error only shows up in bungeecord.

This is the error on my bungeecord log: http://pastebin.com/heVu3NHB

Everything works fine with someone that is 1.8 joins, but when someone that is 1.9 or 1.10 joins, it gives me that error.

**Comment by MylesIsCool** [comment]
@KillerAntMC If you're able to test this localhost and use /viaver debug and replicate it would be useful. (As that would provide the packets before the kick)

**Comment by KillerAntMC** [comment]
This is what the console says when debugging is enabled: http://pastebin.com/b15kYJiv

**Comment by KillerAntMC** [comment]
I've tried different bungeecord versions and it's still giving me the same error.

**Comment by MylesIsCool** [comment]
@KillerAntMC If you try just orefuscator without protocollib (as a test) does it still happen?

**Comment by KillerAntMC** [comment]
It's fixed when protocollib isn't enabled.

**Comment by Matsv** [comment]
This is something that needs to be fixed in Orefuscator. The issue is most likely that it's not registered as async.

**Comment by MylesIsCool** [comment]
https://github.com/MylesIsCool/Orebfuscator <- has links you need.

**Comment by KillerAntMC** [comment]
Thank you!
