### ISSUE TITLE
ViaVersion is incompatible with both ProtocolSupport & PacketListenerAPI enabled

### ISSUE THREAD

**Issue by Kurimatzu** [MylesIsCool/ViaVersion#463]
### What version of ViaVersion are you using? Type /ver viaversion
ViaVersion version 0.9.7-SNAPSHOT
Author: _MylesC

### What version of Spigot are you using? Type /ver

This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Checking version, please wait...
You are 349 version(s) behind

### What plugins are you using? Type /plugins

Plugins (3): ViaVersion, PacketListenerApi, ProtocolSupport

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

No

### How does this error happen? login? Using an item? 

Login.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
"Unsupported protocol version 210"

To enter the client 1.10, I'm kicked from the server with the message "Unsupported ProtocolVersion 210"

(is the lack of support for the plugin PacketListenerAPI?)

**Edit by @Matsv:** [Link to PacketListenerAPI's issue](https://github.com/InventivetalentDev/PacketListenerAPI/issues/3)

**Comment by Kurimatzu** [comment]
@Matsv It is not possible to add support for them?

**Comment by MylesIsCool** [comment]
Does ProtocolSupport and PacketListener work together on it's own?

**Comment by Kurimatzu** [comment]
I can't say, I don't think.

**Comment by MylesIsCool** [comment]
@Kurimatzu Can you test this?

**Comment by Kurimatzu** [comment]
The ProtocolSupport along with the PacketListenerAPI, work perfectly.

**Comment by MylesIsCool** [comment]
I'll take a look into it when I get a moment, hopefully I can get it working but load order tends to be so specific sadly

**Comment by Kurimatzu** [comment]
@MylesIsCool Did you make any progress?

**Comment by MylesIsCool** [comment]
@Kurimatzu No
