### ISSUE TITLE
bad packet ID error

### ISSUE THREAD

**Issue by PietH96** [MylesIsCool/ViaVersion#464]
Hi,

we are using ViaVersion with the version 0.9.6 and players on our Bungee get kicked accidentally with that bad Packet ID errors in the bungeecord console:

http://hastebin.com/tapugicazu.coffee

We got no error in the spigot console.

We are using Bungeecord on the latest version at the time of my post here and Spigot with version 1.9.4.

Why does this happen?

Thanks in advance!

**Comment by Matsv** [comment]
What bungee plugins do you use?

**Comment by MylesIsCool** [comment]
Not ViaVersion related,

iirc this is because Minechat messed up or something on the lines of that.

**Comment by PietH96** [comment]
What do you mean with "Minechat"?

**Comment by MylesIsCool** [comment]
An app for your phone.

**Comment by PietH96** [comment]
In our test all players played with the PC version.

**Comment by Matsv** [comment]
@PietH96 Could you try to remove some bungee plugins, see if one of them is causing it?

**Comment by PietH96** [comment]
We use only self-written plugins, none of these modifies any packet.

**Comment by PietH96** [comment]
When we remove ViaVersion, everything works perfect!

**Comment by Matsv** [comment]
Does it happen without bungeecord? So connecting directly to the server you want

**Comment by PietH96** [comment]
Yes, the error also occurs without bungeecord.

**Comment by Matsv** [comment]
What plugins do you use?
