### ISSUE TITLE
Ping Issue, with ProtocolSupport

### ISSUE THREAD

**Issue by nathampa0909** [MylesIsCool/ViaVersion#465]
### What version of ViaVersion are you using? Type /ver viaversion
0.9.6

### What version of Spigot are you using? Type /ver
PaperSpigot 1.8.8

### What plugins are you using? Type /plugins
http://prntscr.com/bq6qhs

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Nop

### How does this error happen? login? Using an item? 
Login

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Kick message: "Unsupported protocol version 210"

I have a owm plugin that set the motd and use ServerPingResponseEvent of ProtocolSupport, I think this is the problem. Can you make a event like ServerPingResponseEvent for change motd for ViaVersion? In this way I think the problem can be solved.

Thanks for attention.

**Comment by Matsv** [comment]
Could you test 2 things:

- Does it happen on normal Spigot
- Does it happen without your plugin.

I don't think we'll provide a StatusResponseEvent, I recommend you to use Protocollib to change the status.

**Comment by nathampa0909** [comment]
@Matsv I use ServerPingResponseEvent  of PS because motd of 1.5.2/1.6.4 is diferent of 1.7+, I will try to change this with ProtocolLib, but I dont know how to make with PL.

**Comment by MylesIsCool** [comment]
I'd suggest removing plugins and testing because this sounds odd and doesn't sound ping related.

**Comment by BestMark** [comment]
Try to disable _late-bind_ (set it to _false_)

**Comment by nathampa0909** [comment]
@BestMark Solved.
