### ISSUE TITLE
Strange Error

### ISSUE THREAD

**Issue by billytheDOLPHIN** [MylesIsCool/ViaVersion#466]
### What version of ViaVersion are you using? Type /ver viaversion
0.9.6
### What version of Spigot are you using? Type /ver
https://gyazo.com/2eedc05fee18fa40803aea66300accb0
### What plugins are you using? Type /plugins
https://gyazo.com/6e611955cb11174382243a9a5a061339
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
no

### How does this error happen? login? Using an item? 
Login
### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://www.spigotmc.org/threads/odd-error-any-ideas-people.162212/

**Comment by Matsv** [comment]
Could you test if this still occurs using the latest devbuild? https://ci.viaversion.com/job/ViaVersion/

**Comment by billytheDOLPHIN** [comment]
hmm seems to be gone.

**Comment by Matsv** [comment]
Thanks for testing, fixed next version :smile:

#BlameMyles

**Comment by MylesIsCool** [comment]
:'(
