### ISSUE TITLE
Crash repport

### ISSUE THREAD

**Issue by UraharaNZ** [MylesIsCool/ViaVersion#467]
### What version of ViaVersion are you using? Type /ver viaversion
0.9.6
### What version of Spigot are you using? Type /ver
1.8.8 latest
### What plugins are you using? Type /plugins
https://gyazo.com/ddbf96dc3f327de41cda012e90dcffb0
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yeah bungeecord:  https://gyazo.com/5842230f11d91eb71b4bacbc0cb117f3
### How does this error happen? login? Using an item? 
idk its rare :S its appear on my sw servers
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://hastebin.com/nuqadafuri.avrasm
aparently its issue on leave and something of perms :S

**Comment by MylesIsCool** [comment]
What is HisoCraft perms?

I'm certain this isn't viaversion related, it comes up as if you stopped your server at any point in time viaversion would be doing something (whether it's handling connections or translating packets)

**Comment by UraharaNZ** [comment]
HisoCraftPerms its custom plugin for permissions of our network, a guy on spigot told me its viaversion issue :S

**Comment by MylesIsCool** [comment]
The main thread is what gets locked in a crash like this so usually it's the stack trace at the top. I'd consult the guy who made the permission plugin and ask if he can see the cause.
