### ISSUE TITLE
[PacketListenerAPI] io.netty.handler.codec.EncoderException

### ISSUE THREAD

**Issue by Kurimatzu** [MylesIsCool/ViaVersion#468]
### What version of ViaVersion are you using? Type /ver viaversion
ViaVersion version 0.9.8-SNAPSHOT
Author: _MylesC
### What version of Spigot are you using? Type /ver

This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins

 Plugins (3): PacketListenerApi, ProtocolSupport, ViaVersion

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

No.

### How does this error happen? login? Using an item? 

Login.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

I'm disconnected when entering with the client 1.7, with the following message on the console.

yKuriDev_ lost connection: Internal Exception: io.netty.handler.codec.EncoderException: io.netty.handler.codec.DecoderException: The received a byte array longer than allowed 49408 > 32767

**Comment by MylesIsCool** [comment]
Are you sure this is PacketListenerAPI?

I've been told PS doesn't work properly on Paper.

Can you test without Via? Without PacketListener? etc

**Comment by Kurimatzu** [comment]
Plugins (2): ProtocolSupport, ViaVersion

I tested without PacketListenerAPI, the error still continues.
1.7 client with forge.

**Comment by MylesIsCool** [comment]
"I've been told PS doesn't work properly on Paper."

**Comment by MylesIsCool** [comment]
Closing see above.
