### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by haelexuis** [MylesIsCool/ViaVersion#469]
Do you have FAQ? I try found when comes out 1.10 update.

**Comment by Matsv** [comment]
The 1.10 update is already out, use the latest version.

You can find the FAQ here:
https://www.spigotmc.org/resources/viaversion.19254/

If you use BungeeCord, make sure you update it to the latest version.

**Comment by haelexuis** [comment]
It works on 1.10 server? :O
- You can use a 1.8-1.9.4 server and allow 1.10 to connect.

**Comment by Matsv** [comment]
Oh yeah correct.

We aim to support a newer client version on an older server version.
We'll never allow older versions on a newer server (Between major versions).
You'll be able to allow 1.11 on your 1.10 server when it comes out.

If you want backwards compatibility, you could take a look at ProtocolSupport. :)

**Comment by haelexuis** [comment]
ProtocolSupport has bugged Sounds, I write sounds correct but they doesn't care.

**Comment by Matsv** [comment]
Yeah, you'd have to wait for the developer to remap it.
I see you already created a ticket :) https://github.com/ProtocolSupport/ProtocolSupport/issues/221

**Comment by haelexuis** [comment]
Ok, but is there big changes between 1.9 and 1.10? I think it is maybe month out and ProtocolSupport still doesn't support it.

**Comment by Matsv** [comment]
The changes are smaller than previous versions.
However ProtocolSupport is a big free project and maintained by only one person. He/she also has other things to do next to ProtocolSupport. Be easy on him/her :smile:

**Comment by haelexuis** [comment]
It looks like big project :D
