### ISSUE TITLE
Fishing rod issue.

### ISSUE THREAD

**Issue by Eternalrealms** [MylesIsCool/ViaVersion#47]
You are unable to see your own fishing line when you try to fish. Other players are able to see it though.

**Comment by HugoDaBosss** [comment]
In the latest version 0.4.5 this doesn't seem to be the case anymore.

**Comment by Eternalrealms** [comment]
It still appears to be an issue for me, can anyone else confirm its fixed?

**Comment by MylesIsCool** [comment]
Cannot replicate, closing. Tested with 1.9 & 1.8.9
