### ISSUE TITLE
An error occurred with entity meta data for PLAYER OldID: 5

### ISSUE THREAD

**Issue by StoreMaker** [MylesIsCool/ViaVersion#470]
### What version of ViaVersion are you using? Type /ver viaversion
ViaVersion version 0.9.7

### What version of Spigot are you using? Type /ver
http://imgur.com/IgKwKP2

### What plugins are you using? Type /plugins
http://imgur.com/oIqROb4

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Not using BungeeCord , only spigot 1.8.8 .

### How does this error happen? login? Using an item? 
No idea how this error happens. We had no error and one day it randomly occured.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/8Ukhv7XY

**Comment by Matsv** [comment]
One of your plugins is sending invalid metadata.

You can disable this informative exception by changing 'suppress-metadata-errors' to true in the ViaVersion config.
