### ISSUE TITLE
Curiosity

### ISSUE THREAD

**Issue by MisterJW123** [MylesIsCool/ViaVersion#471]
Just as a curiosity how hard would it be to add 1.7.10 to the list?

Sorry I don't know where else to put this

**Comment by MylesIsCool** [comment]
As replied a billion times in other places,

We're not officially going to make it, you can do as you wish. If you want 1.7, use 1.8.8 server + via + protocolsupport.

Something like that would take 50+ dedicated hours to make test and debug. If you want to do that yourself, you can feel free to but we have no plans to create it.
