### ISSUE TITLE
[Suggestion] 1.1.0 for other versions

### ISSUE THREAD

**Issue by Kurimatzu** [MylesIsCool/ViaVersion#473]
Would it be possible to add support for other versions?
(if the server is on, release 1.1.0 support, 1.8, 1.9 1.7, 1.6, 1.5)

The ProtocolSupport, stopped being updated, (in addition to be very buggy, sounds do not work, etc)

The ViaVersion is higher, contains optimizations that the ProtocolSupport doesn't have.

Would it be possible to study this possibility?

**Comment by Matsv** [comment]
Hi,

We'll not officially support older version/backwards compatibility between major versions.  
The aim of ViaVersion is to allow a newer client on an older server.

Know that backwards compatibility is way more work. You'd have to handle things that didn't exist in previous minecraft versions.

ProtocolSupport has a devbuild that supports 1.10 IIRC.
