### ISSUE TITLE
PacketPlayOutScoreboardTeam on 1.8 Spigot

### ISSUE THREAD

**Issue by sgtcaze** [MylesIsCool/ViaVersion#474]
### What version of ViaVersion are you using? Type /ver viaversion
0.9.7

### What version of Spigot are you using? Type /ver
Both 1.8.8 and 1.9.4 spigot were tested. 1.8.8 spigot is affected. 1.9.4 works fine.

### What plugins are you using? Type /plugins
NametagEdit and ViaVersion

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No Proxy/External Software

### How does this error happen? login? Using an item? 
This issue only affects **1.8 servers** running ViaVersion. When a user is first sent the PacketPlayOutScoreboardTeam packet, their nametag displays properly in tab and above their name.

However, if you send another update, the nametag will not display properly to only the user. Other users will see the nametag formatted correctly. 

In the video, the 1.9.4 portion of the video shows what should happen. In the 1.8.8 section of the video when I update my user's nametag, you can see it does not update in tab. I believe this is caused by a race condition or perhaps the wrong meta is being sent. For example, if I were to clear a player's tag, wait a second, then set their nametag - it works. I experimented with delays, using older ViaVersion releases and even older/newer NametagEdit releases.

video (fixed link)
https://youtu.be/4iIDZajrh6E

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No errors.

**Comment by MylesIsCool** [comment]
Have you tried with autoteam off?

**Comment by sgtcaze** [comment]
@MylesIsCool ah this works! I'll let our users know.
