### ISSUE TITLE
Hand Twitching

### ISSUE THREAD

**Issue by joecoolmc** [MylesIsCool/ViaVersion#476]

**Comment by Matsv** [comment]
You mean while interacting the item goes up and down?

**Comment by MylesIsCool** [comment]
You're using a plugin that updates your inventory.

This is a "feature" of 1.9, you'd have to contact the author of it to stop the twitching, it'll be a plugin modifying your hand constantly. (I'm not sure which it could be, most likely EssentialsHub)


Closing as it sadly isn't fixable
