### ISSUE TITLE
Right Clicking Signs [ServerSigns] Not Working

### ISSUE THREAD

**Issue by MistriHD** [MylesIsCool/ViaVersion#478]
### What version of ViaVersion are you using? Type /ver viaversion
0.9.7
### What version of Spigot are you using? Type /ver
PaperSpigot 1.8.8
### What plugins are you using? Type /plugins
WorldEdit, Custom Spawn Plugin, BungeeBridgeC, ViaVersion, WorldGuard, ProtocolLib, NoCheatPlus, Custom Core Plugin, Custom Shop Plugin, EditableSign, ServerSigns, HolographicDisplays, Minigame Plugin
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Waterfall (latest) -- BungeeBridgeS
### How does this error happen? login? Using an item? 
ServerSigns plugin executes a set command when right clicking signs. This works in 1.8, but doesn't in 1.9 and 1.10.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
No. Nothing happens.

**Comment by Matsv** [comment]
Could you test if this happens while interacting with:

* an empty slot
* an item with some use like a fishing rod

**Comment by MistriHD** [comment]
Update, it actually doesn't work on any versions (1.8, 1.9, or 1.10). I thought it was only 1.8 working, but apparently not.

**Comment by Matsv** [comment]
@MistriHD It's in that case not a ViaVersion issue sadly. We do only modify the clients for higher versions. You might want to contact the developer from that plugin.
