### ISSUE TITLE
Packet Limiter Problems

### ISSUE THREAD

**Issue by checkplys** [MylesIsCool/ViaVersion#480]
Well, this issue isn't from server point of view, it's from player.
I'm from portugal, and I get high ping on a lot of US/Canada or brazilian servers.
So, what happens, is that when I join, I lag and when it stabilize the lag, well, I get kick from ViaVersion packet limiter.
I know that's an option to make packet limiter allow more packets per second, but contacting server owners isn't that easy, and sometimes they will just do nothing.
Is there anything you can do with it?
This happens in joserobjr (a contributor)'s server for example.

**Comment by MylesIsCool** [comment]
We can't change existing configs, so we can't solve the issue. It was actually raised previously because of this.
