### ISSUE TITLE
ViaVersion Broke 2 of My plugins

### ISSUE THREAD

**Issue by Zenoxez** [MylesIsCool/ViaVersion#484]
### What version of ViaVersion are you using? Type /ver viaversion

0.9.8

### What version of Spigot are you using? Type /ver

This server is running CraftBukkit version git-Spigot-c3c767f-33d5de3 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

### What plugins are you using? Type /plugins

CoreProtect, Drugs, WorldEdit, CustomPermissionMessages, Essentials, PlugMan, PlayTime, Votifier, WorldGuard, PowerlessLamps, JailDuty, ChatReaction, PermissionsEx, CommandWatcher, Lottery, ViaVersion, mcMMO, Vault, GAListener, EssentialsSpawn, EnjinMinecraftPlugin, EZRanksLite, PlotSquared, Auctions, Multiverse-Core, ChestCommands, GangsPlus, SimplePrefix, MineResetLite, EZPrestige, PvPManager, AreaShop, CommandSign, HolographicDisplays, SignShop, CratesPlus, CSGO-CratesPlus

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

No

### How does this error happen? login? Using an item? 

There are no errors in the console. After I added ViaVersion and downgraded from 1.10 to 1.8 GAListener stopped giving items to players and my Auction plugin stopped giving the Auctioned item to the highest bidder. It's like the plugins are not able to give items to players.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

No, no errors.

**Comment by Lmmb74** [comment]
Have you checked that the versions of that plugins are 1.8 compatible, and that the given items are not 1.9 or 1.10 only?

**Comment by EvilOlaf** [comment]
Did you downgrade your server software from 1.10 to 1.8 or your client?

**Comment by Matsv** [comment]
ViaVersion does not modify anything that could cause this.
Downgrading your server is dangerous, it could lead to several issues like world corruption and not working plugins because they are made for a higher version. You can try removing ViaVersion and see if it works again, but I doubt it. This is probably caused by downgrading your server.
