### ISSUE TITLE
Could not find a valid metadata

### ISSUE THREAD

**Issue by MeGysssTaa** [MylesIsCool/ViaVersion#487]
### What version of ViaVersion are you using? Type /ver viaversion
0.9.8
### What version of Spigot are you using? Type /ver
1.8.8_R0.1
### What plugins are you using? Type /plugins
ProtocolLib, ViaVersion, Reflex, NoCheatPlus
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I don't.
### How does this error happen? login? Using an item? 
I use Reflex anticheat. It has an NPC (fake entity) check which spawns fake player entities behind the player on join. When he hit any entity, the NPC becomes visible for 2 seconds. 1.7 - 1.9 clients reacts on it normally and they can see the visible NPC. But if you use 1.10 client (on ViaVersion 1.8 server), I'm getting instantly kicked with this reason: http://prnt.sc/c8joqz
### Is there an error in the console? Use pastebin.com. Is there a kick message?
When I'm hitting an entity and NPC becomes visible, I'm getting kicked and I can see this error in the console: http://prnt.sc/c8joqz

If this is Reflex plugin fault, can you please tell me what's wrong there and what can I do?
Thanks.

**Comment by Matsv** [comment]
Could you give the console error? You pasted the same link twice

**Comment by MeGysssTaa** [comment]
Oh, sorry =\
Here it is: http://prnt.sc/c8k7xj

**Comment by Matsv** [comment]
Looks like one of your plugins is sending wrong metadata, probably Reflex, we can't help you sadly since the plugin is closed-source.

You could contact the author and ask him/her to send valid metadata for the npcs.
**1.8 metadata:** http://wiki.vg/index.php?title=Entities&oldid=7375#Human

**Comment by MeGysssTaa** [comment]
Will players still get kicked if I enable 'suppress-metadata-errors'?

**Comment by Matsv** [comment]
Probably yeah, it'll only hide the console exception
