### ISSUE TITLE
Scoreboard invisible after death or world switch

### ISSUE THREAD

**Issue by KingHorse2015** [MylesIsCool/ViaVersion#488]
### What version of ViaVersion are you using? Type /ver viaversion
Version 0.9.8

### What version of Spigot are you using? Type /ver
1.8.8

### What plugins are you using? Type /plugins
`Plugins (33): AsyncWorldEditInjector, WorldEdit, TuxTwoLib, Frame_Protector, SurvivalGames, FarmProtect, WorldGuard, Multiverse-Core, RogueParkour, AsyncWorldEdit, VoidGenerator, OpToggle, iConomy, PermissionsEx, NoteBlockAPI, ViaVersion, Multiverse-Portals, Vault, CubeRunner, MultiInv, Essentials, SkyWarsReloaded, Paintball, BattleArena, TNTRun, Quake, ProtocolLib, LibsDisguises, EpicSpleef, Citizens, EssentialsChat, EssentialsSpawn, UltraCosmetics`

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Normal
### How does this error happen? login? Using an item? 
Switching worlds
### Is there an error in the console? Use pastebin.com. Is there a kick message?
No error messages!

**Comment by Matsv** [comment]
Does this also happen on 1.8?

**Comment by KingHorse2015** [comment]
Yes

**Comment by Matsv** [comment]
It's not a ViaVersion issue in that case. We do only modify 1.9 and higher on spigot 1.8.8.

Contact the author from the scoreboard plugin.

**Comment by KingHorse2015** [comment]
You are right, not a problem of viaversion, just removed from the server, same issue

**Comment by Matsv** [comment]
No worries :)
