### ISSUE TITLE
Update check error while joining

### ISSUE THREAD

**Issue by TheIronMinerLv** [MylesIsCool/ViaVersion#490]
### What version of ViaVersion are you using? Type /ver viaversion
0.9.8
### What version of Spigot are you using? Type /ver
PaperSpigot-"4c7641d" (MC: 1.8.8)
### What plugins are you using? Type /plugins
I'll send my plugins private, if necessary (about 60plugins)
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Right now I'm not using bungee, because I'm just building server...
### How does this error happen? login? Using an item? 
When I joined the server
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/Ntb2dQ92

**Comment by Matsv** [comment]
We are aware of this issue, it's a problem at the third-party API (Spiget), we hope it'll be solved soon. You can ignore it for now or disable the update checker in the config.

I keep this issue open until it's fixed at Spiget's side

**Comment by Matsv** [comment]
We released ViaVersion 0.9.9, that uses Spiget API v2. That'll fix this issue.

**Comment by TheIronMinerLv** [comment]
Thanks!
