### ISSUE TITLE
Login error thing

### ISSUE THREAD

**Issue by xXCalleManXx** [MylesIsCool/ViaVersion#499]
### What is the output link of /viaversion dump?
http://hastebin.com/fexivorisu.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Spigot

### How does this error happen? login? Using an item? 
Login

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/Fw6Xe5gw

**Comment by Matsv** [comment]
Could you try if this still happens now?

**Comment by Matsv** [comment]
Should be fixed now, Mojang pushed a wrong change to their authentication server. Ask a reopen if the problem still occurs for you.
