### ISSUE TITLE
Player crashes - InventoryClickEvent (ViaVersion 1.11)

### ISSUE THREAD

**Issue by kirill3345** [MylesIsCool/ViaVersion#500]
### What is the output link of /viaversion dump?
?

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
LiteGameCreative, LiteGameAntiCheat, ViaVersion-1.11

### How does this error happen? login? Using an item? 
InventoryClickEvent

### Is there an error in the console? Use pastebin.com. Is there a kick message?
"[Server thread/INFO]: kirill3345 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/MylesIsCool/ViaVersion/issues
{Type: Byte, Source #0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.InventoryPackets$8 (Anonymous), Data: [Pair{Type|Unsigned Byte, 4}, Pair{Type|Short, 12}, Pair{Type|Byte, 0}, Pair{Type|Short, 1}], Packet ID: 14}
Actual Error: "

**Comment by MylesIsCool** [comment]
"What is the output link of /viaversion dump?"

Please complete the full error, also please pastebin.com the full error.

**Comment by kirill3345** [comment]
http://pastebin.com/WqZc0rPc

**Comment by MylesIsCool** [comment]
"What is the output link of /viaversion dump?"

**Comment by Dimatert9** [comment]
Попробуй включить debug: true в server.properties и в spigot.yml
А также напиши команду /viaversion dump и скинь то что она напишет. Или если она создала какойто файл, то и его скинь.

**Comment by kirill3345** [comment]
http://imgur.com/EkN7kh2
http://imgur.com/xslF4Rm

**Comment by Matsv** [comment]
**Direct link:** http://hastebin.com/ilevukotel.json

**Comment by kirill3345** [comment]
I alary enabled debug: true  in  server.properties.

**Comment by Matsv** [comment]
@kirill3345 Could you pastebin the full error? We can't do a lot with the current one, we need the info after `Actual error:`

**Comment by kirill3345** [comment]
After the "Actual error:" There is nothing.

**Comment by kirill3345** [comment]
http://pastebin.com/3ZMe19rh

**Comment by Matsv** [comment]
Thanks, should be fixed using the latest build.
