### ISSUE TITLE
java.lang.Exception: Could not find valid metadata

### ISSUE THREAD

**Issue by Morols1** [MylesIsCool/ViaVersion#501]
### What is the output link of /viaversion dump?
http://hastebin.com/umagevoxay.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord

### How does this error happen? login? Using an item? 
I dont now, its happend very often

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/EBsZkCXb

**Comment by Matsv** [comment]
One of your plugins is sending invalid metadata, make sure that all your plugins are compatible with spigot 1.8.x. You can disable this informative exception by enabling suppress-metadata-errors in the config.
