### ISSUE TITLE
NPCRightClickEvent gets activated twice

### ISSUE THREAD

**Issue by Blamo27** [MylesIsCool/ViaVersion#502]
The event InventoryCloseEvent is fired when I open an inventory :

When I try to close my inventory with the 1.8.9 client version it's working but if the event is also fired if a player open an inventory with the 1.9.4 version.

I tried with 1.8.9 & 1.9.4 versions.

ViaVersion 0.9.9.

Can you fix this bug ?
Thanks.

**Comment by Matsv** [comment]
Can't reproduce this bug with only ViaVersion and ProtocolLib.
Please follow the issue template (https://github.com/MylesIsCool/ViaVersion/blob/master/ISSUE_TEMPLATE.md) and give us steps how to reproduce it.

Thanks

**Comment by Blamo27** [comment]
/viaversion dump output :
-> http://hastebin.com/lubekugoko.json

Version: git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (1.8.8-R0.1-SNAPSHOT)
-> No error in the console or else

**Comment by MylesIsCool** [comment]
What are the drawbacks of this issue?

Are we able to use a certain plugin and see something?

**Comment by Blamo27** [comment]
This was removing an inventory that I was trying to use.

**Comment by Blamo27** [comment]
@MylesIsCool I used a plugin that is opening an inventory when player right click at an NPC.

**Comment by Matsv** [comment]
@Blamo27 do you have a link for us to that plugin, or a way to reproduce it?

**Comment by Blamo27** [comment]
Click on this link to download a small plugin that I created to reproduce the same bug :
=> https://file.io/AyJ9Vb

You need Citizens 2.0 to run this plugin.
And after :
-> Create an NPC
-> /trait test
-> RightClick on the NPC

You should see a message when you Open / Close the inventory.

**Comment by Matsv** [comment]
```
{
success: false,
error: 404,
message: "Not Found"
}
```
The file does not exist.

**Comment by Blamo27** [comment]
Yes sorry, https://dropfile.to/fsGEa8U
I changed this.

**Comment by Matsv** [comment]
The InventoryCloseEvent works as expected. The problem is that NPCRightClickEvent gets activated twice, that'll close the previous inventory.

**Comment by Blamo27** [comment]
Oh ..  But how to fix this problem ?

**Comment by Matsv** [comment]
@Blamo27 Working on a small patch now

**Comment by Blamo27** [comment]
Thanks !

**Comment by Matsv** [comment]
Should be fixed using the latest devbuild :smile:
