### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AsVaidas** [MylesIsCool/ViaVersion#503]
### What is the output link of /viaversion dump?
http://hastebin.com/viquwufoju.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
PaperSpigot (Newest)

### How does this error happen? login? Using an item? 
Just disconects with error

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://nmcg.lt/log.txt

**Comment by Matsv** [comment]
One of your plugins is sending chunk packets wrongly, it fails to read the NBT.
Any chance you can copy your server to your local pc, and debug it?
Remove some plugins until it no longer happen?

Thanks

**Comment by AsVaidas** [comment]
I use ViaBackwards, 1.10 server connecting with 1.9 version. With 1.10 client everything works ok, but with 1.9 client it just disconects. But this problem just in spawn. If i teleport to survival world, i can play without any problem. After playing, i can go to spawn, and everything magicaly fixes, no disconect, nothing, i can play normally.

**Comment by Matsv** [comment]
@AsVaidas This is still an incompatibility with another plugin sadly. Make sure that all your plugins are compatible with Spigot 1.10.

**Comment by MylesIsCool** [comment]
Closing if you have further issues, consult the plugins you have installed and try to remove.
