### ISSUE TITLE
Bug item head slot

### ISSUE THREAD

**Issue by Blamo27** [MylesIsCool/ViaVersion#504]
### ViaVersion dump and Spigot version

/viaversion dump output :
-> http://hastebin.com/lubekugoko.json

Version: git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (1.8.8-R0.1-SNAPSHOT)
-> No error in the console or else

### Conflit with Magic

I'm using a Magic item. (Plugin)

### An error using an item

With the Magic plugin, we can vanish ourselves by rightclicking with an item which is going directly to the head slot armor.

But in 1.9 :
=> Video to explain: https://streamable.com/clg0

**Comment by MylesIsCool** [comment]
Are you sure this is not part of the fact 1.9 now renders items in the head slot properly instead of what 1.8 would do?

**Comment by Blamo27** [comment]
No in 1.9, this is working fine.

**Comment by Matsv** [comment]
@Blamo27 Could you also create a video in 1.8 that shows how you expect it to be?

**Comment by Blamo27** [comment]
Of course : https://streamable.com/10fh

**Comment by Matsv** [comment]
This is something that renders differently for the client. We won't fix this issue.

**Comment by Blamo27** [comment]
@Matsv Is it possible to create a plugin that is replacing the item in the head slot with "MATERIAL.AIR" for 1.9 clients to prevent this bug ?
