### ISSUE TITLE
Problem with ViaVersion on PaperSpigot-1.8.8

### ISSUE THREAD

**Issue by md79** [MylesIsCool/ViaVersion#506]
Hello, I wanted to do server with support 1.7.x-1.10.x. Unfortunately when I connect to the server using version 1.7.10 after 2 seconds I was kicked with message: http://pastebin.com/ETLewBM6

I tried to use "/viaversion dump" but the console shows errors: http://pastebin.com/svMhNWXt

Plugin list:

- ViaVersion-0.9.10 (https://ci.viaversion.com/job/ViaVersion/89/)
- ProtocolSupport-4.23 (http://build.true-games.org/job/ProtocolSupport/388/)
- ProtocolLib-4.1.0 (http://ci.shadowvolt.com/job/ProtocolLib/325/)

The server is running on PaperSpigot-1.8.8 (https://ci.destroystokyo.com/job/PaperSpigot/443/)

**Comment by Matsv** [comment]
Please try this build of ProtocolSupport-> http://build.true-games.org/job/ProtocolSupport/388/

**Comment by Matsv** [comment]
Could you change debug: true in server.properties and give us the full exception?

**Comment by md79** [comment]
Errors from the console when I turn on debugging: http://pastebin.com/Bh26APTS

**Comment by MylesIsCool** [comment]
Have you tried without ProtocolSupport?

I read something somewhere that it's not so good with paper.
(and also try with normal spigot maybe?)

**Comment by md79** [comment]
ViaVersion don't support version 1.7.x so I must use ProtocolSupport (This error occurs only on 1.7.x.). On normal Spigot I don't have problem with that. However, I would like to use PaperSpigot...

**Comment by MylesIsCool** [comment]
I honestly can't help you if it's not within my reach to fix.

https://www.spigotmc.org/threads/protocolsupport-1-8-8.158746/


ProtocolSupport isn't compatible with paper, going to close this as there's no much else I can say.

It might work if you went 1.10 with just ProtocolSupport otherwise you're gonna have to take normal Spigot.
