### ISSUE TITLE
1.10.2 Tab list updates

### ISSUE THREAD

**Issue by flash110** [MylesIsCool/ViaVersion#507]
### What is the output link of /viaversion dump?
http://hastebin.com/tibuxusipu.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I am using bungeecord 1.10.2 and Spigot 1.8.8.
I have custom hub and core plugins 

### How does this error happen? login? Using an item? 
Part of one of my plugins adds a prefix to the players name in the tab list, and when it updates so they can see the prefix's they can see everyone else's prefix but their own. Once they re-log they can see everyone's.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Nope

**Comment by Matsv** [comment]
Try changing auto-team to false in the ViaVersion config

**Comment by MylesIsCool** [comment]
See answer above, will be the issue. You can also use /viaver autoteam in-game.
