### ISSUE TITLE
Sponge DisplaceEntityEvent Error

### ISSUE THREAD

**Issue by Maxqia** [MylesIsCool/ViaVersion#508]
For #505 
During the 1.8->1.9 transition, Sponge renamed the DisplaceEntityEvent to the MoveEntityEvent, When I try to run ViaVersion for Sponge on 1.10 it outputs a NoClassDefFoundError.

**Comment by Matsv** [comment]
Could you post the full exception?

**Comment by Maxqia** [comment]
http://pastebin.com/GuzqNnVk

**Comment by MylesIsCool** [comment]
Fixed in latest version
