### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#518]
Hello,

I had a good idea. If an administrator doesn't want to allow all of his players to connect on 1.10 for example on his server, or exclusively to reduce the lags of this player, he can allows him to connect on 1.10. 
So could you add a feature to allow or ban players for using versions with the config.yml or with a command, or with permissions ?

Thanks ! :D

**Comment by Matsv** [comment]
This isn't something we'll implement in ViaVersion, there might be load balance plugins for Bungee on the Spigot resource page.
