### ISSUE TITLE
Issue with BungeeCord with Lower Versions

### ISSUE THREAD

**Issue by MylesIsCool** [MylesIsCool/ViaVersion#519]
### What is the output link of /viaversion dump?
http://hastebin.com/bumacadaso.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Using BungeeCord version

### How does this error happen? login? Using an item? 
Login with 1.8.8 on 1.10 server http://myles.us/m93X.png

Using ProtocolSupport to support older versions on 1.10 spigot:
1.10 works
1.8 does not

Possible protocol mismatch?

**Comment by InfinityAspire** [comment]
Having a similar issue, was testing with Hexacord, https://github.com/HexagonMC/BungeeCord/releases, with ViaVersion on Bungee and ProtocolSupport on Spigot to try and allow 1.7 - 1.11 clients to connect. 1.7.x and 1.8.x clients couldn't connect but 1.9.x - 1.11 Snapshot could. Same error as above

**Comment by MylesIsCool** [comment]
Should now be fixed on latest build (of 1.11 DEV) (Got the original reporter to test, if any other issues just open a ticket)
