### ISSUE TITLE
Wither Boss Bars breaking

### ISSUE THREAD

**Issue by Z609** [MylesIsCool/ViaVersion#52]
[15:57:55 INFO]: An error occurred with entity meta data for WITHER
[15:57:55 INFO]: throwing
[15:57:55 WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.
> at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
> at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.write(NettyChannelInjector.java:268) ~[?:?]
> at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
> at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
> at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
> at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
> at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
> at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
> at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:327) ~[?:?]
> at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198) [server.jar:git-PaperSpigot-7aa4900-62a2169]
> at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5$3.run(NettyChannelInjector.java:345) [ProtocolLib.jar:3.6.5-b222]
> at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [server.jar:git-PaperSpigot-7aa4900-62a2169]
> at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [server.jar:git-PaperSpigot-7aa4900-62a2169]
> at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [server.jar:git-PaperSpigot-7aa4900-62a2169]
> at java.lang.Thread.run(Thread.java:745) [?:1.8.0_73]
Caused by: java.lang.RuntimeException: An internal error occured.
> at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20) ~[?:?]
> at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.encode(NettyChannelInjector.java:490) ~[?:?]
> at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.encode(NettyChannelInjector.java:262) ~[?:?]
> at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
> ... 14 more
Caused by: java.lang.NullPointerException
> at us.myles.ViaVersion.transformers.OutgoingTransformer.transformMetadata(OutgoingTransformer.java:638) ~[?:?]
> at us.myles.ViaVersion.transformers.OutgoingTransformer.transform(OutgoingTransformer.java:217) ~[?:?]
> at us.myles.ViaVersion.handlers.ViaEncodeHandler.encode(ViaEncodeHandler.java:62) ~[?:?]
> at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) ~[?:?]
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_73]
> at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_73]
> at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16) ~[?:?]
> at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.encode(NettyChannelInjector.java:490) ~[?:?]
> at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$3.encode(NettyChannelInjector.java:262) ~[?:?]
> at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[server.jar:git-PaperSpigot-7aa4900-62a2169]
> ... 14 more

I'm running BungeeCord by the way.

**Comment by checkplys** [comment]
#41

**Comment by Paulomart** [comment]
You are using an older version. I'm not sure the current master is published to spigot. But it fixes this problem.

**Comment by MylesIsCool** [comment]
Duplicate See #41
