### ISSUE TITLE
ViaVersion Bungeecord error

### ISSUE THREAD

**Issue by DuckCraftPvP** [MylesIsCool/ViaVersion#520]
### What is the output link of /viaversion dump?
http://hastebin.com/ahetiyohas.json

### How does this error happen? login? Using an item? 
Login

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/KWUy3E2C

**Comment by MylesIsCool** [comment]
As stated in the main plugin page the current release is not compatible with ProtocolSupport for 1.9.4.

We do have the 1.11 development build you can download from ci.viaversion.com but it's a dev build which would fix this issue. (As we later added compatibility)
