### ISSUE TITLE
ViaVersion List Color

### ISSUE THREAD

**Issue by InfinityAspire** [MylesIsCool/ViaVersion#521]
### What is the output link of /viaversion dump?
N/A

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
N/A

### How does this error happen? login? Using an item? 
Do /viaver list with a lot of players online.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
N/A

Simple issue, when doing /viaver list, using the bungee 1.11 build, lines after the first aren't colored; http://prntscr.com/cyeggr

**Comment by MylesIsCool** [comment]
Does this happen on the build if you use bukkit with same amount of players?

Seems very odd

**Comment by Matsv** [comment]
Should be fixed now. Thanks for reporting
