### ISSUE TITLE
ONLY 1.9 can join.

### ISSUE THREAD

**Issue by fiba1** [MylesIsCool/ViaVersion#523]
**### What is the output link of /viaversion dump?
http://hastebin.com/ocebatadim.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

BungeeCord version git:BungeeCord-Bootstrap:1.10-SNAPSHOT:18f57f2:1195 by md_5
(Latest)
CraftBukkit version git-Spigot-7d15d07-c194444 (MC: 1.9) (Implementing API version 1.9-SNAPSHOT)

I tested this with only ViaVersion installed, and it still didn't work, so, not an issue with any plugins.

### How does this error happen? login? Using an item? 

Triggered on login.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

Console.
Internal Exception: java.io.IOException: An established connection was aborted by the software in your host machine

Kick message.
Internal Exception: io.netty.handler.codec.DecoderExeption: java.IOException: Packet 0/32 (SPacketChunkData) was larger than I expected, found 61440 bytes extra whilst reading packet 32.

**Comment by MylesIsCool** [comment]
ViaVersion isn't compatible with CraftBukkit 1.9 (all the other ones seem to work from what we've tested) at this point in time.
Consider using proper Spigot / CB 1.9.1.
