### ISSUE TITLE
max-pps default is 600, docs say 800

### ISSUE THREAD

**Issue by ItsHarry** [MylesIsCool/ViaVersion#524]
Not a big deal, just thought I'd let you know the max-pps is set to 600 by default, while the docs say it's 800 by default: https://docs.viaversion.com/display/VIAVERSION/Configuration

In my opinion the config should also have 800 as default to prevent false kicks

**Comment by Matsv** [comment]
We changed it to 800 for the 1.11 update. We updated the docs too early. We thought it would be released by now. Sorry about that :)
