### ISSUE TITLE
(BungeeCord) InitialHandler - encountered exception

### ISSUE THREAD

**Issue by zedwick** [MylesIsCool/ViaVersion#526]
### What is the output link of /viaversion dump? 
http://hastebin.com/yoqociyolo.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
(running this on BungeeCord)

### How does this error happen? login? Using an item? 
I am not sure where the initial connection is coming from as the IP does not match any player who has previously connected, so cannot offer too much help

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/vZwia8hE
(real IP address changed to 0.0.0.0 in above paste)

**Comment by MylesIsCool** [comment]
I can't seem to replicate this at all.
I have tried with bungee testing different versions, 1.7.10, 1.7.4, 1.6, 1.5, 1.1, 1.0. I would assume it's just somebody sending bad data and nothing to worry about.

Does this happen often?

**Comment by zedwick** [comment]
Seem to be getting it at-least once an hour (sometimes a couple of times, but always around the same time). Repeatedly at 57 minutes past the hour, and sometimes on the hour.

I'd assume it's a server list pinging the server. Maybe on the old ping which I think bungee still supports?

**Comment by MylesIsCool** [comment]
@zedwick Well surely if it was old ping i'd be able to replicate it using an older version?

**Comment by zedwick** [comment]
Ah, the IP belongs to minecraft-index.com

**Comment by zedwick** [comment]
Actually, the other error I am seeing is not the same. Will make a new issue for that.

**Comment by MylesIsCool** [comment]
Am I able to close this issue? Realistically we can't really do anything if somebody is submitting bad data

**Comment by zedwick** [comment]
It would be nice to not have such a large error showing in the console 24+ times a day, so if you could do something to put a stop to that I'd be happy.

The server is still listed as 100% uptime so it's not causing me any issues beyond the log spam.

Feel free to close if you're done with it :)

**Comment by MylesIsCool** [comment]
@zedwick This kind of error would happen with bungee even if we patched it, the real solution is to ip block the other server.

We'll look into having a feature to suppress malformed packet errors, but at the end of the day if we suppressed this and mojang changed something in the future we'd have no idea.
