### ISSUE TITLE
ViaBackwards - Chunk Issue

### ISSUE THREAD

**Issue by Liluch** [MylesIsCool/ViaVersion#527]
### What is the output link of /viaversion dump? 
http://hastebin.com/qofikecato.json

### Is there an error in the console? Use pastebin.com. Is there a kick message?
13.11 20:16:12 [Server] INFO Actual Error: 
13.11 20:16:12 [Server] INFO {Type: Chunk, Source #1: nl.matsv.viabackwards.protocol.protocol1_9_4to1_10.packets.BlockItemPackets$7 (Anonymous), Source #0: nl.matsv.viabackwards.protocol.protocol1_9_4to1_10.packets.BlockItemPackets$7$1 (Anonymous), Data: [], Packet ID: 32}
13.11 20:16:12 [Disconnect] User danuxx has disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/MylesIsCool/ViaVersion/issues

**Comment by Matsv** [comment]
Could you change debug=true in server.properties and paste the full error on pastebin?

**Comment by Matsv** [comment]
Could you change debug=true in server.properties and paste the full error on pastebin?

**Comment by MylesIsCool** [comment]
It's worth noting this is an issue potentially with ViaBackwads given the error.
It should be considered being posted on Mats GitHub https://github.com/Matsv/ViaBackwards/, with debug=true as Mats asked above :)

**Comment by Matsv** [comment]
Please update your ViaBackwards to the latest version, ask a reopen if it still occurs.

**Comment by Liluch** [comment]
New error:
 [Disconnect] User danuxx has disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NoSuchMethodError: us.myles.ViaVersion.protocols.protocol1_9_3to1_9_1_2.storage.ClientWorld.getEnvironment()Lorg/bukkit/World$Environment;
