### ISSUE TITLE
us.myles.viaversion.libs.gson.JsonSyntaxException: Expected a us.myles.viaversion.libs.gson.JsonObject but was us.myles.viaversion.libs.gson.JsonNull

### ISSUE THREAD

**Issue by zedwick** [MylesIsCool/ViaVersion#528]
### What is the output link of /viaversion dump? 
http://hastebin.com/nokazagura.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Running viaversion on bungeeCord

### How does this error happen? login? Using an item? 
Seems to occur on "InitialHandler has connected"

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/1KHAdcyR
IP has been changed to 0.0.0.0 in the above paste, however I believe it belongs to minecraft-mp.com

**Comment by MylesIsCool** [comment]
Should fix this :)
