### ISSUE TITLE
ViaVersion 1.10 to 1.11 Title Issue

### ISSUE THREAD

**Issue by Jalau11** [MylesIsCool/ViaVersion#529]
### What is the output link of /viaversion dump? 
http://hastebin.com/opiwizewax.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord, MysticBungee (Own plugin, should not interfer)

### How does this error happen? login? Using an item? 
Sending titles to a 1.11 version client causes this error to show.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Client kick message: : Packet 0/69 (ie) was larger than I expected, found 11 bytes extra whilst reading packet 69

No console errors :)

**Comment by Jalau11** [comment]
Found the packet that is causing the issue: new PacketPlayOutTitle(EnumTitleAction.TIMES, titleJSON, fadeIn, stay, fadeOut);
 Seems like it is no longer needed anyways but it didn't cause any error before so you should either cancel it or modify it.

**Comment by Matsv** [comment]
Please remove ViaVersion from your spigot server and only use it as Bungee plugin. This issue is probably caused because your Title plugin is not updated yet to 1.11. ViaVersion will handle it if you use the Bungee edition
