### ISSUE TITLE
Kicked for longer chat messages

### ISSUE THREAD

**Issue by TitanicFreak** [MylesIsCool/ViaVersion#530]
### What is the output link of /viaversion dump? 
http://hastebin.com/obonudiqen.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
GoLilyPad, about it.

### How does this error happen? login? Using an item? 
1.11 apparently changed how long chat messages can be. They can be up to 256 characters now from the looks of it. However ViaVersion doesn't seem to actually handle that well as it just kicks you from the server if you try putting a 256 character message in chat.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
There is an error, a generic one. But hey why not include it. http://hastebin.com/kagebipeju.css

**Comment by MylesIsCool** [comment]
Fixed in latest dev build, will be released tomorrow most likely
