### ISSUE TITLE
ViaVersion bug 1.0.0

### ISSUE THREAD

**Issue by VBeekDev** [MylesIsCool/ViaVersion#531]
### What is the output link of /viaversion dump? 
You are not allowed to use this commands

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I use viaversion 1.0.0 with bungeecord
Other bungee plugins: Bungeetablistplus, stafflist, buycraft, EasySetSpawn and liteannouncer

### How does this error happen? login? Using an item? 

When I am on a random realm on my network (1.11 on 1.8 server) and go to another i got kicked with an error.
https://gyazo.com/59c39adfe1f8a0a5dd86f72da96ce7af

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No

**Comment by MiniDigger** [comment]
@VBeekDev enter the /viaversion dump command in the console so you have the permissions for it ;)

**Comment by VBeekDev** [comment]
console /viaversion info: https://gyazo.com/42b52e10f9f931bdac50ccd643c3714a

**Comment by Matsv** [comment]
Please execute /viaversion dump

**Comment by VBeekDev** [comment]
http://hastebin.com/xavikafabo.json

**Comment by Matsv** [comment]
Do you use ViaBackwards on your server?

**Comment by jiongjionger** [comment]
same issue with PaperSpigot 1.10.2 and Bungeecord(1.11)

img: http://ww1.sinaimg.cn/large/0060lm7Tgw1f9s73uwafnj310g04dmzk.jpg
dump: http://hastebin.com/yafaluwike.json

I tried to remove ProtocolSupport, it still appears such errors, 1.11 can not join the game

**Comment by MylesIsCool** [comment]
What plugins do you use on your spigot server where the error occurs?

**Comment by MylesIsCool** [comment]
Could you try without Bungeetablistplus? and see what happens?

**Comment by MylesIsCool** [comment]
This is an issue in BungeeCord with item pickup, hopefully will be fixed soon. Alternative is to use 1 build behind bungee + ViaVersion for Bungee
