### ISSUE TITLE
Players can't join with 1.11

### ISSUE THREAD

**Issue by Sckaletz** [MylesIsCool/ViaVersion#533]
### What is the output link of /viaversion dump? 
http://hastebin.com/cosukusove.json%3E

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Using latest Bungeecord: git:BungeeCord-Bootstrap:1.11-SNAPSHOT:9ecdde2:1200
The error is shown in Bungee console when someone is trying to connect with 1.11: http://pastebin.com/Hu6FF83y

### How does this error happen? login? Using an item? 
When players try to join with 1.11

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Only error is shown on Bungeecord. No errors on spigot 1.8.8 servers

**Comment by Matsv** [comment]
Could you try to use ViaVersion as Bungee plugin and remove it on your Spigot servers?

**Comment by MylesIsCool** [comment]
This is an issue with BungeeCord, hopefully will be fixed soon. Alternative is rolling back your BungeeCord by 1 version and using ViaVersion on the BungeeCord.

**Comment by Sckaletz** [comment]
I just removed Viaversion from all my spigot 1.8.8 servers and only added it to my Bungeecord 1.11 and now everything works without issues :D
