### ISSUE TITLE
Villagers with no trades.

### ISSUE THREAD

**Issue by nicuch** [MylesIsCool/ViaVersion#534]
### What is the output link of /viaversion dump? 
http://hastebin.com/efubirogak.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No.

### How does this error happen? login? Using an item? 
Villagers have no trades.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No.

**Comment by jordanwilliams1** [comment]
Was just about to report this ^^

**Comment by Lmmb74** [comment]
Every villager or just a bunch?

**Comment by MylesIsCool** [comment]
Fixed in latest dev build
