### ISSUE TITLE
Bungee Version: Signs don't load properly

### ISSUE THREAD

**Issue by Esmorall** [MylesIsCool/ViaVersion#535]
I use the plugin on bungee-side

### What is the output link of /viaversion dump? 
http://hastebin.com/exezofeyiy.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Lastest version of bungeecord

### How does this error happen? login? Using an item? 
If i join using 1.11 on 1.8 servers, the text on the signs take time to load

### Is there an error in the console? Use pastebin.com. Is there a kick message?
there are any errors

**Comment by Matsv** [comment]
> What is the output link of /viaversion dump?

Please follow the issue template

**Comment by Esmorall** [comment]
Ready

**Comment by Esmorall** [comment]
![image](https://cloud.githubusercontent.com/assets/23460760/20278296/884f8a22-aa7a-11e6-9ffa-54e63e8af05f.png)
there is supossed to be the rules, but text doesnt load

**Comment by Matsv** [comment]
Could you list your Spigot plugins on that server?

**Comment by Esmorall** [comment]
it happens in all of my servers, this is the server with less plugins
![image](https://cloud.githubusercontent.com/assets/23460760/20278988/2ac47752-aa7d-11e6-9c02-5baf99cfd6c4.png)
but still happening
even if i put a new sign and rejoin

**Comment by Esmorall** [comment]
![image](https://cloud.githubusercontent.com/assets/23460760/20279128/a35087e2-aa7d-11e6-9934-3ada77b357c2.png)
but if i wait some of them loads
![image](https://cloud.githubusercontent.com/assets/23460760/20279111/99f4b83a-aa7d-11e6-8207-dcc93ec3ddd7.png)
Sometimes their load but not all

**Comment by mcraftpete** [comment]
Hi,
I have same issue , mine appears to be signs and spawners , at minute it seems to be affecting 1.9 players , i am to confirm 1.11 as well.
I am also using just the bungee plugin and with the local spigot ones diabled , i did however update my bungee to todays version.

**Comment by Matsv** [comment]
@mcraftpete could you also give your /viaversion dump output

**Comment by mcraftpete** [comment]
sure yes its here ... http://hastebin.com/imumucocix.json

**Comment by MylesIsCool** [comment]
I've looked at this issue myself and I want to say it's something to do with packet order?

The data is sent from what I can see.

(Just updating with further info, incase anyone else wants to take a look)

**Comment by Matsv** [comment]
@Esmorall Could you try if this build solves your issue? https://fs.matsv.nl/files/ViaVersion-1.0.1.jar

**Comment by Matsv** [comment]
Myles confirmed it working, please ask for a reopen if you still experience this issue.
