### ISSUE TITLE
Hands are switched (main hand at the left)

### ISSUE THREAD

**Issue by smessie** [MylesIsCool/ViaVersion#537]
### What is the output link of /viaversion dump? 
http://hastebin.com/wehuwarohu.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Running on bungeecord, you can see the other plugins on the dump file

### How does this error happen? login? Using an item? 
Whole the time

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Nope

Matsv had looked to it on my server.
You can disable the bug by going to options>skin customization.

http://i.smessie.tk/v92f9dqdoP.png
http://i.smessie.tk/8bSF8iRZPf.png

**Comment by Matsv** [comment]
Already opened one, please follow #536. :)

Thanks for your help with testing.
