### ISSUE TITLE
guardian farms (possible mob spawns?)

### ISSUE THREAD

**Issue by jordanwilliams1** [MylesIsCool/ViaVersion#539]
Put the latest version of ViaVerison in and it seems to be effecting mob spawns. guardian farms seems to be not working a lot of the time then they work for a few mins then just completely stop. Seems to be only effecting guardian farms but could also be effecting all mob spawns.

**Comment by Matsv** [comment]
We only touch Spigot at packet level, this is not caused by ViaVersion.
