### ISSUE TITLE
Small Feature Request

### ISSUE THREAD

**Issue by YugieDev** [MylesIsCool/ViaVersion#540]
When you do the command /viaver list could you have it so it shows the number of players next to it because it would be a nice small feature to add :)

**Example**
[1.11] (3): Notch, Jeb, Jeb_
[1.10] (2): Yugie, Myles

So it counts the number of the players that are using the version and puts the amount next to it. Just think it would be a nice addition :)

**Comment by MylesIsCool** [comment]
Definitely something that would be nice

**Comment by MylesIsCool** [comment]
In latest dev build :)
