### ISSUE TITLE
Crash upon item pickup

### ISSUE THREAD

**Issue by jordanwilliams1** [MylesIsCool/ViaVersion#541]
### What is the output link of /viaversion dump? 
http://hastebin.com/inumosipor.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yes, Bungee cord latest

### How does this error happen? login? Using an item? 
Drop a item, Pick it up. Get sent back to the hub because "the previous server went down"
https://youtu.be/DOJdfzZYtUk

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Also dropped the item in the hub and got kicked with a error message:
https://i.gyazo.com/56e9465d8cdb637487f29fcfbea4fd53.png

**Comment by MylesIsCool** [comment]
Use latest BungeeCord (just released)
