### ISSUE TITLE
Issue with 1.11 clients joining

### ISSUE THREAD

**Issue by Invectix** [MylesIsCool/ViaVersion#542]
### What is the output link of /viaversion dump? 
http://hastebin.com/ejamebijef.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord build no. 1200
using plugins:
BuycraftX
BungeeKick
BungeeMsg
ServerListPlus
SlashServer

### How does this error happen? login? Using an item? 
When logging in.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://gyazo.com/193e20563a2b3ca17fdd3afbf77a7b09

**Comment by MylesIsCool** [comment]
Update to latest BungeeCord, they literally just fixed it :)
