### ISSUE TITLE
Sign text sometimes disappears from signs on 1.11

### ISSUE THREAD

**Issue by Wazez** [MylesIsCool/ViaVersion#543]
Sign text sometimes disappears from signs when using 1.11.

Viaversion build 102
https://ci.viaversion.com/job/ViaVersion/102/

No error in console or login. Sign functionality still works (e.g essentials buy/kit signs)
Sometimes when re-logging the text reappears, sometimes other signs don't show sign text.

**MC client version 1.8**
![image](https://cloud.githubusercontent.com/assets/5465426/20284107/e2ad662a-ab0f-11e6-87af-344b7a33ccc9.png)

**Mc client version 1.11**
![image](https://cloud.githubusercontent.com/assets/5465426/20284117/e89fd162-ab0f-11e6-83ca-98f38e658f8e.png)

Tested with both cases of Viaversion under /BungeeCord/plugins and /server/plugins.

**Comment by MylesIsCool** [comment]
Consider reading issues before reporting,

This is a duplicate, if you only run ViaVersion on spigot server and not on bungee this will not happen (makesure you use latest bungee though).
