### ISSUE TITLE
DecoderException on login with 1.11

### ISSUE THREAD

**Issue by minoneer** [MylesIsCool/ViaVersion#544]
### What is the output link of /viaversion dump? 
http://hastebin.com/ofofobebeq.sm

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:9ecdde2:1200 by md_5
More then120 Plugins, about half custom made, not going to list all of them here. If certain plugins are of interest, I'm happy to provide details.

### How does this error happen? login? Using an item? 
The error appears as "Connection Lost" in the client GUI (see attached screenshot). No errors in Spigot, Bungee or Client Logs.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No error messages

![2016-11-14_23 05 46](https://cloud.githubusercontent.com/assets/6442649/20284812/1ceb406a-aabf-11e6-9395-c827499abaa5.png)

**Comment by MylesIsCool** [comment]
Update BungeeCord

**Comment by minoneer** [comment]
Thanks, missed those updates, sorry to bother you. Fixed the issue.

**Comment by MylesIsCool** [comment]
@minoneer np, they just came out :)
