### ISSUE TITLE
I get this console error on bungeecord

### ISSUE THREAD

**Issue by Esmorall** [MylesIsCool/ViaVersion#546]
### What is the output link of /viaversion dump? 
http://hastebin.com/wugadinopi.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I am using the lastest version of bungeecord 1​20​4 and Via Version 1.0.0 installed just on bungee side

### How does this error happen? login? Using an item? 
This happen everytime in the console, sometimes kicking players!!

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/1vfXbsPc
and this:
http://pastebin.com/BcSWMmuZ

**Comment by Esmorall** [comment]
also this error http://pastebin.com/BcSWMmuZ

**Comment by MylesIsCool** [comment]
Should be fixed in the latest dev build, just patched.
