### ISSUE TITLE
[CLOSE]1.11 BUG with ProtocolSupport in Spigot 1.10

### ISSUE THREAD

**Issue by GabrielAugustoTI** [MylesIsCool/ViaVersion#547]
### What is the output link of /viaversion dump? 
 http://hastebin.com/udiwopuneg.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord (fork from HexagonMC, latest version, fork only adds 1.7 compatibility)

### How does this error happen? login? Using an item? 
On join BungeeCord with 1.11 says "Timed out" and ping is not showing.
Viaversion is installed with bungee.
Bungee is ping_passthrough: true

**Comment by GabrielAugustoTI** [comment]
Bungee connect says nothing in console!

**Comment by MylesIsCool** [comment]
Could you provide the log of your BungeeCord to hastebin.com? (From startup to trying to connect)

**Comment by GabrielAugustoTI** [comment]
http://hastebin.com/usimunipon.pas Nothing says when i try connect!

**Comment by GabrielAugustoTI** [comment]
Only Timed out...

**Comment by GabrielAugustoTI** [comment]
You can test: play.satoshicraft.com
1.10->1.7 works, 1.11 not works

**Comment by GabrielAugustoTI** [comment]
And only bukkit works, but i don't can players connect only in spigot
play.satoshicraft.com:25560

**Comment by GabrielAugustoTI** [comment]
https://github.com/SpigotMC/BungeeCord/issues/1996

**Comment by GabrielAugustoTI** [comment]
Build 1.0.1 FIXED! Thanks!
