### ISSUE TITLE
Armor Stand / Companion Issue

### ISSUE THREAD

**Issue by alexmarkey** [MylesIsCool/ViaVersion#548]
### What is the output link of /viaversion dump? 

http://hastebin.com/jifumoqasu.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

LilyPad

### How does this error happen? login? Using an item? 

We sell Companions on our server, which are little animals made of Armor stands - http://prntscr.com/d7d1b0 

Build 1.0.0 seems to have broken them on clients 1.9+.  Here is all of the information that I have found out:

- Companion with the hologram patch on (1.11) - http://prntscr.com/d7cxmg , Companion with the patch off (1.11) - http://prntscr.com/d7cy48 , Does not seem to be the patch affecting / breaking them?

- Using Viaversion 0.9.9 and a 1.10.2 client the Companion is not broken and is working as expected - http://prntscr.com/d7cyyh, ViaVer 1.0.0 seems to have broken them

- This is what the companion looks like in 1.10.2 on ViaVersion 1.0.0 - http://prntscr.com/d7d0ek

**Comment by alexmarkey** [comment]
I believe something may have changed with armor stands in 1.11 since the Hologram Patch is no longer necessary in 1.11 (Disabling the patch has all our holograms in their correct positions)

**Comment by MylesIsCool** [comment]
"Just to update on this issue,

From what we've found you're possibly using a bad id for armour stands which causes this issue and also causes our system not to shift your armour stands (the issues are the same).

From our tests armour stands should be spawned on 1.8 with a Spawn Object packet with the id 78. For some reason you're using id 30? Which is actually a entity id and not an object id."

**Comment by MylesIsCool** [comment]
I'm going to close this as I'm in firm belief this is a plugin error, if it still occurs after you get it sorted (tested with proper ids) ask for reopen :)
