### ISSUE TITLE
Console being flooded

### ISSUE THREAD

**Issue by alexmarkey** [MylesIsCool/ViaVersion#549]
### What is the output link of /viaversion dump? 

http://hastebin.com/avohufaxon.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

LilyPad

### How does this error happen? login? Using an item? 

Console on almost all servers on our network are being flooded with the following message - http://prntscr.com/d7e6sh

### Is there an error in the console? Use pastebin.com. Is there a kick message?

http://pastebin.com/Kas2tyRf

**Comment by MylesIsCool** [comment]
Just to update on this issue,

From what we've found you're possibly using a bad id for armour stands which causes this issue and also causes our system not to shift your armour stands (the issues are the same).

From our tests armour stands should be spawned on 1.8 with a Spawn Object packet with the id 78. For some reason you're using id 30? Which is actually a entity id and not an object id.

**Comment by MylesIsCool** [comment]
Gonna move this to #548 as same issue.
