### ISSUE TITLE
Resource pack bug??

### ISSUE THREAD

**Issue by timr2000** [MylesIsCool/ViaVersion#55]
i've got a custom resource pack.. but euhh it's a little bit buggy, it makes my items in my hand really big :p idk what that is.. http://imgur.com/IMW4AM7

**Comment by MylesIsCool** [comment]
we can't fix this sadly, the way they are formatted changed but it looks hilarious haha

**Comment by timr2000** [comment]
It's not a really big problem XD and yes it looks hilarious :P
