### ISSUE TITLE
Health regen error [Spigot 1.8.8 + BungeeCord]

### ISSUE THREAD

**Issue by ssamjh** [MylesIsCool/ViaVersion#551]
### What is the output link of /viaversion dump? 
http://hastebin.com/ipagopulec.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord

### How does this error happen? login? Using an item? 
If a player eats food, on a 1.8.8 server with BungeeCord (that has via version installed on it) player will regen health too fast and be kicked by the anticheat.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Nope

**Comment by ssamjh** [comment]
I have just noticed that if ViaVersion is installed on the server itself, it is fine. So the issue only occurs when ViaVersion is running on BungeeCord alone.

**Comment by Matsv** [comment]
The stimulate-pt timing might be wrong on bungee, will look into it when I'm back home.

**Comment by MylesIsCool** [comment]
Could you provide the anticheat you are using? (NoCheatPlus?)

**Comment by ssamjh** [comment]
AAC, let me know if you need any more info, this report was sort of rushed, sorry

**Comment by ssamjh** [comment]
Also, I do use ViaBackwards on the same BungeeCord instance if that makes any difference.

**Comment by Esmorall** [comment]
Also my players reported to me a bug with the health regeneration, but im not sure if its related to viaversion, but it starts happen after i installed it

**Comment by MylesIsCool** [comment]
I don't own a copy of AAC, I've attempted to replicate this with NoCheatPlus as it has this kind of check and cannot replicate it.

Are you able to provide more info about how much we're violating this check?

And is it possible to edit the AAC config so it does not trigger but still gets people with hacks?

**Comment by R4G3-BABY** [comment]
I can confirm this it happens in my server to.

**Comment by MylesIsCool** [comment]
I don't think there is an easy solution to this due to network latency, the best solution is just using the bukkit version unfortunately.
