### ISSUE TITLE
Signs blank and Skulls default to skeleton

### ISSUE THREAD

**Issue by ssamjh** [MylesIsCool/ViaVersion#552]
### What is the output link of /viaversion dump? 
http://hastebin.com/ipagopulec.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord (same setup as my other issue)
https://github.com/MylesIsCool/ViaVersion/issues/551

### How does this error happen? login? Using an item? 
With a Spigot 1.8.8 server with ViaVersion and ViaBackwards running on a BungeeCord server, signs and skulls seem to break. Fixed this and the health regen issue by running ViaVersion on Spigot itself.

**Comment by MylesIsCool** [comment]
This is exactly the same as #535.
