### ISSUE TITLE
Inventory bug with 0 amount of item

### ISSUE THREAD

**Issue by tade159SK** [MylesIsCool/ViaVersion#553]
Hi, on our network we have a problem, that in inventory that is showing servers with players (Quantity of Item)
Item with amount o 0 (zero) is not showing in inventory in Client 1.11 and Server 1.8.8
We are using latest ViaVersion

**Comment by tade159SK** [comment]
Screen from 1.11 Client: https://ctrlv.cz/shots/2016/11/15/WojX.png

**Comment by MylesIsCool** [comment]
Could you test this with 1.11 (not really sure how)?

I suspect Mojang has removed items with 0 amount.

**Comment by tade159SK** [comment]
Screen from 1.11 Client: https://ctrlv.cz/shots/2016/11/15/WojX.png
Screen from 1.8.9 Client: https://ctrlv.cz/shots/2016/11/15/ScNe.png

**Comment by MylesIsCool** [comment]
Could you test this with 1.11 (vanilla server)?

This isn't a bug if mojang removed it.

**Comment by tade159SK** [comment]
This can't be tested with vanilla server, because this Inventory is in plugin

**Comment by MylesIsCool** [comment]
If you can't replicate it in vanilla, mojang probably removed it

**Comment by MylesIsCool** [comment]
Closing as this honestly can't be fixed if mojang removed it.
