### ISSUE TITLE
Title Message

### ISSUE THREAD

**Issue by MCArcadeX** [MylesIsCool/ViaVersion#554]
We run a big minecraft network, and its about 800 players online, we got an error with viaversion, we run viaversion on the spigot servers, but the players are being disconnected when they get a title message (text in the middle of the screen, basically titlemanager). Are it fixed if we run the plugin on the bungeecord instead of the spigot servers, or is it a bug with the plugin?

We run latest 1.0.0

**Comment by MylesIsCool** [comment]
You need to update BungeeCord, also consider donating if you enjoy our plugin :)
