### ISSUE TITLE
Switching servers whilst using Elytra

### ISSUE THREAD

**Issue by Venlious** [MylesIsCool/ViaVersion#555]
### What is the output link of /viaversion dump? 
http://hastebin.com/ufaseruvaj.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord 1200. I'll supply a plugin list if error can't be repeated. I'm also running the ViaVersion on the BungeeCord, not on the Spigot.

### How does this error happen? login? Using an item? 
I accidentally stumbled upon it by switching from a 1.10 server to a 1.8 server whilst flying in the air with an elytra. I've recorded what happens so you may see for yourself.

The error does not happen if you switch from a 1.10 server to another 1.10 server. I'm not sure if the same happens with switching between a 1.10 server to 1.9 or 1.9 to 1.8.

https://www.youtube.com/watch?v=4urSJRy9dNQ

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No error appears in the console, nor is a kick issued.

**Comment by Matsv** [comment]
Should be fixed next version.

Could you test the latest devbuild if it's also fixed for you?
https://ci.viaversion.com/job/ViaVersion/

**Comment by Venlious** [comment]
Latest version fixes the issue. Thank you kindly!
