### ISSUE TITLE
Creative inventory Issue

### ISSUE THREAD

**Issue by Nev3rGiveUp** [MylesIsCool/ViaVersion#556]
### What is the output link of /viaversion dump? 
http://hastebin.com/ikotuladuf.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
My plugins doesn't really matter since this is an inventory bug and I don't have any inventory modifying plugins.

### How does this error happen? login? Using an item? 
I am using ViaVersion on my 1.8.8 server. When I join from version 1.11 and I open my creative inventory , when I click Left Shift + the red X in the inventory (removes all items) it kicks me with a message "Disconnected". It's not a big issue but I hope I helped to improve this awesome plugin! Keep up the good work!

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No error.
![screenshot_1](https://cloud.githubusercontent.com/assets/17798518/20321106/eb01484c-ab7c-11e6-9f18-ec6d837efb09.png)

**Comment by Matsv** [comment]
Could you enable debug in server.properties and give us the full error?

**Comment by Nev3rGiveUp** [comment]
Sure , can't really do it right now. I will paste it tomorrow :)

**Comment by MylesIsCool** [comment]
This is fixed in latest dev build will be released tomorrow.

Alternatively download from ci.viaversion.com
