### ISSUE TITLE
Cannot load the plugin #latest version 1.0.0

### ISSUE THREAD

**Issue by flipper1406** [MylesIsCool/ViaVersion#557]
### What is the output link of /viaversion dump? 
https://www.spigotmc.org/resources/viaversion.19254/history

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
i tried to install the plugin like the other version on an spigot server running on 1.8 with Java 8.
No new plugins additionaly to the working older version, so i left them out.

### How does this error happen? login? Using an item? 

right by the start of my server

### Is there an error in the console? Use pastebin.com. Is there a kick message?

Could not load 'plugins/ViaVersion-1.0.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml

**Comment by flipper1406** [comment]
#edit:
the older version I used was the version 0.9.7 and there it worked

**Comment by electronicboy** [comment]
I would suggest providing the full error, It's most likely a case that you uploaded a corrupt jar to your server

**Comment by MylesIsCool** [comment]
You probably some how downloaded a corrupted jar file :( just redownload http://ci.viaversion.com/job/ViaVersion/98/artifact/jar/target/ViaVersion-1.0.0.jar
