### ISSUE TITLE
Error spaming on bungeecord

### ISSUE THREAD

**Issue by Esmorall** [MylesIsCool/ViaVersion#559]
### What is the output link of /viaversion dump? 
http://hastebin.com/exezofeyiy.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
i am using the lastest dev build of viaversion, and the lastest bungeecord 1205

### How does this error happen? login? Using an item? 
Is spaming everytime on bungeecord

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/5TLFrXPX

players get kicked with the message "Timed Out"

**Comment by Matsv** [comment]
Could you try the latest devbuild? http://ci.viaversion.com/job/ViaVersion/

**Comment by Esmorall** [comment]
of course, just released!

**Comment by Esmorall** [comment]
at the moment, there is any errors, thanks :D
