### ISSUE TITLE
Please fix!

### ISSUE THREAD

**Issue by AdinSk** [MylesIsCool/ViaVersion#560]
https://ctrlv.cz/shots/2016/11/16/nHe4.png

**Comment by Matsv** [comment]
Please follow the issue template. https://github.com/MylesIsCool/ViaVersion/blob/master/ISSUE_TEMPLATE.md

**Comment by AdinSk** [comment]
http://hastebin.com/juhebiqovu.json

**Comment by MylesIsCool** [comment]
Fill in the full template and provide full details thanks.

**Comment by MylesIsCool** [comment]
If you want this fixed,

Provide console logs + Possibly enable debug=true in server.properties and replicate and give the full error.

Otherwise the issue will just be closed as we can't replicate.

**Comment by Matsv** [comment]
Closing because you didn't respond. Please ask for a reopen when you are able to provide us the information we need.
