### ISSUE TITLE
Rarely client crashes (properly potion items)

### ISSUE THREAD

**Issue by Black-Hole** [MylesIsCool/ViaVersion#561]
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
1.11 client connecting to ViaVersion 1.0.1 Snapshot Build 115 running on BungeeCord 1.10. Minecraft servers are at 1.10.2, no plugin that manipulates packets.

### How does this error happen? login? Using an item? 
rarely, no client action required

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/FJM9Wcra

**Comment by MylesIsCool** [comment]
Could you try latest snapshot build 117?

**Comment by Black-Hole** [comment]
I will try on our test server, but since it happens rarely, it could take until tomorrow when the plugin will will updated on the production server to get feedback from more users.

**Comment by MylesIsCool** [comment]
Any updates concerning this?

**Comment by Black-Hole** [comment]
Yes, no more crashes of that kind. Some with pistons, I'll look if there is an issue for that already.
