### ISSUE TITLE
Eggs losing color

### ISSUE THREAD

**Issue by PhanaticD** [MylesIsCool/ViaVersion#563]
### What is the output link of /viaversion dump? 
http://hastebin.com/erorezayap.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I am using waterfall

### How does this error happen? login? Using an item? 
the issue is that on 1.11 mob eggs appear white, on 1.10 they are normal colored

### Is there an error in the console? Use pastebin.com. Is there a kick message?
nope

**Comment by Matsv** [comment]
Is this for all the eggs or just the one that got added in 1.11?

**Comment by Matsv** [comment]
Do you mean the mob eggs that were introduced in 1.11? 
We don't support new blocks/mobs/items. Things that didn't exist in 1.10 also won't work in 1.11.

**Comment by PhanaticD** [comment]
no

**Comment by Lmmb74** [comment]
You mean common spawn eggs turn into white like if they had a wrong entity to spawn, right? That happened to me when I tried to use nbttags to create a custom one for spawning primed tnt xD. But that happens to you with the normal ones I guess, right?

**Comment by MylesIsCool** [comment]
As per request on IRC a while back closing as can't be replicated, if anyone knows how to replicate with correct nbt for specific server version do ask for reopen.
