### ISSUE TITLE
Hologram lowered when riding an item

### ISSUE THREAD

**Issue by alexmarkey** [MylesIsCool/ViaVersion#564]
### What is the output link of /viaversion dump? 

http://hastebin.com/qiwezakiku.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

LilyPad

### How does this error happen? login? Using an item? 

Using Crates on our servers to reward our users using a fancy animation, when the chest opens it displays a hologram with an item entity below it (Using HolographicDisplays API for this).  This is the desired outcome - http://prntscr.com/d87iix
The outcome above we get on 1.8 1.9 and 1.10

On 1.11 we get the outcome below
http://prntscr.com/d87hvr
As you can see inside the enderchest is the item entity, being Lowered

### Is there an error in the console? Use pastebin.com. Is there a kick message?

N/A

**Comment by MylesIsCool** [comment]
Is the item sitting on a hologram itself?

Are all other holograms not involving items at the right height?

**Comment by CT16** [comment]
> EDIT: enabling hologram-patch in the ViaVersion config might solve your problem.

Doesn't do anything for 1.11. Only breaks it for 1.10, where there's no issue.

**Comment by Matsv** [comment]
@CT16 this issue is not yet solved, we still have to reproduce/patch it.

**Comment by alexmarkey** [comment]
All other holograms not involving items are at the right height,
I believe the item is sitting on a hologram (I can send you the plugin via skype if required)

**Comment by TheIntelloBox** [comment]
When is it fixed ?

**Comment by linkinkov** [comment]
I can confirm it. All plugins that use ArmorStand to view text or items - lowered (1.11.2)

**Comment by MylesIsCool** [comment]
After several attempts, it isn't really possible to get this working without displacing the other holograms. This is really a can't fix issue without causing problems for the height of other holograms or black gitchyness.
