### ISSUE TITLE
Hand is still inverted after joining a 1.10 server that runs protocolsupport (and stays that way when when joining 1.8 servers without protocolsupport)

### ISSUE THREAD

**Issue by cloakfox** [MylesIsCool/ViaVersion#565]
### What is the output link of /viaversion dump? 
Havent setup the perms yet for bungee lol.

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I am using viaversion with bungeecord together.
Bungee plugins: http://imgur.com/a/yjjx3

### How does this error happen? login? Using an item? 
When joining the network your hand looks fine, but as soon as you join for example kitpvp, anarchy, fcove. Your hand get's inverted and is suddenly on the left side. It stays this way untill you disconnect.
http://imgur.com/a/0hSnr

### Is there an error in the console? Use pastebin.com. Is there a kick message?
There are no errors in console.

**Comment by cloakfox** [comment]
This only happens on 1.11!

**Comment by cloakfox** [comment]
Nevermind also happens on 1.10

**Comment by cloakfox** [comment]
Saw an error pop up too, not sure what it is exacly and if it's viaversion related.
http://pastebin.com/7R1Frfw6

**Comment by Matsv** [comment]
Please provide us with the /ViaVersion dump output.

**Comment by MylesIsCool** [comment]
If anyone can provide more details on this issue, please post & we'll reopen.
