### ISSUE TITLE
Unable to join a 1.11 server when on 1.11 (using BungeeCord and viaversion 1.0.1)

### ISSUE THREAD

**Issue by cloakfox** [MylesIsCool/ViaVersion#566]
### What is the output link of /viaversion dump? 
NaN

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

I am using viaversion with bungeecord together.
Bungee plugins: http://imgur.com/a/yjjx3

### How does this error happen? login? Using an item? 
When I try to join a test server thats on 1.11, I am unable to join. I get disconnected from the entire network and am unable to reconnect.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Couldnt find any, but should be pretty easy to reproduce one.
Simply use a bungeecord proxy together with latest ViaVersion 1.0.1, and try to join a 1.11 spigot server through that.

**Comment by MylesIsCool** [comment]
Provide full information, use /viaver dump on console.

**Comment by cloakfox** [comment]
I havent setup any perms for it yet, and I don't want to restart my whole proxy/network for it. It takes less then 5 minutes to set it up ony our own side.

**Comment by Matsv** [comment]
It's also executeable from the console

**Comment by cloakfox** [comment]
here is the output: http://hastebin.com/ilozekezik.json

**Comment by MylesIsCool** [comment]
All your backend servers are marked as less than 1.10, use /viaver probe / wait for it to refresh. And it will work.
