### ISSUE TITLE
Packet 0/72 (ii) was larger than expected, 368 extra bytes whilst reading packet 72

### ISSUE THREAD

**Issue by shawlaf** [MylesIsCool/ViaVersion#568]
### What is the output link of /viaversion dump? 

http://hastebin.com/cikapileza.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

We are running bungeecord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:9ecdde2:1200

The plugins running are the necessary (custom coded) proxy plugins required for our network and buycraft's bungee version

### How does this error happen? login? Using an item? 

Whenever someone tries to connect using 1.11

### Is there an error in the console? Use pastebin.com. Is there a kick message?

No stacktraces in console, login screen: http://prntscr.com/d8w8mx
Ingame world is visible for a split second until player is disconnected

**Comment by shawlaf** [comment]
I can give more detail about the join listener of our server side plugin if necessary, I need to leave not to will begin back in about 2 hours

**Comment by MylesIsCool** [comment]
Update BungeeCord.
