### ISSUE TITLE
Big error.

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#569]
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Nop.

### How does this error happen? login? Using an item? 

ALWAYS. EACH SECOND.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.
All players are disconnected.

**Comment by MylesIsCool** [comment]
Could you enable debug=true in server.properties and give us the console log output after?

**Comment by Matsv** [comment]
Please enable debug in server.properties and give us the full error

**Comment by TheIntelloBox** [comment]
http://hastebin.com/lohipowana.md

**Comment by TheIntelloBox** [comment]
This is very very important, all of my players are disconnected.

**Comment by MylesIsCool** [comment]
Have you tried redownloading ViaVersion / rebooting your server?

**Comment by TheIntelloBox** [comment]
Yes, this changes nothing.

**Comment by MylesIsCool** [comment]
Could you post your startup log?

From the errors it looks like ViaVersion has an issue loading.

**Comment by TheIntelloBox** [comment]
I can't, it is spamming my console with the same error at each reload.

**Comment by TheIntelloBox** [comment]
http://pastebin.com/xUrfXFYX
Here.

**Comment by TheIntelloBox** [comment]
Up !

**Comment by Matsv** [comment]
Could you provide the startup log for us? You can get it in the latest.log file.

Also, please note that this is a free plugin, we are not 27/7 available to provide support.

**Comment by TheIntelloBox** [comment]
With debug or no ?

**Comment by Matsv** [comment]
Yes

**Comment by TheIntelloBox** [comment]
There is 0 error before what I gave you.

**Comment by TheIntelloBox** [comment]
http://hastebin.com/otetosumar.md
http://pastebin.com/2fwwbthE

**Comment by TheIntelloBox** [comment]
This is a major bug... All of my players are kicked.

**Comment by MylesIsCool** [comment]
Try without SkinRestorer

**Comment by TheIntelloBox** [comment]
Okay. :D

**Comment by MylesIsCool** [comment]
Is this fixed?

**Comment by TheIntelloBox** [comment]
Yep, without SkinsRestorer it's work. How to resolve the problem ?

**Comment by MylesIsCool** [comment]
Don't use skinrestorer, obviously not compatible.

**Comment by TheIntelloBox** [comment]
And you can't do anything, or contact the creator of this plugin ? :(
