### ISSUE TITLE
SexyMotd console ?

### ISSUE THREAD

**Issue by timr2000** [MylesIsCool/ViaVersion#57]
Found another Console spam.. it think it's not that bad but it spam's my console whith this..
http://pastebin.com/WgipsacF

**Comment by Paulomart** [comment]
Please use pastebin or something.

**Comment by timr2000** [comment]
Sorry :S never used that

**Comment by Paulomart** [comment]
http://pastebin.com

**Comment by MylesIsCool** [comment]
This is nothing to do with this plugin.

**Comment by timr2000** [comment]
ohh srry :s
