### ISSUE TITLE
Blocks disappearing client-side 1.9+

### ISSUE THREAD

**Issue by amchckn** [MylesIsCool/ViaVersion#571]
This issued has been caused by ViaVersion since 1.11 was released for it, here's some info:
1.8, latest viaversion (intended behavior): https://a.pomf.cat/tfosva.mp4
1.9+, latest viaversion (issue): https://a.pomf.cat/ahdekj.mp4
1.9+, pre-1.11 viaversion (intended behavior): https://a.pomf.cat/tmrrjb.mp4
Let me know if you need anything else to fix this issue, as this is a fairly urgent matter, thanks.

**Comment by Matsv** [comment]
Please follow the issue template.
(https://github.com/MylesIsCool/ViaVersion/blob/master/ISSUE_TEMPLATE.md)

Also, please note that this is a free plugin, we can't be here 24/7 to provide support.

**Comment by MylesIsCool** [comment]
Further to the above, if you're able to be the only person on the server with the issue and then do /viaver debug in both cases and provide separate outputs it would be highly useful to work out what's happening pacet wise.

**Comment by amchckn** [comment]
All samples below were done in one burst of four block breaks. All behaviors demonstrated in the media provided above was replicated during these tests.
1.8.9 latest viaversion (yes there was mining during this, no output was given): https://gist.github.com/f88eba40f79dd7c1421be7372fd5aaf1
1.9+ (1.11 in this case) latest viaversion: https://gist.github.com/fb14fb3f6b6c428794228b121a481999
1.9+ (1.10 in this case) pre-1.11 viaversion (0.9.10-SNAPSHOT specifically): https://gist.github.com/89ceed881550e0791683abb3aca8ad49

**Comment by MylesIsCool** [comment]
I'm assuming you're using ViaVersion for Bukkit?

What's the easiest way to replicate this with no plugins?

Could it be plugin related? Once again we don't know cause you haven't provided any dump info.

**Comment by amchckn** [comment]
1.10 client, latest viaversion: https://a.pomf.cat/jrnlrq.mp4
The only plugin on the server is viaversion, connecting directly to bukkit, no proxy.

Replicating is incredibly simple, use latest viaversion, use a 1.9 or above client, take a high efficiency tool (5+) and mine blocks in a cobblestone generator.
I even have a schematic of my cobblestone generator for you to test with: https://transfer.sh/9b9id/viaversiontest.schematic

If you want any other information I suggest contacting me privately about such, as I'd rather not put out any more information publicly whilst under a strict NDA. Thanks.

**Comment by AlexandreSinger** [comment]
Hey guys, I hope you are doing well. Do you need anything more from us to fix this bug?

**Comment by MylesIsCool** [comment]
@AlexandreSinger 

From the last time I tested after chckn gave me the exact spigot he used + client.


December 29, 2016
myles - 12/29/2016
Finally got round to do some more testing, I'm using 1.10.2 on the same spigot version and can't replicate. I'm pretty confident that my structure is identical to yours, https://a.pomf.cat/tthipa.mp4 I don't believe this to be slower than normal mc

**Comment by AlexandreSinger** [comment]
1.9+, latest viaversion (issue): https://a.pomf.cat/ahdekj.mp4
1.9+, pre-1.11 viaversion (intended behavior): https://a.pomf.cat/tmrrjb.mp4

There's a major difference between those two videos. It's a problem caused by ViaVersion since @amchckn tested this on a server with nothing but viaversion.

**Comment by MylesIsCool** [comment]
@AlexandreSinger Unfortunately what you've given me doesn't help me, I can't replicate your issue, which is why I posted a video with the settings I had showing there was no lag.

**Comment by JamieSinn** [comment]
What do you need to replicate this, I can also replicate it locally using 1.8.9 viaversion.

**Comment by MylesIsCool** [comment]
@JamieSinn 

Server version, plugin version, client version (s)

Does this stop with an older version of ViaVersion?

Do you have any plugins installed?


From having nothing what do I need to replicate it.

**Comment by xion87** [comment]
Got a similiar issue with mobs, also villagers are disapearing random with client 1.11*

**Comment by MylesIsCool** [comment]
There hasn't been any progress on this issue in a while, if anyone can provide an environment where this can be replicated locally I will happily reopen :)
