### ISSUE TITLE
Randomly being kicked

### ISSUE THREAD

**Issue by JoeyHaalboom** [MylesIsCool/ViaVersion#572]
### What is the output link of /viaversion dump? 
http://hastebin.com/gagimoqora.json (In the Hub)

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Bungeecord build 1204, Java 8, Plugins: AdvancedBungeeAnnoucer, BungeeOnlineTime, ClientStats, DynamaticAntiBot, NetworkManager, ProtocolLib, Quietcord, serverlistplus, Skinsrestorer, UltimateFriends.

### How does this error happen? login? Using an item? 

No idea, It seems random.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

Yes http://pastebin.com/7FgYqSMj

**Comment by Lmmb74** [comment]
First of all, you should try using BungeeCord build 1205.

**Comment by JoeyHaalboom** [comment]
Sorry I typed out of memory. Im using 1205 already.

**Comment by MylesIsCool** [comment]
Could you try without any bungeecord plugins?

The error seems related with some sort of malformed packet in bungee.

**Comment by TheIntelloBox** [comment]
I have the same problem without Bungee.

**Comment by Mario359** [comment]
Same problem

**Comment by TheIntelloBox** [comment]
Fix it please, this is so important ! :(

**Comment by MylesIsCool** [comment]
@TheIntelloBox @Mario359 

Unless you have the exact same stack trace, it isn't the same issue and you should open a new issue with FULL details.

**Comment by TheIntelloBox** [comment]
The same problem is here : We are randomly be kick.

**Comment by MylesIsCool** [comment]
@TheIntelloBox It's not the same cause, so use your own issue.

**Comment by TheIntelloBox** [comment]
Okay okay. But this is similar.

**Comment by MylesIsCool** [comment]
Could you try without SkinRestorer?

**Comment by JoeyHaalboom** [comment]
The error still happens when I remove ViaVersion. So in my case it wasnt Viaversion causing it. Atleast I think so.

**Comment by MylesIsCool** [comment]
@JoeyHaalboom Ah cool, thanks :)
