### ISSUE TITLE
BossBar API bugs after reload.

### ISSUE THREAD

**Issue by ElieTGM** [MylesIsCool/ViaVersion#573]
### What is the output link of /viaversion dump? 

http://hastebin.com/uquqokejaq.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

BungeeCord (ViaVersion not installed on it), i use the plugin on my hub server with my custom coded core plugins (OctoCore, LobbyModule, PEX, OctoMusic).

### How does this error happen? login? Using an item? 

It's an API error, if I, for example, have a compass and when i right click it it shows a bossbar, after a reload, when i click the compass again it doesn't show a bossbar. Using 1.10, as bossbar for 1.8 do not work. (server is in 1.8, yet i'm using this method for 1.9 +).

### Is there an error in the console? Use pastebin.com. Is there a kick message?

Nope.

**Comment by MylesIsCool** [comment]
This really isn't fixable, reloads aren't honestly supported. You should just use a plugin manager.
The best solution is to use a plugin like BarAPI.

Why?

Because we can't consistently keep internal objects over reloads. (Because of Classloader restrictions)
