### ISSUE TITLE
Random kick (& Low TPS)

### ISSUE THREAD

**Issue by Mario359** [MylesIsCool/ViaVersion#574]
### What is the output link of /viaversion dump? 
http://hastebin.com/aqayokusom.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Spigot 1.10.2

### How does this error happen? login? Using an item? 
No

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Kick message : http://image.noelshack.com/fichiers/2016/46/1479673250-capture.png
No error in the console

**Comment by MylesIsCool** [comment]
You have a plugin sending bad JSON data, test by removing plugins.
