### ISSUE TITLE
Boat 1.8

### ISSUE THREAD

**Issue by duckweedvn** [MylesIsCool/ViaVersion#576]
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Nope

### How does this error happen? login? Using an item? 
When i right click on boat, I could not climb them

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Nope

**Comment by Matsv** [comment]
First of all, please follow the issue template. 

We don't change anything for the 1.8 client, so this is probably not caused by ViaVersion.

**Comment by MylesIsCool** [comment]
No response, this sounds like an issue with either:

Desyncing
Other Plugin

Ask for reopen with correct details if not the above.
