### ISSUE TITLE
Sneaking Problem

### ISSUE THREAD

**Issue by lukas1101** [MylesIsCool/ViaVersion#578]
### What is the output link of /viaversion dump? 
---

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Craftbukkit 1.8.7
- PermissionsEx
- WorldEdit
- Modifyworld
- ViaVersion
- Essentials
- EssentialsSpawn
- EssentialsChat

### How does this error happen? login? Using an item? 

I dont know why, but you can only see a Player sneaking, if the Player is opped.
Other Players can't see an unopped Player sneaking...
I cant explain that...

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No

**Comment by Matsv** [comment]
This is not caused by ViaVersion. I recommend you to debug it, remove plugins one by one until it no longer happens to see which one is causing it.

**Comment by lukas1101** [comment]
I fixed it... 

You have to add the permission: "-modifyworld.sneak"

**Comment by Matsv** [comment]
Great to hear that (:
