### ISSUE TITLE
Error in bungee side

### ISSUE THREAD

**Issue by Esmorall** [MylesIsCool/ViaVersion#581]
### What is the output link of /viaversion dump? 
http://hastebin.com/oxotudifat.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
i have viaversion installed only on bunge-side

### How does this error happen? login? Using an item? 
This error happen sometimes when a player join the server.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

error in the console:
http://pastebin.com/NeJZxCR9
Kick message:
http://i.imgur.com/EWUX0eO.jpg

**Comment by MylesIsCool** [comment]
This error is down to you not having enough memory.

I'd suggest upgrading your ram / looking into memory issues / rebooting often.

**Comment by Esmorall** [comment]
i didnt have that problem before using viaversion on bungee-side, also i tried to increase the ram but didnt seems to work.
in the pastebin there is a part that says "SEVERE" and there is a ViaVersion error output.

Sorry if i have a mistake, i dont speak english.

**Comment by Esmorall** [comment]
Also has this error:
http://pastebin.com/e8jC1749
