### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Omanoctoa** [MylesIsCool/ViaVersion#582]
Console told me to post this...
http://pastebin.com/kBRwUCUL

Minecraft 1.10.2 Server (just updated Spigot to lastest today, prior to error).
Plugins...alot...
PermissionsEx, Essentials, CoreProtect, MithicMobs, Craftconomy3, TwoTuxLib, MultiInv, Lib'sDisguises, Factions, ProtocolLib, WorldGuard...just to name a few big ones (83 altogether)

No idea about the circumstances of the error, it just appeared. I opened console and that's what I saw - no players online atm.

**Comment by MylesIsCool** [comment]
Might not be an error and might just be a client sending bad data from looks of it.

**Comment by MylesIsCool** [comment]
I'm just gonna assume this could be a bad client, we might suppress errors before login in the future if this becomes an issue.
