### ISSUE TITLE
Not displaying clients players should connect with

### ISSUE THREAD

**Issue by BiGUNMAN** [MylesIsCool/ViaVersion#583]
### What is the output link of /viaversion dump? 
http://hastebin.com/obawisomiy.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Bugneecord 1206 & ViaBackwards

### How does this error happen? login? Using an item? 
When logging in with a 1.8.X client users get the following error message: http://i.imgur.com/pogmSeG.png --- instead of receiving a message stating what clients are supported.

My server is 1.10, I have ViaBackwards for 1.9 and ViaVersion for 1.11, I'm using viaversion on individual spigot instances instead of bungeecord.

They are connecting to my hub server, these are the spigot.yml client messages if that makes any difference:
  'outdated-client: '&cOutdated client! Please use &a{0}'
  'outdated-server: '&cOutdated server! I''m still on &a{0}'

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://i.imgur.com/pogmSeG.png

**Comment by MylesIsCool** [comment]
This is a BungeeCord related issue and unrelated to ViaVersion.

Consider editing your Bungee error messages.
