### ISSUE TITLE
SkinsRestorer causes malformed reading - Incompatible

### ISSUE THREAD

**Issue by craftrise** [MylesIsCool/ViaVersion#585]
SkinsRestorer problem == Viaversion please fix this.

https://paste.ee/p/SIWLF

**Comment by MylesIsCool** [comment]
Consider filling out the issue template it's there for a reason.

**Comment by craftrise** [comment]
- http://hastebin.com/ejineqiheg.json (Now removed SkinsRestorer)

- No

- There seems to be a problem like a packet limit.

- https://paste.ee/p/SIWLF

**Comment by craftrise** [comment]
I look forward to your thoughts on the subject.

**Comment by craftrise** [comment]
Fixed problem.

**Comment by MylesIsCool** [comment]
@craftrise 

Are you able to provide details to others who might be experiencing the same issue?

Or was it another plugin kind of thing?
