### ISSUE TITLE
BIG ERROR - BUNGEECORD

### ISSUE THREAD

**Issue by Esmorall** [MylesIsCool/ViaVersion#586]
### What is the output link of /viaversion dump? 
http://hastebin.com/oxotudifat.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
i am using bungeecord 1206 (lastest)

### How does this error happen? login? Using an item? 
all the time is spaming on bungee console and all the servers start to lag a lot (chat and commands)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/m4VNsm21

**Comment by MylesIsCool** [comment]
Try without skinrestorer

**Comment by Esmorall** [comment]
ok i will try

**Comment by Esmorall** [comment]
now i dont have the error :)

it will be fixed?

**Comment by MylesIsCool** [comment]
Related to #585, follow for updates.
