### ISSUE TITLE
MainHandPatch NPE

### ISSUE THREAD

**Issue by Esmorall** [MylesIsCool/ViaVersion#587]
### What is the output link of /viaversion dump? 
http://hastebin.com/uhecikinij.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Bungecoord

### How does this error happen? login? Using an item? 
Spam in bungee console

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/vAc7ig8u
also this error
http://pastebin.com/9Fp7STg6

**Comment by MylesIsCool** [comment]
Does this error have any in-game effect?

**Comment by Esmorall** [comment]
each 5 seconds bungeecord kicks players from the server with this message 

`28.11 18:00:51 [Server] WARNING -> UpstreamBridge - NativeIoException: syscall:read(...)() failed: Connection reset by peer
28.11 18:00:51 [Server] INFO disconnected with: NativeIoException : syscall:read(...)() failed: Connection reset by peer @ io.netty.channel.unix.FileDescriptor:-1`

**Comment by MylesIsCool** [comment]
But is this actually players being kicked? Or is it just people disconnecting.

**Comment by Esmorall** [comment]
is hard to determine, cause sometimes players disconnect normally but other times their join a server and get kicked, but that was not happen before install viaversions on bungee.side

pdd: sorry for my bad english

**Comment by Esmorall** [comment]
in the afternoon of today the server starts to lag a lot (chat, commands and server connections) while the console of bungeecord was spaming IndexOutOfBound errors and viaversion errors

**Comment by Matsv** [comment]
I'm sorry for the late answer, and chance you have the logs of those exceptions?

**Comment by Esmorall** [comment]
the first http://pastebin.com/vAc7ig8u

**Comment by Esmorall** [comment]
I am having now this error
http://pastebin.com/7cMyJaQ9
please help, is causing lot of lag on my server with +600 people
