### ISSUE TITLE
Sword blocking suggestion

### ISSUE THREAD

**Issue by v0idst4r** [MylesIsCool/ViaVersion#589]
This isn't exactly an error so I won't use the template. I propose you should always get a shield when holding a sword instead of just when you're right clicking. This will make block hitting much easier. With the current system 1.8 players have an advantage against 1.9+ players because how slow the block mechanic works.

**Comment by v0idst4r** [comment]
Also, the server is very slow to process if you are holding a shield or not. I propose it should check when the player sends a CPacketHeldItemChange.

**Comment by MylesIsCool** [comment]
There isn't a gameplay difference, client side it looks slow, but to 1.8 clients it's instant. It's possible, but could just lead to people getting more annoyed if we changed it.

**Comment by v0idst4r** [comment]
Say you're holding a sword, then you quickly hotkey to a soup and try to use it, it'll still register as you trying to block with your sword and won't use the soup

**Comment by MylesIsCool** [comment]
I don't see a lot of attention for this to be a feature, if it gains traction we'll consider adding in the future.
