### ISSUE TITLE
10 issues

### ISSUE THREAD

**Issue by ridalarry** [MylesIsCool/ViaVersion#59]
1) Bows and arrows will not work for 1.9 clients
2) It will take forever to eat with a 1.9 clients
3) Skin hats pants etc... will not show up for 1.9 clients
4) If you are using 1.9 and wear an armor, it will work, but it will not show on the armor bar
5) Your client will crash if you get near a wither boss with 1.9 client
6) You can not see the ender dragon boss bar
8) For 1.9 clients all spawn eggs will not have textures (all of them are white spawn egg named "spawn"), but its still working
9) Spawners dont have the right type as they all show as pig spawners for 1.9 clients, but its still working
10) "AAC" an anti hack plugin crash the players after being online for around 10 seconds

**Comment by ajthemacboy** [comment]
In my previous testing #8 isn't true, but I haven't tested of these.

**Comment by Paulomart** [comment]
Have you verified that this is true for the latest version?

**Comment by alexvermaning0** [comment]
i have none of those want to join my server? play.kwarkkings.us.to

**Comment by alexvermaning0** [comment]
only 3 en 6

**Comment by ridalarry** [comment]
Im using this version of spigot https://gyazo.com/9598032774f082c6de18605ba461f2bd I am not sure if they updated 1.8.8 after releasing 1.9

**Comment by ridalarry** [comment]
alex your server is whitelisted

**Comment by Wilco2998** [comment]
try now ridalarry

**Comment by gigosaurus** [comment]
1) Bows and arrows appear mostly fine, the only thing that doesn't work is the drawback animation doesn't show for 1.9 clients http://i.imgur.com/1L5Rtyh.jpg
2) Same for me
3) working fine for me: http://i.imgur.com/RKV29U2.jpg
4) Same for me
8) Same for me

**Comment by ridalarry** [comment]
Correcting some of my issues and adding another 2 issues
1) It works but not all of the time https://gyazo.com/2e564b8cd290c79b6350b5bb7774d90d
2) still not working
3) I mean the skin hats jackets etc... (the skins are 2 layers the second layer is not showing not the entire skin the first layer is fine)
4) Still not working
5) Seems to be fixed
6) You can not see the ender dragon and wither boss bars
8) For 1.9 clients all spawn eggs will not have textures (all of them are white spawn egg named "spawn", but on alex server it works fine for some reason), but its still work on right click
9) Still not working
10) Didn't recheck yet
11) On placing the dragon head its not moving, but on alex server it did
12) You can not sign a book nor read signed books

**Comment by Wilco2998** [comment]
11) the dragon head only works with redstone, it's meant to not animate if no redstone near

**Comment by HugoDaBosss** [comment]
The bow works fine sometimes. 
They behave very odd, because when shooting your first arrow everything is fine.
If you then don't move, and shoot again, the arrow wont even show up.
If you move a little bit, it will launch with a small velocity.
If you move enough it will launch with normal velocity.
I have no idea which causes this.

**Comment by ajthemacboy** [comment]
@Wilco2998 Pretty sure the dragon head is supposed to be still unless it's powered by redstone.

**Comment by Paulomart** [comment]
Please submit a ticket for each problem. Also make SURE that such ticket is not already open. Thanks

**Comment by ridalarry** [comment]
Ok I will close this and submit new ones for each one seperated.
