### ISSUE TITLE
ViaVersion + Lib's Disguises

### ISSUE THREAD

**Issue by L4BORG** [MylesIsCool/ViaVersion#590]
### What is the output link of /viaversion dump? 
http://hastebin.com/apecixezuq.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Latest BungeeCord (ServerListPlus, NuVotifier)

### How does this error happen? login? Using an item? 
https://www.youtube.com/watch?v=i6PoM364p44 (moving with keys is not an issue, trying to turn around is...)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No errors of exceptions in console, except:
http://pastebin.com/1Ka21EAi

with:
```
settings:
  moved-wrongly-threshold: 0.625
  moved-too-quickly-threshold: 100.0
```

Latest TacoSpigot 1.8.8, latest ViaVersion (1.0.2), ProtocolLib 4.1.0. The same issue occurs with or without NoCheatPlus.

**Comment by L4BORG** [comment]
Using Lib's Disguises 8.6.7 (1.8) from https://www.spigotmc.org/resources/libs-disguises.81/

**Comment by MylesIsCool** [comment]
Does this happen with certain mobs?

Can you elaborate on this issue?

**Comment by L4BORG** [comment]
Actually I just did some more testing and the issue is only present with ProtocolLib 4.1.0, I didn't test all versions in between but it seems to be ok with ProtocolLib 3.6.5.

The issue is that you can not move and turn around while being disguised. You can only move OR you can only turn around (would bug occasionally), when you start moving AND turning (yaw/pitch is changing) you would see... what you can see in that video.

**Comment by MylesIsCool** [comment]
This seems like an incompatibility with LibDisguises and specific ProtocolLib versions.

Unfortunately there's no correlating behaviour that we could really fix, we don't modify movement for mobs just translate the packets.

I'd suggest just using an older version of PL.
