### ISSUE TITLE
Blocks placing bug

### ISSUE THREAD

**Issue by CreaModZ** [MylesIsCool/ViaVersion#592]
### What is the output link of /viaversion dump? 
http://hastebin.com/utamefihom.json (i have tried multiple configurations like disabling pt, autoteam, collisions...)

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
- BungeeCord (Waterfall latest version).
- Only one custom BungeeCord plugin.

- PaperSpigot 1.8.8
- No bukkit plugins, except ProtocolLib, when this problem happened.

### How does this error happen? login? Using an item? 
When a player (version 1.9/1.10/1.11) place a block he is pushed to the side, and not to the top, and can place a block on himself.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Nop, but some gifs: 
- https://i.gyazo.com/e0d7e990e883c9782e5ce8e8668c6af6.gif (1.9.4 -> incorrect)
- https://i.gyazo.com/c2cb40fea610498d3c8c3e0bcab295a1.gif (1.9.4 -> incorrect)
- https://i.gyazo.com/8a494f0f85091b28f699a303712d3d75.gif (1.9.4 -> incorrect)
- https://i.gyazo.com/15d58e96ec0c399e2de37cd529f45605.gif (1.9.4 -> correct, without ViaVersion)

**Comment by CreaModZ** [comment]
This problem doesn't happend with ViaVersion on my Spigot. Also Shield blocking doesn't work with ViaVersion Bungeecord (with shield-blocking: true in the config).

**Comment by MylesIsCool** [comment]
This is a bug in paper and cannot be fixed bungee side AFAIK.

We have a custom patch on viaversion for bukkit and you'd need to use the bukkit version to fix both these issues.

We have no plans for shield support for bungee due to the complexities of inventory tracking.
