### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by Martini002** [MylesIsCool/ViaVersion#593]
### What is the output link of /viaversion dump? 
http://hastebin.com/waxotikuxa.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord

### How does this error happen? login? Using an item? 
Login

### Is there an error in the console? Use pastebin.com. Is there a kick message?
[10:45:02 INFO]: alvo lost connection: Internal Exception: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/MylesIsCool/ViaVersion/issues
{Type: String, Source #0: us.myles.ViaVersion.protocols.protocol1_9to1_9_1.Protocol1_9TO1_9_1$1 (Anonymous), Data: [Pair{Type|Integer, 19553}, Pair{Type|Unsigned Byte, 0}, Pair{Type|Byte, 4}, Pair{Type|Unsigned Byte, 102}, Pair{Type|Unsigned Byte, 108}], Packet ID: 35}
Actual Error:

**Comment by Matsv** [comment]
Could you change debug=true in server.properties and provide us with the full error?

**Comment by MylesIsCool** [comment]
Provide more info if you want this solved and request reopen.
