### ISSUE TITLE
Lag on join and teleport.

### ISSUE THREAD

**Issue by Arias00** [MylesIsCool/ViaVersion#594]
### What is the output link of /viaversion dump? 
http://hastebin.com/hizilanina.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Spigot (1.8.8-R0.1-SNAPSHOT). Plugin list: http://pasteboard.co/5SXEehJGD.png

### How does this error happen? login? Using an item? 
When a player joins the server and when someone teleports to any place, there is lag like for 5 seconds. When I saw this problem try to remove plugins one by one, it was not removed until I removed ViaVersion, so it is definitely from this plugin. I would like to know if some of the other plugins are interfering or something, my list of plugins is up. Also only happens when it is in a version other than 1.8, such as 1.9, 1.10 or 1.11. In 1.8 there is no error of this plugin.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No

### Additional information
Another person also spoke of this problem, but you did not solve it since he did not indicate enough information, I hope the one I put its enough. Link of the another person's issue:       https://github.com/MylesIsCool/ViaVersion/issues/588

**Comment by MylesIsCool** [comment]
Would you be able to test without anti-cheat possibly? to see if it's interfering (only for a small while as I can understand that this is dangerous).

**Comment by Arias00** [comment]
Already solve it, thanks for your help.
