### ISSUE TITLE
All players become invisible to a 1.11 player if a player in 1.8 kills them

### ISSUE THREAD

**Issue by Simo389** [MylesIsCool/ViaVersion#597]
### What is the output link of /viaversion dump? 
http://hastebin.com/idonadovaq.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord, version: 1.11-SNAPSHOT:8574688:1205

### How does this error happen? login? Using an item? 
I can reproduce this on my server currently - when a player running 1.8 kills a player running 1.11, the player running 1.11 then respawns and can no longer see any other players on the server. I reported this on Spigot and someone suggested reporting here: https://www.spigotmc.org/threads/1-8-1-11-protocol-issues-with-invisibility.198963/

It seems to happen 4 in 5 times, and from other versions doesn't happen - so I'm guessing there's just a packet issue between the 1.8 client and 1.11 client?

### Is there an error in the console? Use pastebin.com. Is there a kick message?
None.

**Comment by MylesIsCool** [comment]
Hi,

Does this issue still happen?
Any chance of testing without NametagEdit?
