### ISSUE TITLE
Spawn Eggs bugged?

### ISSUE THREAD

**Issue by L4BORG** [MylesIsCool/ViaVersion#598]
### What is the output link of /viaversion dump? 
http://hastebin.com/anuzalosev.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord

### How does this error happen? login? Using an item? 
1.11 clients won't render proper spawn eggs (they're all white) when you're looking at spawn eggs in item frames.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No.

**Comment by L4BORG** [comment]
1.8, 1.9 and 1.10 clients will still render proper spawn eggs.

**Comment by Matsv** [comment]
We might not handle metadata items yet, thanks for reporting.

**Comment by marint94** [comment]
Can confirm.
This also happens in custom inventories. Most of them are white.
<img width="380" alt="screen shot 2016-12-25 at 21 04 48" src="https://cloud.githubusercontent.com/assets/1753790/21472706/cd9b468a-cae5-11e6-883b-64e4e7dd85c5.png">

**Comment by MylesIsCool** [comment]
@marint94 Would you be able to confirm what the eggs are on a different version?

**Comment by L4BORG** [comment]
@MylesIsCool 

![Image](http://i.imgur.com/fXad870.png)

**Comment by L4BORG** [comment]
Horse egg is still bugged, the rest are ok now:

![inv](http://i.imgur.com/ore4576.png)
