### ISSUE TITLE
JSON Issue on login

### ISSUE THREAD

**Issue by danjb2000** [MylesIsCool/ViaVersion#599]
### What is the output link of /viaversion dump? 
http://hastebin.com/watetivule.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
LilyPad, PaperSpigot Instances.

### How does this error happen? login? Using an item? 
This error only happens on joining with 1.11.
The error occurs when the player is kicked whilst joining the server, or kicked from the server at all.

It would appear as if it was a JSON problem as it does not correct format the text, with line breaks e.t.c.
https://d-b.io/i/f1b026d.png 
https://d-b.io/i/c11b22e.png

Happens with multiple plugins, ruled out those. 

### Is there an error in the console? Use pastebin.com. Is there a kick message?
When looking at the console, the console shows the kick message perfectly as it should be. No errors.

**Comment by MylesIsCool** [comment]
I'm unsure if you're able to test this, (really busy at the moment), but does this happen if you run your plugin on a 1.11 server?

**Comment by danjb2000** [comment]
I'm currently trying it on 1.8 and 1.10 instances for reference.

I'll see if I can test this on 1.11 later on + get back to you.  Cheers

**Comment by MylesIsCool** [comment]
Testing this myself using 1.9+, seems mojang has removed new line in kick messages.
