### ISSUE TITLE
Client crash (1.10.2 servers, 1.11 client)

### ISSUE THREAD

**Issue by PhanaticD** [MylesIsCool/ViaVersion#600]
### What is the output link of /viaversion dump? 
http://hastebin.com/hakepaniga.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I am using viaversion for waterfall (85) https://ci.destroystokyo.com/view/All/job/Waterfall/85/

### How does this error happen? login? Using an item? 
piston redstone contraptions causes this error

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://hastebin.com/lodemehoka.pas

**Comment by MylesIsCool** [comment]
Duplicate of #570
