### ISSUE TITLE
Error on startup, TacoSpigot 1.10.2 Latest.

### ISSUE THREAD

**Issue by GoldenOrangeX** [MylesIsCool/ViaVersion#601]
### What is the output link of /viaversion dump? 
N/A

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord
ServerListPlus
BungeePerms
BungeeAlias

### How does this error happen? login? Using an item? 
On startup, possible lead to server unresponsiveness.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://hastebin.com/ocaxemafon.md

**Comment by MylesIsCool** [comment]
Consider filling in the entire issue template, you're missing the viaver dump.
Also could you provide more of the console log.

**Comment by MylesIsCool** [comment]
Closing seems unrelated, one off error
