### ISSUE TITLE
Error with custom bungeecord

### ISSUE THREAD

**Issue by linkinkov** [MylesIsCool/ViaVersion#602]
### What is the output link of /viaversion dump? 
Plugin is not start

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeAlert1.5.jar
BungeeAuthMeBridge-1.6.2.jar
BungeePexBridge.jar
BungeeReload.jar
CommandSyncServer.jar
LiteBans.jar
PixelVipBungee.jar
ServerListPlus-3.4.7-Universal.jar
SkinsRestorer-v12.9.4.jar
WCNP.jar
and ViaVersion the last version

### How does this error happen? login? Using an item? 
Error with start bungeecord with plugin.
I use custom version of bungeecord with anti-bot features

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/HTJRwd0R

**Comment by Matsv** [comment]
This is something that has to be fixed on your end. We don't provide any support for this since the bungeecord is private.
