### ISSUE TITLE
Players can't be hit after a glitched log out

### ISSUE THREAD

**Issue by BadassDevelop** [MylesIsCool/ViaVersion#603]
### What is the output link of /viaversion dump? 
http://hastebin.com/caharogaro.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
https://gyazo.com/b4e2fb36fc8dc227e3b2a6b7137c97d9

### How does this error happen? login? Using an item? 
Whenever a player gets kicked by my optimized configuration of NoCheatPlus or ViaVersion's PPS settings, they can't be hit. This issue happens with or without any other plugins being added. I've manually kicked several different players several different times, and the only time this glitch happens is if NCP or ViaVer kicks them.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
This error only happens when a player gets kicked by a plugin like LiteBans: http://pastebin.com/KjL6LcUq - which doesn't generate an issue.

**Comment by MylesIsCool** [comment]
This is a bug in this plugin:

Caused by: java.lang.NullPointerException
    at me.therealdan.timeplayed.mechanics._TimeTrackingHandler.onQuit(_TimeTrackingHandler.java:35) ~[?:?]


Not ViaVersion.

**Comment by BadassDevelop** [comment]
This was happening BEFORE that plugin was added. If you read my post you'd see the "This issue happens with or without any other plugins being added".

**Comment by MylesIsCool** [comment]
Replicate this without any other plugins and provide the error then, please

**Comment by BadassDevelop** [comment]
There is no error produced in console, but they are completely invincible.

**Comment by BadassDevelop** [comment]
I've managed to reproduce the error for myself, and it just says "Disconnected" on my screen when I log back on I am invincible to everything. This happened while I was on a normal Spigot 1.8 server with no other plugins.

**Comment by MylesIsCool** [comment]
Please provide full steps to replicate. Additionally any console errors if any.

**Comment by BadassDevelop** [comment]
I updated to the latest development build and this issue was patched for my server.
