### ISSUE TITLE
1.11.1 clients can't join a 1.11 server

### ISSUE THREAD

**Issue by TrevorSayre** [MylesIsCool/ViaVersion#605]

**Comment by MiniDigger** [comment]
this is known, there is no support for that yet, see https://www.spigotmc.org/threads/1-11-1-protocol-hack.202024/#post-2099005

**Comment by TrevorSayre** [comment]
Thanks, just nice to track it on GitHub instead of a forum thread. I appreciate your work :)

**Comment by MylesIsCool** [comment]
Use latest dev build of the main branch for a fix if you need it, spigot 1.11.1 did just come out anyway.
