### ISSUE TITLE
1.11.1/2 server can't let 1.11 clients to log

### ISSUE THREAD

**Issue by TNTUP** [MylesIsCool/ViaVersion#606]
### What is the output link of /viaversion dump? 
Couldn't dump, 403 error http://hastebin.com/documents

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No bungee, test server 1.11.1

### How does this error happen? login? Using an item? 
Protocol Not Supported

### Is there an error in the console? Use pastebin.com. Is there a kick message?

See above.

I'm asking this, like in 1.9's it was possible but in 1.11's not. Is it due to the new items/bugfixes? Should allow them, but ignoring non existent items (iron nugget by example) into something, a missing texture item?

**Comment by MylesIsCool** [comment]
We did this for 1.9.x versions but is not the primary aim of ViaVersion. Use ProtocolSupport etc

**Comment by Matsv** [comment]
Will support it inside ViaBackwards soon.

**Comment by TNTUP** [comment]
@MylesIsCool I'm not supporting 1.9/1.10 on a 1.11.2 server. I meant allowing 1.11 only on 1.11.1/2. ViaVersion can handle it though. 

@Matsv Neat! That'll require 2 plugins just for allowing 1.11 (I guess there's so much things to do to allow 1.11 in a 1.11.2 server that Viaversion could?)

Thanks for the input guys! Merry Christmas :D
