### ISSUE TITLE
/viaversion dump error

### ISSUE THREAD

**Issue by essem2** [MylesIsCool/ViaVersion#608]
### What is the output link of /viaversion dump? 
error, see log

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Server: BungeeCord Build 1217
Plugins: 
BungeeWeb v0.1
BungeeBack v1.x (custom)
Yamler v2.3.0-SNAPSHOTb-5
BungeeChatFilter v1.5-SNAPSHOTb-5
ViaVersion v1.0.3
BungeeUtil v2.0.3

### How does this error happen? login? Using an item? 
on command (from console)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/edxCmtmg

**Comment by MylesIsCool** [comment]
Unfortunately this is down to cloudflare issues, but we're looking into an alternative soon.

**Comment by MylesIsCool** [comment]
Fixed in next version (use dev builds if you need it)
