### ISSUE TITLE
ProtocolLib used with Via doesn't accept connections during boot

### ISSUE THREAD

**Issue by MedicOP** [MylesIsCool/ViaVersion#612]
### What is the output link of /viaversion dump? 
The issue is the same as described in #362. The dump command is not working at the time of writing this report. I'm using Spigot 1.8 and the latest version of ViaVersion.

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
The problem only happens with ProtocolLib installed.

If using BungeeCord, when attempting to join the server it will show "Logging in..."

If not using BungeeCord, the server does not show up in the Minecraft server list ("Can't connect to server."). Upon trying to join, it will show "Logging in" for a fraction of a second before showing "Disconnected"

### How does this error happen? login? Using an item? 
If a player attempts to log in to the server while it is starting up before ViaVersion has **loaded**, this player will be able to log in but no further connections are accepted. Nothing appears in the console when you try to join.

The problem only happens if the player attempts to log in before ViaVersion has **loaded**. It does not happen if the player attempts to log in after ViaVersion has **loaded** but not been **enabled** yet.

Reloading or restarting the server fixes the issue.

Obviously late-bind has to be set to false for this issue to occur.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Nothing shows up in the console.

Not sure if relevant, but YourKit profiler shows deadlock on Netty Epoll Server IO threads 

![ac34c953a23940aaa4f8533214bd8013](https://cloud.githubusercontent.com/assets/18251099/21731160/4eacaa22-d453-11e6-9cce-dda479bac06d.png)

**Comment by MylesIsCool** [comment]
Is there any further information you can provide from profiling?

and, when you state that it is fixed by reloading, are you saying that it undeadlocks the threads?

and have you tested without any other plugins?

**Comment by MedicOP** [comment]
Okay, I have more information about this. It only seems to happen if ProtocolLib is installed. I'm using the latest version of ProtocolLib for 1.8. I tested with only ViaVersion and ProtocolLib installed. Sorry for not testing more thoroughly.

The login issue is fixed by reloading. I haven't checked whether it undeadlocks the threads.

Other information from profiling I can provide is I can see BukkitChannelInitializer.initChannel is called each time someone tries to log in, not sure if that helps.

**Comment by Shevchik** [comment]
Try disabling native transport.

**Comment by MylesIsCool** [comment]
I have tried to replicate this but i'm not able to, here's what i've tried:

Installing around 20 plugins (to slow down boot time),
Joining with 1.11 on 1.8.8 server,

However I cannot cause this deadlock, it's worth noting I don't have native transport so perhaps it's down to that. (I am using latest ProtocolLib)

I'm pretty sure Shevchik is right and it's down to this if you try disabling it and it still happens might need you to pass some sort of test configuration so we can solve this.

**Comment by MedicOP** [comment]
Just wanted to say that the problem can be reproduced on both Windows and Linux with just ProtocolLib installed. Native-transport only works on Linux systems, so it's most likely not caused by it.

Doesn't change anything about this, just leaving it here in case anyone else ever finds this ticket
