### ISSUE TITLE
ViaVersion combined with SpongeForge doens't load correctly or crashes server

### ISSUE THREAD

**Issue by stefan7080** [MylesIsCool/ViaVersion#613]
### What is the output link of /viaversion dump? 
Can't tell because it doesn't load correctly or crash

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I'm using SpongeForge and as plugins EssentialsCmds and ViaVersion

### How does this error happen? login? Using an item? 
Starting the server

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/HqQK77bf (Full Log of the non-sponge plugin)
http://pastebin.com/qb7beGgp (Full Log of the sponge plugin)

Also tried the legacy version, and the legacy version combined with the sponge version and it didn't load at all.

If the ViaVersion loads (non-sponge version) it just says the server is outdated.
Help? Bug? Idk. Maybe I am just not seeing something I have to.

**Comment by MylesIsCool** [comment]
Could you delete any ViaVersion configs and try again?

**Comment by MylesIsCool** [comment]
No response closing. Request reopen if still an issue.
