### ISSUE TITLE
Falling into the void causes "Flying is not enabled on this server" or "You are sending too many packets"

### ISSUE THREAD

**Issue by v0idst4r** [MylesIsCool/ViaVersion#617]
### What is the output link of /viaversion dump? 
It won't run, there seems to be a problem with hastebin http://prnt.sc/dvsbha

The version of viaversion is 1.0.3
Craftbukkit version: http://imgur.com/mDHZorQ

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Only viaversion

### How does this error happen? login? Using an item? 
Falling into the void on 1.11

### Is there an error in the console? Use pastebin.com. Is there a kick message?
The kick message is either "Flying is not enabled on this server" or "You are sending too many packets"

**Comment by MylesIsCool** [comment]
You can use the development builds from https://ci.viaversion.com/job/ViaVersion/ to obtain a working /viaversion dump.

In addition, does increasing max pps fix this? Otherwise gonna need the dump.

**Comment by MylesIsCool** [comment]
Increase config for max pps

**Comment by v0idst4r** [comment]
It still kicks for flying or related, it also occurs on HiveMC which uses ViaVersion

**Comment by v0idst4r** [comment]
Reopen this, this is a very serious bug
