### ISSUE TITLE
Run condition upon login, maybe?

### ISSUE THREAD

**Issue by PatoTheBest** [MylesIsCool/ViaVersion#619]
### What is the output link of /viaversion dump? 

Failed to dump, please check the console for more information
[ViaVersion] Could not paste ViaVersion dump to Hastebin
java.io.IOException: Server returned HTTP response code: 403 for URL: http://hastebin.com/documents

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Plugins (9):  FastAsyncWorldEdit, ViaVersion, Vault, PlaceholderAPI, ProtocolLib, AAC, AACAdditionPro, WorldEdit, TheTowersRemastered

### How does this error happen? login? Using an item? 
This has happened only once in my local test server, been using this plugin for a while now. Run condition on login maybe?

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/FzRWpfut

**Comment by MylesIsCool** [comment]
This is related to server lists sending invalid data.
