### ISSUE TITLE
Ban message not formatted correctly - 1.9+

### ISSUE THREAD

**Issue by alexmarkey** [MylesIsCool/ViaVersion#620]
### What is the output link of /viaversion dump? 
Couldnt viaver dump at the time of this error - http://prntscr.com/dxfoom

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
LilyPad
Bukkit-Connect.jar

### How does this error happen? login? Using an item? 
A banned player on our network receives the following message when attempting to log in 
http://prnt.sc/dw6ujv
The above screenshot is taken from a 1.8 clients perspective.  This is the outcome which we want.

On 1.9+ clients, the message is not formatted correctly - http://prnt.sc/dw6uao

ViaVersion config - http://pastebin.com/hSKQYdZQ

**Comment by MylesIsCool** [comment]
Testing this myself using 1.9+, seems mojang has removed new line in kick messages.

**Comment by alexmarkey** [comment]
Tested on Mineplex by getting banned, they have multiple lines working in 1.9+

http://prntscr.com/dxv4py

???

**Comment by MylesIsCool** [comment]
I can't replicate this issue, you're gonna need to provide code perhaps the method has changed. Normally using json I was unable to use new lines. However, using AdvancedBan (on the bukkit server with Via) multiline works fine for the plugin:
http://myles.us/jh3.png

I'm really confused by this
