### ISSUE TITLE
Duplicate Airbars At Top

### ISSUE THREAD

**Issue by 7r580** [MylesIsCool/ViaVersion#623]
When using Airbar

https://www.spigotmc.org/resources/airbar.16649/

With ViaVersion, if you switch servers, (even when running airbar on only 1 server) the bars travel to other servers. Maxim states it's a problem with ViaVersion, and told us to come here and file a report.

You can see others have this issue

https://www.spigotmc.org/threads/airbar-paid.113651/page-6

**Comment by MylesIsCool** [comment]
Consider using the issue template: https://github.com/MylesIsCool/ViaVersion/blob/master/ISSUE_TEMPLATE.md

It's there for a reason, use the latest dev build of ViaVersion for working /viaver dump -> https://ci.viaversion.com/job/ViaVersion/

**Comment by 7r580** [comment]
We're not a dev. Just letting you guys know about the conflict. If you 
chose to resolve, that's between you and Maxim. :)

**Comment by MylesIsCool** [comment]
There was nothing saying you had to be one, but I can't resolve this issue without you answering the issue template. It's there so it can be solved.

**Comment by 7r580** [comment]
Just fyi, we just tried UltraBar, and it's doing it there too.

I'm running 45 servers, so if you want to look into it, we're on 1.11. 
Does it with the VV 1.04 snapshot as well. It's something with boss 
bars, I haven't a clue beyond that, but others are reporting it as well. 
So maxim's airbar and the ultrabar plugin both do it with Via Version 
installed.

Good luck on finding the issue! :)

**Comment by MylesIsCool** [comment]
Unless you fill in the issue template, this will not be solved. It's there to provide info us with useful info. It only takes 2 minutes.

**Comment by 7r580** [comment]
Ohwell! :)

**Comment by MylesIsCool** [comment]
If anyone wants to provide proper info so this can be solved if you have the issue, create a new ticket.

**Comment by ysl3000** [comment]
I think it's no problem with via version. The problem is that the Bossbars aren't cleared on join when using bungeecoord.

It's like the playerlist-header/footer. Sending a header/f on one server and switching to a server without playerlist-header/footer will not clear the old h/f.

The problem is that you've to remove each bossbar on serverleave / subserverleave. It's not getting cleared at leave.

**Comment by Maximvdw** [comment]
"The problem is that you've to remove each bossbar on serverleave / subserverleave. It's not getting cleared at leave."

Boss bars are cleared on subserver leave. Bungeecord will send a packet removing it. However when using ViaVersion the packet is never send.
