### ISSUE TITLE
Kicks players, version 1.9.4, I know you don't really help with older versions but please.

### ISSUE THREAD

**Issue by DemonicBagel** [MylesIsCool/ViaVersion#627]
### What is the output link of /viaversion dump? 
It could not dump
03.02 21:10:22 [Server] INFO at us.myles.ViaVersion.commands.defaultsubs.DumpSubCmd$1.run(DumpSubCmd.java:64) [ViaVersion-1.0.3.jar:?]
03.02 21:10:22 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_77]
03.02 21:10:22 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_77]
03.02 21:10:22 [Server] INFO java.io.IOException: Server returned HTTP response code: 403 for URL: http://hastebin.com/documents
03.02 21:10:22 [Server] WARN Could not paste ViaVersion dump to Hastebin

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
The bug only started happening when I added ProtocolSupport so that is all I will list for now.

### How does this error happen? login? Using an item? 
The error is that players get kicked out of the game whenever someone mines. So far, the error occurs when a player mines an ore that produces an item, like coal, or Redstone.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
[Console Log - Debug Mode On.docx](https://github.com/MylesIsCool/ViaVersion/files/751979/Console.Log.-.Debug.Mode.On.docx)

**Comment by MylesIsCool** [comment]
You're using an old version.

Consider updating.
