### ISSUE TITLE
[Minor] Spawned Mobs not showing with armor or weapons while in 1.11 in a 1.8 server w/ ViaVersion

### ISSUE THREAD

**Issue by Zaino60** [MylesIsCool/ViaVersion#628]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/2eda0271a0c5a1c25fdd25e82909b8fa

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord, version https://gyazo.com/98bf260aa9a48970a7856355948c0bcd
This bug is server-side, plus I'm not using ViaVersion Bungee version. (I'm using the spigot plugin)

### How does this error happen? login? Using an item? 
When you look a spawned mob that has armor or weapon in a 1.8.8 server, while in 1.11 client it just appears as a normal mob without armor or weapon.
- Example of bug https://gyazo.com/459a804b95c2449b093591837ae53534 (Left 1.11, right 1.8, notice the skeleton)
- Example command of spawned skeleton with armor not showing in 1.11: `/summon Skeleton ~ ~ ~ {SkeletonType:0,Equipment:[{id:272},{id:310},{id:311},{id:312},{id:397}]}`

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No

**Comment by Zaino60** [comment]
This is still happening in latest ViaVersion. Is anything going to do something in respect?

**Comment by MylesIsCool** [comment]
Unfortunately, it is only myself actively looking into issues and time is sparse with issues (a lot of people ask me about weird bugs unfortunately)

I've tried this myself and this is a 1.8 server using LibsDisguises and it seems fine from what I can test.
http://myles.us/j3b.png

(I'm running 1.0.3 in the screenshot, which looking at the changes between the one you're running shouldn't matter)

**Comment by Zaino60** [comment]
I don't use LibsDisguises (or any disguises plugin) in my server, but I tried installing it and still the mobs with armor spawned BY COMMAND BLOCK (such as the example above) still show without armor for 1.11 clients in a 1.8 server w/ ViaVersion.

Exact command used (it's for an adventure map): http://pastebin.com/k4FipJYE But the bug happens with any command executed by command block regarding mob spawning with armor. (Like the example above). It's not a LibsDisguises thing since disguises don't have anything to do in this bug.

**Comment by MylesIsCool** [comment]
@Zaino60 I'm wondering if it's something to do with the client not being able to understand certain nbt tags or something like that?

**Comment by Zaino60** [comment]
I doubt, because the mob actually spawns with all the armor and gear and players in 1.8 can see it.
Example: https://gyazo.com/459a804b95c2449b093591837ae53534 (Left 1.11, right 1.8, notice the skeleton)

**Comment by MylesIsCool** [comment]
Well NBT does change between versions so it could be a change considering it can be displayed fine on both versions using libsdisguises

**Comment by Zaino60** [comment]
But it's weird because it's a visual bug actually. The players in 1.11, even though can't see the armor of weapon of the mob, can battle it and notice it's not a normal skeleton since it hits harder and takes more time to kill. That's why I thought this just needed adapting, like you did with the mob eggs in order to show the actual color of the mob in both MC versions.

**Comment by Zaino60** [comment]
@MylesIsCool Sorry for bumping but this is still happening and it's been 2 months. Is there a possibility for this to be fixed?

**Comment by MylesIsCool** [comment]
@Zaino60 I've had a relook at this and missed something, the reason it's not displayed is due to the following:

- By default if you use the notation {id:123} it defaults to 0 Count, in 1.9+ Count 0 is not displayed.
- You're using numerical id's, Mojang stopped supporting these in 1.7 and enforces names.

So for your example command, using:
`/summon Skeleton ~ ~ ~ {SkeletonType:0,Equipment:[{id:stone_sword, Count:1},{id:diamond_boots, Count:1},{id:diamond_leggings, Count:1},{id:diamond_chestplate, Count:1},{id:skull, Count:1}]}`

Correcting the commands to use this format will fix the issue on both versions, and also allow you in the future to update your server software without issues.
