### ISSUE TITLE
ProtocolSupport & ViaVersion

### ISSUE THREAD

**Issue by IsaiahPatton** [MylesIsCool/ViaVersion#629]
### What is the output link of /viaversion dump? 

http://pastebin.com/8YXqCmuG

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

http://pastebin.com/BRBqMkNG

Latest Spigot 1.11.2.

Using latest version of ViaVersion & latest Jenkins Build of ProtocolSupport.

### How does this error happen? login? Using an item? 

Loging in to the server.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

Error in ProtocolSupport-errlog file, 
file said "Please post this error to http://github.com/MylesIsCool/ViaVersion/issues"

http://pastebin.com/0xhDesHU

There is also a error on startup saying can't hook into ProtocalSupport http://pastebin.com/Hddysr46

**Comment by MrPowerGamerBR** [comment]
If you are on 1.11.2, why use ViaVersion? (the only reason is the packet limiter... and that's it)

**Comment by MylesIsCool** [comment]
You're not even using the latest version of ViaVersion, use latest and reproduce dump. Otherwise why would you be using ViaVersion?
