### ISSUE TITLE
ProtocolSupport

### ISSUE THREAD

**Issue by Misat11** [MylesIsCool/ViaVersion#630]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/95f19b62755725f27507f994184abafa

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
When I want to connect server 1.9.4 with version 1.11.2, i see only: Server stay on 1.9.4. When I connect with 1.8-1.8.9 is work normally. With 1.11.2 working only when I change in config version of server, but after a while it change back to -1.

I'm using bungeecord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:b728aea:1216 by md_5

Plugins in bungee: in viaversion dump
Plugins on server: WorldEdit, Skript, TitleMotd, AnimatedScoreboard, Essentials, PlaceholderAPI, CommandsDispatcher, GadgetsMenu, OnlyProxy, Modifyworld, BungeePerms, NameHistory, LaggRemover, ProtocolLib, WorldGuard, Multiverse-Core, iConomy, SocketAPI, PAC, Multiverse-Portals, pvpstats, PlayerHider, Vault, Color4Signs, ChairStairs, EssentialsSpawn, ProtocolSupport, LightAPI, AuthMe, HolographicDisplays, FreeBungeeChat, Citizens, ChestCommandsPlus, AuthMeBridge, CommandNPC, ShinyItems

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Nothing in console.

**Comment by MylesIsCool** [comment]
Disable automatic pinging of servers then https://docs.viaversion.com/display/VIAVERSION/Configuration#Configuration-BungeeOptions
