### ISSUE TITLE
Failed to initialize a channel.

### ISSUE THREAD

**Issue by dobrac** [MylesIsCool/ViaVersion#631]
### What is the output link of /viaversion dump? 
 [ViaVersion] Could not paste ViaVersion dump to Hastebin
java.io.IOException: Server returned HTTP response code: 403 for URL: http://hastebin.com/documents
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840) ~[?:1.8.0_101]
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[?:1.8.0_101]
at us.myles.ViaVersion.commands.defaultsubs.DumpSubCmd$1.run(DumpSubCmd.java:64) [ViaVersion-1.0.3.jar:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [server.jar:git-Spigot-21fe707-e1ebe52]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I am using Waterfall version Build 99, Spigot 1.8.8 (With fixed /timings command)
Plugins:
 - AuthMe (My own created, nothing to do with AuthMe on spigot - just the name)
 - TimedRestart (My own created, for restarting server at certain time)
 - MySQL (My own API for mysql connection)
 - ReloadServer (My own plugin for loading plugins from different location than /plugins, ViaVersion is normally loaded on start from /plugins)

### How does this error happen? login? Using an item? 
You can't join the server, kicked with this error message: https://ctrlv.cz/shots/2017/02/12/4eRS.png

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Log of the server: http://pastebin.com/Hssp4QXP
Kick message: https://ctrlv.cz/shots/2017/02/12/4eRS.png

**Comment by MylesIsCool** [comment]
Consider first updating the version to latest, otherwise do any of your plugins do anything with minecraft's server connection?

**Comment by dobrac** [comment]
Maybe, in AuthMe plugin is function for switching server on Waterfall (BungeeCord) by PluginMessaging.

**Comment by dobrac** [comment]
Error log from new version (1.0.4): https://hastebin.com/agugeyedis.bash
Dump: https://hastebin.com/oqogaqinal.vbs

**Comment by MylesIsCool** [comment]
@dobrac That doesn't look like the output from /viaver dump, also might be worth just trying with just viaversion see if it works and add plugins.

**Comment by dobrac** [comment]
It is output from the console, because the command can't be run, it writes this error on that time, when error happens. I can't test it without plugins, that would be nonsense, but the error doesn't happen all times, when I restart it, it can dissapear.

**Comment by dobrac** [comment]
Here is viaversion dump, when the server is running normally: https://gist.github.com/f0124e0bb929a1975fb743ba01523ffe

**Comment by MylesIsCool** [comment]
@dobrac Something is causing it to lock up and I can't work it out from this end because you're using custom plugins, hence the suggestion. I don't think it's particularly hard to copy the server and try it locally or what but that, of course, depends on your configuration.

**Comment by dobrac** [comment]
I think, you don't understand me, the error happens only sometimes and it happens from the start. I don't know, how to test it without plugins, because I can't reproduce the bug.

**Comment by dobrac** [comment]
I can show you the sources of the plugins, but I don't want to publish them anywhere. Maybe, if you have some secret communicator, I can show you the sources via TeamViewer or something simillar.

**Comment by MylesIsCool** [comment]
@dobrac I've had a review of the error and the code in ViaVersion and it might be in relation to players joining before ViaVersion has fully loaded, do you have a full startup log for the error? Does a player try to connect?

**Comment by dobrac** [comment]
In the first message is log of the server startup, here is it again: http://pastebin.com/Hssp4QXP

Actually it is possible, it happens, when servers restart during the day, and people are joining it at high rate. Auths and Lobbys are most used servers with 1000 players online.

**Comment by MylesIsCool** [comment]
If you could try, https://ci.viaversion.com/job/ViaVersion/140/, it would be appreciated. It should now fallback to default Minecraft behaviour if ViaVersion doesn't know everything when they connect.

**Comment by dobrac** [comment]
Thank you, I will try it. I will write here results as soon as spossible.

**Comment by dobrac** [comment]
I tryied it now, while players are trying to connect and it is looking good. I will write in few days after testing, if the same bug will happen again. (If it will happen earlier, I will write then)

**Comment by MylesIsCool** [comment]
@dobrac Thanks :)

**Comment by dobrac** [comment]
I have to say sadly, that it didn't solve the issue :(

Here is the log: https://hastebin.com/zelomofufe.bash

**Comment by MylesIsCool** [comment]
Do you still get this issue? Have you tried with different setups?

**Comment by MylesIsCool** [comment]
If you still get this error could you try latest dev build & request reopen with the error (the old screenshot went away)

Kind regards
