### ISSUE TITLE
Help with packets

### ISSUE THREAD

**Issue by maxim19116** [MylesIsCool/ViaVersion#634]
Give advice on how to make so that PI log player sent more packets than usual? Please help.

**Comment by MylesIsCool** [comment]
By default when players are kicked it will be logged in your console: https://docs.viaversion.com/display/VIAVERSION/Configuration#Configuration-GlobalPacketLimiterOptions

If you want to code something:
You can use the ViaVersion API to get the PPS, There is a UserConnection.getPacketsPerSecond() (not in the docs as there's an issue with getters and setters at the moment)

Or you can code it yourself, https://github.com/MylesIsCool/ViaVersion/blob/fac7eab59e8f4845f7392e52a767927f1d4ef99d/common/src/main/java/us/myles/ViaVersion/api/data/UserConnection.java#L150
