### ISSUE TITLE
Mobs some times not showing while using Minecraft 1.11

### ISSUE THREAD

**Issue by Zaino60** [MylesIsCool/ViaVersion#637]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/10b38dd7e52d8d3b23628be751f08a8c

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

BungeeCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:01f4448:1226 by md_5
This bug is server-side, plus I'm not using ViaVersion Bungee version. (I'm using the spigot plugin)

### How does this error happen? login? Using an item? 
Some times when using a 1.11 client in a 1.8 Minecraft server w/ ViaVersion, it may randomly happen that mobs stop appearing to you when they are actually there, whilst if you re-log with Minecraft 1.8 you always see them and this doesn't happen, it's very weird.
Here's an example video showing the bug: https://www.youtube.com/watch?v=yqAZWgFzTrc&feature=youtu.be

### Is there an error in the console? Use pastebin.com. Is there a kick message?

No there's not.

**Comment by BabelSolea** [comment]
invisible mobs - thats a ug of mc 1.11.x not of that plugin.
have 1.11.2 server with out VV and have same bug.

mobs have sounds but invisible and usually they back after some time.. few hours usually

**Comment by Zaino60** [comment]
That sucks lol, but thanks for letting me know. Gotta report it to Mojang then!

**Comment by BabelSolea** [comment]
that knwn bug. Majong know it.

**Comment by MylesIsCool** [comment]
Closing as looks like a MC bug.
