### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by mineyannik** [MylesIsCool/ViaVersion#638]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/f0427853f7b0c41818dd1409858b96e4

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
- BungeeCord 
- Spigot

### How does this error happen? login? Using an item? 
I do not know

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/vbYkQymJ

**Comment by mineyannik** [comment]
This is in the console before the crash.

http://pastebin.com/LEz4F3a5

**Comment by mineyannik** [comment]
Again a crash
http://pastebin.com/gYkaUhKL

**Comment by MrPowerGamerBR** [comment]
Are you sure this is caused by ViaVersion?

**Comment by mineyannik** [comment]
I do not know but i think so because in every crash report there ist this line
` Recent tasks from 9673-9703{ViaVersion:us.myles.ViaVersion.bukkit.listeners.protocol1_9to1_8.HandItemCache@9703,ViaVersion:us.myles.ViaVersion.bukkit.listeners.protocol1_9to1_8.HandItemCache@9705,ViaVersion:us.myles.ViaVersion.bukkit.listeners.protocol1_9to1_8.HandItemCache@9707,BuycraftX:net.buycraft.plugin.execution.strategy.PostCompletedCommandsTask@9709,LogBlock:de.diddiz.LogBlock.Consumer@9709,ViaVersion:us.myles.ViaVersion.bukkit.listeners.protocol1_9to1_8.HandItemCache@9709,ViaVersion:us.myles.ViaVersion.bukkit.listeners.protocol1_9to1_8.HandItemCache@9711,ViaVersion:us.myles.ViaVersion.bukkit.listeners.protocol1_9to1_8.HandItemCache@9713,ViaVersion:us.myles.ViaVersion.bukkit.listeners.protocol1_9to1_8.HandItemCache@9715,ViaVersion:us.myles.ViaVersion.bukkit.listeners.protocol1_9to1_8.HandItemCache@9717,ViaVersion:us.myles.ViaVersion.bukkit.listeners.protocol1_9to1_8.HandItemCache@9719,ViaVersion:us.myles.ViaVersion.bukkit.listeners.protocol1_9to1_8.HandItemCache@9721,ViaVersion:us.myles.ViaVersion.bukkit.listeners.protocol1_9to1_8.HandItemCache@9723,ViaVersion:us.myles.ViaVersion.bukkit.listeners.protocol1_9to1_8.HandItemCache@9725,ViaVersion:us.myles.ViaVersion.bukkit.listeners.protocol1_9to1_8.HandItemCache@9727,BuycraftX:net.buycraft.plugin.execution.strategy.PostCompletedCommandsTask@9729,ViaVersion:us.myles.ViaVersion.bukkit.listeners.protocol1_9to1_8.HandItemCache@9729,ViaVersion:us.myles.ViaVersion.bukkit.listeners.protocol1_9to1_8.HandItemCache@9731,ViaVersion:us.myles.ViaVersion.bukkit.listeners.protocol1_9to1_8.HandItemCache@9733,}`

And there is a lot of viaversion stuff

**Comment by mineyannik** [comment]
I disabled Via Version as I mentioned before. My server crashes again so it is definitely not a Via Version bug.

Sorry for the circumstances, you made a great plugin!
