### ISSUE TITLE
Error in my hub server

### ISSUE THREAD

**Issue by xion87** [MylesIsCool/ViaVersion#639]
### What is the output link of /viaversion dump? 
https://gist.github.com/dff0821b18bd1a98552c3156daacf796

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Waterfall, changeskin

### How does this error happen? login? Using an item? 
dunno i think is a issue with libdisguise or ultracosmetic

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://hastebin.com/minesuyeqe.md

**Comment by MylesIsCool** [comment]
Read the error, not down to ViaVersion, only the plugin author can fix this. There is a config option if you wish to fix this (suppress-metadata).

 [Netty Server IO #3/WARN]: [ViaVersion] This is most likely down to one of your plugins sending bad datawatchers. Please test if this occurs without any plugins except ViaVersion before reporting it on GitHub
[15:15:36] [Netty Server IO #3/WARN]: [ViaVersion] Also make sure that all your plugins are compatible with your server version.
[15:15:36] [Netty Server IO #3/ERROR]: [ViaVersion] An error occurred with entity meta data for ENTITY OldID: 9
