### ISSUE TITLE
1.9 spigot cant connect as 1.10 1.11.2 clients.

### ISSUE THREAD

**Issue by BabelSolea** [MylesIsCool/ViaVersion#642]
VV dump https://gist.github.com/anonymous/feba5073d8b8f49e426d347eecbe3c38

can't connect from clients:
1.11.2
1.10

can connect from clients:
1.9

puur spigot 1.9
vanilla world
+ viaversion 1.04 default config

log.log info:
```
[16:13:58 INFO]: UUID of player BabelSolea is c8b6216e-93ee-33bb-bfe1-8ba020d08116
[16:13:59 INFO]: BabelSolea[/95.27.125.26:13330] logged in with entity id 14 at ([world]36.825521191747946, 69.0, 249.16393174962235)
[16:13:59 INFO]: BabelSolea lost connection: Internal Exception: java.io.IOException: Error while writev(...): Broken pipe
[16:13:59 INFO]: BabelSolea left the game.
```

connect client error
![image](https://cloud.githubusercontent.com/assets/23665302/24049716/eaa5e904-0b3d-11e7-9c19-d2cb7791b15e.png)

what i did wrong? what should i do?

**Comment by MylesIsCool** [comment]
Are you able to test with a version slightly higher than 1.9?

Some builds of 1.9 spigot are weird as some have the protocol compatibility with 1.9.1.

**Comment by BabelSolea** [comment]
im noob with using some multi versions plugins)
so can ure help me with that case scheme:

bungee- latest
-lobby server any version - players clients 1.8-1.11.2
--minigame #1 server 1.8 - players clients 1.8-1.11.2
--minigame #2 server 1.9 - players clients 1.8-1.11.2
-- minigame #3 server 1.11.2 - players clients 1.8-1.11.2
-- survival server 1.11,2 - players clients 1.8-1.11.2

so where i need put VV?
and d i need use somewhere protocol plugin?

**Comment by MylesIsCool** [comment]
You can just use ViaVersion on the Bungee.

If you want to handle older clients, use another plugin, like ProtocolSupport. (ViaVersion isn't for you in this case)
