### ISSUE TITLE
ViaVersion - git-Spigot-283de8b-4316a8c (1.11.2)

### ISSUE THREAD

**Issue by Thymue** [MylesIsCool/ViaVersion#645]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/e9232dd01350558f6222502281b6400a

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No, just spigot
Plugins (3): ViaVersion, ProtocolLib, ServerListPlus

### How does this error happen? login? Using an item? 
Server starting, after Done message

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Yes, http://pastebin.com/rzg2XRbL

**Comment by Thymue** [comment]
(it's just not working at all)

**Comment by Thymue** [comment]
On other spigot version it works so 1.11.x players can connect..

**Comment by Thymue** [comment]
Also it says "ViaVersion detected server version: 1.11.1(316)" and i have Spigot 1.11.2 installed

**Comment by MylesIsCool** [comment]
This message is due to an issue in our update service provider Spiget and will be resolved soon, it has no impact on ViaVersion.

Via does not allow any versions when running on 1.11.1. It supports only newer versions.
