### ISSUE TITLE
Some lag issues.

### ISSUE THREAD

**Issue by fanikz** [MylesIsCool/ViaVersion#647]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/af912bb6619397a75d218b55eb4f3602

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No I am not using BungeeCord.

### How does this error happen? login? Using an item? 
Random times. A lot of lag spikes.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://hastebin.com/pavinosado.lua

**Comment by MylesIsCool** [comment]
Fingers crossed this should be fixed, https://github.com/MylesIsCool/ViaVersion/commit/ce286cf322f820e1f80d2da654a0e6c83ea5115a
