### ISSUE TITLE
Error in console. Crash on command execution

### ISSUE THREAD

**Issue by ICEconchy** [MylesIsCool/ViaVersion#648]
### What is the output link of /viaversion dump? 
Unable to get viaversion dump due to crash on command execution.

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Latest version of bungeecord.
Plugins:
Advanced-portals
Animatronics
ArmorStandTools
Multiverse-Core
ProdigyGadgetDiamon
Protocollib
ServerSelectorX
Viaversion

### How does this error happen? login? Using an item? 
When starting the server, once everything enables and loads, the error appears.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/U8V278Fb

**Comment by MylesIsCool** [comment]
Redownload ViaVersion and try again?

**Comment by ICEconchy** [comment]
I've done that. Same thing.

**Comment by MylesIsCool** [comment]
So what's the full console output? To me it looks like file corruption but it could be something else I guess.

**Comment by MylesIsCool** [comment]
I would assume you've probably solved this as I've seen your posts on spigot, considering you're having it with other plugins i'd assume it's a java / network issue.
