### ISSUE TITLE
Join Error

### ISSUE THREAD

**Issue by ChavitaHD** [MylesIsCool/ViaVersion#65]
Hello,

Throws this error on startup:
https://paste.parallaxmc.com/ikimupozif.avrasm

**Comment by HugoDaBosss** [comment]
This probably has been fixed already:
https://github.com/MylesIsCool/ViaVersion/commit/99fd01c3590de40c207ba8a74c516a8ace0a4651

**Comment by ChavitaHD** [comment]
I am on the newest version.

**Comment by HugoDaBosss** [comment]
Did you build it yourself or did you download it? Because this commit isn't yet in the public build.

**Comment by ChavitaHD** [comment]
Download, I'll wait for a public release then.

**Comment by HugoDaBosss** [comment]
The (supposed) fix should be in the latest version: 0.4.5

**Comment by Paulomart** [comment]
@ChavitaHD is this still happening with the latest version? Otherwise close please.
