### ISSUE TITLE
Server crashes when anyone logs in

### ISSUE THREAD

**Issue by FuZyKingZ** [MylesIsCool/ViaVersion#650]
### What is the output link of /viaversion dump? 
cant do the command as i cant join the server

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Im using Waterfall(latest build) 

Plugins:
WorldEdit, EmptyWorldGenerator, TimTheEnchanter, killStats, ClearChat, GroupManager, ClearLag, SimpleFreeze, PlugMan, DiscordMC, WorldBorder, NametagEdit, BuycraftX, WorldGuard, Multiverse-Core, SignEdit, DeluxeTags, MobStacker, iDisguise, EchoPet, CommandWatcher, ViaVersion, WGCustomFlags, Tablist, Vault, ChatColor, BetterAlias, ChestShop, Essentials, SimpleRename, CommandSigns, ProtocolLib, Citizens, AuctionHouse, Spawners, ChestCommands, EssentialsProtect, EssentialsChat, RandomTeleport, PlayerVaults, SuperVanish, EssentialsSpawn, LiteBans, Factions, CrazyEnchantments, ObsidianDestroyer, FactionChat

### How does this error happen? login? Using an item? 
Login

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/FRqPYGmH

**Comment by MylesIsCool** [comment]
This is not ViaVersion related and is some sort of chunk corruption, i'd suggest running some sort of region fixer on your server.
