### ISSUE TITLE
Guardian render issue again on 1.10.2 running spigot 1.8

### ISSUE THREAD

**Issue by net32** [MylesIsCool/ViaVersion#656]
Guardian render issue again on 1.10.2 running spigot 1.8

**Comment by MylesIsCool** [comment]
It would be nice if you filled in the issue template perhaps providing screenshots, unfortunately, I am not psychic so I don't really know what happens and what should happen.

**Comment by xion87** [comment]
@MylesIsCool maybe is related to my ticket #660

**Comment by MylesIsCool** [comment]
If you have this issue consider asking for reopen with info so we actually know what's wrong.
