### ISSUE TITLE
Use bStats for metrics

### ISSUE THREAD

**Issue by MiniDigger** [MylesIsCool/ViaVersion#658]
since via is a extremely popular resource, its also a great way to gather anonymous stats about server versions or java versions. 
since mcstats.org is dead for quite some time now, I suggest using bStats.  https://bstats.org/
its a multi platform metrics service, so it will also work for sponge and bungee.
setup is easy, you just shade and relocate or just copy paste a class and call a method on it. server admins can easily opt out of the service if they don't want their data to be shared.

**Comment by LaxWasHere** [comment]
http://i.imgur.com/dMLZJBP.png

**Comment by MiniDigger** [comment]
if there is significant interest in this I can submit an PR later today.

**Comment by MylesIsCool** [comment]
At this point in time, I don't believe this to be in the project's interest, why?

- It does not really enhance ViaVersion for the user (They only really help us, and it becomes another service to depend upon)
- A lot of users don't read changelogs etc, so they wouldn't be informed that their server has started to submit anonymous statistics.

In regards to the latter, I asked some server owners using the plugin and the general consensus was they'd turn it off or said they were not fond of the idea.

This, of course, could change in the future but at this point in time, it's not something for ViaVersion.
