### ISSUE TITLE
Incorrect Fire Charge Velocity

### ISSUE THREAD

**Issue by HugoDaBosss** [MylesIsCool/ViaVersion#66]
When shooting a fire charge from a dispenser it will just stutter forward.
The charge it self doesn't move, it just teleports a few meters everytime.
There is probably something wrong with the Entity Velocity packet, as arrows tend to behave strange sometimes as well.

**Comment by Matsv** [comment]
Same problem on 1.8. Don't think ViaVersion is causing this.
https://fileserver.matsv.nl/media?id=e1b5b3b62b01a8362c933eaca08ad341

**Comment by HugoDaBosss** [comment]
You are right, didn't know such big bugs were in the 1.8 bukkit. Will close this issue.
