### ISSUE TITLE
Invisible mobs and Armor Stands

### ISSUE THREAD

**Issue by xion87** [MylesIsCool/ViaVersion#660]
### What is the output link of /viaversion dump? 
https://gist.github.com/67b2d019a355f164d4c2d0014cdef839

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Latest Waterfall

### How does this error happen? login? Using an item? 
No errors:
Server is 1.8.8:
1.11 cllients: i got cases where some players don't see the mobs (like zombie, creepers  or villagers ecc) and are invisible until reloging
1.8.x: players are claiming that sometimes armor stands are not loaded correct and are invisible until reloging

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Nope

**Comment by MylesIsCool** [comment]
ViaVersion doesn't modify 1.8 data so if it happens on 1.8 too i'm not really sure that ViaVersion could be causing it

**Comment by xion87** [comment]
i tried to downgrade and see if this still happen

**Comment by MylesIsCool** [comment]
So does this happen on 1.8.8 client?

**Comment by xion87** [comment]
well, i downgraded and seem all issues gone
for 1.8.8 it happen only for armor stand on my creative server (like entity not loaded) instead for 1.11 this issue related to all mobs/armor stand

**Comment by MylesIsCool** [comment]
What version did you downgrade to?

**Comment by xion87** [comment]
1.0.3

**Comment by MylesIsCool** [comment]
There are no changes to entities between those versions (excluding bossbar mechanics, which only touch enderdragon / wither).

If you decide to update in the future, it would be nice if you could test on different versions to attempt to locate which Minecraft version causes the issue. If you're using any ProtocolLib plugins that use mobs this could also be a cause.

**Comment by MylesIsCool** [comment]
See above for info on why this is being closed, request reopen if reinvestigation wanted.
