### ISSUE TITLE
Connexion impossible with higher version than the server version

### ISSUE THREAD

**Issue by C0LiSii0N** [MylesIsCool/ViaVersion#661]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/1e0d04ccfe9d6b9888edc71cd799e8aa

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I have spigot 1.9 with only ViaVersion v1.0.4

### How does this error happen? login? Using an item? 
On login player have this error;
Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/32 (gt) was larger than I expected, found 120832 bytes extra whilst reading packet 32

### Is there an error in the console? Use pastebin.com. Is there a kick message?
The only thing in my logs is this;
[18:32:11] [Server thread/INFO]: OnSenFou lost connection: Internal Exception: java.io.IOException: Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte

**Comment by MylesIsCool** [comment]
There are specific builds of early 1.9 craft bukkit that don't work with ViaVersion, either use spigot or use a later 1.9 build.

Unfortunately, it's because spigot created compatibility themselves which causes the software to not know which build it is.
