### ISSUE TITLE
Repo for OpenNTB

### ISSUE THREAD

**Issue by przemek3697** [MylesIsCool/ViaVersion#662]
Repo for OpenNTB Library is unreachable
``
 from/to spacehq-repo (https://repo.spacehq.org/content/repositories/releases/): repo.spacehq.org: Unknown host repo.spacehq.org
``

Look in your Jenkins job console, u have this same issue :) But your jenkins is using local version of this lib :/

**Comment by przemek3697** [comment]
similar issue with org.yaml.snakeyaml
in maven central you can find official version 1.18 (not snapshot)
[Maven repo](https://mvnrepository.com/artifact/org.yaml/snakeyaml/1.18)

**Comment by DarkShimy00** [comment]
The dependency has moved to com.github.steveice10.opennbt as of commit https://github.com/Steveice10/OpenNBT/commit/659bda0f7c1bb8f6986ca518e38c1cc0874b0ceb.

**Comment by MiniDigger** [comment]
I brought that up earlier this week, @matsv wanted to setup a public mirror on Jenkins. idk what the status on that is.
