### ISSUE TITLE
Client crash when sending custom PacketPlayOutEntityEquipement

### ISSUE THREAD

**Issue by Marcely1199** [MylesIsCool/ViaVersion#664]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/eaeff05f44e0316d7eca75fe9ff1a62b

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
:(

### How does this error happen? login? Using an item? 
When sending the packet PacketPlayOutEntityEquipement to a player.
Entity is holographic so server doesn't know anything about it.
My code is the the following:	
```
public static Object createPacket(int entityId, Equipment e, ItemStack is){
		try{
			final Object nmsIS = NMSClass.CRAFTITEMSTACK.getMethod("asNMSCopy", ItemStack.class).invoke(null, is);
			
			if(Version.version.getVersionNumber() < 9)
				return NMSClass.PACKETPLAYOUTENTITYEQUIPMENT.getDeclaredConstructor(int.class, int.class, NMSClass.ITEMSTACK).newInstance(entityId, e.v18, nmsIS);
			else
				return NMSClass.PACKETPLAYOUTENTITYEQUIPMENT.getDeclaredConstructor(int.class, NMSClass.ENUMITEMSLOT, NMSClass.ITEMSTACK).newInstance(entityId, NMSClass.ENUMITEMSLOT.getMethod("valueOf", String.class).invoke(null, e.v19), nmsIS);
			
		}catch(InstantiationException | IllegalAccessException | IllegalArgumentException | InvocationTargetException | NoSuchMethodException | SecurityException e1){
			e1.printStackTrace();
		}
		
		return null;
	}
	
	
	public static enum Equipment {
		Helmet(5, "HEAD"),
		Chestplate(4, "CHEST"),
		Leggings(3, "LEGS"),
		Boots(2, "FEET"),
		MainHand(0, "MAINHAND");
		
		private int v18;
		private String v19;
		
		private Equipment(int v18, String v19){
			this.v18 = v18;
			this.v19 = v19;
		}
	}
```

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Kick message: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: 6

Please fix it quickly because my clients are going to kill me else

**Comment by Matsv** [comment]
Does the client also disconnect on 1.8?

**Comment by MylesIsCool** [comment]
Since you're running for a 1.8 server all packets sent should be for 1.8, the indexes for your Equipment enum are for 1.9+.

For 1.8 equipment is - Equipment slot. 0: held, 1–4: armor slot (1: boots, 2: leggings, 3: chestplate, 4: helmet)

**Comment by Marcely1199** [comment]
Now it isn't working completly
