### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Deathworld** [MylesIsCool/ViaVersion#665]
Hey, I just updated ViaVersion in the last dev version, and I have big errors :/

### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/af22dcdc79d788fa1a67dafc7b5b0e04

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yes, I'm using BungeeCord

### How does this error happen? login? Using an item? 
On Login

### Is there an error in the console? Use pastebin.com. Is there a kick message?
`19:35:27 [GRAVE] java.lang.NullPointerException
19:35:27 [GRAVE] 	at us.myles.ViaVersion.protocols.protocol1_11to1_10.ItemRewriter.toClient(ItemRewriter.java:100)
19:35:27 [GRAVE] 	at us.myles.ViaVersion.protocols.protocol1_11to1_10.packets.InventoryPackets$3$1.handle(InventoryPackets.java:66)
19:35:27 [GRAVE] 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:18)
19:35:27 [GRAVE] 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:96)
19:35:27 [GRAVE] 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:150)
19:35:27 [GRAVE] 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:423)
19:35:27 [GRAVE] 	at us.myles.ViaVersion.api.PacketWrapper.constructPacket(PacketWrapper.java:331)
19:35:27 [GRAVE] 	at us.myles.ViaVersion.api.PacketWrapper.send(PacketWrapper.java:301)
19:35:27 [GRAVE] 	at us.myles.ViaVersion.api.PacketWrapper.send(PacketWrapper.java:286)
19:35:27 [GRAVE] 	at us.myles.ViaVersion.api.PacketWrapper.send(PacketWrapper.java:348)
19:35:27 [GRAVE] 	at us.myles.ViaVersion.protocols.protocol1_9to1_8.storage.EntityTracker.setSecondHand(EntityTracker.java:83)
19:35:27 [GRAVE] 	at us.myles.ViaVersion.protocols.protocol1_9to1_8.storage.EntityTracker.handleMetadata(EntityTracker.java:167)
19:35:27 [GRAVE] 	at us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.SpawnPackets$7$4.handle(SpawnPackets.java:338)
19:35:27 [GRAVE] 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:18)
19:35:27 [GRAVE] 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:96)
19:35:27 [GRAVE] 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:150)
19:35:27 [GRAVE] 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:423)
19:35:27 [GRAVE] 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:73)
19:35:27 [GRAVE] 	at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:61)
19:35:27 [GRAVE] 	at us.myles.ViaVersion.bungee.handlers.BungeeEncodeHandler.encode(BungeeEncodeHandler.java:18)
19:35:27 [GRAVE] 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
19:35:27 [GRAVE] 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
19:35:27 [GRAVE] 	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1022)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:291)
19:35:27 [GRAVE] 	at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:51)
19:35:27 [GRAVE] 	at net.md_5.bungee.UserConnection.sendPacket(UserConnection.java:189)
19:35:27 [GRAVE] 	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:104)
19:35:27 [GRAVE] 	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:86)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
19:35:27 [GRAVE] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
19:35:27 [GRAVE] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
19:35:27 [GRAVE] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
19:35:27 [GRAVE] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
19:35:27 [GRAVE] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
19:35:27 [GRAVE] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
19:35:27 [GRAVE] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
19:35:27 [GRAVE] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
19:35:27 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
19:35:27 [GRAVE] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
19:35:27 [GRAVE] 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1017)
19:35:27 [GRAVE] 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
19:35:27 [GRAVE] 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
19:35:27 [GRAVE] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
19:35:27 [GRAVE] 	at java.lang.Thread.run(Thread.java:745)`

Thanks ! :)

**Comment by Matsv** [comment]
Blame me, will look into it

**Comment by Matsv** [comment]
Actually, could you try to use the latest version? The one you use now is a few commits behind. This issue is fixed in commit https://github.com/MylesIsCool/ViaVersion/commit/c92fcc9f9af4052d59481652a590f391b881e3fa
