### ISSUE TITLE
Multiple bossbars

### ISSUE THREAD

**Issue by przemek3697** [MylesIsCool/ViaVersion#666]
ViaVersion 1.0.4 on BungeeCord build 1213
Spigot server ver 1.8.10 

On one of the servers we have citizens to spawn some mobs as info on their customName.
One of this mobs is Wither, everything is fine until the player change server, the bossbar is visible all the time until it logs out of the server. If player return to server where we have this wither, player can see multiplied bossbar's.
Affected MC versions 1.9.x & 1.10.x
If u want screenshot pleas tell mi that.

To be clear, if I disable bossbar path in ViaVersion config, affected players **can't see any** bossbar from our server.

In recent days I was looking for some easy access method to clean this bossbars for player who switch server but I cant find any method not using reflection ofc.

**Comment by przemek3697** [comment]
issue number 666 hell yea :D

**Comment by MylesIsCool** [comment]
Could you try the latest BungeeCord to see if that makes a difference?

And also could you provide the output of /viaversion dump?

**Comment by przemek3697** [comment]
Latest version of bungee (1233) have this same issue.
There u have viaVersion dump but I need to edit this (only server names, and plugins (only ours))
https://gist.github.com/przemek3697/340c9939e37c3b7794a38fd2e27fad68

**Comment by przemek3697** [comment]
In heap-dump every map with "bossbars" is clear. Looks like bungee & you remove all data about bossbars. But they are still in user view... Looks like packet with remove flag isn't working ( || sending)

**Comment by MylesIsCool** [comment]
So are all your subservers 1.8?

**Comment by przemek3697** [comment]
Yes

**Comment by przemek3697** [comment]
Can I provide u some extra data or something? Because i dont know what we are standing on right now. You are doing some fix or u know what is going on but u don't know how to resolve this?

**Comment by MylesIsCool** [comment]
At this point in time, I'm unsure of the cause. If you could provide instructions on how to exactly replicate eg.

1. Login to server with citizens wither
2. Logout
3. Login again and it duplicates
4. If you then change server you will see it fixes it.

Something like that just to make sure everything is clear so we can get it solved. And also clarifying when you say log out if you mean switch server or logging out of the bungee.

**Comment by przemek3697** [comment]
Bungee -> BungeeCord (1213 or latest) with ViaVersion 1.0.4
Spigot -> Minecraft server instance for Minecraft 1.8.8 (protocol 47)

First method:
1. Login to Bungee
2. Switch spigot instance without citizens to spigot instance with citizens and wither
3. Switch spigot instance to spigot instance without citizens (on this point u can still see bossbar from the previous one spigot instance)
4. Switch spigot instance to spigot instance with citizens and wither (on this point u will see second bossbar)
5. Logout from Bungee

If u will repeat point 2 six times u will see six bossbars 

It also can be reproduced in this steps (second method):
1. Login to Bungee
2. Switch spigot instance without citizens to spigot instance with citizens and wither
3. Switch spigot instance with citizens and wither to another instance with citizens and wither (at this point u will see second bossbar)
4. Repeat point 3 (u will see third bossbar)
...
10. (u will be able to see ten bossbars)
11. Logout from Bungee

Only step "Logout from Bungee" can remove bossbars from user view.
1. (Method first or second)
2. Login to Bungee (at this point you no longer see any bossbars)

Logout is logging out from bungee (to clarify ;) )

**Comment by Matsv** [comment]
Confirmed.
The code that should handle this in Bungee doesn't do anything since bungee thinks the client version is 1.8 with Viaversion (https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/ServerConnector.java#L220-L225).

Possible patch: track the BossBars and send remove packets on server switch without breaking the current functionality of the ViaBossBar API.

I will work on a patch when I have more time if nobody else did it yet. (:

**Comment by przemek3697** [comment]
I think I have a fix. But need more time.
(information only)

**Comment by Matsv** [comment]
@przemek3697 I created a small patch that fixes it for me. Could you try if this build solves your issue? (: (https://fs.matsv.nl/files/ViaVersion-BungeeBossPatch.jar)

**Comment by przemek3697** [comment]
@Matsv Yep every thing is working now 👍 
(I was close to write this same code :/ )
Question
U dont't need to add this check??
if(user.get(ProtocolInfo.class).getPipeline().contains(Protocol1_9TO1_8.class)){

**Comment by Matsv** [comment]
@przemek3697 Thanks for testing, will push it to master. That check is unnecessarily since `EntityTracker.class` will only be created if you use that pipe. So this check: 
`if (user.has(EntityTracker.class)) {` is basically always false if you are not on that pipe  (:
