### ISSUE TITLE
Can't join in 1.12

### ISSUE THREAD

**Issue by Deathworld** [MylesIsCool/ViaVersion#667]
### What is the output link of /viaversion dump? 
https://gist.github.com/dcc886eddd4cddd5e877b3469b070b51

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I'm using BungeeCord. The plugins are availables in the Dump :P 

### How does this error happen? login? Using an item? 
I don't have any errors in my console, I can use commands ect in the console but I can't login : It says outdated version, but I'm using 1.12 pre2 with the last ViaVersion Dev Version, and I don't have the errors in the servers list... (there ^^ http://prntscr.com/f98dp4)... I know it's not clear, but sorry, I'm bad in english :(

### Is there an error in the console? Use pastebin.com. Is there a kick message?
I don't have any errors in my console...

Thanks !

**Comment by Matsv** [comment]
Could you try the latest version in combination with 1.12-pre4? (:

**Comment by Deathworld** [comment]
Just tried, and "outdated server" :/
Thanks !

**Comment by Matsv** [comment]
What version did you use as client and could you give me a new /viaversion dump output?

**Comment by Deathworld** [comment]
I was using 1.12pre4
https://gist.github.com/29c1c89469a8a4c608133281935d5194
Thanks !

**Comment by Deathworld** [comment]
So I just came back to an older version, 1.0.5-1.12pre2, but I got this error when I tried to connect I got this error : http://prntscr.com/f9aubw
https://gist.github.com/cd46debdf935eeda5b43c530271df391

Thanks !

**Comment by Matsv** [comment]
@Deathworld that issue was fixed a few commits ago. Could you use the latest version, enable /viaversion debug on your BungeeCord and try to connect and paste the full log? Thanks (:

**Comment by Deathworld** [comment]
`16:22:31 [INFOS] [ViaVersion] INCOMING: HANDSHAKE 0 -> 0 [HANDSHAKE[47]] Value: PacketWrapper{packetValues=[], readableObjects=[Pair{Type|VarInt, 47}, Pair{Type|String, mc.nobordercraft.fr}, Pair{Type|Integer, 25565}, Pair{Type|VarInt, 1}], id=0}
16:22:31 [INFOS] [ViaVersion] INCOMING: STATUS 0 -> 0 [STATUS_REQUEST[47]] Value: PacketWrapper{packetValues=[], readableObjects=[], id=0}
16:22:31 [INFOS] [ViaVersion] OUTGOING: STATUS 0 -> 0 [STATUS_RESPONSE[47]] Value: PacketWrapper{packetValues=[], readableObjects=[Pair{Type|String, {"version":{"name":"BungeeCord 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x","protocol":47},"players":{"max":200,"online":0},"description":{"extra":[{"color":"green","text":"» "},{"color":"aqua","bold":true,"text":"Dragonia "},{"color":"gold","text":"- PvP-Faction - Magie - 1.8 à 1.12\n"},{"color":"green","text":"» Serveur ouvert - "},{"color":"red","bold":true,"text":"BETA"}],"text":""},"favicon":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAPM0lEQVR42u1bCZBU1RU9v7tnBhgG2fdl2FRQEIYdWWVfBEFEVgUBQQQUiKIiKooLBNS4BssVMW5VIWW0olGDVUSrkljR0kSlTNwSklKrIkFFZv7ycs7v94dPT/cIOMho5lGvuqfnz+937zv33HPv+wA1o2bUjJpRM2rG9zmc2Mz8HAn++xFY6EQGJfORn2qGxqkpGJMwSP97BTty/in/NsXXVOiLik6q/rYnkUh1RnEy+mArNmXucgFnXc76nPn2cxnbSg7Lcs/IIdXaGU4RClNnY2x8kY04x3BeXYD8x/j7XfVR76+cHzdE/T38bD9/NzR2/T2cn3A+zbmIs0fMQXFnVKsYcQpRJ9UJxcRtCnlIFfKzGYWo/et2aLW3O042/dDDnI5e4RyAnqYPuvunoYupizrv8No8e59kbdSSYZMZAu8TRYavPn/+kPMhfc5ZGPve5HFzBHePW1uf5qaSjdEgYWO+AV+uaoXm/5ShZ2F0MANnmnMw3p+Eke4YDHGHob83ECV+f/Qs64A2htevTFuSLIiTIEdzzjd5T10jJwScer+HcyNncez65HHZ9TqoFX7xCSgSJJdxtz+dgOFmMWYGSzDLm4spLo0PJmOU0eejMdgMR3+ioHcgFNBxe23MR6MrDf4ZEfRePvK+oHO/ZjaIHOByetYJhp9/k4Bzt3XU94MG5+C/RB3UjrzetzEaviEDf4KF/mosdC/ETH8ezjZzcJY5FxPNVIwxZ2KEGYsh5gwMMEPRz+uJUwyNfLoo5EE0JdwfqIe6pXSKaYQGAZ1q+B2GTjCR0Zo2JOQMX+igE77g+yXHHA2KbRIW755IDkIfh0bry67rjW7+ZbjQrMel7ios8JfhPMPdNwsw3ZyHKUYhQFI0DAEzDkPNCAzU9E5Eexk0196+C0PgI6ZJ0xYtS5ugkUuSDMghcpKxhoYO0N+txcW6Z0DnlTuCry9wtoiRZNWNPP6T8YRd5N0m3K2XZnB3b8Val8Z7a7CYCFhkVmCeuQizzUKca84nCmZhkjjAKAzGEyUjcXowAqebVmhWyvt00M24045d9AYaHTRFo4Ac45EgDb/X2DAIJ9diZmOy2YobzT243pBIQ0RYJ/ybc3CVOoE7zjslYYVJuFut0eLvMpgLKLseK4NrscJchaVGSLgU883FmGsuxAwzD9PCxU7HBDMFo81EnGHGYLA/nGFAA3fH4JqIvR9MDviECDAMA7cWCgzRcUgYaJJ/TAnDaBB6G2u8a3+n13OrxAmxmI8W1+skdPh8M67SDri34HJzE34i+JurCcvL6ZSVuMAoDEiE5gKcU4EHxmGYNwR9lf5eogFgNkg0II3q67jT0YKb8v3vmVoNEeHGeUDGWoOzTd9OvZ9TVU6IjD+1Kzp9/nNsMA/gFu82XG220BE30wlEgVmH5eYKLDEkQbMc58d4YKqZSR6YhnEhD5As3cHoY2qj4OnmaAKiKbx/fhhoeXGkMS6cF6kLFAZeptFpXkgcEh4ZTlDaHB/LEEddsIQ7wpz9vuJuO271FHt34jrFv9mINeYGrDLXMAyuxEUhD1xCHliKOVl5gChwhQAa9nQLOqCNdUCFyEuPIhr4Z8sDfo5dz4UEvf6H86RYmB1J7CexDsvoXl95/tnNuNL8Eve69+Nmcx9uMndhvREKNuEKcyNWm+twSVYemJ/BA3SAp1RISfwS1SAYw4mcS7DagDy0L5XmgeAInBBphl1HhQAuMPqjVYL0b7HNfQSbzcP4aeiAuw9xQMQDy8yakAcWWB6YFfLA3DAdigfGygG+9ADz/XuxXXFyZt/0uNTKYu9bjM50UESMVx4RH0jo2LcnUrruexHbzJO4M9iO2+SAgNN7EBtdOsIlElxygbsBqz0SYSAiFA+soNOUDrPwQCAyZL5XEdQ24/sqjKZoHGZiXvNGTBZ/G/wj1Rg5ZB9n58MKBcIdozAoWYJThYLHFffP42GP8PefwwPeE7jD3I51IelR+IRwv4xxfw1/FhJuwEqPYeALNeKBRVl4gDWCdypO1MKm2OZHstJoTI/Z1gG5UFCaBQFyxgH7ftthEWLy4GIGa9d24Sn/d3hMhgdKbazqPiV5PUdiul1KkIuneKlzPwugV5nWvqRxQkBwBS7y5ICIB9LpMM0DdILLeoCiJnUf0xyYBpOp3OiMwqMW5+4Mkos75BrOlpyjOS/nfDV2nWdn30pRQHUHwjbBxRJ4DZ55FLeaP2JHKY0xxWj9F5W4FCh1c8UtDWrGl4WUtO8q5REZngqjOA+cbXlgPIYZXvePEHRpFDiVKvH02JAR23EH7IjtcHSvXravUGavebJSB3AR0S/6U8cHf8AOn3lbsFpP6RouojdKnPMxLdEazVN0Roq7lzoZHVNrsbzcAEpb1fe3kOWVEv2DPDCpXA9MxsgoDM6PkJfKjc5oXf2ykF30/jPbfIHtL8RbaQM4/2Sv658zFKjTkyxZmZ0bPijBw3ytcnWiftcGLZOUn2FLSjyRsfO2mVGQz+Iovx96Rjef35tOECGKB5QOxQNnpWWxr8KIqNPCEn/DTqeSRmg8DD7MEgbR+xEZxiUzDL2Rc1NWB8SYuC0Xtp8l617rce5orbxcqYrqLcnSNnECwyd58J4FvF9zxrzuuakvTpM09uUA8YBkseoCTq8LOmnh8y0KKktTCdtkfS4D+vGQWJcj3cV7Bfk5MOaktAP8kmtVk3MxvVQIcXfzFmE2nghbdeWd3vAt6/bQ4svC1h1KRIiUtzu7oONHrNK+6IGuX52Czp91w0mBwmBuxfI4IOpUGO2JNTYS38IDd1XCA89UwvSH1SsQxN6yTCpOSDGe+WFBeWWYF9aGiURdFEYLHcnydRdTZ6C8r1pdqjCSxtIEksZpWTw1TIfiAaVDFkZmLIZ6ChNmgV+xMCKNN8vV2UlZ16/PqP7iIRCvMI+qe6yGY5coN9cKuwB5FbpB9tr6TGG/UCeIVWFAzvCpDENBRI3gr8GSQOlwBebRMdID8fJ4fHl5TMepVeaRSGXAnbqx0qKKsFTYhknGHBDatN4WQG4WItwXQ9JRt8+dSmAYfV7MLPCutP9TuKv0IWw6cC82SBV6FEke5bHHAsklGlyWx35aD8ykHjgnZ5uM0+2ItpK7D0ZwJ9rK299OGKLhBtxh+wNuDkHU/aiKnyxGZpJk5NGGNP4dZQlK5AOqCQR7GTjTxrcgLqhr1xUClMcew8OXA7K1ycQDqhA5XbW88pH/emQIMegQhTI+T+HHdezga7a6IAqDYd+1BM7C9CkwVhPdcbL4YLuM3oYt3iSMCDqj+C0u8g41JumhqXydwDmNcwWvvZ8C6gNmFCnCgEgIzrM8EG+TKQxYc5iBKDEDUOKRNA3DoEy7HUG6A9o6tkp9O0d5HDlkYpU7gF8Y3WyMyEwVH+uEl/nzwEexxUlW8l0t0FQkMo2ZZbcgT1QEszLaZOl2+YCwvaWU2Quneur1sWBS5+i/dMTdnOofNudmfKUmCb8zyOGAKVXugM/wuvMmngX1/ivDuJv86GJrnLMYc51OaJdSvErNEapJ5XPBlrufGoYB4UKoGpVKXhHUmRL96VYPRDwgUaROETOBHGCItoAp1CXCAqZWOWI/nfA6xZavVllmuzzmgElV7YDoRpNoZBlhPYLGEJdNaHCysi9xdCIcNTVogNLcAWUBqcIZsTaZ0qF4QKGiMJCE1rFZV4okOaAD2rit0SKg7jD1UWTkgKhdnoUDRh0rB0hljbUhkZdxBF7BeErciExXn4QOB0R+LJ0DhQB5ICBhBpEeiPOAjtQUBj3R1ahWECm2RxtD4g1YPPkUTQq/Cu3yWCrsU+UhUGTPIylSHErfBOsCtA0rzwrPAoRvH8Fm/ZDHXXqc5GmoDUqvwfJS9Q6WlrfKwgpRoeCqTXaQB/qEB6klDAORofSB0iO/0ygUhAI611geyDS+LDprOBbHZM7h3JRlboIMH2YLyd+NWOMJ9jKONUMZtf8XRMTeruhc1tP29cUByiijMcgTDwwIeaCbeMCoViDHmHZoZVqiqWmMhiY6Nkunw0Mc8C/7zMF3EkJHPcgNEeyWiNwketqgxQckRZ3mjiJK2vO1sZ16P0QhQlm9kzB3BX9ygcdUGIgHeoQ80Fk8oH6ETpMMZTdTZD2RYpwHIgJ87bgZH0NHuyLU/ZKwlS6fzd0q+JZFRZ93o0HPyVgdnpIHgogHiBjLAy3URDERD+jUKEMW33tMzgaPkCynS68zPh2d+AxGX4e7pgUlbR3hxMIpSTJLdUb7BA2KHLGcse4TBQqDIM4D0gUtMnjAtssjBMw+ng5IHxyiE/ViR3AHndq2gXK4DrTXa0yh076SHmA6DDJ5oAl5QGeHlgcCGwZfC33HigCPlCyP6GEm+1hNWPBQbCVPJpET2i8r/pkNPL0qHR7KAycYe3ocHZs9Xx2MP+LD12jRjOdo9+vRGS9QBUoU+XEeoCAKGAZ+80N5wLM8MKvK8/+xY0sVtukODUkt2cg+Y6QuLjPCbmUAlse+9EAvqweoCr1OKPa1+9IDjUMeKPLFA3TkO7aZc9wyQK4wkFwun6oP1EUegyGZR2JNacQWxniZFCF/H9cDAZ0QlsnMLp/zuneVCfQQBdOhK0UY9RR/ELt/MO6TEiwjqCzv16N0qgMojf2oW8yfAzrBpRM8xT4N1blEGzpgrUiQKDggQUQs7ZyI4aBUdqoHutPjNM7tOsjgrs8n5M+yPYLFNOAWMvhvOqLdp6r8VAuoNpiFSa7ODSfQAXqGgKowkFJkeHyjUx8SZR3bktsoBFCWu/Yhy9OqE/mV9++5UD2moqdCw+JGtb+aouoc6ZxAnaJVWFC6FHO+mY9pZawLPJ0cqT+g6/UMEVGyDQefI8qnM5QxdkgPaPejsjz2UEU1I/n0aE2iWk2F99oQ9N0vR6gjJJkctdBUMEn4kOk9svvbNOgG/l1HhMK+UE+fRgaeQMM/FglCjx8f2qypdiOZhZSKOc/R2QPT19ZC1H6EBmzVzzp3tE9zJNSL1tPk9hmFROz0eLIQxd+/KBqh0xxU54enSV5hbFK2pqbjTKcPuoEFTmhc5uiBrlKPGIfh4XPH8ZgmjyTsY3ovUSN8FB2o/hBFj3YzRQWXIomFLTP9HwLGd8o+IZaopMZQp2dPTO7+cFLe4acQp7LMcqaasD9a46uyKfNjHYn/Z+NrRs2oGTXjmI7/AT4eOvr4ct33AAAAAElFTkSuQmCC","modinfo":{"type":"FML","modList":[]}}}], id=0}
16:22:31 [INFOS] [ViaVersion] INCOMING: HANDSHAKE 0 -> 0 [HANDSHAKE[47]] Value: PacketWrapper{packetValues=[], readableObjects=[Pair{Type|VarInt, 47}, Pair{Type|String, mc.nobordercraft.Fr}, Pair{Type|Integer, 25565}, Pair{Type|VarInt, 1}], id=0}
16:22:31 [INFOS] [ViaVersion] INCOMING: STATUS 0 -> 0 [STATUS_REQUEST[47]] Value: PacketWrapper{packetValues=[], readableObjects=[], id=0}
16:22:31 [INFOS] [ViaVersion] OUTGOING: STATUS 0 -> 0 [STATUS_RESPONSE[47]] Value: PacketWrapper{packetValues=[], readableObjects=[Pair{Type|String, {"version":{"name":"BungeeCord 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x","protocol":47},"players":{"max":200,"online":0},"description":{"extra":[{"color":"green","text":"» "},{"color":"aqua","bold":true,"text":"Dragonia "},{"color":"gold","text":"- PvP-Faction - Magie - 1.8 à 1.12\n"},{"color":"green","text":"» Serveur ouvert - "},{"color":"red","bold":true,"text":"BETA"}],"text":""},"favicon":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAPM0lEQVR42u1bCZBU1RU9v7tnBhgG2fdl2FRQEIYdWWVfBEFEVgUBQQQUiKIiKooLBNS4BssVMW5VIWW0olGDVUSrkljR0kSlTNwSklKrIkFFZv7ycs7v94dPT/cIOMho5lGvuqfnz+937zv33HPv+wA1o2bUjJpRM2rG9zmc2Mz8HAn++xFY6EQGJfORn2qGxqkpGJMwSP97BTty/in/NsXXVOiLik6q/rYnkUh1RnEy+mArNmXucgFnXc76nPn2cxnbSg7Lcs/IIdXaGU4RClNnY2x8kY04x3BeXYD8x/j7XfVR76+cHzdE/T38bD9/NzR2/T2cn3A+zbmIs0fMQXFnVKsYcQpRJ9UJxcRtCnlIFfKzGYWo/et2aLW3O042/dDDnI5e4RyAnqYPuvunoYupizrv8No8e59kbdSSYZMZAu8TRYavPn/+kPMhfc5ZGPve5HFzBHePW1uf5qaSjdEgYWO+AV+uaoXm/5ShZ2F0MANnmnMw3p+Eke4YDHGHob83ECV+f/Qs64A2htevTFuSLIiTIEdzzjd5T10jJwScer+HcyNncez65HHZ9TqoFX7xCSgSJJdxtz+dgOFmMWYGSzDLm4spLo0PJmOU0eejMdgMR3+ioHcgFNBxe23MR6MrDf4ZEfRePvK+oHO/ZjaIHOByetYJhp9/k4Bzt3XU94MG5+C/RB3UjrzetzEaviEDf4KF/mosdC/ETH8ezjZzcJY5FxPNVIwxZ2KEGYsh5gwMMEPRz+uJUwyNfLoo5EE0JdwfqIe6pXSKaYQGAZ1q+B2GTjCR0Zo2JOQMX+igE77g+yXHHA2KbRIW755IDkIfh0bry67rjW7+ZbjQrMel7ios8JfhPMPdNwsw3ZyHKUYhQFI0DAEzDkPNCAzU9E5Eexk0196+C0PgI6ZJ0xYtS5ugkUuSDMghcpKxhoYO0N+txcW6Z0DnlTuCry9wtoiRZNWNPP6T8YRd5N0m3K2XZnB3b8Val8Z7a7CYCFhkVmCeuQizzUKca84nCmZhkjjAKAzGEyUjcXowAqebVmhWyvt00M24045d9AYaHTRFo4Ac45EgDb/X2DAIJ9diZmOy2YobzT243pBIQ0RYJ/ybc3CVOoE7zjslYYVJuFut0eLvMpgLKLseK4NrscJchaVGSLgU883FmGsuxAwzD9PCxU7HBDMFo81EnGHGYLA/nGFAA3fH4JqIvR9MDviECDAMA7cWCgzRcUgYaJJ/TAnDaBB6G2u8a3+n13OrxAmxmI8W1+skdPh8M67SDri34HJzE34i+JurCcvL6ZSVuMAoDEiE5gKcU4EHxmGYNwR9lf5eogFgNkg0II3q67jT0YKb8v3vmVoNEeHGeUDGWoOzTd9OvZ9TVU6IjD+1Kzp9/nNsMA/gFu82XG220BE30wlEgVmH5eYKLDEkQbMc58d4YKqZSR6YhnEhD5As3cHoY2qj4OnmaAKiKbx/fhhoeXGkMS6cF6kLFAZeptFpXkgcEh4ZTlDaHB/LEEddsIQ7wpz9vuJuO271FHt34jrFv9mINeYGrDLXMAyuxEUhD1xCHliKOVl5gChwhQAa9nQLOqCNdUCFyEuPIhr4Z8sDfo5dz4UEvf6H86RYmB1J7CexDsvoXl95/tnNuNL8Eve69+Nmcx9uMndhvREKNuEKcyNWm+twSVYemJ/BA3SAp1RISfwS1SAYw4mcS7DagDy0L5XmgeAInBBphl1HhQAuMPqjVYL0b7HNfQSbzcP4aeiAuw9xQMQDy8yakAcWWB6YFfLA3DAdigfGygG+9ADz/XuxXXFyZt/0uNTKYu9bjM50UESMVx4RH0jo2LcnUrruexHbzJO4M9iO2+SAgNN7EBtdOsIlElxygbsBqz0SYSAiFA+soNOUDrPwQCAyZL5XEdQ24/sqjKZoHGZiXvNGTBZ/G/wj1Rg5ZB9n58MKBcIdozAoWYJThYLHFffP42GP8PefwwPeE7jD3I51IelR+IRwv4xxfw1/FhJuwEqPYeALNeKBRVl4gDWCdypO1MKm2OZHstJoTI/Z1gG5UFCaBQFyxgH7ftthEWLy4GIGa9d24Sn/d3hMhgdKbazqPiV5PUdiul1KkIuneKlzPwugV5nWvqRxQkBwBS7y5ICIB9LpMM0DdILLeoCiJnUf0xyYBpOp3OiMwqMW5+4Mkos75BrOlpyjOS/nfDV2nWdn30pRQHUHwjbBxRJ4DZ55FLeaP2JHKY0xxWj9F5W4FCh1c8UtDWrGl4WUtO8q5REZngqjOA+cbXlgPIYZXvePEHRpFDiVKvH02JAR23EH7IjtcHSvXravUGavebJSB3AR0S/6U8cHf8AOn3lbsFpP6RouojdKnPMxLdEazVN0Roq7lzoZHVNrsbzcAEpb1fe3kOWVEv2DPDCpXA9MxsgoDM6PkJfKjc5oXf2ykF30/jPbfIHtL8RbaQM4/2Sv658zFKjTkyxZmZ0bPijBw3ytcnWiftcGLZOUn2FLSjyRsfO2mVGQz+Iovx96Rjef35tOECGKB5QOxQNnpWWxr8KIqNPCEn/DTqeSRmg8DD7MEgbR+xEZxiUzDL2Rc1NWB8SYuC0Xtp8l617rce5orbxcqYrqLcnSNnECwyd58J4FvF9zxrzuuakvTpM09uUA8YBkseoCTq8LOmnh8y0KKktTCdtkfS4D+vGQWJcj3cV7Bfk5MOaktAP8kmtVk3MxvVQIcXfzFmE2nghbdeWd3vAt6/bQ4svC1h1KRIiUtzu7oONHrNK+6IGuX52Czp91w0mBwmBuxfI4IOpUGO2JNTYS38IDd1XCA89UwvSH1SsQxN6yTCpOSDGe+WFBeWWYF9aGiURdFEYLHcnydRdTZ6C8r1pdqjCSxtIEksZpWTw1TIfiAaVDFkZmLIZ6ChNmgV+xMCKNN8vV2UlZ16/PqP7iIRCvMI+qe6yGY5coN9cKuwB5FbpB9tr6TGG/UCeIVWFAzvCpDENBRI3gr8GSQOlwBebRMdID8fJ4fHl5TMepVeaRSGXAnbqx0qKKsFTYhknGHBDatN4WQG4WItwXQ9JRt8+dSmAYfV7MLPCutP9TuKv0IWw6cC82SBV6FEke5bHHAsklGlyWx35aD8ykHjgnZ5uM0+2ItpK7D0ZwJ9rK299OGKLhBtxh+wNuDkHU/aiKnyxGZpJk5NGGNP4dZQlK5AOqCQR7GTjTxrcgLqhr1xUClMcew8OXA7K1ycQDqhA5XbW88pH/emQIMegQhTI+T+HHdezga7a6IAqDYd+1BM7C9CkwVhPdcbL4YLuM3oYt3iSMCDqj+C0u8g41JumhqXydwDmNcwWvvZ8C6gNmFCnCgEgIzrM8EG+TKQxYc5iBKDEDUOKRNA3DoEy7HUG6A9o6tkp9O0d5HDlkYpU7gF8Y3WyMyEwVH+uEl/nzwEexxUlW8l0t0FQkMo2ZZbcgT1QEszLaZOl2+YCwvaWU2Quneur1sWBS5+i/dMTdnOofNudmfKUmCb8zyOGAKVXugM/wuvMmngX1/ivDuJv86GJrnLMYc51OaJdSvErNEapJ5XPBlrufGoYB4UKoGpVKXhHUmRL96VYPRDwgUaROETOBHGCItoAp1CXCAqZWOWI/nfA6xZavVllmuzzmgElV7YDoRpNoZBlhPYLGEJdNaHCysi9xdCIcNTVogNLcAWUBqcIZsTaZ0qF4QKGiMJCE1rFZV4okOaAD2rit0SKg7jD1UWTkgKhdnoUDRh0rB0hljbUhkZdxBF7BeErciExXn4QOB0R+LJ0DhQB5ICBhBpEeiPOAjtQUBj3R1ahWECm2RxtD4g1YPPkUTQq/Cu3yWCrsU+UhUGTPIylSHErfBOsCtA0rzwrPAoRvH8Fm/ZDHXXqc5GmoDUqvwfJS9Q6WlrfKwgpRoeCqTXaQB/qEB6klDAORofSB0iO/0ygUhAI611geyDS+LDprOBbHZM7h3JRlboIMH2YLyd+NWOMJ9jKONUMZtf8XRMTeruhc1tP29cUByiijMcgTDwwIeaCbeMCoViDHmHZoZVqiqWmMhiY6Nkunw0Mc8C/7zMF3EkJHPcgNEeyWiNwketqgxQckRZ3mjiJK2vO1sZ16P0QhQlm9kzB3BX9ygcdUGIgHeoQ80Fk8oH6ETpMMZTdTZD2RYpwHIgJ87bgZH0NHuyLU/ZKwlS6fzd0q+JZFRZ93o0HPyVgdnpIHgogHiBjLAy3URDERD+jUKEMW33tMzgaPkCynS68zPh2d+AxGX4e7pgUlbR3hxMIpSTJLdUb7BA2KHLGcse4TBQqDIM4D0gUtMnjAtssjBMw+ng5IHxyiE/ViR3AHndq2gXK4DrTXa0yh076SHmA6DDJ5oAl5QGeHlgcCGwZfC33HigCPlCyP6GEm+1hNWPBQbCVPJpET2i8r/pkNPL0qHR7KAycYe3ocHZs9Xx2MP+LD12jRjOdo9+vRGS9QBUoU+XEeoCAKGAZ+80N5wLM8MKvK8/+xY0sVtukODUkt2cg+Y6QuLjPCbmUAlse+9EAvqweoCr1OKPa1+9IDjUMeKPLFA3TkO7aZc9wyQK4wkFwun6oP1EUegyGZR2JNacQWxniZFCF/H9cDAZ0QlsnMLp/zuneVCfQQBdOhK0UY9RR/ELt/MO6TEiwjqCzv16N0qgMojf2oW8yfAzrBpRM8xT4N1blEGzpgrUiQKDggQUQs7ZyI4aBUdqoHutPjNM7tOsjgrs8n5M+yPYLFNOAWMvhvOqLdp6r8VAuoNpiFSa7ODSfQAXqGgKowkFJkeHyjUx8SZR3bktsoBFCWu/Yhy9OqE/mV9++5UD2moqdCw+JGtb+aouoc6ZxAnaJVWFC6FHO+mY9pZawLPJ0cqT+g6/UMEVGyDQefI8qnM5QxdkgPaPejsjz2UEU1I/n0aE2iWk2F99oQ9N0vR6gjJJkctdBUMEn4kOk9svvbNOgG/l1HhMK+UE+fRgaeQMM/FglCjx8f2qypdiOZhZSKOc/R2QPT19ZC1H6EBmzVzzp3tE9zJNSL1tPk9hmFROz0eLIQxd+/KBqh0xxU54enSV5hbFK2pqbjTKcPuoEFTmhc5uiBrlKPGIfh4XPH8ZgmjyTsY3ovUSN8FB2o/hBFj3YzRQWXIomFLTP9HwLGd8o+IZaopMZQp2dPTO7+cFLe4acQp7LMcqaasD9a46uyKfNjHYn/Z+NrRs2oGTXjmI7/AT4eOvr4ct33AAAAAElFTkSuQmCC","modinfo":{"type":"FML","modList":[]}}}], id=0}
16:22:34 [INFOS] [ViaVersion] INCOMING: HANDSHAKE 0 -> 0 [HANDSHAKE[331]] Value: PacketWrapper{packetValues=[], readableObjects=[Pair{Type|VarInt, 331}, Pair{Type|String, ts.nobordercraft.fr}, Pair{Type|Integer, 25565}, Pair{Type|VarInt, 2}], id=0}
16:22:34 [INFOS] [ViaVersion] INCOMING: LOGIN 0 -> 0 [LOGIN_START[331]] Value: PacketWrapper{packetValues=[], readableObjects=[], id=0}
16:22:34 [INFOS] [ViaVersion] OUTGOING: LOGIN 0 -> 0 [LOGIN_DISCONNECT[331]] Value: PacketWrapper{packetValues=[], readableObjects=[], id=0}`

I don't know if it's enough/too much ?
Thanks ^^

**Comment by Deathworld** [comment]
Just tried in my computer, same problem... :/
Thanks !

**Comment by MylesIsCool** [comment]
So what version are you trying to connect with? and which viaversion is on your bungeecord?

**Comment by Deathworld** [comment]
I'm trying to connect with Minecraft 1.12pre4 with the latest ViaVersion Dev Version (1.12 pre4)
Thanks

**Comment by MylesIsCool** [comment]
Which server is the main server you connect to because ViaVersion isn't compatible with your Vanilla server version.

**Comment by Deathworld** [comment]
The main server is "Login". "Faction" & "Login" are in 1.8.8 and "Vanilla" is in the latest Spigot version (1.12-pre2)

Thanks !

**Comment by MylesIsCool** [comment]
Are there any console logs from the Login server and you're ensuring that this is forced for Bungee to login to the Login server?

**Comment by Matsv** [comment]
We do not support spigot 1.12-pre2 with ViaVersion.

**Comment by Deathworld** [comment]
Yes, the proxy forces to connect to Login.
I don't have any errors except about the version

Mhh Matsv, I came back to an older ViaVersion Version, the #22 I believe all works perfectly with pre2 (but of course we can't connect with pre3-4)

Thanks
