### ISSUE TITLE
Players able to lose items if put into the offhand slot

### ISSUE THREAD

**Issue by theminecoder** [MylesIsCool/ViaVersion#67]
Just tested this with a dev instance of one of my servers.

If you are in creative on the server (for what ever reason) and then put a block into the offhand slot, then logout, you lose the item completely.

![image 2016-03-03 at 1 11 38 am](https://cloud.githubusercontent.com/assets/1396368/13481371/0c4875e0-e0dd-11e5-8af7-43f874da5066.png)

As shown by the screenshot, it is not ghosting any other slot either.

**Comment by Paulomart** [comment]
Is this also happening in survival?

**Comment by HugoDaBosss** [comment]
It should drop the item if placed in the offhand slot, this was working before.

**Comment by MylesIsCool** [comment]
This only happens in creative, possibly we'll look into fixing it. It just needs modification of the Creative spawn packet (or what it's called) I believe.

**Comment by theminecoder** [comment]
Can confirm the item does not drop in creative.

Thanks for the update though.

**Comment by MylesIsCool** [comment]
Going to close, adding this as a feature would cause creative players to unintentionally drop items possibly. Ghosting is fine for now.
