### ISSUE TITLE
Incompatibility with PermissionsEx and FastLogin

### ISSUE THREAD

**Issue by Mario359** [MylesIsCool/ViaVersion#670]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/5f33b6934896f6828a7f9950ab8ce724

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Spigot 1.11.2
Using ViaVersion-1.0.5-1_12pre5
PermissionsEx 1.23.4
FastLogin 1.9 (with AuthMe v5.2 (build: 1542))

### How does this error happen? login? Using an item? 
On join

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No error in the console
Just a kick message : https://images.discordapp.net/.eJwFwdsNwyAMAMBdGADzLDjbIIJI1AQj7KgfVXfv3Vc961KbOkQmbwD7yZXWrllold50J-pXK_NkXemGIlLqcbchDM5EkzOmkBBdsM4m8DaGkF4WvTUx-2wQnvEe9Bl6jq5-fwiiIuY.3_t7v1y2vQhmN2nGq-9r5tbqYBY
`Internal Exception: io.netty.handler.codec.DecoderException:
java.lang.IndexOutOfBoundsException: readerIndex(4) + lenght(8) exceeds writerIndex(10): PooledUnsafeDirectByteBuf(ridx: 4, widx: 10, cap: 10)`

**Comment by Mario359** [comment]
works fine with the latest build

**Comment by MylesIsCool** [comment]
Was probably an issue with pre 5 and not the plugins :)
