### ISSUE TITLE
Netty error on boot

### ISSUE THREAD

**Issue by xXxBobDolexXx** [MylesIsCool/ViaVersion#671]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/6df23d338e312aa3bacb511d4bcf2288

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No other software aside from plugins
Plugins list: https://pastebin.com/vPAJN7U3

### How does this error happen? login? Using an item? 
On server boot, people can still connect 

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/KzuZfC5V

**Comment by MylesIsCool** [comment]
This is a server list (most likely) sending bad packets, we don't ignore this error in case of actual issues.

You can just ignore this :)
