### ISSUE TITLE
Random disconnect Paper 1.11.2 1.12 pre5

### ISSUE THREAD

**Issue by andris155** [MylesIsCool/ViaVersion#672]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/91ed07a1c35edecfcccd5d12d7018930

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
https://ci.md-5.net/job/BungeeCord/1234/
Plugins: SkinsRestorer-v13.0.2, BungeeAuthMeBridge-1.6.2, AddressLimit

### How does this error happen? login? Using an item? 
Random

### Is there an error in the console? Use pastebin.com. Is there a kick message?
`[14:29:34] [Server thread/INFO]: andris155 lost connection: Disconnected`

![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/26284029/94724f3c-3e32-11e7-8fef-b1db5067bfbc.PNG)

**Comment by MylesIsCool** [comment]
Could you try without SkinRestorer on your Bungee?

**Comment by MylesIsCool** [comment]
Could you try with the new build?

https://ci.viaversion.com/job/ViaVersion-DEV/

I suspect it was that issue.

**Comment by MylesIsCool** [comment]
Closing as I suspect it was the issue in the previous comment.
