### ISSUE TITLE
1.8 BossBar on newer versions

### ISSUE THREAD

**Issue by MaTaMoR** [MylesIsCool/ViaVersion#673]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/844b0b544c8af1c13c9ea439df66fb05

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I'm using BungeeCord lastest version, 

### How does this error happen? login? Using an item? 
When the BossBar is sent to the player.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/dwdzm9NH

The problem is probably with one of my custom plugins, i' basically creating a BossBar entity and editing it's data with Reflection, it works just fine on 1.8, but if a client with any other version tries to connect it doesn't work and spam the console with error, this is my code: https://pastebin.com/A01vtKhu i used as a base the plugin from [inventivetalent](https://www.spigotmc.org/resources/api-bossbarapi-1-7-1-8-1-9-1-10.7504/)

**Comment by MylesIsCool** [comment]
As per the error message:
Old ID: 3 New ID: 3
[00:02:24] [Netty Epoll Server IO #1/INFO]: Old Type: Byte New Type: Boolean
[00:02:24] [Netty Epoll Server IO #1/WARN]: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Byte

See line 155, ensure you're sending the correct data watcher values / line 165. I would assume somehow you need to ensure you're casting to a byte when you set id 3.
