### ISSUE TITLE
Internal Error - /viaversion pps

### ISSUE THREAD

**Issue by xSzescianPL** [MylesIsCool/ViaVersion#674]
**What version of ViaVersion are you using? Type /ver viaversion**

1.0.4 - https://www.spigotmc.org/resources/viaversion.19254/

**What version of Spigot are you using? Type /ver**

"This server is running CraftBukkit version git-Spigot-550ebac-7019900 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)"

**What plugins are you using? Type /plugins**

PlotMe, PlotMe-DefaultGenerator, ViaVersion

**How does this error happen? login? Using an item?**

The "/viaversion pps" command displays an error. http://imgur.com/a/4ZovK

**Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)**

No.

**Is there an error in the console? Use pastebin.com. Is there a kick message?**
Yes. https://pastebin.com/XF9EuNzy

**What is the output link of /viaversion dump?**

https://gist.github.com/bd9b7eab4a06a3a6368e53e388aa620e

**Comment by MylesIsCool** [comment]
Thanks for providing us with all the info to make this an easy fix, you can use dev builds or just wait for next release (there's no harm)

https://ci.viaversion.com/job/ViaVersion/

**Comment by xSzescianPL** [comment]
This version of ViaVersion works, thanks for the help.
