### ISSUE TITLE
Crash with ViaVersion v1.0.5_1.12-pre6

### ISSUE THREAD

**Issue by IsaiahPatton** [MylesIsCool/ViaVersion#675]
### What is the output link of /viaversion dump? 

None. As ViaVersion disables on plugin enable.

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

git-Paper-1104 (MC: 1.11.2) (Latest version)

![image](https://cloud.githubusercontent.com/assets/16439221/26556433/823b1f1a-4468-11e7-983a-175bafaa4311.png)
Plugins with version number: https://pastebin.com/q7Nvfgsc

### How does this error happen? login? Using an item? 

On server startup server outputs error message and disables ViaVersion.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

`java.lang.ClassCastException`: https://pastebin.com/3PzjhgX8

### Outher info

Java version: 8
Server host: server.pro
Server IP: imini.myserver.gs

This error also happened in the pre5 version.

**Comment by MylesIsCool** [comment]
Reset your config, you have invalid values (the easiest way is to reset this).
(There is a field that you've put characters instead of true or false)
