### ISSUE TITLE
The World Chunks Unload

### ISSUE THREAD

**Issue by GoNotCougsWA** [MylesIsCool/ViaVersion#677]
### What is the output link of /viaversion dump? 
Sorry idk where the dump is but.. I think it is https://gist.github.com/8de7720fbfd2d22b887eaaa8c486cce5

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Spigot Version: 1.8.8-R0.1-SNAPSHOT
Bungeecord Version: BungeeCord-Bootstrap:1.11-SNAPSHOT:0b8ab8e:1223
Plugins: PermissionsEx, Plugman, WorldEdit, Viaversion, Vault, ProtocolLib, LibsDisguies, HolographicDisplays, Chicken-Wars (Chicken-Wars is a custom coded plugin by ME!)

### How does this error happen? login? Using an item? 
There is a plugin called "LibsDisguises" And On 1.11 clients when you move your head the chunk you are in unloads. I know its viaversion because it only on 1.11.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
There is no kick message but there is a error https://pastebin.com/inuDMePe

**Comment by MylesIsCool** [comment]
So how exactly do I replicate this? (You state about LibsDisguises but not anything else)
And does this just happen on 1.11, or 1.10, 1.9 too?

**Comment by GoNotCougsWA** [comment]
@MylesIsCool To replicate this You need ProtocoLib and LibsDisguises. I upload the version I am using on my mysql website http://diamondminer.serveminecraft.net/ChickenWarsaddononplugins
You do /dis <Some Random Mob like a chicken> Example: /dis chicken (I hope this helped you)

It Happens on 1.9.X, 1.10, This Never happen before. I remember getting the plugin and checking it and it works with Viaversion. I never updated LibsDisguises but I have updated Viaversion.
If you can't find the problem I can try a different Disguises plugin

**Comment by MylesIsCool** [comment]
@GoNotCougsWA Before I look into this do you do anything with chunks in your plugin & have you tried latest libs for 1.8?

**Comment by GoNotCougsWA** [comment]
@MylesIsCool 
For LibsDisguises I have the latest of LibsDisguises for 1.8.8.
and I have the latest ProtocoLib that is for the version LibsDisguises.

I send you a link because LibsDisguises is right now only for 1.11 but... it hard to find the version for 1.8.8.
Just so you know if you can't find it. I can look thought my plugin and just if it is from one of my plugins

**Comment by MylesIsCool** [comment]
I've attempted to replicate this:

1.8.8 spigot server, plugins from above and did /disguise chicken. Unfortunately, after quite a few attempts I can't replicate any chunk unload issues (it's worth noting that we've not had someone recently report chunk unload issues and libdisguises is quite a popular plugin).

If your plugin uses something like modifying chunk packets that could be the issue.

**Comment by GoNotCougsWA** [comment]
My Plugin don't have a chunk packet. I might just get a different Disguises plugin

**Comment by MylesIsCool** [comment]
After reviewing Lib's code there are some weird chunk hacks which you can disable from the config of the plugin which is the only thing I can suggest, closing otherwise :) 

"Bed: true" is the option in the config that might fix this.

**Comment by GoNotCougsWA** [comment]
Ok
