### ISSUE TITLE
Potion / Creeper Error.

### ISSUE THREAD

**Issue by DuckCraftPvP** [MylesIsCool/ViaVersion#679]
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No bungeecord. i use protocol support and protocol lib.

### How does this error happen? login? Using an item? 
when you join on 1.8 on my 1.9 server all potions and creeper eggs reset to default example: Creeper eggs turn into white spawn eggs and dont work. Is there a way to fix this?

### Is there an error in the console? Use pastebin.com. Is there a kick message?
no error or message of anykind.

**Comment by MylesIsCool** [comment]
This isn't a ViaVersion issue.

ViaVersion supports newer clients.

1.8 on a 1.9 server is ProtocolSupport and as provided by them they don't support this version anymore.
