### ISSUE TITLE
Incorrectly duplicates errors to console

### ISSUE THREAD

**Issue by Eternalrealms** [MylesIsCool/ViaVersion#68]
http://hastebin.com/ijoxajajol.avrasm

**Comment by Eternalrealms** [comment]
http://hastebin.com/oturugayec.avrasm

**Comment by Eternalrealms** [comment]
This also caused a lot of lag on my server.

**Comment by HugoDaBosss** [comment]
Are the players still able to join?
Because I had this issue before and it made it impossible for any players to join.

**Comment by MylesIsCool** [comment]
I'll look into modifying our error handler again to see if we can optimise it so that we don't get this spam. We just don't want to lose proper errors.

**Comment by MylesIsCool** [comment]
Should be fixed in next version, I've commited the fix.
