### ISSUE TITLE
BossBar acting weird.

### ISSUE THREAD

**Issue by ThijsHero** [MylesIsCool/ViaVersion#680]
### What is the output link of /viaversion dump? 
Bungee:
https://gist.github.com/25740bcc259abcd4c4b77f50226a3918
Bukkit:
https://gist.github.com/47ec2d5795e31545152105f00f2c82c9
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I'm using HexaCord normally. Im using ServerListPlus with it, The Viaversion plugin and thats it

### How does this error happen? login? Using an item? 
It just appears when the bossbar goes on. Im using a plugin named AirBar that creates a BossBar, and it just gives 'Wither' on version higher then 1.8.8 (because thats my main server version).

The BossBar acting weird: https://gyazo.com/c33ab2645d262b235024683379525356

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No kick message, no nothing, only when i dont use the ViaVersion plugin in the BungeeCord it gives me this error when using VIaVersion and ProtocolSUpport at the same time.

Kick Message when not using ViaVersion in bungee: 
https://gyazo.com/bbccea2c6fabcd2dd937b6a0c1777afe

**Comment by GrandmaJam** [comment]
Its because you're using a leaked version of airbar

**Comment by ThijsHero** [comment]
Nope, I bought it from spigot. Its all legit.

**Comment by Matsv** [comment]
Custom named withers work fine for me on 1.8. Sadly can't try to reproduce it with that plugin since it's premium.

**Comment by Matsv** [comment]
We sadly can't help you with issues you have with premium plugins. If you have a way to reproduce the issue, I'd love to hear it. Spawning a custom named wither / creating a BossBar with the ViaVersion API works correctly for us.
