### ISSUE TITLE
End and Nether kicking issues

### ISSUE THREAD

**Issue by redfrosting** [MylesIsCool/ViaVersion#681]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/3d944b6cb382569d0396c80b8dbfa393

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Nope.

### How does this error happen? login? Using an item? 
When accessing the nether and end.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Kick message:
http://i.imgur.com/CxlMnKt.png

**Comment by MylesIsCool** [comment]
Would you be able to contact me on Discord / IRC? (Both are on ViaVersions resource page)

Otherwise, spigot messages if none of the above. The issue is a very weird one and I can't replicate it.

**Comment by Matsv** [comment]
Does [this build](http://fs.matsv.nl/files/ViaVersion-1.1.1-libsdiguisespatch.jar) solve your issue?

**Comment by Matsv** [comment]
Workaround provided in the latest devbuild.

TODO: Create an issue / PR to fix this inside LibsDisguises. It looks like LibsDiguises is sending too many bytes. The blockentities still read correctly, but there is some data after that.

**Comment by CullanP** [comment]
This issue is also still happening to us at mineheroes, would you mind telling me what's wrong with libsdisguises or where the issue resides so I at least have some idea of where to look or what packet is causing the issue

**Comment by MylesIsCool** [comment]
See https://github.com/libraryaddict/LibsDisguises/issues/220

**Comment by CullanP** [comment]
I've fixed it now, thanks for you help I appreciate it
