### ISSUE TITLE
encountered exception

### ISSUE THREAD

**Issue by FiveEYZ** [MylesIsCool/ViaVersion#684]
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
https://github.com/HexagonMC/BungeeCord
its only running on bungeecord using ViaVersion-1.1.2-SNAPSHOT build 167 from jenkins

### How does this error happen? login? Using an item? 
just saw this in the bungee console and it said i should report it

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://gist.github.com/FiveEYZ/714ebda9459b124ce862d2def17a836b

**Comment by MylesIsCool** [comment]
This is down to server lists sending pings or someone accessing your server too soon, it's fine to ignore and should be rather infrequent :)
