### ISSUE TITLE
Wrong  hitregistration form different clients

### ISSUE THREAD

**Issue by Kaana38** [MylesIsCool/ViaVersion#687]
### What is the output link of /viaversion dump? 
{
  "versionInfo": {
    "javaVersion": "1.8.0_131",
    "operatingSystem": "Windows 10",
    "serverProtocol": 47,
    "enabledProtocols": [
      47,
      107,
      108,
      109,
      110,
      210,
      315,
      316,
      335
    ],
    "platformName": "CraftBukkit",
    "platformVersion": "git-Spigot-db6de12-18fbb24 (MC: 1.8.8)",
    "pluginVersion": "1.1.2-SNAPSHOT"
  },
  "configuration": {
    "anti-xray-patch": true,
    "auto-team": true,
    "block-disconnect-msg": "You are using an unsupported Minecraft version!",
    "block-protocols": [],
    "bossbar-anti-flicker": false,
    "bossbar-patch": true,
    "checkforupdates": true,
    "force-json-transform": false,
    "hologram-patch": false,
    "hologram-y": -0.96,
    "item-cache": true,
    "max-pps": 800,
    "max-pps-kick-msg": "You are sending too many packets!",
    "nms-player-ticking": true,
    "piston-animation-patch": false,
    "prevent-collision": true,
    "reload-disconnect-msg": "Server reload, please rejoin!",
    "replace-pistons": false,
    "replacement-piston-id": 0,
    "send-supported-versions": false,
    "shield-blocking": true,
    "simulate-pt": true,
    "suppress-metadata-errors": false,
    "tracking-max-kick-msg": "You are sending too many packets, :(",
    "tracking-max-warnings": 4,
    "tracking-period": 6,
    "tracking-warning-pps": 120,
    "use-new-deathmessages": true,
    "use-new-effect-indicator": true
  },
  "platformDump": {
    "plugins": [
      {
        "enabled": true,
        "name": "ViaVersion",
        "version": "1.1.2-SNAPSHOT",
        "main": "us.myles.ViaVersion.ViaVersionPlugin",
        "authors": [
          "_MylesC",
          "Matsv"
        ]
      }
    ]
  }
}

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
None

### How does this error happen? login? Using an item? 
When you hit a player on version 1.8 and the attacker is on 1.11. Than the attacker give more damage than normal.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
None

**Comment by MylesIsCool** [comment]
ViaVersion does not change hit registration it is purely client sided in how it works and cannot change how much someone can hit.

However, if you downgrade from newer server version it can change the amount of damage it does.
