### ISSUE TITLE
Error with Iron Bars

### ISSUE THREAD

**Issue by armedturret** [MylesIsCool/ViaVersion#688]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/080b9bd8c89f55066ff3040c4162d242

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Np

### How does this error happen? login? Using an item? 
Walking into or standing on a singular iron bar causes shaky collisions unless you're in 1.8

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No

**Comment by Matsv** [comment]
Won't be fixed. See #114 for more info.
