### ISSUE TITLE
Feature/1.12 on older server: Show bed items as red beds

### ISSUE THREAD

**Issue by Brokkonaut** [MylesIsCool/ViaVersion#689]
1.12 players currently see bed items (in inventory, hand or as item) as white beds - But when placed it will be a red bed and players on older clients will also see it as red bed (when it is in the hand or dropped as an item).

So I think it would be useful if they would be sent as red beds to 1.12 clients.

**Comment by TheIntelloBox** [comment]
Please. :c

**Comment by MylesIsCool** [comment]
Now in latest dev build.
