### ISSUE TITLE
Strange Error

### ISSUE THREAD

**Issue by claushbang** [MylesIsCool/ViaVersion#69]
Hello!

`02.03 21:15:29 [Server] ERROR Unable to inject handlers, are you on 1.8? 
02.03 21:15:29 [Server] WARN java.lang.NoSuchMethodException: net.minecraft.server.v1_8_R3.MinecraftServer.getServerConnection()
02.03 21:15:29 [Server] WARN at java.lang.Class.getDeclaredMethod(Class.java:2130)
02.03 21:15:29 [Server] WARN at us.myles.ViaVersion.ViaVersionPlugin.injectPacketHandler(ViaVersionPlugin.java:60)
02.03 21:15:29 [Server] WARN at us.myles.ViaVersion.ViaVersionPlugin.onEnable(ViaVersionPlugin.java:43)
02.03 21:15:29 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:320)
02.03 21:15:29 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:348)
02.03 21:15:29 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416)
02.03 21:15:29 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:351)
02.03 21:15:29 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:323)
02.03 21:15:29 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.CraftServer.<init>(CraftServer.java:260)
02.03 21:15:29 [Server] WARN at net.minecraft.server.v1_8_R3.PlayerList.<init>(PlayerList.java:71)
02.03 21:15:29 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedPlayerList.<init>(SourceFile:14)
02.03 21:15:29 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:179)
02.03 21:15:29 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524)
02.03 21:15:29 [Server] WARN at java.lang.Thread.run(Thread.java:745)`

It works perfectly fine on Spigot 1.8.x, however for another one of my servers in my network, I use a different server software called "sportbukkit" which is just a fork of CraftBukkit/Bukkit as well. I'm not quite seeing why it's not working with it; some help would be nice.

https://github.com/overcastnetwork/sportbukkit

**Comment by Z609** [comment]
SportBukkit isn't running the latest nms packages.

Are there any updates to this "SportBukkit?" You need to make sure it's R3.

**Comment by Paulomart** [comment]
Well this is a hack and it supports only spigot ATM, I think this is a won't fix.

**Comment by MylesIsCool** [comment]
We only support vanilla Spigot possibly PaperSpigot. This is due to how the injection process works, it might be portable in the future which I'll reopen if we get round to it. The recommended use is just normal Spigot 1.8.8. (Though a lot of other people report compatibility with various versions)

**Comment by saucequan** [comment]
I know this is closed, however I decided to test this again with SportBukkit and it works flawelessly. I'm not sure if this was an issue you fixed unconsciously or not. Either way, great job!

**Comment by Matsv** [comment]
@saucequan great to hear that :)
