### ISSUE TITLE
Protocol error

### ISSUE THREAD

**Issue by Kretena1** [MylesIsCool/ViaVersion#690]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/20bf4956390bac32a0c81c510b5a656d

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yes im using bungeecord for 1.8-1.12 with installed ultimatefriend, skinsrestorer, authmebridge, bungeehub, liteannouncer

### How does this error happen? login? Using an item? 
When player is logging. This is not happening to every play. Someone can join, someone cant join.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/0gpzJ7qr

**Comment by MylesIsCool** [comment]
Ensure you've updated all your Bungee plugins to 1.12.

eg. SkinsRestorer

**Comment by MylesIsCool** [comment]
See above :)
