### ISSUE TITLE
Viaversion doesnt support TacoSpigot 1.8.8

### ISSUE THREAD

**Issue by SnakeDaoust1232** [MylesIsCool/ViaVersion#691]
Infomation:
- So a while back i made this issue: https://github.com/MylesIsCool/ViaVersion/issues/682. That issue was me trying to figure out why viaversion wasn't letting my players join. I was told to talk to techcable about the issue as it was with tacospigot. He has since resolved that issue and now my players can join but now there is a different issue. People cannot join the server 1.9+ with the newest version of viaversion installed. I talked to techcable, who is the dev of tacospigot and he said that you guys need to add support for the newest version of tacospigot 1.8.8. 

What is the output link of /viaversion dump? 
- https://gist.github.com/anonymous/c5849450ca7bd99c8ee9212963ceaf43

Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
- https://github.com/HexagonMC/BungeeCord
- https://ci.techcable.net/job/TacoSpigot-1.8.8

How does this error happen? login? Using an item? 
- Login

Is there an error in the console? Use pastebin.com. Is there a kick message?
- Nope

When i try to join the server(It kicks any client 1.9+):
- https://gyazo.com/db7bf33d4c29c8a9a3a3e0bb5879345a

**Comment by MylesIsCool** [comment]
I've put a link to the ProtocolSupport which works with taco on our discord. http://myles.us/ViaVersion/ProtocolSupport1.8.8.jar

**Comment by SnakeDaoust1232** [comment]
Just to let you know, for anyone else that may have my issue as well... i had latebind set to true, it needs to be set to false. Then everything works fine.

**Comment by ysl3000** [comment]
Is latebind a Tacco option only?

**Comment by MrPowerGamerBR** [comment]
@ysl3000 nope, it is from Spigot.
