### ISSUE TITLE
Player can't join with version 1.11.x and higher 

### ISSUE THREAD

**Issue by Min3MonDE** [MylesIsCool/ViaVersion#693]
### What is the output link of /viaversion dump? 
https://gist.github.com/Min3MonDE/685cf62ddfae1d3e656ac4ece19d514d (deleted selfmade plugins)

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I'm using BungeeCord and some selfwritten plugins. (It's about an error while running one of them)

### How does this error happen? login? Using an item? 
Login, after spawning an Entity. 

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/X4Qg93uA

You can't join the server if there is a plugin spawned entity on 1.11.x. On any other lower version of minecraft you can succesfully join and see the entity. It's like in -> https://github.com/MylesIsCool/ViaVersion/issues/635 but the player get's kicked instantly. I'm using Custom Entitys but even default entitys won't work.

The mobs are getting spawned with the spawnEntity method of World class.

**Comment by MylesIsCool** [comment]
We don't support entities not supported by the client. Sending types that don't exist are bad ids and hence the error.

**Comment by Min3MonDE** [comment]
I tried it with a cow and a chicken. Both times a failure.

**Comment by MylesIsCool** [comment]
@Min3MonDE Mobs work fine for me, if you're working with custom mobs you have to ensure the network ids are properly registered. This issue will be with your code as plugins like Essentials use the same code internally (https://github.com/Curtis3321/Essentials/blob/master/Essentials/src/net/ess3/SpawnMob.java#L165), and work.

**Comment by Min3MonDE** [comment]
Thanks you for your quick response!
