### ISSUE TITLE
Shulker boxes in older versions

### ISSUE THREAD

**Issue by gabor6505** [MylesIsCool/ViaVersion#694]
### Description

I would like to ask if You could add **Shulker Boxes in older game versions**, so people can still use them. I don't know if it's possible, but you could simulate it with a normal chest maybe. Currently when I run a 1.12 Spigot server and join with 1.9.4 or 1.10.2, I just see an **empty air block**, I glitch when I jump into it and if I **place a block** in place the Shulker box, it just **overwrites the shulker box**.

I really like your plugin btw, it's awesome!
**Thanks for the help and sorry if this feature has already been planned or is impossible.**

### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/cc0688ce6139be1fe5cbab96fc9ff6a3

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Clearlag, CommandNPC, EssentialsX, EssentialsXChat, EssentialsXSpawn, Multiverse Core, Server Signs, TNT Run Recoded, Viabackwards, Viaversion, WorldEdit, WorldGuard

**Comment by Matsv** [comment]
Shulker boxes should work? :O 
what color do you use?

**Comment by gabor6505** [comment]
Thanks for the quick answer,
Well I have tested again, provided screenshots below. Maybe a plugin is doing the bug?

1.11.2
![2017-06-21_22 41 54](https://user-images.githubusercontent.com/12859334/27406121-405c4f82-56d4-11e7-92dc-afb815b1d6f0.png)

1.10.2
![2017-06-21_22 42 30](https://user-images.githubusercontent.com/12859334/27406135-467c76a8-56d4-11e7-85bb-70ce57062639.png)

1.9.4
![2017-06-21_22 43 20](https://user-images.githubusercontent.com/12859334/27406146-4c8c235e-56d4-11e7-8003-8830ed3b1df4.png)

Although if I place down these enderchests, it does show up as long as I'm logged in, if I disconnect, all of the previously placed ones appear invisible again. And also, if I want to stand on them with 1.10/1.9, it still glitches (when I place them like enderchests)

**Comment by Matsv** [comment]
Thank you so much for reporting it, I must've messed something up with the chunks

**Comment by gabor6505** [comment]
No worries glad I could help! 😃

**Comment by Matsv** [comment]
Pretty strange issue. The fake blockentity / blockchange is sent correctly. Couldn't find anything at the moment. Strangest part is that I tested everything before I released it and it worked then, so I have no idea what changed.

Sadly won't be home until Sunday, so don't have the time to investigate it until then.

**Comment by Matsv** [comment]
Moving this issue to https://github.com/Matsv/ViaBackwards/issues/15 since this isn't a ViaVersion issue. Please follow it there (:
