### ISSUE TITLE
Nether sending skylight data

### ISSUE THREAD

**Issue by ArtNRG** [MylesIsCool/ViaVersion#695]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/ebe0c3b0a44db81d2810b5ffbc4eb83f

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Waterfall-Bootstrap:1.12-SNAPSHOT:5219ea6:126
SkinsRestorer version 13.1.2
ViaVersion version 1.1.1
ServerListPlus version 3.4.7
ViaBackwards version 2.1
BungeeTabListPlus version 2.7.4

### How does this error happen? login? Using an item? 
User logged out in nether world and try to login. 

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/BQ0EraHQ

**Comment by MylesIsCool** [comment]
From the looks of it, this means your world is possibly sending the wrong dimension, not sure though.

**Comment by MylesIsCool** [comment]
Do you happen to use LibsDisguises? Could you also confirm which versions this issue happens on?

**Comment by MylesIsCool** [comment]
If anyone else has this issue and can provide info, i'll happily reopen but we don't have enough info to replicate / fix.
