### ISSUE TITLE
Invisible blocks

### ISSUE THREAD

**Issue by xBreaksx** [MylesIsCool/ViaVersion#697]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/5c0015fccbec2f868bb6aa6300350263

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
(Running 1.10 PaperSpigot)
Running BungeeCord Waterfall version git:Waterfall-Bootstrap:1.11-SNAPSHOT:9677e47:103 by md_5
LetterHeads, ColoredSigns, PluginManager, PlugMan, MySQL, BimmCore, PowerNBT, AutoRestart, TabListAPI, ParticleLIB, ViaVersion, LongChat, TestPlugin (custom), ViaBackwards, Actionbar, VoidSpawn, LuckPerms, ChatControl, CrackShot, FullJoin, Votifier, Multiverse-Core and Portals and NetherPortals AND SignPortals, ProtocolLib, Vault, ScriptBlock, FastAsyncWorldEdit, FastAsyncVoxelSniper, VoteSend, MobArena, PerWorldInventory, HolographicDisplays, AAC, MCInfected, EnjinMinecraftPlugin, UltimateArena, PlaceholderAPI, ExperienceRanks (custom), WorldGuard, UAAntiXray (custom), EssentialsProtect, PlaceholderInjector, EssentialsAntiBuild, EssentialsSpawn, Inventory (custom), CustomGUI, SuperbVote, GunRecoil (custom), and PlayEffect.

### How does this error happen? login? Using an item? 
Placing a sign or head causes the block to look invisible until the chunk is unloaded and reloaded.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No error or kick message.

**Comment by Matsv** [comment]
Does this also happen on version 1.10.2?

**Comment by xBreaksx** [comment]
Do you mean the spigot or the client version?
The PaperSpigot version _is_ 1.10.2.

**Comment by MylesIsCool** [comment]
Could you provide the details of what versions this happens on? Does it happen on 1.10?

By version, we refer to the client.

**Comment by xBreaksx** [comment]
I for sure know it happens on 1.12, 1.11(.x), 1.10.2, and 1.10.

The ONLY version that signs and heads work for is 1.9(.x).

**Comment by MylesIsCool** [comment]
Does it happen without the anti-xray plugin / protocol lib?

**Comment by xBreaksx** [comment]
I guess it was the custom anti-xray plugin as signs/heads work fine without it.

**Comment by MylesIsCool** [comment]
Does the anti-xray plugin use some sort of chunk listener?

**Comment by xBreaksx** [comment]
Yeah, I think it uses either a chunk listener or block iterator.

I'm not the developer of it so I don't exactly know for sure.

**Comment by MylesIsCool** [comment]
You can get around this by ensuring chunk modifications are done in async & sync. Going to close this issue as it's not something we can fix our end. :)
