### ISSUE TITLE
Broadcast for the version of the player

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#698]
Hello !

Could you add : when a player connects, a broadcast where it's written the name of the version.
Example : MylesIsCool joined the server with Snapshot 17w06a.

**Comment by MylesIsCool** [comment]
I would consider this bloating the console and for big servers, not something they would want, I'd suggest if you want this you consider making your own plugin using our API as it's easily possible. Otherwise, hope someone has made it / ask someone to make it for you.
