### ISSUE TITLE
Teams prefixes/suffixes not visible on 1.9+

### ISSUE THREAD

**Issue by Inuun** [MylesIsCool/ViaVersion#699]
Team prefixes are not visible on 1.1.2 clients, 1.11.2 and lower version can see prefixes without problems.

### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/18b31e9f65873e3bb6b2827f6f8c2ce3

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Today tested without proxy

### How does this error happen? login? Using an item? 
Huh, this is not implemented feature rather than error

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No

**Comment by MylesIsCool** [comment]
Could you provide screenshots? What you expect vs what happens?

Is this only on 1.12?

**Comment by Inuun** [comment]
Team prefix '&7' works correctly on 1.1 client, but with '&4&lADMIN &r' prefix looks like not modified.

Server software: PaperSpigot 1.8.8
Client: Minecraft 1.11.2
Result: '&7' and '&4&lADMIN &r' is displayed correctly

Server software: PaperSpigot 1.8.8
Client: Minecraft 1.12
Result: only '&7' is displayed correctly

plugin is using Bukkit.getScoreboardManager().getMainScoreboard()

**Comment by Inuun** [comment]
Oh, It's works like you remove all players from teams and remove teams, then you create teams and add players. Then users with 1.12 client must rejoin to see you own prefix.

**Comment by MylesIsCool** [comment]
Could you post the full code you're using?

**Comment by Inuun** [comment]
Unfortunately not, code is depending on many api classes from core plugin. Core plugin cannot be given to others. I create version for testing with hardcoded settings and I put it in repository on github.

**Comment by Inuun** [comment]
https://github.com/Inuun/TestingTablist

First step: install plugin from 'target' dir

How to reproduce:
1. join with 1.12 minecraft
2. see tablist
3. type /tablist
4. see tablist (only your nickname is white)
5. join with 1.11 minecraft
6. type /tablist
7. see tablist

**Comment by MylesIsCool** [comment]
I can replicate part of your issue but not all of it, when using the plugin provided (thanks for providing it all much appreciated!) I can only see the tab info on 1.8.8 client, all other versions don't display anything.

**Comment by Inuun** [comment]
hmm, I tested it with ProtocolSupport also

**Comment by MylesIsCool** [comment]
I had ProtocolSupport installed at the time of testing

**Comment by Inuun** [comment]
This server is running CraftBukkit version git-PaperSpigot-"8b18730" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

https://image.prntscr.com/image/eNvV3joCTbqq8OhcO1RQFw.png

huh, join 164.132.203.177:77

**Comment by Inuun** [comment]
Tested again. You are right, 1.8.8 client see own name in colors after "reload". Using 1.11.2 and 1.12 you see white nickname.

**Comment by MylesIsCool** [comment]
So this is possibly a scoreboard issue between 1.8.8 and 1.9 then? :)

**Comment by Inuun** [comment]
Probably yes, but is good idea to test it without viaversion on 1.11 spigot. I test it and write about result.

**Comment by Inuun** [comment]
Confirmed, this is issue with ViaVersion. On 1.11 server with TestingTablist after typing /tablist I see my nickname in colors.

**Comment by MylesIsCool** [comment]
As a workaround you can just disable ViaVersion autoteam, /viaversion autoteam. Will hopefully have a proper fix out for this soon :) (But yeah it's to do with our teaming stuff!)

**Comment by MylesIsCool** [comment]
Should be fixed in dev builds while still maintaining functionality. :)
