### ISSUE TITLE
Kick Error

### ISSUE THREAD

**Issue by ChavitaHD** [MylesIsCool/ViaVersion#70]
Hello,

I never get this error, but a lot of my players that are beta testing my revamped server get this error, and then get kicked.

http://prntscr.com/aaj474

What does it mean, and how can I fix it?

**Comment by HugoDaBosss** [comment]
Are you using any title/tablist plugin?
And what plugins are you using?

**Comment by HugoDaBosss** [comment]
Do you have any tips for me to recreate this issue?

**Comment by StamBoom** [comment]
Are You using bungeecord?
