### ISSUE TITLE
Exception when joining 1.8.8 server with 1.12 client (dev builds 170 up to 172)

### ISSUE THREAD

**Issue by Brokkonaut** [MylesIsCool/ViaVersion#701]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/6f5cb79e1f5af0f3d1db3b0f8dc898fa

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yes, BungeeCord - Without any special plugins
This server is running BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:6958943:1244 by md_5

### How does this error happen? login? Using an item? 
When logging in to a 1.8.8 server with a 1.12 client - it did not happen in the last ViaVersion release but in the recent dev builds.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://cubeimage.de/images/2017/06/26/GXx.png
No error in the console

**Comment by MylesIsCool** [comment]
Fixed :)
