### ISSUE TITLE
BossBar isn't working with 1.12 clients

### ISSUE THREAD

**Issue by MrCreeperkopf** [MylesIsCool/ViaVersion#703]
### What is the output link of /viaversion dump? 
https://gist.github.com/d4fc66b07554c6265afc3989a2c685d6

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
We are using our own fork of BungeeCord but we updated our fork to the newest commit of the official BungeeCord yesterday. We don't use any plugins on our BungeeCord that manipulates the bossbar.

### How does this error happen? login? Using an item? 
When a 1.12 client is connecting to the server he will be immediately kicked off cause of an error occurs on bungee side. I tried to debug this and came to the result that this can't be an issue of our bungee server. The amount of readable bytes in the ByteBuf when a 1.10 client connects are 151. When a 1.12 client connects only one byte.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
The stacktrace: https://pastebin.com/NexKN0J2

**Comment by MylesIsCool** [comment]
Does this issue happen if you direct connect to the 1.9.4 backend server?

**Comment by MrCreeperkopf** [comment]
Nope. Only with BungeeCord.

**Comment by MylesIsCool** [comment]
Can this be replicated with vanilla BungeeCord?

**Comment by MrCreeperkopf** [comment]
No. But our system is nearly identical with the vanilla BungeeCord.

**Comment by MylesIsCool** [comment]
I would suggest looking at the changes you have made as this looks like some sort of issue there.
