### ISSUE TITLE
Error with bungee crashing (Error from console supplied)

### ISSUE THREAD

**Issue by Tree182** [MylesIsCool/ViaVersion#704]
### What is the output link of /viaversion dump? 
https://gist.github.com/0a6ac43047088181d65a3162e931efb3

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Bungeecord 1.8.8 with Skins restorer

### How does this error happen? login? Using an item? 
Bungeecord randomly crashed after around 3 hours of being on

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Error code: 

https://pastebin.com/jENwZGBg

**Comment by MylesIsCool** [comment]
This might be down to you using an old version of SkinRestorer, I would suggest trying to update it and see if that helps.

The error provided basically says that ViaVersion had a malformed packet sent to it, and doesn't really indicate anything else which can be helpful to this problem.

**Comment by Tree182** [comment]
It didn't do this before I updated to the 1.12 Viaverson tho?

**Comment by MylesIsCool** [comment]
See above
