### ISSUE TITLE
ViaVersion Bungeecord not working

### ISSUE THREAD

**Issue by ToggleIP** [MylesIsCool/ViaVersion#705]
Hi,

I use a 1.8 bungeecord server but the server is up but it says cant connect to server and if you connect it says disconnected.

**Comment by Matsv** [comment]
Please fill in the issue template, we can't help you with the amount of information you gave us.

**Comment by ToggleIP** [comment]
### What is the output link of /viaversion dump? 
https://gist.github.com/f3fd9f9c46a368e477fc50c5c1f166cb

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

I use Bungeecord 1.8
No Plugins in it yet


### How does this error happen? login? Using an item? 

On login and on bungeecord start
### Is there an error in the console? Use pastebin.com. Is there a kick message?
no console error / Kick message disconnected
