### ISSUE TITLE
ViaVersion not working on bungeecord 1.8

### ISSUE THREAD

**Issue by ToggleIP** [MylesIsCool/ViaVersion#706]
What is the output link of /viaversion dump?

https://gist.github.com/f3fd9f9c46a368e477fc50c5c1f166cb

Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

I use Bungeecord 1.8
No Plugins in it yet

How does this error happen? login? Using an item?

On login and on bungeecord start

Is there an error in the console? Use pastebin.com. Is there a kick message?

no console error / Kick message disconnected

**Comment by Matsv** [comment]
Use the latest version of bungeecord, ViaVersion is not compatible with yours

**Comment by ToggleIP** [comment]
Ok thank you for the information.
