### ISSUE TITLE
Disconnection when falling in void on 1.11.2

### ISSUE THREAD

**Issue by v0idst4r** [MylesIsCool/ViaVersion#708]

**Comment by MylesIsCool** [comment]
Consider filling out the form fully, providing vague information does not help us replicate nor solve the issue.

**Comment by MylesIsCool** [comment]
See above.

**Comment by v0idst4r** [comment]
The server thinks it's getting a billion packets per second from the client when in the void even though on client side it's sending absolutely no packets at all to the server

**Comment by v0idst4r** [comment]
If you fall into the void you'll get kicked before you can respawn and then you'll be in an infinite loop.

**Comment by v0idst4r** [comment]
1.11.2 client and 1.8.9 server

**Comment by v0idst4r** [comment]
It doesn't happen on 1.12 for me, I guess this issue is irrelevant now I just need to update my forge mod.
