### ISSUE TITLE
Viaversion Disconnect When Use 1.12 or 1.11 but server use version 1.10.2

### ISSUE THREAD

**Issue by theodore120** [MylesIsCool/ViaVersion#709]
### What is the output link of /viaversion dump? 
https://gist.github.com/c476100add49fc2491fbc9394749d875

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yeah i'm use BungeeCord
Plugin List:
ActionHealth, AntiBugDame, AntiCreeper, AntiOP, ArmorStandTools, ASkyBlock, AuctionHouse, AutoSaveWorld, BanDesignByQuangCPvP_VN, Banknotes, BannerBoard, BannerBoard_LeaderHeads, BannerBoard_Skills, CarlTheCreeper, ChatItem, CheckMyInventory, ChestCommands, ChestShop, Citizens, CommandAliases, CommandNPC, CoreProtect, CrazyEnchantments, CustomOreGen, DeluxeChat, DontSpam, Essentials, EssentialsChat, EssentialsKitChest, EssentialsSpawn, EvilAdmin, ForceChat, Heads, HolographicDisplays, Hub, ItemCases, ItemTags, KillerMoney, KitAdder, LeaderHeads, LimitCrafting, mcMMO, MovingThings, MultiWorld, NapThe, NBTEditor, NightVisionReloaded, NoCheatPlus, NoLagg, NoPlugins, PandaWire, PermissionsEx, PlaceholderAPI, PlayerPoints, PlugMan, PremiumVanish, ProtocolLib, QuickBoard, SharpSK, ShopGUIPlus, Shopkeepers, SilkSpawners, skDragon, Skellett, SkinsRestorer, SkQuery, skRayFall, Skript, skUtilities, SmartGiants, SQLibrary, StackMob, TimedItems, TimeIsMoney, TradeMe, TuSKe, Umbaska, UUIDSpoof_-_Fix, Vault, Vehicles, VehiclesFlags, ViaVersion, WorldEdit, WorldGuard, WorldGuardFix, YouTubeBridge
### How does this error happen? login? Using an item? 
Error disconnect when i use version 1.11.2 or 1.12, i join Server 1 second it will kick me with Message [Proxy] Lost Connecttion to Server. But if i use version 1.10.2 to join server not have disconnect

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Sure i'm use Debug on server.protect
Here log console:
https://pastebin.com/hBsGs5EW

**Comment by MylesIsCool** [comment]
Does the error still happen without BannerBoard?

**Comment by theodore120** [comment]
i did try delete those related BannberBoard But still have error still disconnect on 1.12

**Comment by MylesIsCool** [comment]
Would you be able to test if this happens with no plugins? and possibly add half see if it works and work from there?

I believe it might be some sort of interference, very odd error though.

**Comment by theodore120** [comment]
Okay i will try

**Comment by theodore120** [comment]
i did try delete all plugins in my server 'Not Viaversion' Don't have error... well error appears cause my plugins?? ...

**Comment by theodore120** [comment]
Thanks For Support i did know it cause MultiWorld
