### ISSUE TITLE
Errors when hooking in into netty

### ISSUE THREAD

**Issue by Marcely1199** [MylesIsCool/ViaVersion#710]
### How does this error happen? login? Using an item?
When using this code (start's at line 78)

```java
try{
	final Method m = channel.channel.getClass().getMethod("remove", NMSClass.NETTY_CHANNELHANDLER);
	
	m.setAccessible(true);
	m.invoke(channel.channel, channel.handler);
}catch(NoSuchMethodException | SecurityException | IllegalAccessException | IllegalArgumentException e){
	e.printStackTrace();
}catch(InvocationTargetException e){ }
```
Also this code causes issues with your plugin:
```java		
try{
	if(channel.get("decoder") != null) // it should never happen but safety purpose
		channel.addAfter("decoder", "MBedwars_IM_" + pchannel.player.getName(), handler);
}catch(IllegalArgumentException e){
	channel.remove(channel.get("MBedwars_IM_" + pchannel.player.getName()));
	if(channel.get("decoder") != null) // it should never happen but safety purpose
		channel.addAfter("decoder", "MBedwars_IM_" + pchannel.player.getName(), handler);
}
```
But I've added these if checks to prevent that error occurs

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/MzGgY5iY

**Comment by MylesIsCool** [comment]
So how does this relate to ViaVersion?

You need to properly format things, the code is too poorly formatted on github to read.

**Comment by Marcely1199** [comment]
This error only occurs when using ViaVersion.
I've reformated the message so it should be readable now

**Comment by MylesIsCool** [comment]
I don't really get why you're injecting your own stuff and not using ProtocolLib.
(Even in your example you have it installed.)

The issue happens because you're trying to remove a channel that doesn't exist. This doesn't look ViaVersion related at all.

**Comment by ysl3000** [comment]
This is stupid. why defining a channel decoder name with each player name?
You don't need it! 
```
try{
	if(channel.get("decoder") != null) // it should never happen but safety purpose
		channel.addAfter("decoder", "MBedwars_IM_" + pchannel.player.getName(), handler);
}catch(IllegalArgumentException e){
	channel.remove(channel.get("MBedwars_IM_" + pchannel.player.getName()));
	if(channel.get("decoder") != null) // it should never happen but safety purpose
		channel.addAfter("decoder", "MBedwars_IM_" + pchannel.player.getName(), handler);
}
```

This should fit perfect:

```
try{
	if(channel.get("decoder") != null) // it should never happen but safety purpose
		channel.addAfter("decoder", "MBedwars_IM", handler);
}catch(IllegalArgumentException e){
	channel.remove("MBedwars_IM"); // this by the way is correct.
	if(channel.get("decoder") != null) // it should never happen but safety purpose
		channel.addAfter("decoder", "MBedwars_IM", handler);
}
```

**Comment by Marcely1199** [comment]
@MylesIsCool I am trying to do that without ProtocolLib
@ysl3000 Thought that it's not possible to have multiple channels with the same name but seems to work.
Players reported this when ViaVersion was installed.

**Comment by ysl3000** [comment]
@Marcely1199 You add a channelHandler after the decode channelHandler of each channel. A channel is dedicated to one player.

**Comment by MylesIsCool** [comment]
I have no idea what you're doing, I personally suggest depending on a proper Packet library instead of doing it yourself.
ViaVersion doesn't just mess with handlers, it might be that you're doing something like injecting in the wrong order. (Which you might want to try switching up the order in the plugin.yml using loadbefore / softdepend with ViaVersion)

Otherwise, I can't really help, there's nothing close to enough info provided and this is most likely down to the way your injecting not being consistent with other plugins / possibly a load order issue.
