### ISSUE TITLE
MC1.12 displays "Invalid Item!" when displayed in chat.

### ISSUE THREAD

**Issue by voodootje0** [MylesIsCool/ViaVersion#712]
When you're on 1.12 and type [item] in the chat it will display invalid items. (ViaVersion 1.1.1)
![image](https://user-images.githubusercontent.com/6852308/28229238-3f19d228-68e2-11e7-9903-79ebe98e64c0.png)

What [item] does, it displays your current item in hand into the chat. It's using fancifuls FancyMessage.

On all other versions (1.8 up to 1.11.2) it just displays everything.

If you type [item] from 1.12 you can still read it from the other versions. So only the display of some other item meta's is broken.

On 1.12 it does work with items without any extra item meta.
![image](https://user-images.githubusercontent.com/6852308/28230047-ab44aef2-68e5-11e7-9dbc-1a38f9fc0a42.png)
![image](https://user-images.githubusercontent.com/6852308/28230101-ddf6beb2-68e5-11e7-8989-75ef3f256da6.png)
Still, works. But when I'm adding a colored lore. it doesn't work anymore.
![image](https://user-images.githubusercontent.com/6852308/28230129-fb7185b2-68e5-11e7-8cc3-963022fc21ab.png)
![image](https://user-images.githubusercontent.com/6852308/28230116-f1d87baa-68e5-11e7-90d0-da6b7884085e.png)

Also when you're using enchants it doesn't work anymore. (I tested it with sharpness 1, also didn't work)
![image](https://user-images.githubusercontent.com/6852308/28230214-5001cdbc-68e6-11e7-991e-fc7822d6fc10.png)
![image](https://user-images.githubusercontent.com/6852308/28230223-595eb9ce-68e6-11e7-83e2-9c0e4db02fcc.png)

I hope you could add a fix for this issue =)
If you need any more information just let me know!

- voodootje0

**Comment by MylesIsCool** [comment]
As an update in regards to this issue, it seems this is down to 1.12 rejecting index labelled json nbt arrays,

Works: {id:\"minecraft:diamond_sword\",Count:1b,Damage:0s,tag:{ench:[{lvl:1s,id:16s}]}}

Does not: {id:\"minecraft:diamond_sword\",Count:1b,tag:{ench:[0:{lvl:1s,id:16s}]},Damage:0s}

Hopefully will have some sort of workaround out soon.

**Comment by MylesIsCool** [comment]
I don't have the time to patch this as i'm on holiday from tomorrow with no computer, hopefully you're cool with this.

If you wanted an alternative you could always consider using a plugin / code from https://www.spigotmc.org/resources/chatitem-display-items-in-chat.19064/ as that works fine between versions :)

**Comment by MylesIsCool** [comment]
Works for me now :), use dev builds if you need to use the version above.
