### ISSUE TITLE
Error in ViaVersion

### ISSUE THREAD

**Issue by serguna99** [MylesIsCool/ViaVersion#714]
### What is the output link of /viaversion dump? 

ViaVersion output error

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I'm using Bungecord from Slavik
Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:unknown:unknown
Plugins:
AdBlock
AncientGates
ArmorStandEditor
AutoMessage
AutoSaveWorld
AWD 
BanItem
bStats
Chairs
ChatManager
ChestCommands
Citizens
ClearLag
ColoredTags
CommandNPC
CPFix
CustomJoinItems
CustomPayloadFixer
DailyRewards
DonatCase
DonateGive
DrinksCMD
DynPad
EcoLeaderboards
Emojii
Essentials
HealthBar
HideStream
HolographicDisplays
ItemFixer
Jobs
JobsCommands
LeaderHeads
LimitEdite
LimitedWorldEdit
Marriage
MaxBans
MineResetLite
Multiverse-Core
PingMOTD
PlayEffect
PlugMan
RainbowArmour
ShoppingCartReloaded
SmokeTrail
Tablist
TitleManager
UralClans
ViaVersion Last
### How does this error happen? login? Using an item? 
Appeared errors are not known to me, it arises in the course of the game process, players play and there is such a mistake, but it does not appear often, but creates crash every 1-2 can 4 hours, I can not say for sure

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/ybNQv2J0

**Comment by serguna99** [comment]
Please check this problem

**Comment by MylesIsCool** [comment]
Consider reading the template that's provided and fill in all fields, also use pastebin in the future as it's a pain to scroll on GitHub.

**Comment by serguna99** [comment]
I updated the information

**Comment by MylesIsCool** [comment]
I need the output of the command "/viaversion dump"

**Comment by serguna99** [comment]
Command not found

**Comment by serguna99** [comment]
https://gist.github.com/d6bd0915a15cd78f2b725793e914f622

**Comment by serguna99** [comment]
Here is the conclusion from the team

**Comment by MylesIsCool** [comment]
Try without the plugins Tablist and see if the error still occurs.

**Comment by serguna99** [comment]
This did not solve the problem

**Comment by MylesIsCool** [comment]
I would suggest trying without ColouredTags then

**Comment by MylesIsCool** [comment]
See above, otherwise you'll need to remove plugins & test.
