### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by the-colamine** [MylesIsCool/ViaVersion#715]
### What is the output link of /viaversion dump? 
https://gist.github.com/0d6e8b8e3c8e80eef2b388118762d61a

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Plugins:
ViaVersion
Dream

### How does this error happen? login? Using an item? 
When server start/restart

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/Whu42KRn

**Comment by MylesIsCool** [comment]
The latest dev build should fix this, https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/artifact/jar/target/ViaVersion-1.1.2-SNAPSHOT.jar
