### ISSUE TITLE
BungeeChannelInitializer errror

### ISSUE THREAD

**Issue by Dimatert9** [MylesIsCool/ViaVersion#716]
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Custom bungeecord

### How does this error happen? login? Using an item? 
When force close channel before initilization 

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/h86Lj6KM

Changed PipelineUtils: https://pastebin.com/PKxkytUr LINE: 52-55
ConnectionDropper: https://pastebin.com/JQLtV1UF

**Comment by MylesIsCool** [comment]
Either change the injection order, or just run the code to add the handlers and close gracefully.

This isn't really a ViaVersion issue.

**Comment by Leymooo** [comment]
So, now this was added in bungeecord, so this error can be reproduced. (Simple bot attack, or fast rejoin 3 times.)
