### ISSUE TITLE
(1.8.9) Error on startup

### ISSUE THREAD

**Issue by roro1506** [MylesIsCool/ViaVersion#717]
### What is the output link of /viaversion dump? 
https://gist.github.com/396b0897763214373b92bbe0bf5e6c55

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
We are using BungeeCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:53cc324:unknown (Linux)
We are also using custom plugins, I'll list them out but you won't find them on internet.

ViaVersion (Of course), HelyGamesAPI, HelyGamesConnector, Punisher (Our Anti-Cheat), GameServer, BedWars (The plugin I am currently developing.)

### How does this error happen? login? Using an item? 
This error happened when the server started, there were nobody on it.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
There is an error in the console : https://pastebin.com/ez6yj7b6
And there is no kick message as there is nobody on the server at the startup.

**Comment by Matsv** [comment]
Should be fixed in the latest devbuild. Please ask for a reopen if it stills happens using it.
