### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Nishh** [MylesIsCool/ViaVersion#718]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/bc3b98316d78c73860b55a7eaf9525d1

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
PaperSpigot 1.11.2 (build 1104)
plugins: https://gist.github.com/Nishh/af751e1e52cf2536446fa7a01a730b80

### How does this error happen? login? Using an item? 
On server start (server.properties and bukkit.yml has debug = true)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://gist.github.com/Nishh/adf63b160e79e331c195fd7b006dbc9f

**Comment by Matsv** [comment]
Should be fixed in the latest devbuild.
