### ISSUE TITLE
weird console spam on join, respawn

### ISSUE THREAD

**Issue by aaa8881** [MylesIsCool/ViaVersion#721]
### What is the output link of /viaversion dump? 

https://gist.github.com/anonymous/47e4ed0a13c11a73f00a10935183b16a

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

yes, bungeecord #1250 (latest) , viaversion, viabackward, Libdisguise, Hidestream, Citizen.. and quite a few others that I'm sure doesn't do anything about packet stuff.. 

### How does this error happen? login? Using an item? 

The only issue is console spam when some players join. I have no idea why because I have never encountered this problem. Console spam is pasted in pastebin below. This console spam happens on player join, and respawn. People who generate this console spam is not logged in same version, but all versions exist from 1.9 to 1.12( 1.9 , 1.10, 1.11, 1.12 ) Server version is 1.11. I am not sure if this is doing particular harm besides console spamming yet. 

### Is there an error in the console? Use pastebin.com. Is there a kick message?

https://pastebin.com/ExQfvqv0

**Comment by aaa8881** [comment]
Before this happens, I had https://pastebin.com/JrcjK3ZT issue. not sure if this is relevant.

**Comment by Matsv** [comment]
One of your Spigot plugins is sending wrong entities. Please try to debug it until it no longer happens.

**Comment by Matsv** [comment]
It's with the latest devbuild of ViaBackwards possible to hide this error. Note that you don't solve anything by just hiding the error. I'd still recommend to find the problem with one of your other plugins.

Otherwise, you can change `suppress-metadata-errors` to `true`.
