### ISSUE TITLE
Error Codec

### ISSUE THREAD

**Issue by thelex337** [MylesIsCool/ViaVersion#722]
https://pastebin.com/QePKg1fu
https://pastebin.com/0yPtcNQV
https://hastebin.com/logimoveyu.lua
https://hastebin.com/wubecejuko.lua

**Comment by Matsv** [comment]
Please follow the [issue template](https://github.com/MylesIsCool/ViaVersion/blob/master/ISSUE_TEMPLATE.md). It's there for a reason.

**Comment by thelex337** [comment]
It a fatal bug ?

**Comment by MylesIsCool** [comment]
As said by mats, please fill in the issue report. Also try using the Dev builds (ci.viaversion.com).

**Comment by Matsv** [comment]
Going to close this issue. Please ask for a reopen if this still occurs for you, and when you're willing to provide more information.
