### ISSUE TITLE
Enchantment effect bug

### ISSUE THREAD

**Issue by NicoDreamzZ** [MylesIsCool/ViaVersion#723]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/2deea22de649d6d41dd171b6b9672dde

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yes, its the latest BungeeCord version. Proxied through a haproxy instance.

### How does this error happen? login? Using an item? 
When i add an enchantment effect without an enchantment to an item, it  is only be visible when i connect with the 1.8.* clients, not with a client higher than that.
```
public static ItemStack addGlow(ItemStack itemStack) {
        net.minecraft.server.v1_8_R3.ItemStack nmsStack = CraftItemStack.asNMSCopy(itemStack);
        NBTTagCompound tag = null;
        if (!nmsStack.hasTag()) {
            tag = new NBTTagCompound();
            nmsStack.setTag(tag);
        }
        if (tag == null) tag = nmsStack.getTag();
        NBTTagList ench = new NBTTagList();
        tag.set("ench", ench);
        nmsStack.setTag(tag);
        return CraftItemStack.asCraftMirror(nmsStack);
    }
```
That ist my code to make an item glow without an enchantment. When i use the code on a 1.12 server it is displayed correctly.

**Comment by limbo56** [comment]
I don't think this is a ViaVersion issue. Anyways, you don't need to use nms for this, just add the "HIDE_ENCHANTS" flag to the item's meta. Here's a method.
```
public static ItemStack addGlow(ItemStack itemStack) {
    ItemMeta meta = itemStack.getItemMeta();
    meta.addEnchant(Enchantment.LURE, 1, false);
    meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
   
    itemStack.setItemMeta(meta);
    return itemStack;
}
```

**Comment by NicoDreamzZ** [comment]
Sure this is a way to make items glow, but i have to give the item a real enchantment, and when i give the user the item it has a enchantment, with my method it only looks like there is a enchantment.

**Comment by limbo56** [comment]
You can just create a register a new enchantment which does nothing and add it to the item.

**Comment by MylesIsCool** [comment]
This is a mojang change and nothing we can personally do about this, see above solution for "glowing" from limbo :)
