### ISSUE TITLE
Issue with spigot server 1.9.4 don't accept client from other versions like 1.9

### ISSUE THREAD

**Issue by Manfighter57** [MylesIsCool/ViaVersion#724]
### What is the output link of /viaversion dump? 

https://gist.github.com/2d75c13adca28e2b823d20513b6ac27d

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Yes, git:BungeeCord-Bootstrap:1.9-SNAPSHOT:a12ac37:1152

### How does this error happen? login? Using an item? 

Login

### Is there an error in the console? Use pastebin.com. Is there a kick message?

Manfighter57 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/MylesIsCool/ViaVersion/issues
{Type: Chunk, Source #1: us.myles.ViaVersion.protocols.protocol1_9_1_2to1_9_3_4.Protocol1_9_1_2TO1_9_3_4$2 (Anonymous), Source #0: us.myles.ViaVersion.protocols.protocol1_9_1_2to1_9_3_4.Protocol1_9_1_2TO1_9_3_4$2$1 (Anonymous), Data: [], Packet ID: 32}
Actual Error:

**Comment by Matsv** [comment]
Please change 'debug' to 'true' in server.properties and give us the full exception. Also update your bungeecord to the latest version.

**Comment by Matsv** [comment]
Closing because you didn't respond. 
Please ask for a reopen if you can provide more information. (:
