### ISSUE TITLE
1.8 for Via Backwards ?

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#725]
Hello !

Could you add 1.8 support for Via Backwards ? :D

**Comment by Matsv** [comment]
As mentioned on the FAQ:

> Please support 1.8 and lower? 
No, use ProtocolSupport if you want Backwards compatibility for 1.8 and lower.

**Comment by TheIntelloBox** [comment]
But why ?

**Comment by Matsv** [comment]
Creating 1.8 support will take a lot of time. I don't have that time.
