### ISSUE TITLE
If a player joins with a minecraft version that isant the server version it kicks player

### ISSUE THREAD

**Issue by kjl13** [MylesIsCool/ViaVersion#729]
### What is the output link of /viaversion dump? 
https://pastebin.com/ui026wnY

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
We are using a bungeecord fork called hexacord to allow players 1.7 through 1.12.1 to login to our network.

### How does this error happen? login? Using an item? 
This error happenes when I login with 1.9 and up
We saw this start to happen when we updated viaversions to the latest version we were using the version behind the latest before.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/8v2UFfhw

**Comment by Matsv** [comment]
Could you try to debug it by removing plugins one by one until it no longer happens?

**Comment by kjl13** [comment]
Sure but it happened when we updated your plugin via versions . As it comes to mind we also updated bungee cord to the latest version. Could it be that?

**Comment by xbette** [comment]
I got told on discord that i need this plugin also: https://www.spigotmc.org/resources/viabackwards.27448/ Maybe you are missing that one ?

**Comment by kjl13** [comment]
We are using a 1.8 server and use protocol support to make our server compatible with 1.7 and use viaversions to make our server compatible with 1,9 and up. But when I updated viaversions to version 1.2.0 from version 1.1.1.

**Comment by kjl13** [comment]
I just tried to downgrade to the version(1.1.1) I was using before and it fixed the issue. Furthermore I beleive it is an issue with the plugin. If you need any other info please feel free to ask.

**Comment by MylesIsCool** [comment]
Which client versions did you test?
What Hexacord build are you using?

**Comment by kjl13** [comment]
The client versions I tested are 1.9, 1.10, 1.11, and 1.12.
The hexacord version I am using is v160 found here: https://github.com/HexagonMC/BungeeCord/releases

**Comment by MylesIsCool** [comment]
Do you use any BungeeCord plugins?

**Comment by kjl13** [comment]
Yes, The plugin names are bungee-yamler version 2.4.0 and our custom bungee plugin . “MoltresBungee”

**Comment by kjl13** [comment]
But this only started happening when I updated via versions from the version 1.1.1 to the latest version.

**Comment by MylesIsCool** [comment]
I'm unable to replicate this issue, Hexacord and ViaVersion work fine with 1.12.1 etc on a 1.8 server.

**Comment by kjl13** [comment]
Would I be able to show you? I need to resolve this issue.

**Comment by kjl13** [comment]
Again here is the error from console with debug true in server.properties: https://pastebin.com/pHsUkJzr
If possible, could I please get support over discord if possible. It would make this much easier.

Thanks, kjl13

**Comment by MylesIsCool** [comment]
There's really nothing I can help with, this will be based on your plugin or your server software version of Hexa.

I've tested locally with latest ViaVersion on Spigot 1.8.8 with latest Hexacord and it works fine. I'd suggest removing plugins and testing if it works, and possibly try just connecting to the backend. Otherwise it's down to your plugins and something blocking it there, as far as i'm aware nothing protocol wise has changed for the entire of ViaVersion.

**Comment by MylesIsCool** [comment]
Closing, see above for details, this won't be an issue with ViaVersion and will be down to configuration/plugins.

If you do find some configuration that doesn't use custom plugins and does cause this issue i'll be happy to investigate and reopen.
