### ISSUE TITLE
BuyCraft Issues

### ISSUE THREAD

**Issue by ChavitaHD** [MylesIsCool/ViaVersion#73]
Another issue.
When I do /buy I cant click anything.
http://prntscr.com/aajm85

**Comment by Paulomart** [comment]
Is it only happening with buycraft?

**Comment by ChavitaHD** [comment]
From what I can see, yes.

**Comment by Paulomart** [comment]
So in other guis not? Then something with buycraft is wrong.

**Comment by ChavitaHD** [comment]
rip

**Comment by Paulomart** [comment]
Not sure. It's strange that happens only for buycraft. You can't click any item right? Can you test removing the potion?

**Comment by ChavitaHD** [comment]
I cant click anything.

**Comment by Paulomart** [comment]
Even without potion in the inventory? Can you install another plugin that adds a gui and tell me if it's working?

**Comment by ChavitaHD** [comment]
Hmm, chestcommands works, I think it is the potion.

**Comment by Paulomart** [comment]
Please make sure

**Comment by ChavitaHD** [comment]
Yup, my chestcommands server selector works.

**Comment by Paulomart** [comment]
Put a potion into your chest commands gui. Test that

**Comment by ChavitaHD** [comment]
Ahh, it is buycraft, can the dev add support to that?

**Comment by Paulomart** [comment]
So potion is working in chest commands?

**Comment by ChavitaHD** [comment]
yes

**Comment by Paulomart** [comment]
Hmm strange then. I will take a look later today

**Comment by timr2000** [comment]
i use buycraft to and it works perfect?

**Comment by HAlexTM** [comment]
Yes @MylesIsCool this thread should be closed as BuyCraft works correctly

**Comment by MylesIsCool** [comment]
Closed works fine
