### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by DamonOnYT** [MylesIsCool/ViaVersion#731]
[Sat, 12. Aug 2017 18:57:25 AEST INFO] sk8erace1 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/MylesIsCool/ViaVersion/issues
{Type: Chunk, Source #1: nl.matsv.viabackwards.protocol.protocol1_12to1_11_1.packets.BlockItemPackets1_12$7 (Anonymous), Source #0: nl.matsv.viabackwards.protocol.protocol1_12to1_11_1.packets.BlockItemPackets1_12$7$1 (Anonymous), Data: [], Packet ID: 32}
Actual Error: 
[Sat, 12. Aug 2017 18:57:25 AEST INFO] sk8erace1 left the game

**Comment by Arkyo** [comment]
+1

**Comment by MylesIsCool** [comment]
Please consider filling out the issue template properly, it provides useful information. And if possible provide full info with debug=true in server.properties.

It's worth noting this issue relates to ViaBackwards so Mats will have to look into it when he's free but the info above is required for him to do so.

**Comment by MylesIsCool** [comment]
See above if this is still a issue and you want it fixed, and provide required info and we'll reopen.
