### ISSUE TITLE
Not possible to join a spigot 1.12.1 server after an BungeeCord with an updated Viaversion

### ISSUE THREAD

**Issue by harm27** [MylesIsCool/ViaVersion#733]
[Image with the error](https://cdn.discordapp.com/attachments/299951182217084928/346681540421484545/Naamloos.png)
### What is the output link of /viaversion dump? 
https://gist.github.com/4b3e7639593149a3eb79e067e4e43a58

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Bungeecord Latested build
Spigot 1.12.1

### How does this error happen? login? Using an item? 
When trying to connect with a 1.12.1 client from a 1.8 server to a 1.12.1 server through a bungeecord server.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Bungeecord error: https://pastebin.com/BysxxYXb
Spigot error: https://pastebin.com/m4E0mpSN

If more info is needed, then i will try get those info. 
Also it worked when both the client and spigot server had the 1.12 version.
Also not sure if it is a viaversion or a bungeecord problem.

**Comment by MylesIsCool** [comment]
I doubt you're using latest version of Bungee probably the issue, otherwise provide the viaversion dump from the Bungee console.

**Comment by harm27** [comment]
The build of bungeecord is frome the sametime as the Viaversion build. Dump added in the first message.

**Comment by harm27** [comment]
And is 1.2.0 the latest build for viaversion?

**Comment by MylesIsCool** [comment]
1.2.0 is the latest ViaVersion

**Comment by harm27** [comment]
Found part of the problem. There was a problem with the capsulation of the jar file of bungeecord. The newest one was called Bungeecord.jar and the used one was called bungeecord.jar. Thats why it failed. Thanks for the help.
