### ISSUE TITLE
chat json error

### ISSUE THREAD

**Issue by aaa8881** [MylesIsCool/ViaVersion#734]
### What is the output link of /viaversion dump? 

https://gist.github.com/ab6b3409615efd0f6a1ee7948a6d615a

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

BungeeCord #1259 , viaversion 1.2.0 , viabackward 2.1.1 , antibotdeluxe 

### How does this error happen? login? Using an item? 
spigot version 1.11.2

1. install showitem , https://www.spigotmc.org/resources/showitem.10133/
2. try to represent item in chat by %item% (by default) , it makes player to hover item to check its attributes. 
3. when player use chat variable to chat, error occurs (on chat event )
4. Also player who connected to 1.12 and 1.12.1 can not see proper attributes, but see "invalid item" 
5. I have already contacted showitem developer, and he said he believes this is issue from viaversion. 

### Is there an error in the console? Use pastebin.com. Is there a kick message?

https://pastebin.com/bcg20PbM

**Comment by MylesIsCool** [comment]
Could you try the latest dev build of ViaVersion?

**Comment by aaa8881** [comment]
yes this is from viaversion 1.2.0 which is the latest.

**Comment by Matsv** [comment]
Please try this build (http://ci.viaversion.com/job/ViaVersion/) (:

**Comment by aaa8881** [comment]
yay fixed!! i'll close issue.
