### ISSUE TITLE
java.lang.UnsupportedOperationException: JsonObject

### ISSUE THREAD

**Issue by Coll1234567** [MylesIsCool/ViaVersion#735]
Output: https://gist.github.com/anonymous/9fb2e632308c5b2bde613227ccd72852

This error occurs when using the Bungee chat API (Built into spigot) to send an Itemstack as a hoverable action in chat (player.spigot().sendMessage(BaseComponent)).

Only observed when my 1.11 server attempts to send this to a 1.12.1 client. When this occurs then item simply shows "Invalid Item!" when you hover over it.

Console error: https://hastebin.com/suyabesice.md

**Comment by MylesIsCool** [comment]
Use latest dev build, https://ci.viaversion.com/job/ViaVersion/
