### ISSUE TITLE
ViaVersions And Viaversions Backwards "cannout connect to server"

### ISSUE THREAD

**Issue by AlexPGAO** [MylesIsCool/ViaVersion#738]
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Viaversions
Backwards Viaversions
ProtocolLib

### How does this error happen? login? Using an item? 
On the Minecraft Server List

**Comment by Matsv** [comment]
We can't help you with the very limited information you provided.

**Comment by MylesIsCool** [comment]
Please recreate this issue / update it with proper information and instructions on what happens and the dump and we'd be happy to help.
