### ISSUE TITLE
Switching from a sword to a different item and trying to use that item will not register

### ISSUE THREAD

**Issue by v0idst4r** [MylesIsCool/ViaVersion#740]
### What is the output link of /viaversion dump? 
https://gist.github.com/171998bbe3f09596b6eb16cccbc92aa1

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
ProtocolLib and AAC on the latest version of Spigot for 1.8

### How does this error happen? login? Using an item? 
When quickly switching from a sword to another item then trying to use it, the item wont be used and you'll instead get a shield and block.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

No

**Comment by v0idst4r** [comment]
I think I made an issue about this in the past, sorry I didn't provide much information that time.

**Comment by v0idst4r** [comment]
As an example say I am holding a sword then the client sends a CPacketHeldItemChange to a health potion, then it sends a CPacketPlayerTryUseItem. It won't register unless you wait roughly 200ms after it sends the new slot.

**Comment by v0idst4r** [comment]
(I also exempted myself from AAC and tried this again and it still occurred.)

**Comment by v0idst4r** [comment]
Here's a video https://www.youtube.com/watch?v=x0YcGKEN7JM

**Comment by MylesIsCool** [comment]
Does this require AAC?

I can't replicate this otherwise. (Normal spigot)

**Comment by v0idst4r** [comment]
No, when I get home today I'll provide specific versions of Spigot and ViaVersion as well as update everything.

**Comment by MylesIsCool** [comment]
Is there any update on this?

**Comment by MylesIsCool** [comment]
See above, otherwise will follow up when we can replicate.
