### ISSUE TITLE
Bungee error on login

### ISSUE THREAD

**Issue by MinecraftB0ss** [MylesIsCool/ViaVersion#741]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/381e90451bbe677c06d08aa3f000330f

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
All relevant info listed in dump.

### How does this error happen? login? Using an item? 
Looks to happen randomly on login

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/sxzBcVju

**Comment by pjorun** [comment]
I have this same error:
https://gist.github.com/pjorun/8ae28d2236db4dcffe2caa3d8879b00a

**Comment by Per-Thulin** [comment]
My variation of DecoderException error.
https://gist.github.com/Per-Thulin/ed7f683c1252f61b26e62828e9bf9955
On Bungee, related to bungee lockups maybe.
ViaVersion-1.2.1-SNAPSHOT, was latest version on Aug 5th

**Comment by MylesIsCool** [comment]
@pjorun This issue doesn't look related to this one, please make a new issue and fill out all details.

@Per-Thulin This just looks like a client sending bad data

**Comment by MylesIsCool** [comment]
Could you possibly try without some of your BungeeCord plugins? I'm in belief this might be down to outdated plugins messing up packets on the bungee.

**Comment by MinecraftB0ss** [comment]
Ill see what i can do about testing with less plugins, however most of them are used and this is in production

**Comment by MylesIsCool** [comment]
Please get back when you have more info & request reopen, I suspect this is down to outdated bungee plugins (most likely).
