### ISSUE TITLE
Blank Sign Bug

### ISSUE THREAD

**Issue by DeveloperBoy** [MylesIsCool/ViaVersion#742]
### What is the output link of /viaversion dump? 
https://gist.github.com/c08ea69ed46a3938f46c545177de731e

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No, only Spigot.

### How does this error happen? login? Using an item? 
When I join in 1.11.2 on a 1.8 Spigot server with the newest ViaVersion plugin, I can't see the text on the signs, they are blank.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No, no error and no kick message.

**Comment by MylesIsCool** [comment]
Read the compatibility guide on the main plugin page, in regards to BKCommonLib.
