### ISSUE TITLE
Could not find valid metadata

### ISSUE THREAD

**Issue by andrei1058** [MylesIsCool/ViaVersion#744]
### What is the output link of /viaversion dump? 
https://gist.github.com/144e6a373f43cde9c865e875ed5ef9c6https://gist.github.com/144e6a373f43cde9c865e875ed5ef9c6

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Bungee network. WorldEdit, Zombies, IPWhitelist, GroupManager, LagMonitor, ViaVersion, Vault, EasyBackup, ProtocolLib, Multiverse-Core, AAC, SkinsRestorer, CorpseReborn, HolographicDisplays, LiteBans

### How does this error happen? login? Using an item? 
I'm not sure. I was just using a pistol which shoots with entities (snowball)

### Is there an error in the console? Use pastebin.com. Is there a kick message?

https://pastebin.com/uWtZQfni

**Comment by MylesIsCool** [comment]
Contact the author of the pistol plugin you use and tell them to send the right data for Minecraft 1.8 or ignore it (probably has side effects) and turn suppress metadata errors on in the viaversion config.
