### ISSUE TITLE
Random kicks on 1.9.4 server with viaversion

### ISSUE THREAD

**Issue by jnijland** [MylesIsCool/ViaVersion#749]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/08616bcb9795ef70ba1c8129e7159188

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Bungeecord, fastaynscworldedit, coreprotect, emptyworldgenerator, essentials, itemrestrict, litebans, multiworld, plotsquared, tplogin, worldedit and worldguard.

### How does this error happen? login? Using an item? 
When flying randomly on the (creative plots) server 

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/t7GQL1wQ

Kick message: Internal Exception: java.io.IOException: An established connection was aborted by the software in your host machine.

**Comment by MylesIsCool** [comment]
Which versions get kicked?

**Comment by krusic22** [comment]
1.9.2 and 1.9.4 cannot connect (using Bungee). There is no error except ReadTimeoutException : null

**Comment by MylesIsCool** [comment]
Could you post info about your BungeeCord version?

**Comment by krusic22** [comment]
Bungee: This server is running BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:0eaabdf:1265 by md_5
ViaVersion 1.3.0
Skins restorer...
Note: The connection doesn't even get to the lobby server.

**Comment by jnijland** [comment]
None of the minecraft versions from 1.9 and higher can connect at the moment. The server is running the special bungeecord version from HexagonMC (https://github.com/HexagonMC/BungeeCord).

**Comment by MylesIsCool** [comment]
Could you try without SkinRestorer? and possibly use ViaVersion on backend servers rather than Bungee

**Comment by jnijland** [comment]
I'm not using SkinRestorer (that reply was from somebody else who, I guess has the same issue). I already have viaversion installed on my spigot server in stead of my bungeecord.

**Comment by MylesIsCool** [comment]
Can you connect if you directly connect to the backend servers?

**Comment by jnijland** [comment]
After some good research I discovered that it was a faulty chunk in the world. Thanks for the quick replies and help. After fixing the chunk this didn't happen anymore.

**Comment by MylesIsCool** [comment]
Glad to hear :)
