### ISSUE TITLE
1.9 Chunks not loading right

### ISSUE THREAD

**Issue by wow4201** [MylesIsCool/ViaVersion#75]
Hi,

on 1.9 client some chunks aren't loading right, when I move around the map, chunks fill in and out.
1.8 clients work fine.

This is basically with no plugins enabled. Some parts of map are completely fine, so weird.

http://imgur.com/y4NhnYe

**Comment by Paulomart** [comment]
Duplicate of #38 please close

**Comment by MylesIsCool** [comment]
As above
