### ISSUE TITLE
Error being spammed constantly in console

### ISSUE THREAD

**Issue by Tree182** [MylesIsCool/ViaVersion#751]
### What is the output link of /viaversion dump? 
https://gist.github.com/21bca1f0c6bff6886b91f22f351735fd

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
This is running on Bungeecord

### How does this error happen? login? Using an item? 
Players getting disconnected

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/xUajyggy

**Comment by MylesIsCool** [comment]
This looks like something else sending bad data and triggers ViaVersion not to interpret it properly as it's bad data for the version, I'd suggest trying with less / no bungee plugins other than via.

**Comment by Tree182** [comment]
I can't really just remove bungee plugins. Obviously the plugins I use are there for a reason, they have a job to do.

**Comment by MylesIsCool** [comment]
You could just make a copy and then test on the copy so you can find what causes the disconnects?

**Comment by Tree182** [comment]
That will be SkinsRestorer I think. The other plugins don't do anything that would interact with Viaversion.

The only other plugins are:
CustomPayloadFixer - This error predates adding this plugin. 
BDBungee - Just syncs up the player count between multiple bungee's
BungeeMotd - Sets the MOTD
RandomHub - Just sends the user to a random lobby on join.

So I'm almost certain that its Via clashing with SkinsRestorer.

**Comment by MylesIsCool** [comment]
If you could test with this on your setup it would be appreciated (by copying it of course).

It's possible because it's a old version of SkinRestorer that it has some packet issues.

**Comment by Tree182** [comment]
Hi yeah I did test. It is an issue with Viaversion not being compatible with skinsrestorer.

**Comment by MylesIsCool** [comment]
Unfortunately, this isn't something that can be fixed our end, from what I saw on their discord it would seem that the latest version of it + ViaVersion would work but I'm unable to confirm that.

The error that appears is due to some sort of bad data being sent and there's no much ViaVersion can do about it, ignoring it would lead to plugins not functioning / Minecraft features not working.
