### ISSUE TITLE
1.12 Players not able to join a 1.11.2 server

### ISSUE THREAD

**Issue by IAB007** [MylesIsCool/ViaVersion#753]
https://gist.github.com/80c1c8d08c960f9cc1fc336850a0b009

I use bungeecord (https://i.imgur.com/MbbNvK5.png) with my own plugin and the Buycraft plugin

The error happen sometime, when I join the server

https://pastebin.com/bTvxeST4

**Comment by MylesIsCool** [comment]
Update your BungeeCord to the latest version, otherwise try using Bungee with no other plugins as they might be sending bad data.

**Comment by MylesIsCool** [comment]
If you need further help just say so, and we'll reopen. (or if you have more info, i.e happens with no plugins etc)
