### ISSUE TITLE
InformativeException

### ISSUE THREAD

**Issue by ArtNRG** [MylesIsCool/ViaVersion#755]
### What is the output link of /viaversion dump? 
https://gist.github.com/49e1660256cae02b5bbbb88d13054243

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
https://pastebin.com/raw/06MYFHjP

### How does this error happen? login? Using an item? 
On disconnect one of users

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/E7cw8gWr

**Comment by MylesIsCool** [comment]
The error provided means the server received bad login info, this most likely is down to a server list / custom client and can be ignored.
