### ISSUE TITLE
It alway disconnect if player use client  higher version

### ISSUE THREAD

**Issue by sayoui** [MylesIsCool/ViaVersion#756]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/10d006835c6e7c24cbf00274793a14ea

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord

### How does this error happen? login? Using an item? 
It alway disconnect if player use client  higher version

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/A7RjeRki

**Comment by MylesIsCool** [comment]
The error provided is down to one of the following:

- A plugin you have is sending bad chunk data

- You have a corrupted chunk

It's most likely the second given the plugins you have. Unfortunately, there's not much we can do about this as it's bad data.

If you want to be certain you could copy your server and remove the plugins and see if it happens.

**Comment by sayoui** [comment]
Give me a few day

**Comment by sayoui** [comment]
my server 
When completely download then delete link me
https://drive.google.com/file/d/0B8-sPc9LpCnPOUdUS2daVkpua0k/view?usp=sharing
tast kick 
map Miner3  /mv tp miner3
XYZ -158 64 -206   /tp -158 64 -206

BungeeCord use
https://ci.md-5.net/job/BungeeCord/1273/

**Comment by MylesIsCool** [comment]
The issue is based on a specific area and given the error is given by ViaVersion (chunks being sent badly) this would be down to chunk corruption. You'd have to repair the chunks / delete them.
