### ISSUE TITLE
Chat says "chat.type.achievement", when someone gets an achievement (1.12.x on 1.8.x server)

### ISSUE THREAD

**Issue by DoNotSpamPls** [MylesIsCool/ViaVersion#757]
### What is the output link of /viaversion dump? 

¯\\\_(ツ)_/¯, but I think it's reproducible on all servers

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

No, only Spigot 1.8.8

### How does this error happen? login? Using an item? 

When someone gets an achievement in a 1.8.x server, clients who are using a 1.12.x client get the generic "chat.type.achievement" message.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

No

**Comment by krusic22** [comment]
Via tries to send the achievement to the 1.12 client. But 1.12 uses a new achievement system so it just display the requested text (it tries to pull a translation but there's none). The easiest way to fix this is just to disable achievement announcements.

**Comment by AirCraze** [comment]
mommy!
