### ISSUE TITLE
Minecarts: Cant get out & Double placing sound

### ISSUE THREAD

**Issue by melerpe** [MylesIsCool/ViaVersion#76]
If you want to leave a minecart you can't get out of it, Even teleporting doesn't work. This is very fustrating, because i have a theme park themed server with traincarts!

And when you place a block i hear double placing sound.

**Comment by HugoDaBosss** [comment]
The issue with minecarts is known: https://github.com/MylesIsCool/ViaVersion/pull/33
And for the double place sound, I'll look into it.

**Comment by HugoDaBosss** [comment]
I proposed a fix for the double placing sound: https://github.com/MylesIsCool/ViaVersion/pull/64

**Comment by MylesIsCool** [comment]
See above, will be out in next version and minecarts is a duplicate.

**Comment by StamBoom** [comment]
Fixed #83
