### ISSUE TITLE
Error+disconnect (protocols.protocol1_9to1_8.packets.WorldPackets$4)

### ISSUE THREAD

**Issue by DardBrinza** [MylesIsCool/ViaVersion#760]
### What is the output link of /viaversion dump? 
https://gist.github.com/9cfcc5d0e3cbf5808f29a2371f29567f

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
WaterFall (latest build #147)

### How does this error happen? login? Using an item? 
[164.138.92.92:49932|masim] -> UpstreamBridge - encountered exception (disconnect)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/m5NYc4uv

**Comment by MylesIsCool** [comment]
I'd suggest copying your Bungee and then testing with no bungee plugins.

The issue is either outdated Bungee plugins or a corrupted chunk.

**Comment by MylesIsCool** [comment]
See above :) (I suspect it's a corrupted chunk)
