### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Esmorall** [MylesIsCool/ViaVersion#762]
### What is the output link of /viaversion dump? 
https://gist.github.com/42b3911246882528f4d24ed523229fc3

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Bungeecord side only

### How does this error happen? login? Using an item? 
i'm not sure

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/gz4gEVQy

**Comment by MylesIsCool** [comment]
Would it be possible for you to copy your bungee and test with no bungee plugins?

**Comment by MylesIsCool** [comment]
See above, then if you have issues otherwise request reopen.
