### ISSUE TITLE
[Feature] Disable multiple features

### ISSUE THREAD

**Issue by DiscoverSquishy** [MylesIsCool/ViaVersion#763]
Hey so I don't know if this was created before but here I go!

It would be nice if there was a (True / False) statements to disable shields along with press F to make a item on your left hand.

Don't know if that's possible but if in the next update this happens I am going to be very happy!

**Comment by Eros** [comment]
It for sure is possible, which do you want this for? Bukkit or Sponge?

**Comment by DiscoverSquishy** [comment]
Bukkit :)

**Comment by MylesIsCool** [comment]
This isn't something we'd do directly in via, as we make gameplay the same as the server version.

Otherwise I believe Eros is working on something cool :)

**Comment by DiscoverSquishy** [comment]
Alright looking forward to something new! :D
