### ISSUE TITLE
Random Error in Console

### ISSUE THREAD

**Issue by lucas2107** [MylesIsCool/ViaVersion#764]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/12c2805faad6553afcebca36ee88884b

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Plugins: http://prntscr.com/h060fk

### How does this error happen? login? Using an item? 
No idea if someone using an item, there is 170 players :/

### Is there an error in the console? Use pastebin.com. Is there a kick message?

https://hastebin.com/afatetuqew.md

**Comment by MylesIsCool** [comment]
This error is caused by a client sending bad packets to the server, in the future we may offer to suppress pre-login packet errors but this may cause issues debugging login issues.
