### ISSUE TITLE
viaversion does not work with travertine

### ISSUE THREAD

**Issue by PhanaticD** [MylesIsCool/ViaVersion#766]
when using viaversion with travertine I get this message:

22:46:12 [INFO] [ViaVersion] ViaVersion detected server version: 1.7-1.7.5(4)
22:46:12 [WARNING] [ViaVersion] ViaVersion does not have any compatible versions for this server version, please read our resource page carefully.

**Comment by krusic22** [comment]
ViaVersion should be used on 1.8 or higher.

**Comment by PhanaticD** [comment]
travertine is 1.12

**Comment by krusic22** [comment]
It's 1.7 - 1.12. Via looks at the lowest supported version I guess.

**Comment by MylesIsCool** [comment]
Have you tested using Travertine and ViaVersion although this error is displayed?

**Comment by PhanaticD** [comment]
hehe my bad

**Comment by PhanaticD** [comment]
actually its not working if the spigot server is on 1.12.2

00:09:48 [WARNING] [user] <-> ServerConnector [skyblock] - bad packet ID, are mods in use!? Unsupported protocol version
00:09:48 [INFO] [dndkeg] disconnected with: Exception Connecting:DecoderException : Error decoding packet id 18 with contents:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 18 0c 50 53 7c 4b 65 65 70 41 6c 69 76 65       |..PS|KeepAlive  |
+--------+-------------------------------------------------+----------------+ @ net.md_5.bungee.protocol.MinecraftDecoder:69

**Comment by PhanaticD** [comment]
actually i wouldnt really expect this to work like this, so probably not a viaversion issue
