### ISSUE TITLE
1.12.2 being kicked

### ISSUE THREAD

**Issue by ridalarry** [MylesIsCool/ViaVersion#767]
This is the latest version of ViaVersion from Jenkins
The server is on 1.11.2
The dump is: https://gist.github.com/af8b7c5e91a4b6bae80ee55b90a65d2a
The kicked player is on 1.12.2 on login
I got HexaCord (BungeeCord fork) and ProtocolSupport
Bungee kick message and error: https://pastebin.com/JuxY4v7y
There is no errors on the normal server.

**Comment by ridalarry** [comment]
https://gyazo.com/58c6f0eedb057d0be177d09aeeabdb7d
cs is commandsync

**Comment by MylesIsCool** [comment]
Fixed via Discord chat, BungeeResourcePack plugin was the issue
