### ISSUE TITLE
Error with joining player

### ISSUE THREAD

**Issue by MangoCZE** [MylesIsCool/ViaVersion#768]
Hi, if player join on my server, in console is error:
`[16:30:49 INFO]: UUID of player Mango is f023f4b2-7d77-3a9f-a9b1-45934966c6f3
[16:30:50 INFO]: Mango[/185.73.100.2:42124] logged in with entity id 13 at ([Auth]98.57725716045061, 72.0, 167.43604175359235)
[16:30:52 INFO]: Mango lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/MylesIsCool/ViaVersion/issues
{Type: Chunk, Source #1: us.myles.ViaVersion.protocols.protocol1_12to1_11_1.Protocol1_12To1_11_1$4 (Anonymous), Source #0: us.myles.ViaVersion.protocols.protocol1_12to1_11_1.Protocol1_12To1_11_1$4$1 (Anonymous), Data: [], Packet ID: 32}
`
and in minecraft client: [Proxy] connerction lost. How to fix it? thanks

**Comment by MylesIsCool** [comment]
Please fill out the issue template fully

**Comment by MangoCZE** [comment]
### What is the output link of /viaversion dump? 

https://gist.github.com/e3189b63254e77c1b61781ed0a26296f

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

BungeeCord ( Waterfall ), 1.12.2

### How does this error happen? login? Using an item? 

On join the game.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Error: https://hastebin.com/tepegomisu.php
Kick message: [Proxy] Lost connection to server.

**Comment by MylesIsCool** [comment]
Try without SkinRestorer,

**Comment by MangoCZE** [comment]
Plugins on proxy: BungeeAdminTools, BungeeRcon, BungeeReport, NuVotifier, ServerListPlus, SkinRestorer, SlashServer, UltimateFriends, ViaVersions, YamlerCore

**Comment by MylesIsCool** [comment]
You should only use ViaVersion on BungeeCord OR Spigot, not both.

I'd suggest removing from the Bungee.

**Comment by MangoCZE** [comment]
without skinrestorer working, thanks
