### ISSUE TITLE
bug something

### ISSUE THREAD

**Issue by kittin25421** [MylesIsCool/ViaVersion#772]
### What is the output link of /viaversion dump? 
me: i tried to used this command but it's not worked (/viaver dumb)

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
me: not bungeecord, i using spigot version git-spigot-596221b-9a1fc1e (1.12-RO.1)
plugins:
Alert
Anticreeper
Autome
ChatMessnger
Chatsounds
ChestShop-Fixed (Error)
Clearlag
ColoredTags
CommandBlockUltimate
CommandCoodown
CrackShot
Craftconomy
CratesPlus
CTNSC_Tablist
CTNSC_DisplayName
CTNSC_Scoreboard
CTNSC_Stats
CTNSC
EasyWarp
EndlessEnchant
EpicBoss
Essentials-2.x
EssentialsChat-2.x
EssentialsProtect-2.x
EssentialsSpawn-2.x
EssentialsXGroupManager-2.0.1
GhostScavengerHunt
HealthBar
Hubthat
IP-Check
Itemizer
LightChatBubbles
LimitDrops
LockettePro
MiniPacks
Mutiverse-Core
Mutiverse-Inventories
MyCommand
MyPet
NoFlyZone
OpenInv
ParticleHats
PlaceholderAPI
PlayMoreSounds
PluginConstructorAPI
ProtocolLib
PvP1vs1
pvparena
RainbowChat
rpgitem-reloaded
Scavenger
ShopChest
Shopkeepers
SignShop
SilkSpawners
SuperTrails
TrollGUI
TTA
UltraCosmetics
Vault
viabackwards-all-2.3.1
ViaVersion-1.3.0
worldedit-bukkit
worldguard

### How does this error happen? login? Using an item? 
me: not errror but when i use command /viaver bug  ,if i die and respawn it will say in console "[ViaVersion] OUTGOING: PLAY 15 -> 15 [UNKNOWN[340]] Value: PacketWrapper{packetValues=[]" many times fast it make server lag and it make scoreboard disappears too (im not good about english sorry)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
me: yes it said "[16:30:49] [Netty Server IO #2/INFO]: [ViaVersion] KMOFLOVE OUTGOING: PLAY 15 -> 15 [UNKNOWN[340]] Value: PacketWrapper{packetValues=[], readableObjects=[], id=15}
[16:30:49] [Netty Server IO #2/INFO]: [ViaVersion] KMOFLOVE OUTGOING: PLAY 39 -> 39 [UNKNOWN[340]] Value: PacketWrapper{packetValues=[], readableObjects=[], id=39}
[16:30:49] [Netty Server IO #2/INFO]: [ViaVersion] KMOFLOVE OUTGOING: PLAY 53 -> 54 [UNKNOWN[340]] Value: PacketWrapper{packetValues=[], readableObjects=[], id=54}"  many times in a second

**Comment by MylesIsCool** [comment]
The command "/viaversion debug" turns on debugging, don't turn it on, you don't need it.

The command initially asked for is "/viaversion dump"

Don't translate anything in the quotes above of course.
