### ISSUE TITLE
{Type: VarInt, Source #0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.PlayerPackets$17 (Anonymous), Data: [], Packet ID: 10}

### ISSUE THREAD

**Issue by McModknower** [MylesIsCool/ViaVersion#774]
[output link of /viaversion dump](https://gist.github.com/1a8ac8cfd4da7a76c9cb025bd8e60e30)

Plugins: ( a lot self-coded )
AsyncWorldEditInjector, WorldEdit, CommandBlockerUltimate, Votifier, WorldGuard, ReloadWarning, AntiTNT, AsyncWorldEdit, MaxBans, Team-Chat, McModknowerLib, ChatChanneler, EasyFriede, ViaVersion, Vault, CombatLogX, Lores, CreativeItemControl, Essentials, McModknowerSpielmodusManager, FirstSpawnMessage, PlotSquared, Discord, Multiverse-Core, Holograms, Modul_CMDBlocker, WorldProtect, Shopkeepers, McModTechVote, PermissionsEx, Kein_Fallschaden_Modul, ChatEx, Tablist, Clearlagg, Respawnkit_Modul, ArmorStandTools, Lobby, SkyPvP

Console output that told me to create the issue:
[16:53:12] [Server thread/INFO]: Crazygamer263 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/MylesIsCool/ViaVersion/issues
{Type: VarInt, Source #0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.PlayerPackets$17 (Anonymous), Data: [], Packet ID: 10}

**Comment by MylesIsCool** [comment]
Is there more to this error? If not could you provide more via debug=true in server.properties?

Is there a cause for this error? Does it happen when you equip armour etc with a plugin?

**Comment by McModknower** [comment]
I just saw the line while i looked through the latest.log file and it happend only once.

**Comment by MylesIsCool** [comment]
I can't really help apart from the above, this will be down to plugins.

The most common one is people sending bad armour equip packets.

(Best idea is if you can consistently replicate, remove plugins + test)
