### ISSUE TITLE
Outdated Client connecting to server on Bungeecord. 

### ISSUE THREAD

**Issue by jasoryeh** [MylesIsCool/ViaVersion#779]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/e60983f3a05fb30dcd9aeee7b19fad82

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I have ViaVersion installed on Bungee. These are the plugins:
- BungeePexBridge
- Scrolls(Custom plugin)
- ClientStats
- ViaBackwards
In addition, the server I am trying to connect to has viaversion and backwards installed too but that didn't make a difference.

### How does this error happen? login? Using an item? 
This happens while trying to connect to a 1.11.1 Sportbukkit server with viaversion and backwards for PGM.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
The console shows no error or kick messages.

**Comment by MylesIsCool** [comment]
ViaVersion can't get your LOBBY01 version, I'd suggest manually setting this in the config.yml.

**Comment by jasoryeh** [comment]
I can connect tolobby01 fine.its pgm01 I cant

**Comment by MylesIsCool** [comment]
What plugins do you have installed on PGM01?

**Comment by jasoryeh** [comment]
It's all the plugins required for ProjectAres -
bukkit-settings
Channels
api-bukkit
commons-bukkit
PGM (ProjectAres)

**Comment by jasoryeh** [comment]
Additional testing shows that only 1.11 versions  can connect to the serer

**Comment by MylesIsCool** [comment]
You'll need to manually override the protocol versions in the config as ViaVersion is saying your server is protocol 340 (http://wiki.vg/Protocol_version_numbers) 1.2.2 which it should be 1.11.

**Comment by jasoryeh** [comment]
Still - https://gist.github.com/d12c7dda6d2dc56aa76d105cacb80975
I've set it, tested it, doesn't work.
I remove viaversion from the server - doesn't work.
![image](https://user-images.githubusercontent.com/13290941/33155298-5cb761dc-cfa4-11e7-9097-6928883bf046.png)
I'm connecting from 1.8.8 > 1.11.1- doesn't work
I've had others test 1.12.2 > 1.11.1 - doesn't work
1.11.x > 1.11.1 - works

**Comment by MylesIsCool** [comment]
ViaVersion doesn't support 1.8, 1.9, 1.10 on a 1.11 server. Only newer versions.

**Comment by jasoryeh** [comment]
What about 1.12 > 1.11

**Comment by jasoryeh** [comment]
I uninstalled viaversion from pgm, works better now.
