### ISSUE TITLE
Leggings/boots glitching

### ISSUE THREAD

**Issue by L4BORG** [MylesIsCool/ViaVersion#780]
### What is the output link of /viaversion dump? 
https://gist.github.com/8f3637daaff4ddb166acad537d974ed3

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord with NuVotifier

### How does this error happen? login? Using an item? 
https://www.youtube.com/watch?v=h2E4mKozpQM&feature=youtu.be (I'm not double clicking in video, this has nothing to do with "quick-move-action-fix") also the issue is not present in https://ci.viaversion.com/job/ViaVersion/184/ so I assume commits in #185 in later are causing this...

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No.

**Comment by MylesIsCool** [comment]
So have you tried with 'quick-move-action-fix' disabled?

**Comment by L4BORG** [comment]
I just did and it seems like that would fix the issue, doesn't make much sense tho, are one click gestures quick move actions?

**Comment by MylesIsCool** [comment]
The patch seems to have incompatibilities under certain circumstances, we'll most likely look into this in the future if we have the same.
