### ISSUE TITLE
Ehh...

### ISSUE THREAD

**Issue by rhys-hartman** [MylesIsCool/ViaVersion#782]
https://pastebin.com/K6P202E0

**Comment by ninja-** [comment]
server version, plugins list?

**Comment by rhys-hartman** [comment]
Server version is 1.8 which supports up to 1.12. The problem in-game is that my players are getting booted off for no apparent reason. I believe the kick message is "Lost connection" or something or rather. Anyways I think that error message may be the reason.

Plugins List: http://prntscr.com/hertd4

**Comment by ninja-** [comment]
> 76 plugins
I am pretty sure one of them is messing up the nbt inside this packet

**Comment by rhys-hartman** [comment]
Alright I'm unsure what that is but would that possibly cause the issue my players are facing? Or is it kind of an irrelevant error message?

**Comment by ninja-** [comment]
well I am assuming one of these 76 plugins (things like: npcs, custom mobs, etc...) is sending a packet that is violating the protocol, which causes the error message you see

**Comment by rhys-hartman** [comment]
Alright I'll go contact the developer of the custom plugins, thanks for the help.
