### ISSUE TITLE
1.11.2 Server - 1.12.1 clients can connect, 1.12.2 clients cannot

### ISSUE THREAD

**Issue by PetrichorCraft** [MylesIsCool/ViaVersion#783]
It was recently pointed out to me that clients with version 1.12.2 cannot connect to my server. I checked, and 1.12.1 clients could. My server version is 1.11.2 (Spigot), and my ViaVersion version is 1.2.0. Do I need a different version, or is this a bug?

### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/33046155bcbdc0b6ac2f68986709dd74

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Nothing like BungeeCord, no.

Plugins:
2048, AddLight, AdvancedBan, Autorank, AutoRestart, AutoSell, BankNote, Battleship, ChatLock, ChatQuiz, ChestShop, ClearLag, ColoredTexts, CompatNoCheatPlus, ConnectFour, CookieClicker, CoreProtect, CrateReloaded, CrazyEnchantments, CT-Core, CustomPolls, DiceFurniture, DisableCommandsPlus, EasyElevators, EnjinMinecraftPlugin, Essentials, EssentialsSpawn, ezAuctions, FancyToDo, FrameLibrary, FurnitureLib, GAListener, GameBox, GameModeInventories, GemCrush, GeneralMarket, GriefPrevention, GroupManager, HeavySpleef, Hologramm, Holograms, Jobs, KeepItems, Lottery, MarriageMaster, mcMMO, MinePacks, Minesweeper, MobArena, Multiverse-Core, MyCommands, NoCheatPlus, NoSpawnerChange, Paintball, PermissionSigns, PerWorldPlugins, PlotSquared, PlugMan, ProtectionLib, ProtocolLib, Questioner, ReportManager, ServerSigns, ShopGUIPlus, SignEdit, SilkSpawners, SimpleBroadcast, SimpleChatLog, SlotMachine, SpawnerShop, Statz, Sudoku, SurvivalGames, Towny, TownyChat, TryMe, TuxTwoLib, Vault, ViaBackwards, ViaVersion, Votifier, Voting, WhacAMole, Wild, WorldBorder, WorldEdit, WorldGuard

### How does this error happen? login? Using an item? 
This error happens on login, I guess you'd say.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No errors in console, no kick message.

Thank you for your time in developing this plugin, and for taking a look at this.

**Comment by MylesIsCool** [comment]
Update ViaVersion.

**Comment by PetrichorCraft** [comment]
From my understanding, I had to use the 1.11.2 version for a 1.11.2 server, rather than just the most recent, 1.12. Is this incorrect?

**Comment by Lmmb74** [comment]
@PetrichorCraft Yup, every version works from 1.8 upwards

**Comment by PetrichorCraft** [comment]
Thank you both very much. Sorry about my miss-understanding.
