### ISSUE TITLE
Exception in netty thread

### ISSUE THREAD

**Issue by theTd** [MylesIsCool/ViaVersion#784]
### What is the output link of /viaversion dump? 
https://gist.github.com/5c609899d648abc666d8d87112db5ed0

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yes, we uses BungeeCord, and have some of our custom plugins installed, but none of them deal with protocol. other plugins are ServerListPlus-3.4.5, Yamler-Bungee-2.3.1 and SkinsRestorer-13.0.2

### How does this error happen? login? Using an item? 
When this happens, I get kicked without any useful message. Sometimes I get suddenly kicked on login or sometimes I can log in but get kicked when walk around.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
I made a custom build of spigot to print the stacktrace caught in netty threads, and then caught these exception
https://pastebin.com/Nz8NFn3d

**Comment by MylesIsCool** [comment]
Are you able to copy your server and test without other plugins and just ViaVersion?

**Comment by theTd** [comment]
Looks like the exception was caused by some custom packets, but because of no stacktrace will be shown if exception were thown in netty threads, finding this out took me great effort. I suggest viaversion catch these exceptions.

**Comment by MylesIsCool** [comment]
You can display stack traces using debug=true in server.properties.

I'm going to close this issue otherwise, I'd suggest just ensuring that custom plugins use the same packets for your server version (check against wiki.vg docs)
