### ISSUE TITLE
Actual Error

### ISSUE THREAD

**Issue by RevengeForceBG** [MylesIsCool/ViaVersion#785]
27.11 20:19:02 [Multicraft] Skipped 64 lines due to rate limit (30/s)
27.11 20:19:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
27.11 20:19:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
27.11 20:19:01 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
27.11 20:19:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
27.11 20:19:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
27.11 20:19:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
27.11 20:19:01 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
27.11 20:19:01 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
27.11 20:19:01 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:494)
27.11 20:19:01 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:236)
27.11 20:19:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
27.11 20:19:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
27.11 20:19:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
27.11 20:19:01 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
27.11 20:19:01 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
27.11 20:19:01 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
27.11 20:19:01 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
27.11 20:19:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
27.11 20:19:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
27.11 20:19:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
27.11 20:19:01 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
27.11 20:19:01 [Server] INFO Actual Error: 
27.11 20:19:01 [Server] INFO {Type: String, Source #0: us.myles.ViaVersion.protocols.base.BaseProtocol$3 (Anonymous), Data: [Pair{Type|VarInt, 10}], Packet ID: 0}
27.11 20:19:01 [Server] INFO io.netty.handler.codec.DecoderException: us.myles.ViaVersion.exception.InformativeException:

**Comment by MylesIsCool** [comment]
This is a client sending bad info you can ignore this, in the future fill out the issue template fully.
