### ISSUE TITLE
Tab Autocomplete not working properly

### ISSUE THREAD

**Issue by braingame49** [MylesIsCool/ViaVersion#786]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/4065fa33dc1e110fe88f29687d05bb73

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
nope, only paperspigot

### How does this error happen? login? Using an item? 
when pressing tab

### Is there an error in the console? Use pastebin.com. Is there a kick message?
nope

When pressing tab it doesn't auto-compete the command, instead it shows all commands, something I don't want, it didnt happen before viaversion

**Comment by MylesIsCool** [comment]
ViaVersion does nothing to tamper with tab complete, this will be down to your server software. (And i'm sure if you remove ViaVersion you'll find it still happens)

**Comment by braingame49** [comment]
Just noticed only happends in 1.12 not in 1.11.2
