### ISSUE TITLE
tab auto-complete doesn't work in 1.12.2

### ISSUE THREAD

**Issue by braingame49** [MylesIsCool/ViaVersion#787]
### What is the output link of /viaversion dump? 

https://gist.github.com/24ba5d4c4a857d0d383c0e299d71f86e
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Only Paperspigot, occurs on spigot as well

### How does this error happen? login? Using an item? 

pressing tab
### Is there an error in the console? Use pastebin.com. Is there a kick message?
no

When I press tab in 1.12.2 it shows all the commands instead of finishing it, also doesn't finish playernames. This also occurs when using spigot and viaversion together.

**Comment by MylesIsCool** [comment]
Remove all your plugins and test if the issue still happens, by default tab won't complete if there's too many options.

**Comment by braingame49** [comment]
also happens on my local dev server with far less plugins

**Comment by MylesIsCool** [comment]
Can you try with no plugins and see if it happens? How does the behaviour compare to 1.11.2?

**Comment by braingame49** [comment]
Testing without plugins (only yours) right now.
It doesn't happen in 1.11.2
