### ISSUE TITLE
Players can still walk normally while blocking (1.9+ on 1.8 servers)

### ISSUE THREAD

**Issue by Esmorall** [MylesIsCool/ViaVersion#789]
Sorry for bad english

### What is the output link of /viaversion dump? 
https://gist.github.com/6e9d5d354f9bda3d73ee79be70aaeee4

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord, lastest version (Waterfall)

### How does this error happen? login? Using an item? 
when a player is playing on a 1.8 server using 1.9+ versions, it is supposed to walk slowly while blocking with the sword, but instead of that the player still can walk normally and get kicked by the anticheat

### Is there an error in the console? Use pastebin.com. Is there a kick message?
nope

**Comment by MylesIsCool** [comment]
Blocking isn't fully supported at a Bungee level. You'd have to downgrade to the Bukkit version to fix this.

This is something we don't plan to add (because we'd have to track inventory items etc).

**Comment by Esmorall** [comment]
i also tried using viaversion on spigot, but still happens

**Comment by MylesIsCool** [comment]
Did you also remove it from Bungee?

**Comment by Esmorall** [comment]
No i didn´t, should it has to be removed from bungee? i would try it at night

**Comment by MylesIsCool** [comment]
It's much less complicated if you do, but essentially Bungee will handle the protocol if it's installed on both.
