### ISSUE TITLE
fix this error

### ISSUE THREAD

**Issue by josecuervo2016** [MylesIsCool/ViaVersion#790]
### What is the output link of /viaversion dump? 

viaversion 1.3.0
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

I'm using waterfall version 158
### How does this error happen? login? Using an item? 
the error is random when they log in to the server or in other circumstances

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/wxaK2WKF

**Comment by MylesIsCool** [comment]
This is down to clients sending bad info.

**Comment by josecuervo2016** [comment]
I do not understand . and how do I solve it?

**Comment by MylesIsCool** [comment]
It is not solvable, it will be a server list website sending bad data etc.
