### ISSUE TITLE
InformativeException on login

### ISSUE THREAD

**Issue by TimvanDijkhuizen** [MylesIsCool/ViaVersion#791]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/5b3c5fe5e52d7e592a0435c525653b69

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yes, we use bungeecord. The public plugins we use are: ClientStats, MemoryPeek and RedisBungee. All the others are custom plugins.

### How does this error happen? login? Using an item? 
Login

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/ed8ZVvXw
(It didn't print any errors after "Actual error:")

**Comment by MylesIsCool** [comment]
Can you enable debug=true in server.properties and then replicate the error? (It will provide the actual error)

**Comment by MylesIsCool** [comment]
See above then we can help.
