### ISSUE TITLE
An error occurred with entity meta data for ENTITY OldID: 8

### ISSUE THREAD

**Issue by MegaDonater1** [MylesIsCool/ViaVersion#792]
Hello, I use the BigBedWars plugin with BossBarApi and an error is displayed in the console of the server itself: https://pastebin.com/3FQr8x3n
In this case, after 5-10 minutes of the game all players from 1.12.2 version are thrown from the server. How can I fix this?
Using bungeecord 1.8-1.12.2, spigot 1.8.

**Comment by MylesIsCool** [comment]
The plugin author / bossbar api provider would need to fix this. Unfortunately this isn't something we can fix as the plugin is sending bad data that can't be translated.
