### ISSUE TITLE
ScoreboardPacket 1.8 to newer does not work

### ISSUE THREAD

**Issue by MrCreeperkopf** [MylesIsCool/ViaVersion#793]
### What is the output link of /viaversion dump? 
https://gist.github.com/0cd6964dee435c52f9a912f94c7173a4

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Yes. Latest BungeeCord 1.12.
Running paperspigot 1.8.8 with ViaVersion, ProtocolLib, AAC, PacketWrapper (for ProtocolLib), and an custom scoreboard API which tries to send a 1.8 ScoreboardTeam packet to 1.8 - 1.12 clients.

### How does this error happen? login? Using an item? 

Sending scoreboard team packet

### Is there an error in the console? Use pastebin.com. Is there a kick message?

https://pastebin.com/fzRP7u1J

**Comment by MylesIsCool** [comment]
This looks like it's sending bad packets, send packets appropriate for the server version.

**Comment by MrCreeperkopf** [comment]
I've checked the compatibility. There is no problem when sending it without ViaVersion installed.

**Comment by MylesIsCool** [comment]
ViaVersion translates the vanilla packet correctly so you're doing something that is sending the wrong data.

Either:

- You're sending bad data (the vanilla client may ignore bad data if it's at the end in certain cases)

- You're sending the packet into the netty pipeline at the incorrect point.

**Comment by MrCreeperkopf** [comment]
I don't know what the problem was but it works now...
