### ISSUE TITLE
Hand Bug

### ISSUE THREAD

**Issue by zBoringDrop** [MylesIsCool/ViaVersion#795]
Sorry for my bad english.
I use the 1.3.0 viaversion version installed only in bungeecord.
The problem is when i switch from a 1.8 server to a 1.9x server that happen the hand bug. I already tested with 0 plugin and from 0 config, but none, the bug on bungee stills why not if i use viaversion on each server.
Why?

**Comment by MylesIsCool** [comment]
We can't replicate this with the scenario you've provided, please fill in the issue template fully if you want help otherwise we can't.
