### ISSUE TITLE
Error in BungeeCord

### ISSUE THREAD

**Issue by Azroohs** [MylesIsCool/ViaVersion#796]
### What is the output link of /viaversion dump? 
https://gist.github.com/99190f4c388e9b86cb2fc9d3fbf6ebaf

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Using BungeeCord, plugins is in the dump

### How does this error happen? login? Using an item? 
Appeared accidentally in the bungeecord log

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/raw/zArSCkCH

**Comment by MylesIsCool** [comment]
This error is due to a bad client connecting usually a server list, you can just ignore it. (or IP ban etc)
