### ISSUE TITLE
Startup error "Loading block mapping..."

### ISSUE THREAD

**Issue by SayNada** [MylesIsCool/ViaVersion#797]
### What is the output link of /viaversion dump? 
https://gist.github.com/3c7f0e9c2ade4f15a146d20db10613d0

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
PaperSpigot

### How does this error happen? login? Using an item? 
Startup

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/Hj7fHwqN

**Comment by Gerrygames** [comment]
This is not an error. It is just a debug for missing mappings in the snapshot. If you do not want to see these debugs do not use the development build. The development build is currently pretty much the same as the latest release except for the support for the Minecraft 1.13 snapshot.

**Comment by Matsv** [comment]
We need the debug messages at the moment. Will be gone at stable builds. (:
