### ISSUE TITLE
ProtocolLib?

### ISSUE THREAD

**Issue by danjb2000** [MylesIsCool/ViaVersion#8]
The plugin doesn't work with ProtocolLib which is all very well on a test server.
But it can't be deployed onto our actual servers.

Any fix?

**Comment by ajthemacboy** [comment]
No fix yet I don't think, but I'm sure he will support ProtocolLib soon.

**Comment by MylesIsCool** [comment]
It's currently being worked on, just about getting pipes in the right order.

**Comment by Paulomart** [comment]
@MylesIsCool I want to contribute to your awesome project. Who far are you with this and are you needing any help?

**Comment by HugoDaBosss** [comment]
You can just submit pull requests, Myles will merge them.

**Comment by Paulomart** [comment]
Yeah but if the already started working at it this will be unlikely and just not need work

**Comment by Paulomart** [comment]
Got it working! 
![2016-03-01_19 46 26](https://cloud.githubusercontent.com/assets/4148404/13437789/4fd8492c-dfe6-11e5-83bb-b401e2107925.png)

**Comment by MylesIsCool** [comment]
I have ViaVersion working with ProtocolLib if you just make it load before ProtocolLib but it's actually being compatible which I've seen unless you have otherwise a patch to insert it into the decoder or on similar lines? Do you have IRC?

**Comment by Paulomart** [comment]
Yeah using onLoad, which irc are you on?

**Comment by MylesIsCool** [comment]
Supported in version 0.4.0
