### ISSUE TITLE
Unable to throw and use enderpearls

### ISSUE THREAD

**Issue by HugoDaBosss** [MylesIsCool/ViaVersion#80]
Version: 0.4.5

Spigot version: git-Spigot-e4d4710-e1ebe52

Plugins: ViaVersion

Happens when: Right clicking with an enderpearl

Results: Nothing at all

**Comment by StamBoom** [comment]
Works in survival/adventure not in creative

**Comment by MylesIsCool** [comment]
Enderpearls has never worked in creative. ;)

**Comment by MylesIsCool** [comment]
Closed enderpearls work as properly
