### ISSUE TITLE
quick-move-action-fix causes OutOfBounds error

### ISSUE THREAD

**Issue by JavituRec** [MylesIsCool/ViaVersion#800]
### What is the output link of /viaversion dump? 
My server restart each day and today I can't access because I am traveling.

### Is there an error in the console?
https://hastebin.com/ocizekeluv.css

**Comment by mmxw11** [comment]
Set 'quick-move-action-fix' to false in the config.
Will take a look into this and #780 when i have the time.

**Comment by mmxw11** [comment]
Patch coming soon. 
The problem was only happening with brewing stands. 1.9 added a new slot (the blaze powder one). 
So on 1.8 servers the client always sent one slot index ahead which resulted to a wrong index.
