### ISSUE TITLE
Exception: Team viaversion already exists in this scoreboard

### ISSUE THREAD

**Issue by Brokkonaut** [MylesIsCool/ViaVersion#803]
Sometimes players get kicked from the server by the proxy. the message is "Team viaversion already exists in this scoreboard" - this only happens when they get assigned to an existing scoreboard on the server. I don't create any "viaversion"-teams in any of my plugin so only this plugin might do it.

### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/506bc8f208fe8720033b23e0d2697c46
ViaVersion build 190

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yes, Bungeecord

### How does this error happen? login? Using an item? 
Sometimes when they get assigned a scoreboard by a server plugin (not every time, only about every 50th player)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/raw/q1mdZAAd (log in the proxy)

**Comment by MylesIsCool** [comment]
Disable viaversion autoteam (in config or by command), it's down to team collision when switching servers due to Bungee.
