### ISSUE TITLE
Unable to use 1.12 items on 1.9 servers

### ISSUE THREAD

**Issue by DCxiaolong** [MylesIsCool/ViaVersion#804]
Unable to use 1.12 items on 1.9 servers

**Comment by x9nico** [comment]
It's logic, if we can do that, 1.11 and old versions will crash

**Comment by Logics4** [comment]
If your server version doesn't have the blocks you want to use then of course you cannot use this. This is not an issue.

**Comment by Matsv** [comment]
This is intended behavior.
