### ISSUE TITLE
Bug with cheat items.

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#809]
Hey,

When my players do /kit 2Years, they have an overcheat stuff, with P40, Sharpness 40, etc.
But they are always kicked : they can't connect to the server. After the restart same problem : disconnect again. My player tested the bug in 1.9 and 1.10. If I delete ViaVersion and ViaBackwards, he can connect without problems.

I'm using Java 8, Paper Spigot 1.12.2.
Bug tested with the plugins : ViaBackwards and ViaVersion only.

The kit was generated by Essentials.

Thanks.

**Comment by MylesIsCool** [comment]
This error is not related to ViaVersion itself, open it on the ViaBackwards GitHub and provide full details.
