### ISSUE TITLE
Double place sound with glass

### ISSUE THREAD

**Issue by HugoDaBosss** [MylesIsCool/ViaVersion#81]
### What version of ViaVersion are you using? Type /ver viaversion
0.4.5
### What version of Spigot are you using? Type /ver
git-Spigot-e4d4710-e1ebe52
### What plugins are you using? /plugins
ViaVersion
### How does this error happen? login? using an item? 
Place a glass block
### Is there an error in the console? Use pastebin.com. Is there a kick message?
No errors

**Comment by ridalarry** [comment]
I have found that this is happening with most if not all of the blcoks not only glass

**Comment by HugoDaBosss** [comment]
I fixed the other blocks already, but it isn't yet pushed to a public release.
https://github.com/MylesIsCool/ViaVersion/commit/8f132fed1478d1c823dd588be7bec750ef4edd69

**Comment by ridalarry** [comment]
oh

**Comment by MylesIsCool** [comment]
Closed fixed
