### ISSUE TITLE
Players cannot edit their inventories

### ISSUE THREAD

**Issue by fastfree** [MylesIsCool/ViaVersion#810]
### What is the output link of /viaversion dump? 
https://gist.github.com/anonymous/7d13b3e367df7548ed3c45f2c50e90b9

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
 Plugins (39): icJukeBox, CoreProtect, AsyncWorldEditInjector, TopLite, WorldEdit, ClearLag, RSCommandSigns, TeleportationTools, Chairs, EasySetSpawn, Broadcaster, OpenTerrainGenerator, MultiWorld, AsyncWorldEdit, iDisguise, Reloader, ProVanish, PermissionsEx, NoteBlockAPI, MapLoader, ChatWithStaff, ViaVersion, GUIBanner, Tablist, Vault, ViaBackwards, GriefPrevention, ViaRewind, Essentials, Autorank, ProtocolLib, NoCheatPlus, SEARCH, TrollCommandsPlusPlus, PAC, ChatEx, ServerListPlus, AuthMe, HolographicDisplays

All are up to date.

### How does this error happen? login? Using an item? 
when on 1.12.2 my players can open their inventories but they cannot move objects in them in any way, in 1.11.2 it works just fine, and in older versions works too.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
there's only an error from my anticheat: PAC: user failed Inventory check [VL: 1] [Ping: 49] [Info: missing packet]

**Comment by fastfree** [comment]
oh also every plugin is up-to-date. i checked myself

**Comment by MylesIsCool** [comment]
This is not an issue with ViaVersion, test without your anticheat.

ViaVersion only modifies versions that aren't your server version, since the issue happens on 1.12.2 this means it's down to another plugin (most likely PAC given the error).

**Comment by fastfree** [comment]
it's not the anticheat, i tested it without.

**Comment by MylesIsCool** [comment]
I'd suggest removing plugins and testing to locate the cause.

**Comment by fastfree** [comment]
oh it was actually pac AND search. 2 anticheats out of 3 don't work with viaversion. pac was saying missing packet, couldn't you fix it by emulating the missing packet somehow?

**Comment by MylesIsCool** [comment]
ViaVersion doesn't change anything on the version your on.

The older versions you have on your server are provided by ViaBackwards / ViaRewind so if there is a problem with a specific version you should post it on the respective github. (ViaVersion only provides new versions, eg. 1.12 on 1.11 server)
