### ISSUE TITLE
Console spammed to death with errors

### ISSUE THREAD

**Issue by sannielollie** [MylesIsCool/ViaVersion#811]
### What is the output link of /viaversion dump? 

https://gist.github.com/anonymous/31e8319c4acf15796f374630b4490440

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Bungeecord
spigot-1.12.2-R0.1-SNAPSHOT-b1610
Plugins (86): GroupManager, PlayTimeRewardsRecoded, PlugMan, Winter, EntityDetection, Minator, InfinityDispensers, CustomPolls, Emoti, RecipeBookDupePatch, Sudo, DeathMessages, NoteBlockAPI, SantaClaus, ViaVersion, ChatColor, ViaBackwards, CoreProtect, dynmap, WorldEdit, Essentials, ClearLag, ChatControl, AdvancedBan, Elevator, AutoCrafters, Votifier, Multiverse-Core, ProtocolLib, NightVision, MVdWPlaceholderAPI, VotingPlugin, SimpleBossBar, EssentialsChat, mcMMO, ElytraPlus, GAListener, Vault, SimpleSit, MassiveCore, EnjinMinecraftPlugin, Superpickaxe, Dynmap-Essentials, MobArena, Trading, LWC, HolographicDisplays, TrailGUI, PlayerPoints, XRayHunter, WorldGuard, AAC, Factions, TransportPipes, UltraBar, AddLight, EssentialsSpawn, CratesPlus, WorldGuardExtraFlags, HolographicScoreboard, CorpseReborn, RedstoneCommand, HeadsPlugin, AnimatedNames, GadgetsMenu, HeadDatabase, Banknotes, SilkSpawners, Citizens, FactionsDynmap, ChopTree3, ConditionalCommands, NoteBlockMusicPlayer, GriefPrevention, MiniaturePets, HeadsInventory, BossShopPro, ProtectionLib, PremiumVanish, FurnitureLib, BungeeTabListPlus, DiceFurniture, PluginLibrary, Statz, Autorank, React

### How does this error happen? login? Using an item? 

All the time when people are online

### Is there an error in the console? Use pastebin.com. Is there a kick message?

https://pastebin.com/2hBxyizq
No kick message
Logfile at the end of the day is 2 gigabytes big - disabled logging for now.

**Comment by MylesIsCool** [comment]
You're using a bad plugin that doesn't inject properly into packets. Best idea is to remove half your plugins, see if it's still there and retry. There's nothing we can do to fix this and it's down to another plugin badly handling packet exceptions which are canceled.
