### ISSUE TITLE
User timed out

### ISSUE THREAD

**Issue by DadoGameTester** [MylesIsCool/ViaVersion#818]
### What is the output link of /viaversion dump? 
I use the last version of ViaVersion (ViaVersion 1.3.0).

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I don't have additional plugins, i'm using spigot 1.12.2.

### How does this error happen? login? Using an item? 
When i enter in the server, he kick me out.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

https://pastebin.com/hSTCcTh3. Yes, is an error in the console. Is a kick message.

**Comment by MylesIsCool** [comment]
As user said 1.7.10, requested to move issue to
https://github.com/Gerrygames/ViaRewind
