### ISSUE TITLE
how fix this

### ISSUE THREAD

**Issue by josecuervo2019** [MylesIsCool/ViaVersion#821]
### What is the output link of /viaversion dump? 
ViaVersion 1.3.0

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
skinrestore, abps, antibotdeluxe, blockservercmd, bungeechatfilter, bungeemotd, bungeeservermanager, configbungeereload, justonemorebungee, litebans, lobbysimplebalance, report, ultimatefriend

### How does this error happen? login? Using an item? 

the error is random. the players are fine and suddenly, kick them all out of the server, the autoteam is already in false,

### Is there an error in the console? Use pastebin.com. Is there a kick message?

https://pastebin.com/SpBfH7jd

**Comment by Matsv** [comment]
Not related to ViaVersion, we never create that team. Try to debug your other plugins until it no longer happens.
