### ISSUE TITLE
Dragon head > skeleton head when no permission to break

### ISSUE THREAD

**Issue by CryLegende** [MylesIsCool/ViaVersion#824]
Version: Waterfall (latest build) **|** PaperSpigot 1.8.8 latest **|** Viaversion 1.3.0

When a player break a dragon skull but no has permission to break in region (protected by ASkyBlock), it happens that the dragon's head turns into a skeleton head.

**Comment by MylesIsCool** [comment]
ViaVersion does not support new blocks, DragonHeads are not present in 1.8.8.
