### ISSUE TITLE
Server-Error-Crash

### ISSUE THREAD

**Issue by Nikita12345222** [MylesIsCool/ViaVersion#828]
[23:07:03] [Server thread/INFO]: butzeck lost connection: Internal Exception: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to http://github.com/MylesIsCool/ViaVersion/issues
{Type: String, Source #1: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.PlayerPackets$8 (Anonymous), Source #0: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.PlayerPackets$8$1 (Anonymous), Data: [Pair{Type|VarInt, 0}, Pair{Type|VarInt, 1}, Pair{Type|UUID, bc6f5d5c-81c6-4ddb-b150-86f4a83a893c}, Pair{Type|String, Leaiana1}, Pair{Type|VarInt, 9}, Pair{Type|String, textures}, Pair{Type|String, eyJ0aW1lc3RhbXAiOjE1MjU0NjQ4MDkyNDEsInByb2ZpbGVJZCI6ImJjNmY1ZDVjODFjNjRkZGJiMTUwODZmNGE4M2E4OTNjIiwicHJvZmlsZU5hbWUiOiJMZWFpYW5hMSIsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83YjJlYzI4YTQwODI2OWE0Y2NiYzgzYWNlMGY2ZmI3MDJiOGU5N2QyYTQ0OTY4N2E5ZTFlMTg4M2YxMGFlZjYiLCJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifX19fQ==}, Pair{Type|Boolean, true}, Pair{Type|String, IeRy6A53TTD6kdqG/0ijzCAobTgaWzDP4hITgszvM6slLEYiukAIdLfwCudoRmjmwdgEbud+GyRIV7i3ADZNQRCsI27Q2PniaD51phttDYq0U6TbUCGR1rRX9lEdLzf4KvyVg37xrHlHcGYJwmbFMgafiVwBybV65Ox0yxwsTy9/u97+F8hiSNS5ZyOKLFTbEssS+scxFZu65rsuY7KQPAwbBwXF4PjzPJbQDu09LrplzAI7QqWtawsDc3+7+leC4FgraqA8CBTDmT2V/ewMraroWszZ8LxXA3mn6UDkdXIQKUHEkX/ERYmTu5ASC0ajRO6mtu47UgTdfG3Wh1k+T9PObcmab4myDpyKu2qcivpaBdi/u6zBmrtBtvwiTDvQJVNiTzPZc6lkkmJEWn/8Fw5MflFrCongZh9qcGf76cldIMwg/OpsAkiX04HT1iFlzKNNROlga0F9z8RKd2hzd0vbPWPqOZxrHGQ8JQKGkxbqmYAK6J4GYnz06+rlurUXvGyQneKQFGoipsda6qQHnS3poDnC1IZF26iQP0OInF3n9RdEzU9ysX0MYOmKu748OuDtGhY1DTtXPX60Jgr7xnMCvi9ddaMZjtDGIQx++vef1yDnz4J4DZg+rjtTVtVl9uB2CNzkM1TJBnJ3Kmujr5VI5XYbUv2iJokRy9koLtE=}, Pair{Type|String, textures}, Pair{Type|String, eyJ0aW1lc3RhbXAiOjE1MjU0NjQ4MDkyNDEsInByb2ZpbGVJZCI6ImJjNmY1ZDVjODFjNjRkZGJiMTUwODZmNGE4M2E4OTNjIiwicHJvZmlsZU5hbWUiOiJMZWFpYW5hMSIsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83YjJlYzI4YTQwODI2OWE0Y2NiYzgzYWNlMGY2ZmI3MDJiOGU5N2QyYTQ0OTY4N2E5ZTFlMTg4M2YxMGFlZjYiLCJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifX19fQ==}, Pair{Type|Boolean, true}, Pair{Type|String, IeRy6A53TTD6kdqG/0ijzCAobTgaWzDP4hITgszvM6slLEYiukAIdLfwCudoRmjmwdgEbud+GyRIV7i3ADZNQRCsI27Q2PniaD51phttDYq0U6TbUCGR1rRX9lEdLzf4KvyVg37xrHlHcGYJwmbFMgafiVwBybV65Ox0yxwsTy9/u97+F8hiSNS5ZyOKLFTbEssS+scxFZu65rsuY7KQPAwbBwXF4PjzPJbQDu09LrplzAI7QqWtawsDc3+7+leC4FgraqA8CBTDmT2V/ewMraroWszZ8LxXA3mn6UDkdXIQKUHEkX/ERYmTu5ASC0ajRO6mtu47UgTdfG3Wh1k+T9PObcmab4myDpyKu2qcivpaBdi/u6zBmrtBtvwiTDvQJVNiTzPZc6lkkmJEWn/8Fw5MflFrCongZh9qcGf76cldIMwg/OpsAkiX04HT1iFlzKNNROlga0F9z8RKd2hzd0vbPWPqOZxrHGQ8JQKGkxbqmYAK6J4GYnz06+rlurUXvGyQneKQFGoipsda6qQHnS3poDnC1IZF26iQP0OInF3n9RdEzU9ysX0MYOmKu748OuDtGhY1DTtXPX60Jgr7xnMCvi9ddaMZjtDGIQx++vef1yDnz4J4DZg+rjtTVtVl9uB2CNzkM1TJBnJ3Kmujr5VI5XYbUv2iJokRy9koLtE=}, Pair{Type|String, textures}, Pair{Type|String, eyJ0aW1lc3RhbXAiOjE1MjU0NjQ4MDkyNDEsInByb2ZpbGVJZCI6ImJjNmY1ZDVjODFjNjRkZGJiMTUwODZmNGE4M2E4OTNjIiwicHJvZmlsZU5hbWUiOiJMZWFpYW5hMSIsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83YjJlYzI4YTQwODI2OWE0Y2NiYzgzYWNlMGY2ZmI3MDJiOGU5N2QyYTQ0OTY4N2E5ZTFlMTg4M2YxMGFlZjYiLCJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifX19fQ==}, Pair{Type|Boolean, true}, Pair{Type|String, IeRy6A53TTD6kdqG/0ijzCAobTgaWzDP4hITgszvM6slLEYiukAIdLfwCudoRmjmwdgEbud+GyRIV7i3ADZNQRCsI27Q2PniaD51phttDYq0U6TbUCGR1rRX9lEdLzf4KvyVg37xrHlHcGYJwmbFMgafiVwBybV65Ox0yxwsTy9/u97+F8hiSNS5ZyOKLFTbEssS+scxFZu65rsuY7KQPAwbBwXF4PjzPJbQDu09LrplzAI7QqWtawsDc3+7+leC4FgraqA8CBTDmT2V/ewMraroWszZ8LxXA3mn6UDkdXIQKUHEkX/ERYmTu5ASC0ajRO6mtu47UgTdfG3Wh1k+T9PObcmab4myDpyKu2qcivpaBdi/u6zBmrtBtvwiTDvQJVNiTzPZc6lkkmJEWn/8Fw5MflFrCongZh9qcGf76cldIMwg/OpsAkiX04HT1iFlzKNNROlga0F9z8RKd2hzd0vbPWPqOZxrHGQ8JQKGkxbqmYAK6J4GYnz06+rlurUXvGyQneKQFGoipsda6qQHnS3poDnC1IZF26iQP0OInF3n9RdEzU9ysX0MYOmKu748OuDtGhY1DTtXPX60Jgr7xnMCvi9ddaMZjtDGIQx++vef1yDnz4J4DZg+rjtTVtVl9uB2CNzkM1TJBnJ3Kmujr5VI5XYbUv2iJokRy9koLtE=}, Pair{Type|String, textures}, Pair{Type|String, eyJ0aW1lc3RhbXAiOjE1MjU0NjQ4MDkyNDEsInByb2ZpbGVJZCI6ImJjNmY1ZDVjODFjNjRkZGJiMTUwODZmNGE4M2E4OTNjIiwicHJvZmlsZU5hbWUiOiJMZWFpYW5hMSIsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83YjJlYzI4YTQwODI2OWE0Y2NiYzgzYWNlMGY2ZmI3MDJiOGU5N2QyYTQ0OTY4N2E5ZTFlMTg4M2YxMGFlZjYiLCJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifX19fQ==}, Pair{Type|Boolean, true}, Pair{Type|String, IeRy6A53TTD6kdqG/0ijzCAobTgaWzDP4hITgszvM6slLEYiukAIdLfwCudoRmjmwdgEbud+GyRIV7i3ADZNQRCsI27Q2PniaD51phttDYq0U6TbUCGR1rRX9lEdLzf4KvyVg37xrHlHcGYJwmbFMgafiVwBybV65Ox0yxwsTy9/u97+F8hiSNS5ZyOKLFTbEssS+scxFZu65rsuY7KQPAwbBwXF4PjzPJbQDu09LrplzAI7QqWtawsDc3+7+leC4FgraqA8CBTDmT2V/ewMraroWszZ8LxXA3mn6UDkdXIQKUHEkX/ERYmTu5ASC0ajRO6mtu47UgTdfG3Wh1k+T9PObcmab4myDpyKu2qcivpaBdi/u6zBmrtBtvwiTDvQJVNiTzPZc6lkkmJEWn/8Fw5MflFrCongZh9qcGf76cldIMwg/OpsAkiX04HT1iFlzKNNROlga0F9z8RKd2hzd0vbPWPqOZxrHGQ8JQKGkxbqmYAK6J4GYnz06+rlurUXvGyQneKQFGoipsda6qQHnS3poDnC1IZF26iQP0OInF3n9RdEzU9ysX0MYOmKu748OuDtGhY1DTtXPX60Jgr7xnMCvi9ddaMZjtDGIQx++vef1yDnz4J4DZg+rjtTVtVl9uB2CNzkM1TJBnJ3Kmujr5VI5XYbUv2iJokRy9koLtE=}, Pair{Type|String, textures}, Pair{Type|String, eyJ0aW1lc3RhbXAiOjE1MjU0NjQ4MDkyNDEsInByb2ZpbGVJZCI6ImJjNmY1ZDVjODFjNjRkZGJiMTUwODZmNGE4M2E4OTNjIiwicHJvZmlsZU5hbWUiOiJMZWFpYW5hMSIsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83YjJlYzI4YTQwODI2OWE0Y2NiYzgzYWNlMGY2ZmI3MDJiOGU5N2QyYTQ0OTY4N2E5ZTFlMTg4M2YxMGFlZjYiLCJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifX19fQ==}, Pair{Type|Boolean, true}, Pair{Type|String, IeRy6A53TTD6kdqG/0ijzCAobTgaWzDP4hITgszvM6slLEYiukAIdLfwCudoRmjmwdgEbud+GyRIV7i3ADZNQRCsI27Q2PniaD51phttDYq0U6TbUCGR1rRX9lEdLzf4KvyVg37xrHlHcGYJwmbFMgafiVwBybV65Ox0yxwsTy9/u97+F8hiSNS5ZyOKLFTbEssS+scxFZu65rsuY7KQPAwbBwXF4PjzPJbQDu09LrplzAI7QqWtawsDc3+7+leC4FgraqA8CBTDmT2V/ewMraroWszZ8LxXA3mn6UDkdXIQKUHEkX/ERYmTu5ASC0ajRO6mtu47UgTdfG3Wh1k+T9PObcmab4myDpyKu2qcivpaBdi/u6zBmrtBtvwiTDvQJVNiTzPZc6lkkmJEWn/8Fw5MflFrCongZh9qcGf76cldIMwg/OpsAkiX04HT1iFlzKNNROlga0F9z8RKd2hzd0vbPWPqOZxrHGQ8JQKGkxbqmYAK6J4GYnz06+rlurUXvGyQneKQFGoipsda6qQHnS3poDnC1IZF26iQP0OInF3n9RdEzU9ysX0MYOmKu748OuDtGhY1DTtXPX60Jgr7xnMCvi9ddaMZjtDGIQx++vef1yDnz4J4DZg+rjtTVtVl9uB2CNzkM1TJBnJ3Kmujr5VI5XYbUv2iJokRy9koLtE=}, Pair{Type|String, textures}, Pair{Type|String, eyJ0aW1lc3RhbXAiOjE1MjU0NjQ4MDkyNDEsInByb2ZpbGVJZCI6ImJjNmY1ZDVjODFjNjRkZGJiMTUwODZmNGE4M2E4OTNjIiwicHJvZmlsZU5hbWUiOiJMZWFpYW5hMSIsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83YjJlYzI4YTQwODI2OWE0Y2NiYzgzYWNlMGY2ZmI3MDJiOGU5N2QyYTQ0OTY4N2E5ZTFlMTg4M2YxMGFlZjYiLCJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifX19fQ==}, Pair{Type|Boolean, true}, Pair{Type|String, IeRy6A53TTD6kdqG/0ijzCAobTgaWzDP4hITgszvM6slLEYiukAIdLfwCudoRmjmwdgEbud+GyRIV7i3ADZNQRCsI27Q2PniaD51phttDYq0U6TbUCGR1rRX9lEdLzf4KvyVg37xrHlHcGYJwmbFMgafiVwBybV65Ox0yxwsTy9/u97+F8hiSNS5ZyOKLFTbEssS+scxFZu65rsuY7KQPAwbBwXF4PjzPJbQDu09LrplzAI7QqWtawsDc3+7+leC4FgraqA8CBTDmT2V/ewMraroWszZ8LxXA3mn6UDkdXIQKUHEkX/ERYmTu5ASC0ajRO6mtu47UgTdfG3Wh1k+T9PObcmab4myDpyKu2qcivpaBdi/u6zBmrtBtvwiTDvQJVNiTzPZc6lkkmJEWn/8Fw5MflFrCongZh9qcGf76cldIMwg/OpsAkiX04HT1iFlzKNNROlga0F9z8RKd2hzd0vbPWPqOZxrHGQ8JQKGkxbqmYAK6J4GYnz06+rlurUXvGyQneKQFGoipsda6qQHnS3poDnC1IZF26iQP0OInF3n9RdEzU9ysX0MYOmKu748OuDtGhY1DTtXPX60Jgr7xnMCvi9ddaMZjtDGIQx++vef1yDnz4J4DZg+rjtTVtVl9uB2CNzkM1TJBnJ3Kmujr5VI5XYbUv2iJokRy9koLtE=}, Pair{Type|String, textures}, Pair{Type|String, eyJ0aW1lc3RhbXAiOjE1MjU0NjQ4MDkyNDEsInByb2ZpbGVJZCI6ImJjNmY1ZDVjODFjNjRkZGJiMTUwODZmNGE4M2E4OTNjIiwicHJvZmlsZU5hbWUiOiJMZWFpYW5hMSIsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83YjJlYzI4YTQwODI2OWE0Y2NiYzgzYWNlMGY2ZmI3MDJiOGU5N2QyYTQ0OTY4N2E5ZTFlMTg4M2YxMGFlZjYiLCJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifX19fQ==}, Pair{Type|Boolean, true}, Pair{Type|String, IeRy6A53TTD6kdqG/0ijzCAobTgaWzDP4hITgszvM6slLEYiukAIdLfwCudoRmjmwdgEbud+GyRIV7i3ADZNQRCsI27Q2PniaD51phttDYq0U6TbUCGR1rRX9lEdLzf4KvyVg37xrHlHcGYJwmbFMgafiVwBybV65Ox0yxwsTy9/u97+F8hiSNS5ZyOKLFTbEssS+scxFZu65rsuY7KQPAwbBwXF4PjzPJbQDu09LrplzAI7QqWtawsDc3+7+leC4FgraqA8CBTDmT2V/ewMraroWszZ8LxXA3mn6UDkdXIQKUHEkX/ERYmTu5ASC0ajRO6mtu47UgTdfG3Wh1k+T9PObcmab4myDpyKu2qcivpaBdi/u6zBmrtBtvwiTDvQJVNiTzPZc6lkkmJEWn/8Fw5MflFrCongZh9qcGf76cldIMwg/OpsAkiX04HT1iFlzKNNROlga0F9z8RKd2hzd0vbPWPqOZxrHGQ8JQKGkxbqmYAK6J4GYnz06+rlurUXvGyQneKQFGoipsda6qQHnS3poDnC1IZF26iQP0OInF3n9RdEzU9ysX0MYOmKu748OuDtGhY1DTtXPX60Jgr7xnMCvi9ddaMZjtDGIQx++vef1yDnz4J4DZg+rjtTVtVl9uB2CNzkM1TJBnJ3Kmujr5VI5XYbUv2iJokRy9koLtE=}, Pair{Type|String, textures}, Pair{Type|String, eyJ0aW1lc3RhbXAiOjE1MjU0NjQ4MDkyNDEsInByb2ZpbGVJZCI6ImJjNmY1ZDVjODFjNjRkZGJiMTUwODZmNGE4M2E4OTNjIiwicHJvZmlsZU5hbWUiOiJMZWFpYW5hMSIsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS83YjJlYzI4YTQwODI2OWE0Y2NiYzgzYWNlMGY2ZmI3MDJiOGU5N2QyYTQ0OTY4N2E5ZTFlMTg4M2YxMGFlZjYiLCJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifX19fQ==}, Pair{Type|Boolean, true}, Pair{Type|String, IeRy6A53TTD6kdqG/0ijzCAobTgaWzDP4hITgszvM6slLEYiukAIdLfwCudoRmjmwdgEbud+GyRIV7i3ADZNQRCsI27Q2PniaD51phttDYq0U6TbUCGR1rRX9lEdLzf4KvyVg37xrHlHcGYJwmbFMgafiVwBybV65Ox0yxwsTy9/u97+F8hiSNS5ZyOKLFTbEssS+scxFZu65rsuY7KQPAwbBwXF4PjzPJbQDu09LrplzAI7QqWtawsDc3+7+leC4FgraqA8CBTDmT2V/ewMraroWszZ8LxXA3mn6UDkdXIQKUHEkX/ERYmTu5ASC0ajRO6mtu47UgTdfG3Wh1k+T9PObcmab4myDpyKu2qcivpaBdi/u6zBmrtBtvwiTDvQJVNiTzPZc6lkkmJEWn/8Fw5MflFrCongZh9qcGf76cldIMwg/OpsAkiX04HT1iFlzKNNROlga0F9z8RKd2hzd0vbPWPqOZxrHGQ8JQKGkxbqmYAK6J4GYnz06+rlurUXvGyQneKQFGoipsda6qQHnS3poDnC1IZF26iQP0OInF3n9RdEzU9ysX0MYOmKu748OuDtGhY1DTtXPX60Jgr7xnMCvi9ddaMZjtDGIQx++vef1yDnz4J4DZg+rjtTVtVl9uB2CNzkM1TJBnJ3Kmujr5VI5XYbUv2iJokRy9koLtE=}, Pair{Type|String, }], Packet ID: 45}

**Comment by MylesIsCool** [comment]
Can you test without other plugins to see if it still happens? (Just copy your server then test)

**Comment by Nikita12345222** [comment]
https://dump.viaversion.com/59e9f249cd6124a27c3a83443c53a80ddfeaa0239bb3fb11c074163a39255172

**Comment by MylesIsCool** [comment]
"Can you test without other plugins to see if it still happens?"

**Comment by CuteCubed** [comment]
still happens

**Comment by MylesIsCool** [comment]
Unfortunately, I'm not able to help you with this issue, because of one of the following:

- The client being disconnected is modified (they're sending bad data)
- You're possibly using BungeeCord and a plugin which is outdated (you never filled in the issue template so I have no idea)
- You're using plugins / have corrupted player data in the world folder.
