### ISSUE TITLE
[RFC] Drop old versions support since 1.13

### ISSUE THREAD

**Issue by XakepSDK** [MylesIsCool/ViaVersion#830]
The whole thing about multiversion was just to support last version and previous for migration purposes, but sometime this gone wrong and now everyone sits on 1.8(!) that is 4(!) years old!
I think, this is time for resolute actions to stop that circus with old versions.

**Comment by XakepSDK** [comment]
Same thread in protocolsupport: https://github.com/ProtocolSupport/ProtocolSupport/issues/817
Same thread in bungeecord: https://github.com/SpigotMC/BungeeCord/issues/2419

**Comment by krusic22** [comment]
ViaVersion's point is to allow new versions to play on old servers that are hard to update due to plugins and or time constraints. (RPG server, PvP,...).
We should not just leave this kind of people in the dark.

**Comment by XakepSDK** [comment]
They just should use old version client to play on old version server.
If that server is so good, they will do it.

**Comment by MylesIsCool** [comment]
I don't personally plan on fixing bugs in older versions. But I'm not gonna remove functionality from the plugin (people would just fork the plugin if I did anyway).
