### ISSUE TITLE
Joining 1.12.2 server on 1.8 bungeecord.

### ISSUE THREAD

**Issue by xEnderCrafterx** [MylesIsCool/ViaVersion#832]
### What is the output link of /viaversion dump? 
https://hastebin.com/ajiyuyewuf.sql

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Bungeecord
-Viaversion
-Bungeehub
-ProtocolLib
-EpicFriends

### How does this error happen? login? Using an item? 
So when I join my 1.8 bungeecord with viaversion so i can join with 1.12 I go to my 1.8 hub right?
Then I go and join housing which is 1.12, and I am on 1.12 it's just the hub is 1.8 and the bungee is 1.8, I go on to it and it gives an error: https://ender.owns-this.site/52dc0a7d.png

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Nope. It justs tells me this message

**Comment by MylesIsCool** [comment]
The error occurs when your BungeeCord is outdated, consider updating it.
