### ISSUE TITLE
1.12.2 ERROR help

### ISSUE THREAD

**Issue by Enlar** [MylesIsCool/ViaVersion#833]
### What is the output link of /viaversion dump? 
https://pastebin.com/THkWpxEa

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Spigot 1.12
 Plugins (32): LuckPerms, HealthBar, ArmorStandEditor, CrispyAntiWDL, DecoHeads, Multiverse-Core, RogueParkour, SkinsRestorer, NoPlugins, FastAsyncWorldEdit, React, RandomTeleport, CustomJoinItems, Vault, ServerListPlus, MoneyMobs, WorldEdit, Essentials, PerWorldInventory, Scavenger, HolographicDisplays, WorldGuard, DonatCase, ChestCommands, EssentialsProtect, EssentialsChat, EssentialsAntiBuild, AuctionGUIPlus, ViaVersion, EssentialsSpawn, TitleManager, AuthMe

### How does this error happen? login? Using an item? 
start server

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/jJJjpYfE

**Comment by MylesIsCool** [comment]
The error does not concern ViaVersion, this is down to your download corrupting etc.
