### ISSUE TITLE
Error loop?

### ISSUE THREAD

**Issue by Z609** [MylesIsCool/ViaVersion#85]
### What version of ViaVersion are you using? Type /ver viaversion
Using the bleeding edge source at https://github.com/MylesIsCool/ViaVersion

### What version of Spigot are you using? Type /ver
This server is running CraftBukkit version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### What plugins are you using? /plugins
ViaVersion, RemoteToolkitPlugin (last version), ProtocolLib (v2.3.2), AAC (latest), HolographicDisplays (latest), Hub (custom, shouldn't be the issue)

### How does this error happen? login? using an item? 
quit via Bungee git:BungeeCord-Bootstrap:1.9-SNAPSHOT:a7664a5:1128

### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/dxcrxKU1 (lots were omitted).
Looks like a loop starts in this according to the stacktrace. It might have to do with AAC, but I absolutely require AAC unfortunately. It spammed 1897 lines in one second.

**Comment by Z609** [comment]
Full Log: http://pastebin.com/JWR1mRw3

**Comment by HugoDaBosss** [comment]
AAC is probably causing this. Since it's closed source we are not able to do something about it ATM.
We are trying to get in touch with the AAC author.

**Comment by Z609** [comment]
I apologize, it turns out it happens when I **quit** and that I was running 1.8.9 during this. Unfortunately, this happens with both versions 1.8 and 1.9 anyway, so I don't think this matters.

Also, 1.9 gets kicked for this:
[http://prntscr.com/aan6ew](http://prntscr.com/aan6ew)

**Comment by HugoDaBosss** [comment]
It's strange you still get kicked, this should have prevented it: https://github.com/MylesIsCool/ViaVersion/pull/77
I'll recheck all the packets using json.
Does your hub plugin use any titles, bossbars or actionbars?

**Comment by Z609** [comment]
BossBars, yes. ActionBars: no. Although we use them on other servers. I'm looking to implement this plugin on all servers :)

**Comment by HugoDaBosss** [comment]
The bossbar is definitely causing the JSON error.

**Comment by Z609** [comment]
K, thank you. I am going to go now.
Thanks for the support thus far.
Should you need more information, I have /pl and /version opened up on the hub servers.

**Comment by MylesIsCool** [comment]
Should be fixed
