### ISSUE TITLE
Unable to get entity for ID: / (and kicked with a json error)

### ISSUE THREAD

**Issue by cloakfox** [MylesIsCool/ViaVersion#86]
### What version of ViaVersion are you using? Type /ver viaversion
0.4.6
### What version of Spigot are you using? Type /ver
Latest 1.8 one.
### What plugins are you using? /plugins
Plugins (15): icJukeBox, WorldEdit, PermissionsEx, Buycraft, ViaVersion, Vault, ProtocolLib, WorldGuard, BetterDrops, AgarioMC, NoCheatPlus, Essentials, EssentialsChat, EssentialsSpawn, EssentialsProtect

### How does this error happen? login? using an item? 
On login with 1.9 client, also it results in a json error.
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/Uns3t3V5
Kick message: is a json error.

**Comment by MylesIsCool** [comment]
Does this still occur on the latest version? Are you using BungeeCord if so what plugins?

**Comment by HugoDaBosss** [comment]
This probably has been fixed in later versions, only occurence of this bug so far.
