### ISSUE TITLE
BungeeCord, getting kicked on connect

### ISSUE THREAD

**Issue by D3visionNL** [MylesIsCool/ViaVersion#860]
### What is the output link of /viaversion dump? 
I can't get the link from the BungeeCord console

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
It happens on BungeeCord 1.12.2 and 1.13

### How does this error happen? login? Using an item? 
It happens when I try to join

### Is there an error in the console? Use pastebin.com. Is there a kick message?
The kick message is: "Connection lost"
Error is:
{Type: FlatItem, Index: 2, Data: [Pair{Type|Byte, 0}, Pair{Type|Short, 42}, Pair{Type|FlatItem, Item(id=238, amount=1, data=0, tag=CompoundTag { {display=CompoundTag(display) { {Lore=ListTag(Lore) { [StringTag { -------------------------- }, StringTag { Cosmetics }, StringTag { -------------------------- }] }, Name=StringTag(Name) { {"extra":[{"color":"white","text":"? "},{"color":"dark_purple","text":"Cosmetics "},{"color":"white","text":"? "},{"color":"gray","text":"(Right button)"}],"text":""} }} }, AttributeModifiers=ListTag(AttributeModifiers) { [] }, Enchantments=ListTag(Enchantments) { [CompoundTag { {id=StringTag(id) {  }, lvl=ShortTag(lvl) { 1 }} }] }} })}], Packet ID: 23}
Actual Error:  @ io.netty.handler.codec.MessageToMessageEncoder:106
>

**Comment by MylesIsCool** [comment]
Enable debug=true in server.properties :)

**Comment by MylesIsCool** [comment]
Could you confirm if this is fixed in our latest build?

https://ci.viaversion.com/job/ViaVersion/

If no, could you provide the new error and we'll reopen the issue.

**Comment by mrfloris** [comment]
That build has resolved it for me (but not bungee) We've received 0 complaints since.
