### ISSUE TITLE
Bug 1.12-1.13

### ISSUE THREAD

**Issue by alexandre14062** [MylesIsCool/ViaVersion#862]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/246f1a0d54ccfaadc43e1ba1f1a8a06ef645d2d8bfe38c43faba479a1ab22bfc

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Whithout Bungeecord

### How does this error happen? login? Using an item? 
no errors
just: https://image.noelshack.com/fichiers/2018/29/3/1531942739-2018-07-18-15-34-28.png

### Is there an error in the console? Use pastebin.com. Is there a kick message?

NO

**Comment by Gerrygames** [comment]
https://github.com/MylesIsCool/ViaVersion/issues/856

**Comment by MylesIsCool** [comment]
See above :)
