### ISSUE TITLE
1.13 is reporting players as connecting with 1.8.x when checking from Spigot console.

### ISSUE THREAD

**Issue by mibby** [MylesIsCool/ViaVersion#863]
Paper dev 1500 (Spigot 1.12.2)
Waterfall dev 192 (Upstream with BungeeCord dev 1333)

ViaVersion-dev build 146
ViaBackwards-dev build 59
ViaRewind v1.3.10

All Via plugins are installed on both BungeeCord & Spigot server.

Using ```/viaversion pps``` on Spigot, players are reported as connecting under 1.8 while on 1.13. Checking from BungeeCord console, it properly shows them as connecting with 1.13.

**Comment by Logics4** [comment]
Do not use ViaVersion in both Spigot and BungeeCord. Use it either in Spigot OR in BungeeCord.

That happens because BungeeCord is essentially doing all the job it has to do to give support for 1.13 clients. It is not a bug.

**Comment by MylesIsCool** [comment]
See above :)

**Comment by mibby** [comment]
1.13 clients weren't able to connect with Via just on Spigot, assuming because BungeeCord is still using an outdated 1.13 protocol. Everything works fine with Via just on Bungee, nothing on the Spigot side needs it to remap certain protocols or packets?

**Comment by MylesIsCool** [comment]
You should consider using 1.13 Bungee, eg. Waterfall
https://destroystokyo.com/ci/job/Waterfall/
