### ISSUE TITLE
Purple textures and block text when connecting with 1.13.

### ISSUE THREAD

**Issue by mibby** [MylesIsCool/ViaVersion#864]
Paper dev 1500 (Spigot 1.12.2)
Waterfall dev 192 (Upstream with BungeeCord dev 1333)

ViaVersion-dev build 146
ViaBackwards-dev build 59
ViaRewind v1.3.10

All Via plugins are installed on both BungeeCord & Spigot server.

Problem with encryption on world load in 1.13 perhaps?
![link1](https://i.imgur.com/HqYAzBi.png)
![link2](https://i.imgur.com/rFMwFNz.png)
![link3](https://i.imgur.com/tHCaDt5.png)
![link4](https://i.imgur.com/d4Vkjri.png)
![link5](https://i.imgur.com/lXaKhjJ.png)

Edit: Actually might be due to the server resource pack. Disabling the pack, things turn back to normal.

**Comment by Matsv** [comment]
Resourcepack related yeah (:
