### ISSUE TITLE
Proxy Error with 1.13

### ISSUE THREAD

**Issue by LorgeN** [MylesIsCool/ViaVersion#866]
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Running Waterfall (BungeeCord fork), latest stable build
Also running a full custom set of plugins

### How does this error happen? login? Using an item? 
Appears to happen on server switch. I am just observing this error in my logs.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/m4Npxr3m

Seems to be happening a bunch of times, with what seems to be a serialized item. I can provide more logs if necessary.

**Comment by MylesIsCool** [comment]
Could you confirm if this is fixed in our latest build?

https://ci.viaversion.com/job/ViaVersion/

If no, could you provide the new error and we'll reopen the issue.
