### ISSUE TITLE
BadPacketException thrown out by HexaCord (Bungeecord Fork)

### ISSUE THREAD

**Issue by Stefatorus** [MylesIsCool/ViaVersion#867]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/4a56744f64bf68f99c2d3bbdf22d263395899f55b7f172d14aafcdad019ed48e

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
HexaCord - Latest Version.
https://sfy.cx/ss/u/bf0f.png

### How does this error happen? login? Using an item? 
It happens on login.
NOTE: Players reach the lobby without being kicked (by that i mean that the players show joining message on the Lobby)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/VH5DvDEX

**Comment by i9hdkill** [comment]
Try to remove SkinsRestorer and try again

**Comment by Stefatorus** [comment]
Didn't help. SkinsRestorer doesn't seem to be the issue. Protocol 25 seems to have something to do with PluginMessaging.

Bug persists in latest waterfall version.

**Comment by i9hdkill** [comment]
Try latest dev build of viaversion. If the issue still persists, enable viaversion debug to eventually get more info

**Comment by Stefatorus** [comment]
I've managed to fix the issue by updating the proxy server. Seems neither HexaCord / Waterfall were properly supporting 1.13 protocols.
