### ISSUE TITLE
Visual Bug with fences & walls

### ISSUE THREAD

**Issue by BUTTERFILED8** [MylesIsCool/ViaVersion#869]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/0c025d8cf32ff5ae705cd559928f9754f43a43ee3b0b5156921fd1d1fabb538f

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Bungeecord!

### How does this error happen? login? Using an item? 
it just doses (All fences/walls)
https://i.imgur.com/D9U0IwR.png
Visual bug connecting fences
### Is there an error in the console? Use pastebin.com. Is there a kick message?
Nope

**Comment by MylesIsCool** [comment]
See above
