### ISSUE TITLE
1.13 cannot connect to servers with ProtocolSupport with ViaVersion on BungeeCord

### ISSUE THREAD

**Issue by Seshpenguin** [MylesIsCool/ViaVersion#870]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/e0c96d57753100b8e592d5a1fb3f72ed130993e003beaeb2103c4fd173949a3b

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord (WaterfallMC) with ViaVersion.
ProtocolSupport on end servers.

### How does this error happen? login? Using an item? 
On logon to servers that have ProtocolSupport, a 1.13 client will fail to connect with an "Outdated server message", stating that the server is on 1.12.2. If ProtocolSupport is removed, a 1.13 client will succeeded in connecting to the 1.12.2 server.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
"Outdated server! I'm still on 1.12.2"

**Comment by rmellis** [comment]
I Am having the same issue, It would be Great to have ViaVersion working senselessly side by side with protocol support, we cant drop Protocoll support because we support 1.5.2 as we have a few PowerPC Mac players (20%) who cant update past java 1.5 and are stuck with Minecraft 1.5.2

**Comment by krusic22** [comment]
I just want to update everyone on this issue.
When ViaVersion pings the server to find the version it fails when ProtocolSupport is installed.
You will see this if you enable /ps debug :
> with protocol version MINECRAFT_FUTURE

The current workaround is as follows (on bungee):

1. Update Bungee
2. Update ViaVersion
3. Set bungee-ping-save to false in ViaVersion
4. Set all the server versions manually
5. Try to connect with 1.13
6. ???
7. Profit

**Comment by Matsv** [comment]
ProtocolSupport is always responding '-1' when we try to discover the server protocol using the Bungee ping service. As @krusic22 said: it's required to set the server protocols manually in the ViaVersion config until ProtocolSupport fixed it.
