### ISSUE TITLE
Enchanted books not showing enchantment name

### ISSUE THREAD

**Issue by ConnorFranta** [MylesIsCool/ViaVersion#871]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/efcd53867b76cc2b825ebe5518cc54d57dc9bc17b397d1f075a96d269847fb4c

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No bungee
ViaVersion 1.4.0-DEV
ViaRewind-1.3.10
viabackwards-all-2.3.1

### How does this error happen? login? Using an item? 
Enchanted books are not showing enchantment name. (Tools are fine)
Login and look at an enchanted book from before 1.13 (1.12.2 specifically) 

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No errors

**Comment by Matsv** [comment]
@ConnorFranta Could you please try the latest devbuild? https://ci.viaversion.com/job/ViaVersion/
