### ISSUE TITLE
Bungee kicking certain players

### ISSUE THREAD

**Issue by danbzns** [MylesIsCool/ViaVersion#873]
### What is the output link of /viaversion dump? 

https://dump.viaversion.com/0e45379487119a399b2a1965a26e5a28d04c336e7fa5051a9513222383f0cf01

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

https://destroystokyo.com/ci/view/WaterfallMC/job/Waterfall/ build #192 

### How does this error happen? login? Using an item? 

Happens a few seconds after login

### Is there an error in the console? Use pastebin.com. Is there a kick message?

https://pastebin.com/1S5x3LD3

**Comment by MylesIsCool** [comment]
Could you confirm if this is fixed in our latest build? (And ensure you've updated your BungeeCord plugins + Waterfall)

https://ci.viaversion.com/job/ViaVersion/

If no, could you provide the new error and we'll reopen the issue.
