### ISSUE TITLE
Item frame hit boxes are in wrong locations

### ISSUE THREAD

**Issue by ConnorFranta** [MylesIsCool/ViaVersion#874]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/efcd53867b76cc2b825ebe5518cc54d57dc9bc17b397d1f075a96d269847fb4c

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No bungee
ViaVersion 1.4.0-DEV
ViaRewind-1.3.10
viabackwards-all-2.3.1

### How does this error happen? login? Using an item? 
Item frames facing:
- North, normal place and break
![image](https://user-images.githubusercontent.com/26499948/42920312-edc6d6ee-8ae3-11e8-8f8d-31962e7b9434.png)

- East, can't place or break, even at an angle
![image](https://user-images.githubusercontent.com/26499948/42920216-9077c4ee-8ae3-11e8-9e58-bebb64c29772.png)

- South, normal place and break
![image](https://user-images.githubusercontent.com/26499948/42920264-ba7bd42e-8ae3-11e8-878c-1fd3ff603116.png)

- West, need to stand at an angle to place/break
![image](https://user-images.githubusercontent.com/26499948/42920291-d7694152-8ae3-11e8-9977-d4bdbf3cc904.png)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
None

**Comment by Matsv** [comment]
Thanks for reporting!

This issue will be fixed in the next version or the latest devbuild (:
