### ISSUE TITLE
Can't connect in 1.13 when i update the plugin viaversion to lastest version

### ISSUE THREAD

**Issue by VenixMC** [MylesIsCool/ViaVersion#875]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/b475941906da29af3b2ab00836408a1d85228e00a302463acd57db30fc27cbf1

### How does this error happen? login? Using an item? 
login and kicked with message outdate client! i still in 1.9.4 version

### Is there an error in the console? Use pastebin.com. Is there a kick message?
login and kicked with message outdate client! i still in 1.9.4 version

**Comment by Matsv** [comment]
Are you using BungeeCord?

**Comment by VenixMC** [comment]
Yes, Waterfall lastest version

**Comment by Tux2** [comment]
The latest version of Waterfall and BungeeCord only support up to 1.13-pre7 release. There hasn't been an official release of Waterfall or BungeeCord for 1.13.

**Comment by Matsv** [comment]
Please update your BungeeCord or use the ViaVersion plugin on your current BungeeCord instance instead of Spigot

**Comment by Acenox** [comment]
@VenixMC Update Waterfall, the update has just been released. 

https://github.com/WaterfallMC/Waterfall

**Comment by MClausz** [comment]
I use latest Waterfall and Viaversion, and I get this:
`[03:42:11 INFO]: MasterClaus lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.`

**Comment by VenixMC** [comment]
Chào anh ân 😄

**Comment by MClausz** [comment]
This issue is caused by BungeeTablistPlus and they fixed it.

**Comment by MylesIsCool** [comment]
See above :)
