### ISSUE TITLE
Keep getting disconnected 

### ISSUE THREAD

**Issue by jordanwilliams1** [MylesIsCool/ViaVersion#876]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/cd24780321338c56ec76e14611be9d9a8f410452a618444eefd5e526ef7db1d2

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Paperspigot 1.12

Plugins causing problem:
DifferentCore
MythicDrops (Modified version)

### How does this error happen? login? Using an item? 

Login.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/raw/39DKUkj0
Kick Message: https://i.gyazo.com/d998e16ffba52b00a610af988aa9ca58.png

**Comment by Matsv** [comment]
Please change debug=true in server.properties and give us the full exception (:

**Comment by jordanwilliams1** [comment]
It was fixed in the latest version :)

**Comment by Matsv** [comment]
Great to hear that!
