### ISSUE TITLE
Flickering Scoreboard Since Updating

### ISSUE THREAD

**Issue by ItsAlpal** [MylesIsCool/ViaVersion#879]
What is the output link of /viaversion dump? 
https://dump.viaversion.com/dd179511ae6694438930e70fc060d599432da8b2f1470d495e34d3edcf1e8e05

Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord Build #1333

How does this error happen? login? Using an item? 
All the time

Is there an error in the console? Use pastebin.com. Is there a kick message?
Nope.

Before and after:
Before: No flickering, full messages
1.13, after: https://ibb.co/nqawpJ As you might be able to see, it's supposed to say 'Owner' up top and lots of variables aren't being filled in.

**Comment by MylesIsCool** [comment]
Not really sure what i'm supposed to be looking for, could you elaborate further? Can you also try with the latest version?

Could you try with only ViaVersion + Scoreboard? (Copy server etc)

**Comment by ItsAlpal** [comment]
Ok it seems to have been an issue with BungeeCord. After updating both BungeeCord and ViaVersion the issue has disappeared.
