### ISSUE TITLE
Invisible fishing hook

### ISSUE THREAD

**Issue by Gerrygames** [MylesIsCool/ViaVersion#880]
### What is the output link of /viaversion dump? 
I can send you the dump if needed.
Server version: Spigot 1.11
Client version: 1.13
Using ViaVersion on Spigot.

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord, ProtocolLib, NoChestPlus and a few custom plugins.

### How does this error happen? login? Using an item? 
If you right click a fishing rod the fishing hook is not visible.
Other players (no matter which version) do see the fishing hook. Only the player throwing it is unable to see it.
The same issue applies to leads.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No console errors.

**Comment by Gerrygames** [comment]
Hm I just tested on my local server without any plugins besides ViaVersion and it works. So it must be one of our plugins or Waterfall.

**Comment by Matsv** [comment]
Please let us know which plugin is conflicting (:
