### ISSUE TITLE
Fireworks colors

### ISSUE THREAD

**Issue by UzumakiYT** [MylesIsCool/ViaVersion#882]
1.8 clients can see colored fireworks such as blue, green, yellow...
while 1.13 clients see them only as red.
I think is a minor problem but still.

**Comment by Matsv** [comment]
Unable to reproduce this issue, colors work fine for me in 1.13. Does this command work for you? `/summon fireworks_rocket ~ ~ ~ {LifeTime:40,FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:0,Trail:1,Colors:[I;2437522],FadeColors:[I;2437522]}],Flight:2}}}}
`
