### ISSUE TITLE
ViaVersion 1.4.0 does not work on Minecraft 1.13

### ISSUE THREAD

**Issue by kajahofman** [MylesIsCool/ViaVersion#883]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/c278d2126f60786fd317c4568759ed77a8489a8b0765213bb56921b1ded299d5

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No, only Spigot 1.12.2.

### How does this error happen? login? Using an item? 
I can't log in to my server with 1.13 client.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Outdated server! I'm still on 1.12.2.

**Comment by MylesIsCool** [comment]
VV is not compatible with ProtocolSupport. I'd recommend either using ViaVersion on Bungee (though there currently may be bugs with that and need to hardcode protocol numbers)

or use ViaRewind / ViaBackwards for now (recommended)

**Comment by kajahofman** [comment]
Thanks.
