### ISSUE TITLE
Players keep getting kicked

### ISSUE THREAD

**Issue by jordanwilliams1** [MylesIsCool/ViaVersion#889]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/f7a4e97efe9597139ac7eafca109a7fe8605c30d65b3afcfebc5ff04315cd477

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Plugins:
DifferentCore (Custom Plugin)
MythicDrops (Modified)
Multiverse-Core
ViaVerison
Papespigot 1.12

### How does this error happen? login? Using an item? 

If a player login near spawn it will disconnect them. 

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/raw/sG3MNX7U

**Comment by jordanwilliams1** [comment]
@Mats Was any of this info any help?

**Comment by ConnorFranta** [comment]
@jordanwilliams1 See #891

**Comment by MylesIsCool** [comment]
Could you confirm if this is fixed in our latest build?

https://ci.viaversion.com/job/ViaVersion/

If no, could you provide the new error.

**Comment by jordanwilliams1** [comment]
@MylesIsCool The game know crashes with this error:
https://i.gyazo.com/bf2f1bdcd53bf08a0c7b44f625006742.png

and this error in the server console:
https://pastebin.com/raw/fD9JM4Se

**Comment by jordanwilliams1** [comment]
I Really hope you can fix this :/

**Comment by MylesIsCool** [comment]
Could you copy the full error from the launcher and pastebin it? (With the latest version)

**Comment by jordanwilliams1** [comment]
@MylesIsCool Crash report from the launcher: https://pastebin.com/tEaHuuYj

**Comment by jordanwilliams1** [comment]
Really would like to update :( @MylesIsCool

**Comment by MylesIsCool** [comment]
I'm on holiday so I can't magically fix a issue which requires proper investigation

**Comment by creeper123123321** [comment]
Could you test 543daa2 ?

**Comment by jordanwilliams1** [comment]
@creeper123123321 It works :) Just a bit spammy 

"Received invalid biome id: 65" 

https://pastebin.com/ceX1uTN6

**Comment by MylesIsCool** [comment]
Your server possibly uses custom terrain which uses a invalid biome id, we'll probably look into a way to reduce the spam in the future of invalid biome
