### ISSUE TITLE
Players with 1.13 client get kicked while they write or when they enter a long command.

### ISSUE THREAD

**Issue by SentinelCraft** [MylesIsCool/ViaVersion#891]
**### What is the output link of /viaversion dump?** 
https://dump.viaversion.com/d81ef3c0d64e38a1b65f1a8a869b30cbefc8eccc19fb573a6f5327915a787eb5

**### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)**
No

**### How does this error happen? login? Using an item?** 
This only happens with players who join with 1.13 client and started after I updated your plugin.

I added your recent snapshot version to get people to join us with 1.13 client. However I am experiencing a weird issue related to your plugin and it only happens with people who join on 1.13. People in any 1.12 version have no issues.

_1._ Everytime people write a **very long command** while on 1.13 client (example: "/msg «player» Hello, I am new here, can you help me? I don't really know what to do"), they get **kicked from spamming while writing it**. 

_2._ It also happens when they submit a **long command, but long enough to not get kicked while writing** (example: "/msg «player» I am new here, help me?). This time they get **kicked for spamming right after they enter the command**.

_3._ There's no issues with regular chat, it's only with long commands, like, for example, the Essentials /msg or a VentureChat ranged chat. Small commands like /login «password» work fine.

**### Is there an error in the console? Use pastebin.com. Is there a kick message?**
I wasn't able to show logs for _1._ since players don't end up submiting the command (they get kicked while writing). But these logs shows me getting kicked after typing a message to another player and it also shows that I typed a small command (AuthMe login) without any issue (evidence for _2._ and _3._). 

This is the kick message:
https://pastebin.com/722szqSn

Would you be able to look into this and help us, when possible?

Thank you!
~Migas | SentinelCraft

**Comment by HexedHero** [comment]
Noticed this been reported by a good amount of players being confused why they are getting "kicked for spam"

**Comment by TNTUP** [comment]
Confirmed, ViaVersion 4.1.2 #.214 I can try updating to the current build #.217 if it helps

**Comment by electronicboy** [comment]
Basically, "tell them to type slower"
In 1.13, the behavior is that basically, the client will fallback to basically sending a tab every time you type a character for a command, pre 1.13 servers aren't really expecting that to happen, and so protect against spamming that as a means to crash server;

ViaVersion either needs to do something like debounce processing the tab back (you will need to return acknowledgments for these from what I recall, however) or look into toying with the spam limiter field;

**Comment by ConnorFranta** [comment]
We had this issue also, it was ChatControl for the new tabbing. Give all players the node:
    - chatcontrol.bypass.spamkick

**Comment by ConnorFranta** [comment]
@Matsv This isn't a ViaVerions issue.

We also had this issue, it was ChatControl for the new tabbing. 
@SentinelCraft In your case, it would be VentureChat.

For chat control give all players the node:
- chatcontrol.bypass.spamkick
We don't use VentureChat, but the node _might_ be:
- venturechat.cooldown.bypass

These plugins will need to update to 1.13 for it to be solved.

**Comment by ConnorFranta** [comment]
@SentinelCraft Interesting... we also have Essentials, and all of ViaVersions plugins, no issues after that node was added.

**Comment by alexmarkey** [comment]
disconnect.spam is the Anti Spam built into spigot, so I believe this is an issue with ViaVersion (As far as I can tell, there is no way to disable spigots AntiSpam, you can only add commands that bypass it)

**Comment by ConnorFranta** [comment]
You also have these that could be affecting it.
NoCheatPlus
AuthMe
NoBotAttacks
Parties

**Comment by SentinelCraft** [comment]
@ConnorFranta Hello again. 

We disabled NoCheatPlus command spam before submitting this report. AuthMe / AntiBotAttack / Parties are not related. The Parties chat also kicks players since it has its own chat command.

Maybe... Is it because we are still on 1.12.1 Spigot version? No idea. I am clueless.

~Migas | SentinelCraft

**Comment by electronicboy** [comment]
It's not a plugin issue, any plugin cancelling all kicks from the server with disconnect.spam as the reason would shim away this issue (however, would break tab completion for them when it starts hitting the kick condition)
1.12.2 and below didn't expect clients to connect which basically end up spamming the tab completion packet at it, and as such the limit is too low considering this

**Comment by alexmarkey** [comment]
Any update on this issue yet - For the time being we are needing to edit the spigot jars and remove their antispam feature as I do not believe there is a way to disable it.

**Comment by jordanwilliams1** [comment]
@MylesIsCool Any update on this :( ? Would of thought it would of been fixed.

**Comment by TNTUP** [comment]
@andrewkm Latest version of Paper 1.12.2 "fixed" it for me, they implemented an tab-spam-limiter config, the increment was 10, maximum was 500, myself I did set the increment of 1, max of 500 and it completely solved the issue for 1.13.x players :)

PS: My english sucks

**Comment by MylesIsCool** [comment]
You can disable this via `disable-1_13-auto-complete` in the config.yml in the latest build as an alternative solution (changing the spam limit in paper is probably better).

This build can be found at https://ci.viaversion.com/job/ViaVersion/

I'm interested in other workarounds for sure, I had a quick look into reflection on the bukkit side but the main issue is it becomes very ugly because of hardcoded values.

**Comment by andrewkm** [comment]
Thank you!

**Comment by xion87** [comment]
ty that fix solved the issue with 1.13 client

**Comment by MrFoxzer** [comment]
Thank you so much you are a life-saver <3
I fixed the 1.13 glitch on my server IP: Play.FadedMc.Com <---Best Drug server!!!

**Comment by soshimee** [comment]
1 tick delay still makes disconnect.spam, it needs to be at least 10 ticks

**Comment by soshimee** [comment]
Bump

**Comment by MaximeMichaud** [comment]
@MylesIsCool What is the best long-term solution ?
Changing the spam limit in paper is probably better or disable-1_13-auto-complete ?
because if I use "disable-1_13-auto-complete" auto-complete is no longer possible in 1.13.x & 1.1.4.x
And if I change the spam limit in paper, that will not cause other problem? Like Lag(s) ?

**Comment by soshimee** [comment]
OPs actually do not get kicked for typing commands quickly. Maybe there are certain permissions for it.

**Comment by toxamin** [comment]
A delay of 1 tick works perfectly fine, and can send a maximum of 1 packet per tick. (20 packets / second)
The reason for this is, every time a tab packet from the client is sent to the server, viaversion creates a task that will run 1 tick later, however, if another tab packet is sent from the client to the server, while a task already exists, the previous task is cancelled.
Source: https://github.com/ViaVersion/ViaVersion/commit/bce35931102b552573024acfb9bc56278dfe7385

To fix this "issue" you may also cancel all kick events in which the reason for the kick is "disconnect.spam".

Please do not argue if you don't know what you're talking about.

This "issue" was fixed over a year ago, please stop replying to it, thank you.

**Comment by soshimee** [comment]
1 tick never worked for me, and the message is "Kicked for spamming" for me. It's not plugin doing this, I have no plugins that can affect chat / disabled in config.yml. (It's about my past, I switched my server to 1.14 completely to prevent more issues.)

**Comment by toxamin** [comment]
"never worked for me" does not mean the solution does not work. Probably user error, such as /reload'ing and expecting it to work. I can prove it works by simply reading the code.
