### ISSUE TITLE
Metadata for entitity not sent because it doesnt exist

### ISSUE THREAD

**Issue by LoXR** [MylesIsCool/ViaVersion#897]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/eedaa4859a4444229393a946bfb383a0f54db12cf10da1e9253f4a10080f5ba3

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yes, Bungeecord #1​33​3 

### How does this error happen? login? Using an item? 
Just spams the console of missing items due to 1.13 on 1.12/1.8.8 spigot/paper servers.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/g25ApZpk

**Comment by MylesIsCool** [comment]
Can you test with 1.4.1? (Latest release)

**Comment by LoXR** [comment]
It isnt fixed, using the latest snapshot 1.4.2 sends this: https://pastebin.com/1iaQbUcF

**Comment by LoXR** [comment]
Should I maybe go to 1.4.1 release or will there be a fix soon? https://pastebin.com/iazz3yJ1

**Comment by MylesIsCool** [comment]
As discussed on discord, down to a plugin sending entity data in wrong order. Can use suppress-metadata-errors in config to hide errors if needed.
