### ISSUE TITLE
20.07 20:25:47 [Server] INFO Missing block completely 327968

### ISSUE THREAD

**Issue by Cobwebster** [MylesIsCool/ViaVersion#899]
1.4.0 version, bungee.

20.07 20:25:47 [Server] INFO Missing block completely 327968
20.07 20:27:45 [Server] INFO Missing block completely 133536
20.07 20:27:49 [Server] INFO Missing block completely 199072
20.07 20:27:51 [Server] INFO Missing block completely 199072

Hopefully the bug is pretty straight forward, I assume all you need is the numbers.

Seems like 1.13 support uses up some heavy performance, we're encouraging our users to use 1.12.2 because allowing 1.13 brings a huge performance spike, not sure if its a bug or just what should be expected.

We're updating to latest shortly.

**Comment by MylesIsCool** [comment]
This is down to not being the latest build, we've also done optimizations in latest too which may help performance to some degree.
