### ISSUE TITLE
Kicked whenever a 1.9 user places a block

### ISSUE THREAD

**Issue by xDacon** [MylesIsCool/ViaVersion#90]
### What version of ViaVersion are you using? Type /ver viaversion
0.4.6

### What version of Spigot are you using? Type /ver
1.8.8
( git-Spigot-db6de12-18fbb24 )

### What plugins are you using? /plugins
Happens on all servers, only plugins that all the server share (i've also narrowed this list down by removing many plugins and testing)
Holographic Displays
Essentials
Permissionsex
Votifier
GAListener
WorldGuard
WorldEdit
Featherboard

### How does this error happen? login? using an item?
When a player places <any> block, it will send them back to Bungeecord Lobby, or kick them from the proxy with this message: https://t.gyazo.com/teams/dacon/a3246f93f56e0aa15f98249df7a57ef9.png 

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No error in console

**Comment by HAlexTM** [comment]
What version of WorldGuard&WorldEdit are you using?

**Comment by xDacon** [comment]
WorldGuard: 6.1.1
WorldEdit: 6.1.1 and 6.0.0

**Comment by HAlexTM** [comment]
Why use both version and not just  6.1.1?
Anyway this happen only to 1.9 clients?

**Comment by Paulomart** [comment]
Does it work without Holographic Displays?

**Comment by xDacon** [comment]
Yes this only happens to 1.9 clients

and what I meant was our servers use WorldGuard 6.1.1 but a couple of them used 6.0.0 and the bug still occurred

**Comment by MylesIsCool** [comment]
Now Fixed. Use 0.4.8
