### ISSUE TITLE
When 1.13 player join Spigot 1.13 pre-7 snapshot server.Player will got a kick

### ISSUE THREAD

**Issue by Ghost-chu** [MylesIsCool/ViaVersion#901]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/49f17830fe82129cc8fb137dd434a220ec9498f2336f72c7e4d258666d5270bd
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
nop

### How does this error happen? login? Using an item? 
Login

### Is there an error in the console? Use pastebin.com. Is there a kick message?
no error in cosole,But client say "InternalException:io.netty.handler.codec.DecoderException:The received
 string length is longer than maximum allowed(60>20)"

**Comment by Matsv** [comment]
Spigot 1.13-PRE7 is not supported by ViaVersion.
