### ISSUE TITLE
Redstone, glass etc. does not update.

### ISSUE THREAD

**Issue by HenrikAndWiktor** [MylesIsCool/ViaVersion#903]
Screenshot:
![2018-07-21_12 30 22](https://user-images.githubusercontent.com/25562757/43034736-5cd372f4-8ce2-11e8-96c8-ed3bbe50afc6.png)

### What is the output link of /viaversion dump? 
https://dump.viaversion.com/0df33600f52f78f4dbad686f70397d97ee2c9e5ecf524f807998833408264933

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I use Bungee, EssentialsX, GroupManager, WorldEdit/WorldGuard, Vault, Viaversion and my own plugin.

### How does this error happen? login? Using an item? 
- Redstone, glass and other connecting/2-block blocks does not update

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No errors at all.

**Comment by Gerrygames** [comment]
https://github.com/MylesIsCool/ViaVersion/issues/856

**Comment by HenrikAndWiktor** [comment]
Thanks
