### ISSUE TITLE
Food is going down SOO FAST with 1.13 client

### ISSUE THREAD

**Issue by JohannesHQ** [MylesIsCool/ViaVersion#904]
Hello, my server version 1.12 and using 1.13 client, and the food is going down so fast in one minute!
Please can you fix this?
Thanks

**Comment by MylesIsCool** [comment]
Cannot replicate, provide full information and follow the issue template - https://github.com/MylesIsCool/ViaVersion/blob/master/ISSUE_TEMPLATE.md


So that we can replicate and then we'll reopen and get this fixed (if it's down to viaversion).
