### ISSUE TITLE
1.13 - Water/Swim bug

### ISSUE THREAD

**Issue by lerobto** [MylesIsCool/ViaVersion#905]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/d26d8ba3aa387ea0dd5c74c45dcb66c68cd0069cccdac8f5086f69a4bbfefced

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
BungeeCord latest version from ci. My Plugins: Yamler, my own CloudAPI and ViaVersion

### How does this error happen? login? Using an item? 
If i will go swim in 1.13 i can walk normally under water.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Nope

**Comment by yannicklamprecht** [comment]
Sprint or walk?

**Comment by KennyTV** [comment]
#872

**Comment by lerobto** [comment]
booth @yannicklamprecht

**Comment by MylesIsCool** [comment]
See issue linked by Kenny for progress on this.
