### ISSUE TITLE
Issue while displaying server-icon in the multiplayer list

### ISSUE THREAD

**Issue by Sukram28** [MylesIsCool/ViaVersion#907]
It's not possible to see server-icons of servers using the Spigot version <= 1.12 while using the 1.13 client
(Note: This issue is not caused by ViaVersion)
I'm not sure if this is fixable, but it would be really cool. 

### What is the output link of /viaversion dump? 
https://dump.viaversion.com/59b729685f0b5fbc79122489d9c7256caca275497dcec77c604dc56b781ed7cb

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I'm only using Spigot 1.12 (and ViaVersion-1.4.1) with no additional software, but this issure also affects other Spigot versions.

### How does this error happen? login? Using an item? 
This issure appears in the client-server-list (Multiplayer-List)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
None

**Comment by krusic22** [comment]
Update ViaVersion should be fixed by #900

**Comment by IMBACalimba** [comment]
For me this error occures only when i start MC 1.13.

All other versions are showing the icon as usual.

**Comment by IMBACalimba** [comment]
Ive installed the latest Version but stil have this issue.

**Comment by TNTUP** [comment]
That issue is solved on my side, Paper 1.12.2 #1500 with ViaVersion 1.4.2-snapshot #214

**Comment by Matsv** [comment]
Fixed in the latest devbuild.
