### ISSUE TITLE
Players in 1.13 version drowned slower than 1.12 and lower

### ISSUE THREAD

**Issue by Klapeks** [MylesIsCool/ViaVersion#912]
I use Spigot 1.9.4
1.9-1.12 players are drowning with normal speed
but 1.13 players are drowning slower.

(sorry for my English :D)

**Comment by codingJWilliams** [comment]
Hey. I can't time it at the moment but I can't remember there being a major difference in drown speed on Spigot 1.12.2 with ViaVersion on BungeeCord (could be a spigot side bug?).

How much of a difference are we talking, and where is viaversion, and do could you post a plugin list please.

**Comment by MylesIsCool** [comment]
See above
