### ISSUE TITLE
[Bungee] 1.12 servers protocol version changing to -1

### ISSUE THREAD

**Issue by xDacon** [MylesIsCool/ViaVersion#915]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/036d210ccf4c9b3b6bbbec5315d28aebfb3a6e785a4ecc9c2153bb3f57b6cdd9

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
In dump

### How does this error happen? login? Using an item? 
Protocol version for 1.12 servers keeps staying at "-1". I've tried manually changing it and also doing /viaversion probe multiple times but it goes back to -1

1.13 clients cannot join 1.12 servers because of this

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No

**Comment by xDacon** [comment]
Yea

**Comment by Matsv** [comment]
Not related to ViaVersion. We use the built-in ping service from Bungeecord. I’m guessing ProtocolSupport always responds the requested protocol id. (Unconfirmed)

**Comment by Matsv** [comment]
You can change the protocol id manually in the ViaVersion config and disable auto probing (:

**Comment by xDacon** [comment]
Was working ok with 1.4.0, weird

Thanks will try that

**Comment by xDacon** [comment]
Changed bungee-ping-interval to -1 but the protocols keep changing back to -1 when I reload the plugin, do these require full reboot?
