### ISSUE TITLE
Plants bug 1.13

### ISSUE THREAD

**Issue by Zeref2k20** [MylesIsCool/ViaVersion#917]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/0be744b0757cc4bc85101aeadf8c0f1f1bce467a052b87fa1fa430d25d436cc4

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
ViaVersion works under Spigot, but server works using BungeeCord

### How does this error happen? login? Using an item? 
All the plants having the height of 2 blocks have appearance like this: https://pp.userapi.com/c830209/v830209350/14a861/QWsiXnWWboc.jpg

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Nope

**Comment by ConnorFranta** [comment]
Know connecting block issue, being worked on. #856
