### ISSUE TITLE
Name item bug 1.13

### ISSUE THREAD

**Issue by Zeref2k20** [MylesIsCool/ViaVersion#918]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/0be744b0757cc4bc85101aeadf8c0f1f1bce467a052b87fa1fa430d25d436cc4

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
ViaVersion works under Spigot, but server works using BungeeCord

### How does this error happen? login? Using an item? 
All the item names have &o by default. Please fix it or add this feature like they have it on Hypixel.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Nope

**Comment by ConnorFranta** [comment]
This was fixed #888
