### ISSUE TITLE
Handle command translations

### ISSUE THREAD

**Issue by Zeref2k20** [MylesIsCool/ViaVersion#919]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/0be744b0757cc4bc85101aeadf8c0f1f1bce467a052b87fa1fa430d25d436cc4

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
ViaVersion works under Spigot, but server works using BungeeCord

### How does this error happen? login? Using an item? 
Executing /gamemode gives the following text (https://pp.userapi.com/c830209/v830209350/14a897/GBjgXbL754A.jpg), but executing /gamemode 1 goes ok. Same thing for /op, /tellraw, etc

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Nope

**Comment by KennyTV** [comment]
Generally happening with most vanilla command messages, tp, give, kill, the list goes on. Gamemode seems to be an exception

**Comment by codingJWilliams** [comment]
Can't repro with 1.13 client, 1.12.2 spigot backend, Via on bungee

**Comment by Lennart99** [comment]
I have the same problem on 1.12.2 server, no bungeecord, no other plugins, 1.13 client
Server and viaversion are latest version

**Comment by MylesIsCool** [comment]
Should be fixed in latest build :), (creeper fixed it)
