### ISSUE TITLE
Disconnect Issue

### ISSUE THREAD

**Issue by AmazedMender16** [MylesIsCool/ViaVersion#921]
Chatcontrol Pro + Viaversion

### Are you using any additional software like BungeeCord? If so, what software and version
Chatcontrol bridge

### How does this error happen? login? Using an item? 
When users MSG a player that uses 1.13 client he user disconnect with this error:
Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.

**Comment by Matsv** [comment]
Please provide your /viaversion dump and enable debug=true in server.properties to get the full exception/

Thanks

**Comment by AmazedMender16** [comment]
Hello,

Sorry :) 
https://pastebin.com/cth9YJ9K
https://dump.viaversion.com/f2f86bf2c03227423875c712584e83e3afcad2ed704383f893e71c73d9f3fedb

**Comment by MothGirlMusic** [comment]
i'm having the same issue

![2018-07-26 10 06 49 pm](https://user-images.githubusercontent.com/1746550/43297686-c18a8c0e-9120-11e8-903a-ea2a633b8265.png)

**Comment by MothGirlMusic** [comment]
i'm in a bungee network with 1.12.2 severs and one 1.13 server.. this happens when i try to teleport to the 1.13 server. [viaversion is installed in the bungee because it didn't work being installed in the spigot servers being that bungee still complained about 1.13 not being the right version and on your wiki it says clearly "one or the other"]

**Comment by MylesIsCool** [comment]
See https://github.com/MylesIsCool/ViaVersion/issues/934#issuecomment-408670009 for details (ensure BungeeCord is updated)

**Comment by MothGirlMusic** [comment]
yup. thank for linking that. i found in debug mode the plugin sending the data that is too long is ViaVersion. bungeecord is latest version [also tried waterfall which is also latest version] for the same results. i'm MothMuse in your plugin's discussion on spigot. i linked the error and pastebin and all that there.
