### ISSUE TITLE
ViaVersion-1.4.1.jar Redstone not connected in Minecraft 1.13

### ISSUE THREAD

**Issue by Peda1996** [MylesIsCool/ViaVersion#922]
Hy, im using the Version ViaVersion-1.4.1.jar,

I found a bug in the new Version of ViaVersion. Redstone is not connected properly in the new Minecraft Version 1.13.
![2018-07-22_20 23 34](https://user-images.githubusercontent.com/1789749/43048766-273a0624-8ded-11e8-9b9e-cc95fbb419e3.png)

Best Reguards

**Comment by Gerrygames** [comment]
https://github.com/MylesIsCool/ViaVersion/issues/856
