### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by MasterGabeMOD** [MylesIsCool/ViaVersion#924]
https://dump.viaversion.com/7666aa46afcdee610ebffa378e2afbf830e8cba774c16e7f43b60c62404d5d56

I'm not sure if this issue comes from ViaVersion or MC 1.13, but we have been experiencing high system load since the 1.13 update. Bungee CPU load average 22.68, 23.95, 24.49 - Around 400-500% CPU usage. We did not have this issue prior to updating to 1.13. 

Server processor: E3-1270V6

**Comment by eliteSchwein** [comment]
remove viaversion from the bungee plugin list and use the newest waterfall version

https://destroystokyo.com/ci/job/Waterfall/

it is updatet to 1.13 release

**Comment by FurmigaHumana** [comment]
I use the normal bungeecord for 1.12 and have only updated viaversion but I have not noticed any increase on cpu load.

**Comment by MylesIsCool** [comment]
See above, we'll happily investigate if we can get data to help us reduce this where possible :)
