### ISSUE TITLE
1.13 sound latency is too big

### ISSUE THREAD

**Issue by ishland** [MylesIsCool/ViaVersion#927]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/853be840152de9abfdcbe954a2be3668c4505ca8eda1e1f955addddafd62302f

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
ASkyBlock (3.0.9.1), AuthMe (5.4.0-b1877), ChopTree3 (4.0.0), Citizens (2.0.22-SNAPSHOT (build 1487)), CleanroomGenerator (1.0.0), ClientStats (2.8.5), CoreProtect (2.14.2), CS-CoreLib (v1.5.18), dynmap (2.6-beta-1-Dev201807082003), Dynmap-ASkyBlock (1.1), FastAsyncWorldEdit (18.07.21-a00345f-1159-20.4.0), GemsEconomy (4.3.2), HomeGUI (2.0.0), Installer (2.4.1), KillerMoney (4.2.0), Multiverse-Core (2.5.0-b727), MyPet (2.3.5), PermissionsEx (1.23.4), PlugMan (2.1.5), RemoteToolkitPlugin (R10_A15.3), Residence (4.7.8.2), RPGItem (0.1.07), ServerSigns (4.5.1), Shopkeepers (2.2.1), Slimefun (v4.1.15), SystemInfo (0.0.4a), TimoSpawn (1.0), TPA (2.2.2), Vault (1.5.6-b49), ViaBackwards (2.3.1), ViaRewind (1.3.9), ViaRewind-Legacy-Support (1.3.1), ViaVersion (1.4.1), WorldEdit (6.1.8-SNAPSHOT;cd4729f)

### How does this error happen? login? Using an item? 
Just use anything to play a sound.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Nope.

**Comment by MylesIsCool** [comment]
Unable to replicate this, try latest dev build as we've modified some sound stuff. Otherwise please provide minimal configuration to replicate and we'll reopen. (As we're unable to replicate with just VV)
