### ISSUE TITLE
Joining with 1.13 client from a 1.12.2 server not possible.

### ISSUE THREAD

**Issue by Alanaaya** [MylesIsCool/ViaVersion#928]
### What is the output link of /viaversion dump

https://dump.viaversion.com/954fba9214d8959a281b698abb319b37098efa1d76bbb3490e3264bda66da1e4

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well) 

I am using the latest BungeeCord version (BungeeCord-Bootstrap:1.13-SNAPSHOT:a710698:1340). However, I am also using the following plugins listed below.

BuycraftX, BungeeYAML, FakeOnlinePlayers, JustOneMoreBungee, NuVotifier, SkinsRestorer, SwiftMOTD, ViaVersion-1.4.1, ViaBackwards-all-2.3.1. Note that I have tried with and without ViaBackwards,  yet I get the same error.

### How does this error happen? login? Using an item? 
Whenever I log into a 1.12.2 server with ViaVersion on Bungeecord with a 1.13 client, trying to connect to a 1.13 server running Spigot 1.13-R0.1-SNAPSHOT it kicks me with the message "The server you were previously on went down, you have been connected to a fallback server"

https://i.imgur.com/ODB2Ola.png

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/Tg2N0Sup

**Comment by MylesIsCool** [comment]
BungeeCord has fixed this in a later release

https://github.com/SpigotMC/BungeeCord/commit/a710698277d6edd83e82c7e9269f56956539655e
