### ISSUE TITLE
1.13 Client crashes after login/loading chunk.

### ISSUE THREAD

**Issue by MinecraftAdmin** [MylesIsCool/ViaVersion#929]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/9ace6241a2991c12f11d68a6d1961e763071749e043350dc0954dc222ceba8ea

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Nope

### How does this error happen? login? Using an item? 
Login and chunk load

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Client crash report.
https://pastebin.com/fRQTx9sH

Disconnect message on Bungeecord
https://pastebin.com/gPiN1qcb

**Comment by codingJWilliams** [comment]
What's your server version, can't repro on 1.12.2 spigot server with latest viaversion dev

**Comment by MylesIsCool** [comment]
Need more info to replicate though should be fixed in latest build
