### ISSUE TITLE
Error when i quit

### ISSUE THREAD

**Issue by AlexNova1555** [MylesIsCool/ViaVersion#93]
### What version of ViaVersion are you using? Type /ver viaversion
0.4.6
### What version of Spigot are you using? Type /ver

This server is running CraftBukkit version git-Spigot-db6de12-3
f3c65f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
You are 61 version(s) behind

### How does this error happen? login? using an item? 
when i exit the server i getting error
#
### Is there an error in the console? Use pastebin.com. Is there a kick message?
http://pastebin.com/5y1PUVCv

**Comment by MylesIsCool** [comment]
You're behind by 1 version use 0.4.6

**Comment by AlexNova1555** [comment]
still getting the error after i updated

**Comment by MylesIsCool** [comment]
It's not technically an error, it's just the way error handling works after the plugin is installed. I'll see if there's a better way to fix this.

**Comment by HugoDaBosss** [comment]
Just printing this line is enough I guess:
java.io.IOException: An existing connection was forcibly closed by the remote host
That's also printed by the default minecraft server.

**Comment by AlexNova1555** [comment]
BTW do you know why i can hear random ghast scream sound ?

**Comment by HugoDaBosss** [comment]
This bug is known https://github.com/MylesIsCool/ViaVersion/issues/10 @AlexNova1555

**Comment by AlexNova1555** [comment]
Good job with the new update !!
but i found that if you spawn bat with egg spawner so its plays the ghast sound XD
and btw do you know why i got that error ?
http://pastebin.com/6Nv5wZwB
and yes i updated to 0.4.7

**Comment by MylesIsCool** [comment]
This might be an issue to do with the spigot version you're using as one update had bad output with netty handlers. I'd suggest updating if it still happens.
