### ISSUE TITLE
1.13 player disconnect when other players join

### ISSUE THREAD

**Issue by NitraCraft** [MylesIsCool/ViaVersion#930]
When players join, player using 1.13 get disconnected.

https://pastebin.com/FcWgMZJC

**Comment by electronicboy** [comment]
```
[13:41:03 WARN]: Caused by: io.netty.handler.codec.DecoderException: The
received string length is longer than maximum allowed (33 > 20)
[13:41:03 WARN]:        at net.minecraft.server.v1_8_R3.PacketDataSeriali
zer.c(PacketDataSerializer.java:219)
[13:41:03 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInCusto
```
Try updating bungeecord, they recently reduced the length of their legacy message channels, beyond that, you have a bungeecord plugin that is sending messages which a channel name that is basically too large

**Comment by NitraCraft** [comment]
<<sending messages which a channel name that is basically too large>> could u explain that a little bit more. I doesnt really understand what u mean

**Comment by MylesIsCool** [comment]
Should be fixed by updating BungeeCord see above.

Plugin channels in 1.13 are in a different format which leads to them needing to be converted.
