### ISSUE TITLE
Missing block completely -1

### ISSUE THREAD

**Issue by TNTUP** [MylesIsCool/ViaVersion#933]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/8c819c1defc709a5c05eb50aa77df967e3d5d35a4c31c22ad69ddd67ebd25483

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
PaperSpigot 1.12.2 Build 1500 with ViaVersion 1.4.2-SNAPSHOT Build 153 with ViaBackwards 2.3.2-DEV Build 59. Plugins are listed already in the dump provided above.

Found ViaBackwards-Snapshot 2.4.0, but I don't expect it would fix this issue.

### How does this error happen? login? Using an item? 
This is the second time it happens when a player clears its plot in a creative world, don't know if the player was on 1.13 or 1.12.2. Never encountered that kind of issue since I'm using ViaVersion, probably caused by PlotSquared

### Is there an error in the console? Use pastebin.com. Is there a kick message?

[10:13:21] [Server thread/INFO]: Fantastictiger issued server command: /plot delete -81;-24
[10:13:25] [Server thread/INFO]: Fantastictiger issued server command: /plot confirm
[10:13:26] [Netty Epoll Server IO #0/INFO]: Missing block completely -1
[10:13:26] [Netty Epoll Server IO #0/INFO]: Missing block completely -1
[10:13:26] [Netty Epoll Server IO #0/INFO]: Missing block completely -1
[10:13:26] [Netty Epoll Server IO #0/INFO]: Missing block completely -1
[10:13:26] [Netty Epoll Server IO #0/INFO]: Missing block completely -1
[10:13:26] [Netty Epoll Server IO #0/INFO]: Missing block completely -1
[10:13:26] [Netty Epoll Server IO #0/INFO]: Missing block completely -1
500k more lines...

no kick occurs, but it hangs the Netty Epoll Server IO's, meaning I guess, current players can still play on the server but they may notice slight lag due to the amount of spam logs but players cannot log on the server until I shutdown the server but it still hangs at Netty so forced to kill the process, meaning if no world save was done, a rollback is expected.

Should I report in ViaBackwards repo instead?

**Comment by MinecraftAdmin** [comment]
Can confirm issue.

**Comment by HexedHero** [comment]
Getting the same thing but a different block ID
"Missing block 2447"
spamming my console

**Comment by Alexre** [comment]
Having this issue with block "1" in 1.8.8, on a plotme server too.

**Comment by SrLeojaco** [comment]
Confirm

**Comment by Alexre** [comment]
Also checked and the problem appears after unloading chunks, for example using the clearlag's command /lagg unloadchunks or other plugins

**Comment by MylesIsCool** [comment]
I've pushed a workaround in the latest dev build - https://ci.viaversion.com/job/ViaVersion/
