### ISSUE TITLE
custom redstone color doesnt work

### ISSUE THREAD

**Issue by eliteSchwein** [MylesIsCool/ViaVersion#936]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/975716a1a8fe0ec07be2c9ead237d1402863ca559cbd7e14d7800456056d5f70

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
waterfall version 212,spigot 1.8.9

### How does this error happen? login? Using an item? 
![2018-07-26_10 09 35](https://user-images.githubusercontent.com/39838619/43249820-0a07d82a-90bc-11e8-94d7-3eb6cb128a2e.png)

custom redstone color (rgb values set) doesnt work, it is just random

### Is there an error in the console? Use pastebin.com. Is there a kick message?
no

**Comment by MylesIsCool** [comment]
Could you try with latest build?

https://ci.viaversion.com/job/ViaVersion/

If it still doesn't work, could you provide another screenshot & we'll reopen
