### ISSUE TITLE
Horses invisible

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#939]
### What is the output link of /viaversion dump? 

https://hastebin.com/wirasawura.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Nop

### How does this error happen? login? Using an item? 

http://image.noelshack.com/fichiers/2018/30/6/1532802309-bug-viaversion.jpg

### Is there an error in the console? Use pastebin.com. Is there a kick message?

Nop

**Comment by TheIntelloBox** [comment]
I see this error when I'm connected with Minecraft 1.13. :)

**Comment by KennyTV** [comment]
Afaik it's the fault of your resource pack or a Minecraft vanilla bug itself (seen and also reported by others in singleplayer worlds)

**Comment by MylesIsCool** [comment]
See above :)
