### ISSUE TITLE
Error message crashing the server

### ISSUE THREAD

**Issue by Johandrex** [MylesIsCool/ViaVersion#94]
I'm using version 0.4.6 & the spigot version "git-Spigot-db6de12-3f3c65f (MC: 1.8.8)"

Here's a list of the plugins I am using - https://fnpaste.com/VZAW

The error message is being spammed in the console every single second until the server crashes after around 30 seconds.

Here's the error message - https://fnpaste.com/B34J

**Comment by ridalarry** [comment]
Try disabling plugins 1 by 1 to know which plugin is causing it.

**Comment by Johandrex** [comment]
It's caused with this plugin enabled though, this issue didn't happen when using 0.4.1

**Comment by Johandrex** [comment]
Issue fixed in latest version
