### ISSUE TITLE
bungecord only

### ISSUE THREAD

**Issue by UnNamedAndre** [MylesIsCool/ViaVersion#940]
i have the last hexagonmc version of bungeecord.. on my server(network) viaversion works only on bungee, and i’d like to put it in my singolar servers in order to make the ‘vanilla’ server just for 1.13. In fact, with via version on bungee appears: bad packet id unsupported protocol version.. 

viaversion doesn’t work on my servers and works only on bungee because my servers have spigot 1.12.2 version with protocolsupport.. but i need that.. can you fix this?

**Comment by krusic22** [comment]
#870

**Comment by UnNamedAndre** [comment]
How can i set server protocol manually?

**Comment by MylesIsCool** [comment]
See issue above, protocols can be set in ViaVersion config.yml see https://docs.viaversion.com/display/VIAVERSION/Configuration for extra info.
