### ISSUE TITLE
BungeeCord Error

### ISSUE THREAD

**Issue by sbHango** [MylesIsCool/ViaVersion#941]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/8b75c46104b09d35b4a5e6dd1e25c1ecd24f5234a594294e11afa9afe2ac3651

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
This server is running BungeeCord version git:BungeeCord-Bootstrap:1.13-SNAPSHOT:0a95af5:1333 by md_5
hub version:
This server is running Paper version git-Paper-1515 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### How does this error happen? login? Using an item? 
I don't know what triggers it, but once in a day or so the hub server just breaks and nobody is able to connect to it. Then bungeecord and hub server shows errors on player connection. I only started having this problem after switching spigot to paperspigot, but that's a must for us.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Bungeecord:
https://pastebin.com/ZHkq7ag1

Hub:
[07:09:18] [Server thread/INFO]: /127.0.0.1:51955 lost connection: Internal Exception: java.lang.IllegalArgumentException: hostname can't be null

**Comment by MylesIsCool** [comment]
The error happens by an invalid packet being sent to the BungeeCord, but this shouldn't hang your whole server. Is there any more info you can provide? Are you certain it locks up fully after this?

**Comment by sbHango** [comment]
The server does not fully hang, if i'm connected to the hub already and this happens. I'm still able to use command etc. but when i look at the console and ppl try to connect I see those errors on each try:
bungee and this one
[07:09:18] [Server thread/INFO]: /127.0.0.1:51955 lost connection: Internal Exception: java.lang.IllegalArgumentException: hostname can't be null

Then I reboot hub and it's all good again

**Comment by MylesIsCool** [comment]
Are you still getting this issue?

Could you try without other Bungee plugins?

**Comment by sbHango** [comment]
Yes, I have tried without bungee plugins and it did happen as well. It happens like once a day, so i dont know what triggers it.

**Comment by MylesIsCool** [comment]
This sounds like a malicious / badly coded client, though it shouldn't hang the server if it is. (In the past when people have had similar issues the servers don't hang)

**Comment by sbHango** [comment]
Another thing to point out. If you're connected to the hub already and this happens, everything else works fine. Only players that try to connect WITH 1.13 version get that error after hub ''breaks'' ''hangs'' however you want to call the issue. Just to test it out, i disconnected from the hub when it broke. Changed my version to 1.13 and was not able to connect. Then changed it to 1.12 and everything is fine. So it definitely has to do something with Viaversion?

**Comment by MylesIsCool** [comment]
Could you confirm if this is still an issue with updated Bungee / ViaVersion?

**Comment by MylesIsCool** [comment]
See above, most likely malicious client.
