### ISSUE TITLE
Door bug.

### ISSUE THREAD

**Issue by TheIntelloBox** [MylesIsCool/ViaVersion#943]
###  What is the output link of /viaversion dump?

https://hastebin.com/wirasawura.json

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Nop

### How does this error happen? login? Using an item? 

http://image.noelshack.com/fichiers/2018/30/7/1532871706-door.jpg

### Is there an error in the console? Use pastebin.com. Is there a kick message?

Nop

**Comment by MylesIsCool** [comment]
See connections issue on issues page.
