### ISSUE TITLE
1.13 clients disconnect after another player joins server

### ISSUE THREAD

**Issue by cloakfox** [MylesIsCool/ViaVersion#944]
### What is the output link of /viaversion dump? 
**https://dump.viaversion.com/07b7531d79acbdfcaddc13fdc1aad72720770295bf1a26e2993e343e55595f1c**

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
**Waterfall build 212**

**Proxy plugins:
AlwaysOnline
BungeeAliases-1.1.2.jar
BungeeServerManager.jar
HubMagic-0.2.6.jar
movemenow-1.2-17.jar
PartyAndFriends.jar
RedisBungee-0.4.jar
StaffList.jar (Custom)
StatscraftX-BungeeCord.jar
SwiftMOTD.jar
ViaVersion-1.4.2-SNAPSHOT.jar**

### How does this error happen? login? Using an item? 
**Basicly when another player joins the server, all 1.13 connected clients disconnect (Server is running PaperSpigot 1.12 build 1515)

On this server I run ViaVersion-1.4.1 with ViaBackwards and Viarewind

All plugins: https://imgur.com/a/ZChAqK0**

### Is there an error in the console? Use pastebin.com. Is there a kick message?
**Error: https://hastebin.com/iwavayuboc.css**

**Comment by MylesIsCool** [comment]
Please enable debug=true in server.properties and post the full error :)

**Comment by cloakfox** [comment]
So I noticed a bunch of errors now, also on startup. So here is the entire log (at the bottem including the disconnect error)

https://hastebin.com/educayemid.md

**Comment by MylesIsCool** [comment]
One error is paper related, the other looks like you need to update BungeeCord possibly.


See https://github.com/MylesIsCool/ViaVersion/issues/934 (Maybe outdated Bungee plugin)

**Comment by cloakfox** [comment]
Updated to BungeeCord, same errors it seems
Server error: https://hastebin.com/otapocovuh.cs

Client crash error: https://hastebin.com/xelodoqejo.cs (For some reason client now crashes, when using BungeeCord)
