### ISSUE TITLE
Bukkit - Bungee plugin messaging channel doesn't work on 1.13 clients

### ISSUE THREAD

**Issue by MClausz** [MylesIsCool/ViaVersion#946]
### What is the output link of /viaversion dump? 

https://dump.viaversion.com/7bb8e736b4ce32601e460903676448108231f178c57936bfc9f63188076c5b25

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Waterfall/BungeeCord, plugins: Bungeetablistplus, serverlistplus

### How does this error happen? login? Using an item? 

My server is 1.12.2 (with viaversion installed), when I tries to send a message from Bukkit to Bungee, it seems BungeeCord doesn't receive the message.
It still works with <= 1.12.2 clients
I tried opening the same issue in BungeeCord github page and md-5 said Viaversion is not supported
https://github.com/SpigotMC/BungeeCord/issues/2487

### Is there an error in the console? Use pastebin.com. Is there a kick message?
no

**Comment by danjono** [comment]
I'm pretty sure this is not a ViaVersion issue. Spigot has changed the Bungee bridge naming convention in 1.13 where the name has to be all lower case and include a colon. BungeeTabListPlus however has  [already updated](https://github.com/CodeCrafter47/BungeeTabListPlus/commit/158542ecf6a54237a9ba55f8913673885aa5d8c1). 

This fix is dependent on the plugin developers fixing their code for their respective plugin.

**Comment by MClausz** [comment]
thanks, I'll look into it
