### ISSUE TITLE
Chests, fences, glass panes are not connected on 1.13 client

### ISSUE THREAD

**Issue by MClausz** [MylesIsCool/ViaVersion#947]
### What is the output link of /viaversion dump? 

https://dump.viaversion.com/7bb8e736b4ce32601e460903676448108231f178c57936bfc9f63188076c5b25

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)

Waterfall/BungeeCord, plugins: Bungeetablistplus, serverlistplus

### How does this error happen? login? Using an item? 

https://i.imgur.com/Twa9mvp.png

### Is there an error in the console? Use pastebin.com. Is there a kick message?
no

**Comment by MylesIsCool** [comment]
See https://github.com/MylesIsCool/ViaVersion/issues/856
