### ISSUE TITLE
Player pushing enabled

### ISSUE THREAD

**Issue by Johandrex** [MylesIsCool/ViaVersion#95]
I'm using version 0.4.6 & the spigot version "git-Spigot-db6de12-3f3c65f (MC: 1.8.8)"

Here's a list of the plugins I am using - https://fnpaste.com/VZAW

It is possible for players using the 1.9 version to push other players using 1.9 even though it's a 1.8 server, please fix this as it'll drive my players insane.

**Comment by MylesIsCool** [comment]
This is a feature we currently don't have, we're hoping to have some sort of option to prevent this.

**Comment by HugoDaBosss** [comment]
@StamBoom  is busy fixing this: https://github.com/MylesIsCool/ViaVersion/pull/88

**Comment by HugoDaBosss** [comment]
This has been fixed: https://github.com/MylesIsCool/ViaVersion/commit/528b234d5ab22de76c5cd10d5169dcb800c1b515
