### ISSUE TITLE
Fix ProtocolSupport support.

### ISSUE THREAD

**Issue by Xayanix** [MylesIsCool/ViaVersion#951]
Im using latest ProtocolSupport for 1.12 and latest build of ViaVersion and im unable to join 1.12 server with 1.13 client.

**Comment by Logics4** [comment]
No.
Use ViaVersion with ViaBackwards and ViaRewind instead of ProtocolSupport.

**Comment by toxamin** [comment]
simple fix:
1. learn java
2. make code that fixes it
3. make pull request
4. ???
5. PROFIT

**Comment by MylesIsCool** [comment]
See what Logics said, otherwise you're welcome to PR the code.
