### ISSUE TITLE
Stairs Issue on 1.13 with server on 1.8.8

### ISSUE THREAD

**Issue by olesien** [MylesIsCool/ViaVersion#952]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/a58b6f3939d02580440940d8e81dbe67ab1b1f50bfb0907c73e42a05bdbf2507

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yes we are using the lastest Bungeecord release (which supports 1.8.8 -> 1.13)
![bplugins](https://user-images.githubusercontent.com/17833751/43464852-581913de-94dc-11e8-82d6-7347c5f3bf3f.PNG)

### How does this error happen? login? Using an item? 
This bug occurs when using 1.13 and looking at stairs (every other version works fine, if you rebuild it, it will look as it should until you login again)
This is how it looks like:
![hubstairs](https://user-images.githubusercontent.com/17833751/43464988-a469f37a-94dc-11e8-8c4f-2953c10b4ea3.PNG)

I tried on a default spigot server (1.8.8) with ONLY viaversion installed, and I got the same issue.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No there is not.

**Comment by olesien** [comment]
Oh well.. Maybe the post still can be to some help

**Comment by MylesIsCool** [comment]
See above
