### ISSUE TITLE
JukeBox and NoteBlockAPI don't work at all on 1.13

### ISSUE THREAD

**Issue by draand28** [MylesIsCool/ViaVersion#955]
Viaversion dump: https://dump.viaversion.com/ae49f6fd851ea2fd861daf0dc5548047aa8eee041a95d867e9c21b8674a92441\

I use Bungeecord 1344 (last version) and git-Spigot-550ebac-7019900 (MC: 1.8) API version 1.8-R0.1-SNAPSHOT. The problem is that I cannot listen to any kind of music from a JukeBox on Spigot 1.8 with viaversion on minecraft client 1.13. Nor NoteBlockAPI or JoinMusik work on 1.13, but on older versions they work just fine. Here is a list of plugins I use:
icJukeBox, CustomHelpMessage, RemoveJoinLeaveMessage, WorldEdit, CommandBlocker, GroupManager, EasyBackup, WorldGuard, WordBlock, Emotes, NoteBlockAPI, ViaVersion, CustomJoinItems, Vault, JoinMusik, EssentialsSpawn, Authme, HolographicDisplays, CitizensCMD.

No, there is no error in console.

**Comment by Logics4** [comment]
If you *really* want a 1.8 server, please use Spigot 1.8.8. It is the only 1.8.X version where ViaVersion is tested on.

**Comment by draand28** [comment]
I've just upgraded to git-Spigot-db6de12-18fbb24 (MC:1.8.8) (API 1.8.8-R0.1-SNAPSHOT) and it's still not working. I've tried with 1.8 - it works, I've tried with 1.12.2 - it works. Only on 1.13 it doesn't work at all (the normal jukebox block with music dics is not working either). Here is a new viaversion dump if you need: https://dump.viaversion.com/a4ab46d7e20b7f055bbb2a15b0e71f9402311ebca9a1c8f79b51abe6e17741ac

**Comment by MylesIsCool** [comment]
Can you test and see if this is fixed in the dev version?

https://ci.viaversion.com/job/ViaVersion

**Comment by draand28** [comment]
Yes it is fixed! Thank you so much!
