### ISSUE TITLE
Games Crashes When I join in 1.13

### ISSUE THREAD

**Issue by pocketcraft1** [MylesIsCool/ViaVersion#961]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/a7102350b3883432dc2a8e8ac6474606ddcf785671a6c5fb69ebc50b74829ae4

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No, I am using Spigot for Minecraft version 1.12.2
<img width="774" alt="plugins" src="https://user-images.githubusercontent.com/38080968/43836211-a0dbbc50-9ae2-11e8-8152-045d124e53d2.PNG">

### How does this error happen? login? Using an item? 
Sometimes the game crashes on login in 1.13, other times it crashed when I change worlds.

### Is there an error in the console? Use pastebin.com. Is there a kick message?

<img width="860" alt="capture" src="https://user-images.githubusercontent.com/38080968/43836133-59f030aa-9ae2-11e8-9baa-6af42554b2f8.PNG">

**Comment by Logics4** [comment]
It seems to be with NoCheatPlus. Does it happen without it installed?

It's relatively common for anti-cheats to mess up with protocol hacks (since they both work with packets).

**Comment by pocketcraft1** [comment]
I think it has something to do with Multiverse.  Sometimes the server lets me login, but if I try to change worlds, my game crashed and it just says that I disconnected.

**Comment by MylesIsCool** [comment]
Could you try the latest dev build - https://ci.viaversion.com/job/ViaVersion?

**Comment by pocketcraft1** [comment]
I tried it and it fixed the problem. Thank you so much.  It also made it where I could see my server icon in 1.13.

**Comment by pocketcraft1** [comment]
My console is filled with the message Received invalid biome id and it is either the number 65 or 71

**Comment by MylesIsCool** [comment]
Do you use a custom world generator?

**Comment by MylesIsCool** [comment]
Your server possibly uses custom terrain which uses a invalid biome id, we'll probably look into a way to reduce the spam in the future of invalid biome
