### ISSUE TITLE
[ViaVersion]: Received invalid biome id 58

### ISSUE THREAD

**Issue by mibby** [MylesIsCool/ViaVersion#963]
Waterfall build 215
ViaVersion build 222
Paper build 1534 (Spigot 1.12.2)

ViaVersion is on BungeCord end only. 

ViaVersion is spamming BungeeCord console with this warning.
```
[02:25:00] [Netty Worker IO Thread #10/WARN] [ViaVersion]: Received invalid biome id 58
```

Edit: Also received a warning for this biome ID.

```
10.08 02:41:26 [Server] WARN [ViaVersion]: Received invalid biome id 73
```

**Comment by MylesIsCool** [comment]
Do you use a custom world generator or world editing tools?

**Comment by mibby** [comment]
I generated my world back during 1.11's release with BiomeBundles & OpenTerrainGenerator. However I do also use WorldEdit & VoxelSniper world editing tools.

**Comment by MylesIsCool** [comment]
The issue is down to your biomes being not valid, I don't know which plugin has caused this but I would probably say that it'll hurt you if you ever want to update to 1.13.

Otherwise we'll probably provide a option to suppress conversion errors.

**Comment by mibby** [comment]
It should be using vanilla biome IDs though for all biomes. I just used the plugin to generate the world initially, then removed it once I had the custom biomes.

**Comment by MylesIsCool** [comment]
As given in the error, 73 is not a vanilla id

https://minecraft.gamepedia.com/Biome/ID

**Comment by mibby** [comment]
Very odd. Would it be possible to default to ID 0 for biome ID if it is outside the vanilla range instead of outputting the warning ```WARN [ViaVersion]: Received invalid biome id 73```?

**Comment by MylesIsCool** [comment]
It does default to this, it just warns you because it's invalid.

As per above "Otherwise we'll probably provide a option to suppress conversion errors."

**Comment by pocketcraft1** [comment]
I found a solution I think for those without BungeeCord.  You can use this plugin, and it disables the spam quite well. https://www.spigotmc.org/resources/console-spam-fix.18410/

**Comment by MylesIsCool** [comment]
If you wish to hide this:

https://ci.viaversion.com/job/ViaVersion/ - Use the option suppress-1_13-conversion-errors in the config.yml

**Comment by mibby** [comment]
Could it be merged into the DEV branch too?
