### ISSUE TITLE
[ViaVersion]: Received invalid anvil values=[0, 1, 2]} to 8 on block

### ISSUE THREAD

**Issue by Retrumek** [MylesIsCool/ViaVersion#965]
pastebin 👍 https://pastebin.com/hEUsSnDj

**Comment by MylesIsCool** [comment]
Fill out the issue template properly, https://github.com/MylesIsCool/ViaVersion/blob/master/ISSUE_TEMPLATE.md

Otherwise we don't have enough information to help you.

**Comment by MylesIsCool** [comment]
See above, then we'll reopen.
