### ISSUE TITLE
Chest placing issue for players using 1.13

### ISSUE THREAD

**Issue by matthewmarion** [MylesIsCool/ViaVersion#967]
### What is the output link of /viaversion dump? 
No error.

### How does this error happen? login? Using an item? 
Chests can be placed next to each other in 1.13 so when players place chests next to each other in 1.12.2, and the player is playing on 1.13, the chest is temporarily removed from their inventory and not added back until they place a chest in a placeable area.

Shown in attachment: https://gyazo.com/c4a5ea85a80d8fc3440d58908795f480

**Comment by maxw2000** [comment]
look at issues #856 , this is a known bug.

**Comment by MylesIsCool** [comment]
This is one of those issues which becomes really messy to fix, it's easier to leave the client with a brief desync as there's no nice way of knowing the player is placing against a chest.

On the bukkit side this could perhaps be fixed just with a listener but for now it's probably best just to leave it unless there is popular demand for us to write a simple bukkit patch.
