### ISSUE TITLE
Bows

### ISSUE THREAD

**Issue by ridalarry** [MylesIsCool/ViaVersion#97]
Using the latest version of spigot and ViaVersion with no other plugins it show no console erros Bows and arrows will not work for 1.9 clients https://gyazo.com/f6c075351e1157d8c43c4a94da7817e7

**Comment by HugoDaBosss** [comment]
If you move around, and then shoot, it will work.
This is also the case in singleplayer 1.9 worlds. (In my case then).

**Comment by HugoDaBosss** [comment]
Can your confirm this? ^

**Comment by zedwick** [comment]
I can confirm moving around and shooting seems to help.
Issue is not present in my singleplayer 1.9 world, however.

**Comment by rj0495** [comment]
[18:26:00 INFO]: [ProtocolLib] Received PacketPlayInBlockPlace[8, legacy: 15] from rj0495:
{ a = { name = "MAIN_HAND", ordinal = 0 }, timestamp = 1457461560740 }
[18:26:02 INFO]: [ProtocolLib] Received PacketPlayInBlockDig[7, legacy: 14] from rj0495:
{ a = { a = 0, c = 0, d = 0 }, b = { g = 0, h = 1, i = -1, j = "down", k = { e = "y", f = "VERTICAL", name = "Y", ordinal = 1 }, l = { c = -1, d = "Towards negative", name = "NEGATIVE", ordinal = 1 }, m = { a = 0, c = -1, d = 0 }, name = "DOWN", ordinal = 0 }, c = { name = "RELEASE_USE_ITEM", ordinal = 5 } }
[18:26:02 INFO]: [ProtocolLib] Sent PacketPlayOutSpawnEntity[14, legacy: 23] to rj0495:
{ a = 56, b = { mostSigBits = -3608493333542254160, leastSigBits = -7007445500614571244 }, c = -180.96075951498796, d = 70.52000000327826, e = 118.6429079189659, f = 24072, g = -1248, h = -2729, i = -3, j = 68, k = 60, l = 54 }

**Comment by rj0495** [comment]
Full PK Dump for 1.9

**Comment by HugoDaBosss** [comment]
Fixed #185 
Thanks @lenis0012 !

**Comment by MylesIsCool** [comment]
Fixed works in next version.
