### ISSUE TITLE
1.8 client disconnect issues

### ISSUE THREAD

**Issue by LoXR** [MylesIsCool/ViaVersion#970]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/34be2219e0318adc605773ab1f1a48ab3e725c84a4c0b8171d915c896767d249

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yes WaterFall & all bungee plugins are in the dump.

### How does this error happen? login? Using an item? 
When a player tried to join a server other then my hub, it immediately disconnects them. Just says User TheDjape has disconnected, reason: Disconnected in the servers console, and in bungee console it gave the error.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Full error https://pastebin.com/tYCpuGAT

**Comment by MylesIsCool** [comment]
As discussed on Discord
