### ISSUE TITLE
Client Crash (Tesselating Block Model)

### ISSUE THREAD

**Issue by Fluxty** [MylesIsCool/ViaVersion#976]
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
We're using ViaVersion at bungee/Travertine. Spigot is TacoSpigot 1.8.8

### How does this error happen? login? Using an item? 
Pretty much when logging into the server the the affected block/slab.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
1.13 Crash report: https://pastebin.com/6h8nAgUS

**Comment by MylesIsCool** [comment]
Can you provide the /ViaVersion dump?

**Comment by Fluxty** [comment]
This is the dump: https://dump.viaversion.com/8ccd4befc0251ce0b81e7ea021e7922120af88db5b6cf619d9d710acf0aba645

Another strange thing about that dump is that ViaVersion seems to asssign all of our servers protocol version 340 despite us being on 1.8.8

**Comment by MylesIsCool** [comment]
Are you on the latest ci.viaversion.com/job/ViaVersion build?

**Comment by MylesIsCool** [comment]
+ do you have ViaVersion on Bungee only?

**Comment by Fluxty** [comment]
Yes, the latest from Aug 12.

**Comment by MylesIsCool** [comment]
Are you able to correlate this issue to a specific block?

If the block is removed does it stop happening?

**Comment by Fluxty** [comment]
We currently have ViaVersion on both Bungee and Spigot, but this is being tested with Bungee only as well. The crash report says the block is a stone brick slab, but I'm unable to figure out what's going on. As soon as I join my 1.8.8 test server on 1.13 it crashes. This is still happening with the new version you just put out.

I tried going on one of our production servers and placing similar blocks as the spawn on the test server but was ultimately unable to re-create the issue. Unfortunately, I have no idea what is going on, but 1.13 players will not be able to join this server.

**Comment by Fluxty** [comment]
Issue is resolved. It's the result of having blocks on the server that aren't in the server's native version. We had a few white concrete, yellow shulker boxes, and glazed teracotta surrounded by stone brick slabs in the build. I could see them on 1.12.2 and everything was fine, but going on 1.13 or 1.13.1 will cause you to immediately crash. Removing the blocks is not possible via breaking, you have to set them to air using something like WorldEdit. After that, everything is good 👍

**Comment by MylesIsCool** [comment]
Awesome, thanks for keeping us in the loop. It'll definitely help for anyone else who has this issue.
