### ISSUE TITLE
Invalid Biome ID 71 and 64 

### ISSUE THREAD

**Issue by pocketcraft1** [MylesIsCool/ViaVersion#980]
### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No just Spigot
Plugins (31): AsyncWorldEditInjector, LuckPerms, EmptyWorldGenerator, Skript, MinePacks, RelaAutoBroadcast, Votifier, Multiverse-Core, OpenTerrainGenerator, AdvancedHelp, VotingPlugin, AsyncWorldEdit, ViaVersion, Multiverse-Portals, Vault, ViaBackwards, ViaRewind, WorldEdit, Essentials, ProtocolLib, WorldGuard, DiscordSRV, EssentialsChat, CrazyAuctions, SuperVanish, PyrCore, GriefPrevention, EnjinMinecraftPlugin, HolographicDisplays, PyrParticles, BossShop
### How does this error happen? login? Using an item? 
In 1.13 only (I think) while I am in the world Biome Bundle, ViaVersion spams the message Received invalid Biome id 65 or Received invalid Biome id 71 

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://pastebin.com/xyVCyKiv

I just was wondering if there is a way for me to stop the spam as of this moment because it can be very annoying. Thanks!

**Comment by MylesIsCool** [comment]
Follow #963 for progress
