### ISSUE TITLE
Noteblocks aren't working

### ISSUE THREAD

**Issue by Markus1812** [MylesIsCool/ViaVersion#984]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/5c26f10b743aa5247dc3ad74c91708b554f4cd5776f812c0f4c75e166745a1bc

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
yes, we are running git:BungeeCord-Bootstrap:1.13-SNAPSHOT:6fadb42:1343 by md_5 

### Problem
If you right click a Noteblock the Sound Particle is coming but you can't here any sounds. Sounds are turned on in Minecraft and i tested it with some friends. They don't hear anything too.

Server is running on 1.8.8, client version is 1.13

**Comment by MylesIsCool** [comment]
This is fixed in our builds from ci.viaversion.com
