### ISSUE TITLE
Server randomly kicks my players while connecting

### ISSUE THREAD

**Issue by BestMark** [MylesIsCool/ViaVersion#986]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/69f768ac00fc776f6d7f746741493eb6ad4999f5a75ec7d9319f15718601d97d

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Yes, I'm using Waterfall 1.12.2 (latest version for 1.12.2)
Paper 1.12.2 (latest build)

### How does this error happen? login? Using an item? 
It happens randomly every hour in my server. When I wanted to connect through BungeePortals it kicked me from my server (Spigot and BungeeCord).

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Error in Paper console: https://pastebin.com/G86w87wg
Error in BungeeCord console while connecting to the server: https://pastebin.com/Px6j7QQy
Paper's developer says that the problem is in Via plugins.
https://github.com/PaperMC/Paper/issues/1235

**Comment by MylesIsCool** [comment]
What version do people getting kicked use? List all that are affected

Can you test with no plugins (apart from ViaVersion)? Are you able to replicate yourself?

**Comment by BestMark** [comment]
Yes, It happened to me when I join from Minecraft 1.12.2 without any mods (from original Minecraft launcher).
I don't have the ability to test this without plugins, as a lot of players are needed and it happens rarely.
Other cases of kicking players:
https://pastebin.com/ExCaZWSr
https://pastebin.com/BSAyAdkx
etc...

**Comment by MylesIsCool** [comment]
Can you copy your server and test by yourself? Because we otherwise have no way to replicate this

**Comment by BestMark** [comment]
Yes, but how can I test this? It happens very rarely (less than 10% chance) when there are a lot of players on my server.

**Comment by MylesIsCool** [comment]
It's a case of just seeing if you can replicate it locally with no other plugins.

Unfortunately if we don't know how to replicate it we don't know how to fix it. There's usually some logic behind it other than random.

**Comment by MylesIsCool** [comment]
See above, unfortunately we can't really squash this bug without any idea how it's caused.
