### ISSUE TITLE
Players on 1.13 cannot connect.

### ISSUE THREAD

**Issue by AtomixCM** [MylesIsCool/ViaVersion#988]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/cf08166689a84114a6dd89d0c2e74595848778ce193e99c55c730204201ece54

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
Using spigot 1.8.8

### How does this error happen? login? Using an item? 
When players log in on 1.13 they get disconnected.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
```21.08 22:11:19 [Disconnect] User CM_lectric has disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.RuntimeException: An internal error occured.````

**Comment by MylesIsCool** [comment]
Enable debug=true in server.properties, reboot then hastebin.com the new error

**Comment by AtomixCM** [comment]
https://hastebin.com/ikeyaqifiq.pl

**Comment by AtomixCM** [comment]
https://hastebin.com/ikeyaqifiq.pl

**Comment by MylesIsCool** [comment]
This should be fixed in the latest version. Request reopen otherwise (it's down to bad characters in team names)
