### ISSUE TITLE
Food

### ISSUE THREAD

**Issue by ridalarry** [MylesIsCool/ViaVersion#99]
Using the latest version of spigot and ViaVersion with no other plugins it show no console errors It will take around 1 minute of right clicking to eat with a 1.9 clients

**Comment by PunKeel** [comment]
Same issue as #97, imo.

**Comment by ridalarry** [comment]
Its not the same issue I have made a post for 10 issues and Paulo asked me to make them seperated. I have closed the 10 issues report and making them seperatly

**Comment by PunKeel** [comment]
I gave you my opinion, nothing more. And I still think the same issue is causing #97 and this (#99) : the digging packet.

**Comment by ridalarry** [comment]
Oh it could be then

**Comment by ridalarry** [comment]
I have noticed that this issue is only appearing if you are not moving. If you move then this bug is no longer happening.

**Comment by MylesIsCool** [comment]
Fixed works in next version.

**Comment by HugoDaBosss** [comment]
Fixed #185 
Thanks @lenis0012 !
