### ISSUE TITLE
Players getting kicked for disconnect.spam when logging in with AuthMe

### ISSUE THREAD

**Issue by Matocolotoe** [MylesIsCool/ViaVersion#992]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/348241a34e270d40aa2853f929e2bc770f45c97a7a4490847e97a46d14497922

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
I don't use BungeeCord
Spigot : 1.8.8
Skript, GadgetsMenu, GameBox, SkQuery, NametagEdit, ExtrasSK, Battleship, GemCrush, Citizens, FastAsyncWorldEdit, MaxBans, WildSkript, KizunaAI, OpGuard, UltimateTNT, PermissionsEx, ViaVersion, MP-GameBundle, AntiBot-Ultra, WorldEdit, 2048, PlotSquared, ProtocolLib, Multiverse-Core, Skellett, SkinsRestorer, skRayFall, AttributeHider, CustomPayloadFixer, ArmorStandTools, AuthMe, TuSKe

### How does this error happen? login? Using an item? 
When using /login AuthMeReloaded command

### Is there an error in the console? Use pastebin.com. Is there a kick message?
No.

**Comment by MylesIsCool** [comment]
https://github.com/MylesIsCool/ViaVersion/issues/891
