### ISSUE TITLE
Recipe Book is broken

### ISSUE THREAD

**Issue by WolfezzKyne** [MylesIsCool/ViaVersion#993]
### What is the output link of /viaversion dump? 
1.5.0

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No, just Spigot

### How does this error happen? login? Using an item? 
Use the recipe book and click some of the items in it (crafting menu)

### Is there an error in the console? Use pastebin.com. Is there a kick message?
Nope

**Comment by MylesIsCool** [comment]
Fixed in dev builds
