### ISSUE TITLE
Villagers have villager spawn eggs instead of emeralds in all their trades, and all trades fail. 1.13.1->1.13

### ISSUE THREAD

**Issue by JethroHotep** [MylesIsCool/ViaVersion#994]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/c100940294addca6189cf855ed68ae8e0e91591a3b119ff2284cd98434bf17dc

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
No bungeecord.  plugins listed in dump.

### How does this error happen? login? Using an item? 
Login with mc 1.13.1 vanilla client to 1.13 server, then do villager trade.  Villagers have villager spawn eggs instead of emeralds in all their trades, and all trades fail.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
no

**Comment by colinrgodsey** [comment]
Same happening here. Also happens with 1.13.1 -> 1.12.2. 1.13 client has no issue in either the 1.13 or 1.12 servers.

**Comment by capacit** [comment]
Same issue, because of this I cannot use ViaVersion. Any fix soon?

**Comment by MylesIsCool** [comment]
I believe this is fixed in our dev builds - https://ci.viaversion.com/job/ViaVersion
