### ISSUE TITLE
Error when joining with 1.13(.1)

### ISSUE THREAD

**Issue by didjee2** [MylesIsCool/ViaVersion#996]
### What is the output link of /viaversion dump? 
https://dump.viaversion.com/b102e260ab56bc15ec0572f9b116ce7db0e2cd1dba8717a3a397bf0fd7760229

### Are you using any additional software like BungeeCord? If so, what software and version? (Please list your plugins as well)
The error occurs on BungeeCord.
https://gyazo.com/eedffd8e35c40c08cf7a5f40a36ef90e (CentrixCore is custom coded)

### How does this error happen? login? Using an item? 
As said above, the error occurs on BungeeCord when logging in with 1.13 / 1.13.1 in a 1.12.2 server.

ViaVersion has been uploaded in our BungeeCord as I saw that it doesn't go together with ProtocolSupport.
I'm using the latest version of BungeeCord.

### Is there an error in the console? Use pastebin.com. Is there a kick message?
https://hastebin.com/eticodorij.shell
This is the kick message I receive on my MineCraft client when joining: https://gyazo.com/11637ad675bbdcc4594fa00fc7b305af.

**Comment by MylesIsCool** [comment]
Same as https://github.com/MylesIsCool/ViaVersion/issues/981

See bottom
